Repository Shopify/polaris, pull requests merged in 2018-11, with the labels that each got.

#522 [Page] Change SecondaryAction to an interface
  src/components/Page/components/Header/Header.tsx
Labels: Skip Changelog

#464 [TrapFocus] Fix TrapFocus stealing focus from contained nodes
  src/components/Focus/Focus.tsx
  src/components/TrapFocus/TrapFocus.tsx
  src/components/TrapFocus/tests/TrapFocus.test.tsx
Labels: Blocking web, Bug fix, Skip Changelog

#484 [Navigation] Add new indicators to nav items
  src/components/Navigation/Navigation.scss
  src/components/Navigation/README.md
  src/components/Navigation/components/Item/Item.tsx
  src/components/Navigation/components/Item/tests/Item.test.tsx
  src/components/index.ts
Labels: Skip Changelog

#531 Use `!important` in print-hidden mixin
  UNRELEASED.md
  src/styles/shared/typography.scss
Labels: Skip Changelog

#503 [Autocomplete] Adds emptyState prop
  src/components/Autocomplete/Autocomplete.tsx
  src/components/Autocomplete/README.md
  src/components/Autocomplete/components/ComboBox/ComboBox.scss
  src/components/Autocomplete/components/ComboBox/ComboBox.tsx
  src/components/Autocomplete/components/ComboBox/tests/ComboBox.test.tsx
  src/components/Autocomplete/tests/Autocomplete.test.tsx
Labels: Component enhancement, Skip Changelog

#541 [Top bar] Update example color
  src/components/AppProvider/README.md
  src/components/Frame/README.md
  src/components/TopBar/README.md
Labels: Skip Changelog

#546 fix broken or nonexistent links to new frame components
  UNRELEASED.md
  src/components/AppProvider/README.md
  src/components/Frame/README.md
  src/components/Navigation/README.md
  src/components/TopBar/README.md
Labels: Skip Changelog

#552 Avoid absolute paths for the moment
  src/test-utilities/enzyme.tsx
  src/utilities/app-bridge-transformers.ts
Labels: Skip Changelog

#560 [Frame] disable navigation left padding and main background color when printing
  src/components/Frame/Frame.scss
Labels: Skip Changelog

#471 [Autocomplete] Reopen popover if popoverWasActive and there are options
  src/components/Autocomplete/components/ComboBox/ComboBox.tsx
  src/components/index.ts
Labels: Skip Changelog

#555 Tidy up a bunch of webpack config stuff
  .eslintignore
  .gitignore
  .prettierignore
  .stylelintignore
  package.json
  playground/assets/.keep
  playground/webpack.config.js
  playground/webpack.config.shrink-ray.js
  scripts/build-shrink-ray.js
  shrink-ray-build/index.tsx
  tophat/index.js
  tophat/snapshots.js
  tophat/webpack.config.js
  yarn.lock
Labels: Skip Changelog

#564 Tophat updates
  playground/index.html
  playground/webpack.config.js
  scripts/build-shrink-ray.js
  tophat/Example.tsx
  tophat/index.js
  tophat/parseMarkdown.js
  tophat/transpileExample.js
  tophat/webpack.config.js
  tophat/webpack.config.shrink-ray.js
Labels: Skip Changelog

#477 [Autocomplete] Fix option selection with arrow keys
  src/components/Autocomplete/components/ComboBox/ComboBox.tsx
Labels: Skip Changelog

#517 Fix focus invariant error
  src/components/Focus/Focus.tsx
Labels: Skip Changelog

#588 Update @percy/puppeteer to 0.4.0
  package.json
  yarn.lock
Labels: Skip Changelog

#605 [Popover] Fix inconsistent border-radius
  src/components/Popover/Popover.scss
Labels: Bug fix, Skip Changelog

#607 Bump sewing-kit version
  package.json
  sewing-kit.config.ts
  yarn.lock
Labels: Skip Changelog

#475 Avoid circular dependencies & add dependency-cruiser
  .dependency-cruiser.json
  .eslintrc
  package.json
  src/components/AccountConnection/AccountConnection.tsx
  src/components/AppProvider/types.ts
  src/components/Autocomplete/Autocomplete.tsx
  src/components/Autocomplete/components/ComboBox/components/TextField/TextField.tsx
  src/components/ButtonGroup/components/Item/Item.tsx
  src/components/DropZone/components/FileUpload/FileUpload.tsx
  src/components/EmptySearchResult/EmptySearchResult.tsx
  src/components/ExceptionList/ExceptionList.tsx
  src/components/Frame/Frame.tsx
  src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.tsx
  src/components/Frame/components/ContextualSaveBar/components/DiscardConfirmationModal/DiscardConfirmationModal.tsx
  src/components/Frame/components/Toast/Toast.tsx
  src/components/Frame/components/ToastManager/ToastManager.tsx
  src/components/Loading/Loading.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/components/CloseButton/CloseButton.tsx
  src/components/Modal/components/Dialog/Dialog.tsx
  src/components/Modal/components/Footer/Footer.tsx
  src/components/Modal/components/Header/Header.tsx
  src/components/Navigation/Navigation.tsx
  src/components/Navigation/components/Item/Item.tsx
  src/components/Navigation/components/Item/components/Secondary/Secondary.tsx
  src/components/Navigation/components/Message/Message.tsx
  src/components/Navigation/components/Section/Section.tsx
  src/components/Navigation/components/UserMenu/UserMenu.tsx
  src/components/Navigation/types.ts
  src/components/OptionList/OptionList.tsx
  src/components/OptionList/components/Option/Option.tsx
  src/components/Page/Page.tsx
  src/components/Page/components/Header/Header.tsx
  src/components/Page/components/Header/components/Action/Action.tsx
  src/components/Page/components/Header/components/ActionGroup/ActionGroup.tsx
  src/components/ResourceList/ResourceList.tsx
  src/components/ResourceList/components/BulkActions/BulkActions.tsx
  src/components/ResourceList/components/CheckableButton/CheckableButton.tsx
  src/components/ResourceList/components/FilterControl/FilterControl.tsx
  src/components/ResourceList/components/FilterControl/components/DateSelector/DateSelector.tsx
  src/components/ResourceList/components/FilterControl/components/FilterCreator/FilterCreator.tsx
  src/components/ResourceList/components/FilterControl/components/FilterValueSelector/FilterValueSelector.tsx
  src/components/SettingToggle/SettingToggle.tsx
  src/components/Toast/Toast.tsx
  src/components/TopBar/TopBar.tsx
  src/components/TopBar/components/Menu/Menu.tsx
  src/components/TopBar/components/Menu/components/Message/Message.tsx
  src/components/TopBar/components/SearchField/SearchField.tsx
  src/components/TopBar/components/UserMenu/UserMenu.tsx
  src/components/TrapFocus/TrapFocus.tsx
  src/components/types.ts
  src/types.ts
  yarn.lock
Labels: Skip Changelog

#610 Use 'import * as styles' format for all imports
  src/components/EmptySearchResult/EmptySearchResult.tsx
  src/components/Navigation/components/Item/components/Secondary/Secondary.tsx
  src/components/Navigation/components/Message/Message.tsx
  src/components/TopBar/components/Menu/Menu.tsx
  src/components/TopBar/components/Menu/components/Message/Message.tsx
  src/components/TopBar/components/UserMenu/UserMenu.tsx
Labels: Skip Changelog

#606 [TextStyle] Change <b> to <span>
  UNRELEASED.md
  src/components/TextStyle/TextStyle.tsx
  src/components/TextStyle/tests/TextStyle.test.tsx
Labels: Bug fix

#601 [DatePicker] Fix date comparision when different references
  UNRELEASED.md
  src/components/DatePicker/components/Month/Month.tsx
  src/components/DatePicker/components/Month/tests/Month.test.tsx
Labels: Bug fix

#526 adds missing tests to Page and its sub-components
  src/components/Page/components/Header/Header.tsx
  src/components/Page/components/Header/components/Action/Action.tsx
  src/components/Page/components/Header/components/Action/tests/Action.test.tsx
  src/components/Page/components/Header/components/ActionGroup/ActionGroup.tsx
  src/components/Page/components/Header/components/ActionGroup/tests/ActionGroup.test.tsx
  src/components/Page/components/Header/utilities.ts
  src/components/Page/tests/Page.test.tsx
Labels: Skip Changelog, Testing

#637 Revert "Update Avatar and Image component to handle onError with images."
  CHANGELOG.md
  src/components/Avatar/Avatar.scss
  src/components/Avatar/Avatar.tsx
  src/components/Avatar/tests/Avatar.test.tsx
  src/components/Image/Image.tsx
  src/components/Image/tests/Image.test.tsx
Labels: Skip Changelog

#596 [Autocomplete] Move props into their own variables in examples
  src/components/Autocomplete/README.md
Labels: Skip Changelog

#465 [Resizer] Add tests
  src/components/TextField/components/Resizer/Resizer.tsx
  src/components/TextField/components/Resizer/tests/Resizer.test.tsx
Labels: Skip Changelog, Testing

#648 Provide better error messaging when README examples have syntax errors
  documentation/Component READMEs.md
  tophat/parseMarkdown.js
Labels: Skip Changelog

#466 [Tabs] Add tests
  src/components/Tabs/Tabs.tsx
  src/components/Tabs/components/List/tests/List.test.tsx
  src/components/Tabs/components/TabMeasurer/tests/TabMeasurer.test.tsx
  src/components/Tabs/tests/Tabs.test.tsx
  src/components/Tabs/utilities.ts
Labels: Skip Changelog, Testing

#647 Prevent polaris-react 3.0.x hotfixes from getting deployed under the 'latest' tag
  package.json
  scripts/deploy.js
  shipit.yml
Labels: Skip Changelog

#524 AppProvider Cleanup
  src/components/AppProvider/AppProvider.tsx
  src/components/AppProvider/index.ts
  src/components/AppProvider/tests/AppProvider.test.tsx
  src/components/AppProvider/types.ts
  src/components/AppProvider/utilities/Intl/Intl.ts
  src/components/AppProvider/utilities/Intl/index.ts
  src/components/AppProvider/utilities/Intl/tests/translate.test.ts
  src/components/AppProvider/utilities/Intl/translate.ts
  src/components/AppProvider/utilities/Intl/types.ts
  src/components/AppProvider/utilities/Link/Link.ts
  src/components/AppProvider/utilities/Link/index.ts
  src/components/AppProvider/utilities/ScrollLockManager/ScrollLockManager.ts
  src/components/AppProvider/utilities/ScrollLockManager/index.ts
  src/components/AppProvider/utilities/createAppProviderContext/createAppProviderContext.ts
  src/components/AppProvider/utilities/createAppProviderContext/index.ts
  src/components/AppProvider/utilities/createAppProviderContext/tests/createAppProviderContext.test.tsx
  src/components/AppProvider/utilities/createPolarisContext/createPolarisContext.ts
  src/components/AppProvider/utilities/createPolarisContext/index.ts
  src/components/AppProvider/utilities/createPolarisContext/tests/createPolarisContext.test.tsx
  src/components/AppProvider/utilities/index.ts
  src/components/AppProvider/utilities/withAppProvider/index.ts
  src/components/AppProvider/utilities/withAppProvider/withAppProvider.tsx
  src/components/AppProvider/utilities/withSticky/StickyManager.ts
  src/components/AppProvider/utilities/withSticky/index.ts
  src/components/AppProvider/utilities/withSticky/withSticky.tsx
  src/components/AppProvider/utils/index.tsx
  src/components/UnstyledLink/UnstyledLink.tsx
  src/components/UnstyledLink/tests/UnstyledLink.test.tsx
Labels: Skip Changelog

#679 fixes prop-types import
  src/components/AppProvider/types.ts
Labels: Skip Changelog, Tooling

#691 Fix several cyclical type imports
  src/components/ColorPicker/ColorPicker.tsx
  src/components/ColorPicker/components/AlphaPicker/AlphaPicker.tsx
  src/components/ColorPicker/index.ts
  src/components/DataTable/DataTable.tsx
  src/components/DataTable/components/Cell/Cell.tsx
  src/components/DataTable/components/Navigation/Navigation.tsx
  src/components/DataTable/index.ts
  src/components/DataTable/types.ts
  src/components/DataTable/utilities.ts
  src/components/ResourceList/ResourceList.tsx
  src/components/ResourceList/components/Context/Context.tsx
  src/components/ResourceList/components/FilterControl/FilterControl.tsx
  src/components/ResourceList/components/Item/Item.tsx
  src/components/ResourceList/types.ts
  src/components/Tabs/Tabs.tsx
  src/components/Tabs/components/List/List.tsx
  src/components/Tabs/components/TabMeasurer/TabMeasurer.tsx
  src/components/Tabs/types.ts
  src/components/Tabs/utilities.ts
  src/components/ThemeProvider/ThemeProvider.tsx
  src/components/ThemeProvider/index.ts
  src/components/ThemeProvider/types.ts
  src/components/ThemeProvider/utils/index.ts
  src/components/index.ts
  src/utilities/color-manipulation.ts
  src/utilities/color-transformers.ts
  src/utilities/color-types.ts
  src/utilities/color-validation.ts
  src/utilities/tests/color-manipulation.test.ts
Labels: Skip Changelog

#685 Tophat: Compile all examples in a single pass
  package.json
  playground/app/components/Example.tsx
  playground/app/pages/AllComponents.tsx
  playground/app/pages/ComponentAllExamples.tsx
  playground/app/pages/ComponentSingleExample.tsx
  playground/app/pages/ExamplesList.tsx
  playground/app/types.ts
  playground/webpack.config.js
  playground/webpack/parseMarkdown.js
  playground/webpack/transpileExample.js
  src/components/Page/README.md
  yarn.lock
Labels: Skip Changelog
