Repository Shopify/polaris, pull requests merged in 2018-12, with the labels that each got.

#720 fixes app bridge type imports
  UNRELEASED.md
  src/components/AppProvider/utilities/createPolarisContext/createPolarisContext.ts
  src/test-utilities/enzyme.tsx
Labels: Tooling

#721 Revert "Fix several cyclical type imports"
  .eslintrc
  src/components/ColorPicker/ColorPicker.tsx
  src/components/ColorPicker/components/AlphaPicker/AlphaPicker.tsx
  src/components/ColorPicker/index.ts
  src/components/ColorPicker/types.ts
  src/components/DataTable/DataTable.tsx
  src/components/DataTable/components/Cell/Cell.tsx
  src/components/DataTable/components/Navigation/Navigation.tsx
  src/components/DataTable/index.ts
  src/components/DataTable/types.ts
  src/components/DataTable/utilities.ts
  src/components/ResourceList/ResourceList.tsx
  src/components/ResourceList/components/Context/Context.tsx
  src/components/ResourceList/components/FilterControl/FilterControl.tsx
  src/components/ResourceList/components/Item/Item.tsx
  src/components/ResourceList/types.ts
  src/components/Tabs/Tabs.tsx
  src/components/Tabs/components/List/List.tsx
  src/components/Tabs/components/TabMeasurer/TabMeasurer.tsx
  src/components/Tabs/types.ts
  src/components/Tabs/utilities.ts
  src/components/ThemeProvider/ThemeProvider.tsx
  src/components/ThemeProvider/index.ts
  src/components/ThemeProvider/types.ts
  src/components/ThemeProvider/utils/index.ts
  src/components/index.ts
  src/utilities/color-manipulation.ts
  src/utilities/color-transformers.ts
  src/utilities/color-validation.ts
  src/utilities/tests/color-manipulation.test.ts
Labels: Skip Changelog

#756 [Scrollable] Test unmount
  src/components/Scrollable/tests/Scrollable.test.tsx
Labels: Skip Changelog

#764 [Documentation] Add syntax highlighting to console logging guidelines
  documentation/Console messages.md
Labels: Skip Changelog

#748 [ResourceList] Remove comment
  src/components/ResourceList/components/Item/Item.tsx
Labels: Skip Changelog

#714 [CalloutCard] Add dismiss button & callback
  UNRELEASED.md
  src/components/CalloutCard/CalloutCard.scss
  src/components/CalloutCard/CalloutCard.tsx
  src/components/CalloutCard/README.md
  src/components/CalloutCard/tests/CalloutCard.test.tsx
Labels: Bug fix

#774 [Tooltip] Updated example to initially be active
  src/components/Tooltip/README.md
Labels: Skip Changelog
