Repository Shopify/polaris, pull requests merged in 2019-04, with the labels that each got.

#1273 [DataTable] Fix sortable header clickable area
  UNRELEASED.md
  src/components/DataTable/DataTable.scss
Labels: Bug fix

#1274 Remove unused crypto dependency
  package.json
  yarn.lock
Labels: Dependency, Skip Changelog

#1275 Fixed typo in ReadMe ('you' -> 'your').
  README.md
Labels: cla-needed

#1289 Use @percy/storybook - the changed the package name with v3
  package.json
  yarn.lock
Labels: Skip Changelog

#1290 Stop false positives in percy
  .storybook/preview-head.html
Labels: Skip Changelog

#1306 [Code Quality] Consistent use of `text-breakword` mixin
  UNRELEASED.md
  src/components/Banner/Banner.scss
  src/components/Labelled/Labelled.scss
  src/components/Modal/components/Header/Header.scss
Labels: Priority: Low, Sass

#1268 Upgrade to polaris-tokens 2.5.0
  UNRELEASED.md
  package.json
  src/components/Frame/Frame.scss
  src/components/Frame/Frame.tsx
  src/components/Modal/components/Dialog/Dialog.tsx
  src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx
  src/components/ResourceList/components/BulkActions/BulkActions.tsx
  src/components/shared.ts
  src/styles/foundation/duration.scss
  yarn.lock
Labels: Dependency, Motion, Package, Sass

#1255 [AppProvider] Remove componentWillReceiveProps
  UNRELEASED-V4.md
  src/components/AppProvider/AppProvider.tsx
  src/components/AppProvider/tests/AppProvider.test.tsx
Labels: Skip Changelog

#1069 Add a retry on failure of update version, PR for update Polaris on multiple repos
  UNRELEASED.md
  package.json
  scripts/new-version-pr-generator.js
  scripts/open-styleguide-pr.js
  scripts/utilities/retry.js
Labels: Tooling

#1309 [Labelled] Contents can now wrap onto multiple lines
  UNRELEASED.md
  src/components/Labelled/Labelled.scss
  src/components/Labelled/Labelled.tsx
Labels: Enhancement

#1254 [ThemeProvider] Remove componentWillReceiveProps
  UNRELEASED-V4.md
  src/components/ThemeProvider/ThemeProvider.tsx
  src/components/ThemeProvider/tests/ThemeProvider.test.tsx
Labels: 🤖Skip Changelog

#1300 Remove duplicate declaration of top-bar-height()
  src/styles/foundation.scss
  src/styles/foundation/settings.scss
Labels: 🤖Skip Changelog

#1364 [a11y] Add documentation for the badge component
  UNRELEASED.md
  src/components/Badge/README.md
Labels: 📓 Documentation

#1366 [a11y] Add docs for card and callout card components
  UNRELEASED.md
  src/components/CalloutCard/README.md
  src/components/Card/README.md
Labels: 📓 Documentation

#1365 [a11y] Add action and option list accessibility docs
  UNRELEASED.md
  src/components/ActionList/README.md
  src/components/OptionList/README.md
Labels: 📓 Documentation

#1362 Add checklist and instructions updating and tophatting documentation changes
  .github/PULL_REQUEST_TEMPLATE.md
  UNRELEASED.md
  documentation/Tophatting documentation.md
Labels: 📓 Documentation

#1385 [documentation] Fix spinner mobile example
  src/components/Spinner/README.md
Labels: 🤖Skip Changelog

#1383 [documentation] Fix Button mobile examples
  src/components/Button/README.md
Labels: 🤖Skip Changelog

#1386 [documentation] DisplayText: hide Large example from mobile tabs
  src/components/DisplayText/README.md
Labels: 🤖Skip Changelog
