Repository Shopify/polaris, pull requests merged in 2019-02, with the labels that each got.

#951 [Collapsible] Set `overflow: visible` once the Collapsible is fully open
  UNRELEASED.md
  src/components/Collapsible/Collapsible.scss
  src/components/Collapsible/Collapsible.tsx
Labels: Quick win, Sass

#918 [DataTable] Fixes initial sort direction not set in sort handler
  UNRELEASED.md
  src/components/DataTable/DataTable.tsx
Labels: Bug fix

#1003 [DataTable] Add full example of data table to documentation
  UNRELEASED.md
  src/components/DataTable/README.md
Labels: Documentation

#978 [ResourceList] Add full example of resource list to styleguide
  UNRELEASED.md
  src/components/ResourceList/README.md
Labels: Documentation

#939 [Card] Add full example to styleguide
  UNRELEASED.md
  src/components/Card/README.md
Labels: Documentation

#1040 Ping Ben when a PR is opened on the style guide
  scripts/open-styleguide-pr.js
Labels: Skip Changelog

#1043 [Range slider] Fix changelog entry
  UNRELEASED.md
Labels: RangeSlider, Skip Changelog

#1047 [TextField] Fix the weird Backdrop issue on Chrome
  UNRELEASED.md
  src/components/TextField/TextField.scss
Labels: Bug fix, Quick win, Sass

#1045 Use index imports for all svg files
  src/components/Banner/Banner.tsx
  src/components/Banner/icons/confetti.svg
  src/components/Banner/icons/index.ts
  src/components/Banner/tests/Banner.test.tsx
  src/components/DropZone/DropZone.tsx
  src/components/DropZone/components/FileUpload/FileUpload.tsx
  src/components/DropZone/icons/index.ts
  src/components/DropZone/images/index.ts
  src/components/EmptySearchResult/EmptySearchResult.tsx
  src/components/EmptySearchResult/illustrations/index.ts
  src/components/EmptySearchResult/tests/EmptySearchResult.test.tsx
  src/components/ResourceList/ResourceList.tsx
  src/components/ResourceList/icons/index.ts
  src/components/Spinner/Spinner.tsx
  src/components/Spinner/icons/index.ts
  yarn.lock
Labels: Skip Changelog

#1074 Remove custom svg transformer for tests
  config/jest/transformers/svg.js
  sewing-kit.config.ts
  src/components/Spinner/tests/Spinner.test.tsx
Labels: Skip Changelog

#1056 [Sass] Import token for spacing
  package.json
  src/styles/foundation/spacing.scss
  yarn.lock
Labels: Skip Changelog

#1076 [Documentation] Add link to console message guidelines in deprecation guidelines
  documentation/Deprecation guidelines.md
Labels: Skip Changelog

#1080 Resolve unsupported React Fragment syntax
  UNRELEASED.md
  src/components/TopBar/components/UserMenu/components/UserMenu/UserMenu.tsx
Labels: Bug, Critical

#1086 Update eslint-plugin-shopify
  .eslintrc
  src/components/AppProvider/AppProvider.tsx
  src/components/Collapsible/Collapsible.tsx
  src/components/DropZone/components/FileUpload/FileUpload.tsx
  src/components/OptionList/OptionList.tsx
  src/components/PositionedOverlay/PositionedOverlay.tsx
  src/components/ResourceList/ResourceList.tsx
  src/components/Tabs/Tabs.tsx
  src/components/ThemeProvider/ThemeProvider.tsx
  src/utilities/react-compose.tsx
  yarn.lock
Labels: Skip Changelog

#1075 Loading a11y docs
  UNRELEASED.md
  src/components/Loading/README.md
Labels: Accessibility, Documentation

#1073 [a11y] Inline error a11y docs
  UNRELEASED.md
  src/components/InlineError/README.md
Labels: Accessibility, Documentation

#1071 [a11y] Banner a11y docs
  UNRELEASED.md
  src/components/Banner/README.md
Labels: Accessibility, Documentation

#1092 Update instructions for testing on mobile to reflect Storybook iframe
  README.md
Labels: Skip Changelog, cla-needed

#1070 [Range slider] Use spacing base-tight
  src/components/RangeSlider/components/SingleThumb/SingleThumb.scss
Labels: RangeSlider, Skip Changelog
