Repository Shopify/polaris, pull requests merged in 2019-09, with the labels that each got.

#2068 [ResourceList] Fix link to ResourceItem in documentation
  src/components/ResourceList/README.md
Labels: 🤖Skip Changelog

#2093 Add displayName to WithAppProvider HoC
  UNRELEASED.md
  src/utilities/with-app-provider.tsx
Labels: 🤖Skip Changelog

#2101 [Content] Update links to headings content guidelines
  src/components/Heading/README.md
  src/components/Layout/README.md
  src/components/Modal/README.md
  src/components/Subheading/README.md
Labels: 🤖Skip Changelog

#2120 Create approve-dependabot.yml
  .github/workflows/approve-dependabot.yml
Labels: 🤖Skip Changelog

#2073 [Link] Fix documentation and examples
  src/components/Link/README.md
Labels: 📓 Documentation, 🤖Skip Changelog

#2112 [Content] Replace repeated heading content guidelines with cross links
  src/components/AccountConnection/README.md
  src/components/Banner/README.md
  src/components/CalloutCard/README.md
  src/components/Card/README.md
  src/components/Collapsible/README.md
  src/components/EmptyState/README.md
  src/components/FormLayout/README.md
  src/components/Heading/README.md
  src/components/KeyboardKey/README.md
  src/components/Layout/README.md
  src/components/Modal/README.md
  src/components/Subheading/README.md
Labels: 🤖Skip Changelog

#2143 Use generics for typing UnstyleLink's forwardRef
  src/components/UnstyledLink/UnstyledLink.tsx
Labels: 🤖Skip Changelog

#2047 [Color system] remove filter control
  UNRELEASED-v5.md
  locales/de.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/it.json
  locales/ja.json
  locales/ms.json
  locales/nl.json
  locales/pt-BR.json
  locales/zh-CN.json
  locales/zh-TW.json
  src/components/ResourceList/ResourceList.tsx
  src/components/ResourceList/components/FilterControl/FilterControl.scss
  src/components/ResourceList/components/FilterControl/FilterControl.tsx
  src/components/ResourceList/components/FilterControl/components/DateSelector/DateSelector.scss
  src/components/ResourceList/components/FilterControl/components/DateSelector/DateSelector.tsx
  src/components/ResourceList/components/FilterControl/components/DateSelector/index.ts
  src/components/ResourceList/components/FilterControl/components/DateSelector/tests/DateSelector.test.tsx
  src/components/ResourceList/components/FilterControl/components/FilterCreator/FilterCreator.tsx
  src/components/ResourceList/components/FilterControl/components/FilterCreator/index.ts
  src/components/ResourceList/components/FilterControl/components/FilterCreator/tests/FilterCreator.test.tsx
  src/components/ResourceList/components/FilterControl/components/FilterValueSelector/FilterValueSelector.tsx
  src/components/ResourceList/components/FilterControl/components/FilterValueSelector/index.ts
  src/components/ResourceList/components/FilterControl/components/FilterValueSelector/tests/FilterValueSelector.test.tsx
  src/components/ResourceList/components/FilterControl/components/index.ts
  src/components/ResourceList/components/FilterControl/index.ts
  src/components/ResourceList/components/FilterControl/tests/FilterControl.test.tsx
  src/components/ResourceList/components/FilterControl/types.ts
  src/components/ResourceList/components/index.ts
  src/components/ResourceList/index.ts
  src/components/index.ts
  tests/setup.ts
Labels: 🤖Skip Changelog

#2046 [Color system] remove app bridge
  README.md
  UNRELEASED-v5.md
  documentation/Component READMEs.md
  documentation/Embedded apps.md
  package.json
  src/components/ActionMenu/tests/ActionMenu.test.tsx
  src/components/AppProvider/AppProvider.tsx
  src/components/AppProvider/README.md
  src/components/Breadcrumbs/tests/Breadcrumbs.test.tsx
  src/components/ContextualSaveBar/README.md
  src/components/ContextualSaveBar/tests/ContextualSaveBar.test.tsx
  src/components/Frame/README.md
  src/components/Loading/Loading.tsx
  src/components/Loading/README.md
  src/components/Loading/tests/Loading.test.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/README.md
  src/components/Modal/components/Footer/Footer.tsx
  src/components/Modal/tests/Modal.test.tsx
  src/components/Navigation/README.md
  src/components/Page/Page.tsx
  src/components/Page/README.md
  src/components/Page/components/Header/Header.tsx
  src/components/Page/components/Header/components/Title/Title.tsx
  src/components/Page/components/Header/tests/Header.test.tsx
  src/components/Page/tests/Page.test.tsx
  src/components/Page/types.ts
  src/components/PolarisTestProvider/PolarisTestProvider.tsx
  src/components/ResourcePicker/README.md
  src/components/ResourcePicker/ResourcePicker.tsx
  src/components/ResourcePicker/index.ts
  src/components/ResourcePicker/tests/ResourcePicker.test.tsx
  src/components/SkeletonPage/SkeletonPage.tsx
  src/components/SkeletonPage/tests/SkeletonPage.test.tsx
  src/components/Toast/README.md
  src/components/Toast/Toast.tsx
  src/components/Toast/tests/Toast.test.tsx
  src/components/TopBar/README.md
  src/components/index.ts
  src/index.ts
  src/types.ts
  src/utilities/app-bridge-transformers.ts
  src/utilities/app-bridge/app-bridge.ts
  src/utilities/app-bridge/context.tsx
  src/utilities/app-bridge/hooks.tsx
  src/utilities/app-bridge/index.ts
  src/utilities/app-bridge/tests/app-bridge.test.ts
  src/utilities/app-bridge/tests/hooks.test.tsx
  src/utilities/frame/hooks.ts
  src/utilities/frame/tests/hooks.test.tsx
  src/utilities/frame/types.ts
  src/utilities/tests/app-bridge-transformers.test.ts
  src/utilities/with-app-provider.tsx
  tests/setup.ts
  yarn.lock
Labels: 🤖Skip Changelog

#2151 [Modal] add code coverage for onTransitionEnd and onIframeLoad
  src/components/Modal/tests/Modal.test.tsx
Labels: 🤖Skip Changelog

#2153 [Link] Improve docblocks and readme for links
  UNRELEASED.md
  src/components/Link/Link.tsx
  src/components/Link/README.md
  src/utilities/link/types.ts
Labels: 🤖Skip Changelog

#2152 [FooterHelp] Delete period from example
  src/components/FooterHelp/README.md
Labels: 🎁 Content, 🤖Skip Changelog

#2168 Move node-cmd from dependencies to devDependencies
  package.json
Labels: 🤖Skip Changelog

#2122 Remove polaris domain name from image markdown elements
  src/components/Avatar/README.md
  src/components/Badge/README.md
  src/components/Banner/README.md
  src/components/Button/README.md
  src/components/ButtonGroup/README.md
  src/components/Caption/README.md
  src/components/Card/README.md
  src/components/Checkbox/README.md
  src/components/ChoiceList/README.md
  src/components/Collapsible/README.md
  src/components/DatePicker/README.md
  src/components/DescriptionList/README.md
  src/components/DisplayText/README.md
  src/components/EmptyState/README.md
  src/components/ExceptionList/README.md
  src/components/FormLayout/README.md
  src/components/Heading/README.md
  src/components/InlineError/README.md
  src/components/KeyboardAccessories/README.md
  src/components/List/README.md
  src/components/Modal/README.md
  src/components/Page/README.md
  src/components/Pagination/README.md
  src/components/Popover/README.md
  src/components/RadioButton/README.md
  src/components/RangeSlider/README.md
  src/components/ResourceList/README.md
  src/components/ResourcePicker/README.md
  src/components/SectionHeader/README.md
  src/components/Select/README.md
  src/components/SkeletonBodyText/README.md
  src/components/SkeletonDisplayText/README.md
  src/components/SkeletonPage/README.md
  src/components/Spinner/README.md
  src/components/Stepper/README.md
  src/components/Subheading/README.md
  src/components/Tabs/README.md
  src/components/Tag/README.md
  src/components/TextContainer/README.md
  src/components/TextField/README.md
  src/components/TextStyle/README.md
  src/components/Thumbnail/README.md
  src/components/Toast/README.md
Labels: 🤖Skip Changelog

#2175 Revert v4.2.2-rc.1 commit
  README.md
  package.json
  src/components/README.md
Labels: 🤖Skip Changelog

#2185 [Card] Improve standards compliance via flex-start
  src/components/Card/Card.scss
Labels: 🤖Skip Changelog

#2155 [RenderAfterMount][useMounted] Add utilities
  src/components/AfterInitialMount/AfterInitialMount.tsx
  src/components/AfterInitialMount/index.ts
  src/components/AfterInitialMount/test/AfterInitialMount.test.tsx
  src/utilities/tests/use-is-after-initial-mount.test.tsx
  src/utilities/use-is-after-initial-mount.ts
Labels: 🤖Skip Changelog

#2189 [Banner] Remove period in example link
  src/components/Banner/README.md
Labels: 🤖Skip Changelog

#2195 [v5] Drop support for ios9
  UNRELEASED-v5.md
  package.json
Labels: 🤖Skip Changelog

#2202 [DropZone] Update readme
  src/components/DropZone/README.md
Labels: 🤖Skip Changelog

#2210 [AppProvider] Remove features from state
  src/components/AppProvider/AppProvider.tsx
Labels: 🤖Skip Changelog
