Repository Shopify/polaris, pull requests merged in 2019-07, with the labels that each got.

#1775 Add translations: default
  src/locales/zh-CN.json
Labels: 🤖Skip Changelog

#1732 Add filter and sort keywords to resource list page
  src/components/ResourceList/README.md
Labels: 🤖Skip Changelog

#1777 Add children typing to Frame and Stack
  src/components/Frame/Frame.tsx
  src/components/Stack/Stack.tsx
Labels: 🤖Skip Changelog

#1773 [Sheet] Remove required component as this is no longer true
  src/components/Sheet/README.md
Labels: 🤖Skip Changelog

#1780 [Filters] Update example
  src/components/Filters/README.md
Labels: 🤖Skip Changelog

#1755 [Tabs - Disclosure] Add rollover on Disclosure and high contrast mode
  UNRELEASED.md
  src/components/Tabs/Tabs.scss
Labels: Accessibility

#1778 [Sheet] Remove note about not supported in embedded apps
  src/components/Sheet/README.md
Labels: 🤖Skip Changelog

#1779 Add translations: default
  src/locales/zh-CN.json
Labels: 🤖Skip Changelog

#1741 Fixed toast manager
  UNRELEASED-V4.md
  src/components/Frame/components/ToastManager/ToastManager.tsx
  src/components/Toast/Toast.tsx
  src/hooks/use-deep-compare/use-deep-compare.tsx
  src/types.ts
  src/utilities/use-deep-callback.tsx
  src/utilities/use-deep-compare-ref.tsx
Labels: 🤖Skip Changelog

#1756 Removed css transition from popover overlay
  UNRELEASED-V4.md
  src/components/Popover/Popover.scss
  src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx
Labels: 🤖Skip Changelog

#1759 [v4] Switch react-transition-group versions
  UNRELEASED-V4.md
  config/typescript/react-transition-group.d.ts
  package.json
  src/components/Frame/Frame.tsx
  src/components/Frame/components/ToastManager/ToastManager.tsx
  src/components/Frame/tests/Frame.test.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/components/Dialog/Dialog.tsx
  src/components/ResourceList/components/BulkActions/BulkActions.scss
  src/components/ResourceList/components/BulkActions/BulkActions.tsx
  src/components/ResourceList/components/BulkActions/tests/BulkActions.test.tsx
  src/components/ResourceList/components/CheckableButton/CheckableButton.scss
  src/components/Sheet/Sheet.tsx
  src/components/Sheet/tests/Sheet.test.tsx
  src/test-utilities/legacy.tsx
  src/test-utilities/tests/legacy.test.tsx
  yarn.lock
Labels: 🤖Skip Changelog

#1797 [v4] Use hooks in components where it's easy
  UNRELEASED-V4.md
  src/components/Badge/Badge.tsx
  src/components/Button/Button.tsx
  src/components/ChoiceList/ChoiceList.tsx
  src/components/Collapsible/Collapsible.tsx
  src/components/DataTable/components/Cell/Cell.tsx
  src/components/DataTable/components/Navigation/Navigation.tsx
  src/components/DatePicker/components/Month/Month.tsx
  src/components/Frame/components/ContextualSaveBar/components/DiscardConfirmationModal/DiscardConfirmationModal.tsx
  src/components/Icon/Icon.tsx
  src/components/Modal/components/CloseButton/CloseButton.tsx
  src/components/Pagination/Pagination.tsx
  src/components/ProgressBar/ProgressBar.tsx
  src/components/ProgressBar/tests/ProgressBar.test.tsx
  src/components/ResourceList/components/CheckableButton/CheckableButton.tsx
  src/components/Sheet/Sheet.tsx
  src/components/Spinner/Spinner.tsx
  src/components/Tag/Tag.tsx
Labels: 🤖Skip Changelog

#1783 [Tooltip] Implement fix for MouseOver event not firing when cursor enters after leaving a disabled element
  UNRELEASED.md
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/tests/Tooltip.test.tsx
Labels: 🐛Bug

#1805 Don't pass polaris from Link into UnstyledLink
  src/components/Link/Link.tsx
Labels: 🤖Skip Changelog

#1807 [Content] Add cross link to button content guidelines
  src/components/Button/README.md
  src/components/ButtonGroup/README.md
Labels: 🤖Skip Changelog

#1815 [Shopify/polaris-bot] Update post-release web upgrade PR description
  scripts/new-version-pr-generator.js
Labels: 🤖Skip Changelog

#1806 [v4] Hookify Link component
  src/components/Link/Link.tsx
Labels: 🤖Skip Changelog

#1822 [a11y] [Navigation] Improve nav focus and hover states
  UNRELEASED.md
  src/components/Navigation/Navigation.scss
  src/components/Navigation/_variables.scss
Labels: Accessibility

#1809 [Content] Remove Latin abbreviations from component pages
  src/components/AccountConnection/README.md
  src/components/ActionList/README.md
  src/components/Avatar/README.md
  src/components/Badge/README.md
  src/components/DatePicker/README.md
  src/components/Layout/README.md
  src/components/List/README.md
  src/components/PageActions/README.md
  src/components/SettingToggle/README.md
  src/components/TextField/README.md
Labels: 🤖Skip Changelog

#1813 Hooky withAppProvider
  src/components/Avatar/tests/Avatar-ssr.test.tsx
  src/components/Avatar/tests/Avatar.test.tsx
  src/components/ColorPicker/tests/ColorPicker-ssr.test.tsx
  src/components/ColorPicker/tests/ColorPicker.test.tsx
  src/utilities/with-app-provider.tsx
Labels: 🤖Skip Changelog

#1795 [SearchInput] fix firefox clear button overflow
  UNRELEASED.md
  src/components/TopBar/components/SearchField/SearchField.scss
Labels: 🐛Bug

#1722 [Avatar] Follow content guidelines for dimensions
  src/components/Avatar/README.md
Labels: 🤖Skip Changelog

#1810 [v4] Export TestProvider with defaults and fix typescript react issue
  src/components/Banner/Banner.tsx
  src/components/Banner/tests/Banner.test.tsx
  src/components/Card/Card.tsx
  src/components/Card/tests/Card.test.tsx
  src/components/ContextualSaveBar/tests/ContextualSaveBar.test.tsx
  src/components/DropZone/components/FileUpload/tests/FileUpload.test.tsx
  src/components/Loading/tests/Loading.test.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/tests/Modal.test.tsx
  src/components/Navigation/Navigation.tsx
  src/components/Navigation/tests/Navigation.test.tsx
  src/components/ResourceList/components/FilterControl/tests/FilterControl.test.tsx
  src/components/Toast/tests/Toast.test.tsx
  src/components/WithinContentContext/context.tsx
  src/components/WithinContentContext/index.ts
  src/components/index.ts
  src/index.ts
  src/test-utilities/PolarisTestProvider.tsx
  src/test-utilities/legacy.tsx
  src/test-utilities/react-testing.tsx
  src/test-utilities/tests/PolarisTestProvider.test.tsx
  src/test-utilities/tests/react-testing.test.tsx
  src/test-utilities/types.ts
  src/utilities/app-bridge/context.tsx
  src/utilities/banner-context.tsx
  src/utilities/i18n/context.tsx
  src/utilities/link/context.tsx
  src/utilities/scroll-lock-manager/context.tsx
  src/utilities/sticky-manager/context.tsx
  src/utilities/within-content-context.tsx
Labels: 🤖Skip Changelog

#1823 [v4] Change matcher layout
  package.json
  src/test-utilities/matchers/index.ts
  src/test-utilities/matchers/types.ts
  tests/each-test.ts
  tests/matchers/index.ts
  tests/matchers/props.ts
  tsconfig.json
  yarn.lock
Labels: 🤖Skip Changelog

#1844 Update Card README to not used deprecated prop
  src/components/Card/README.md
Labels: 🤖Skip Changelog

#1838 [Collapsible] Hide content when exited
  src/components/Collapsible/Collapsible.scss
  src/components/Collapsible/Collapsible.tsx
  src/components/Collapsible/tests/Collapsible.test.tsx
Labels: 🤖Skip Changelog

#1830 [v4] Remove unwanted subcomponent aliases in Autocomplete Combobox
  UNRELEASED-V4.md
  src/components/Autocomplete/components/ComboBox/ComboBox.tsx
Labels: 🤖Skip Changelog

#1831 [v4] Remove deprecated functionality
  UNRELEASED-V4.md
  src/components/Card/Card.tsx
  src/components/Card/README.md
  src/components/Card/tests/Card.test.tsx
  src/components/Navigation/README.md
  src/components/Navigation/components/Item/Item.tsx
  src/components/Navigation/components/Item/tests/Item.test.tsx
  src/components/Select/Select.tsx
  src/components/Select/tests/Select.test.tsx
  src/styles/shared/lists.scss
Labels: 🤖Skip Changelog

#1857 Revert consistent-rem
  UNRELEASED-V4.md
  src/components/Sheet/README.md
  src/styles/foundation/utilities.scss
  src/styles/global.scss
Labels: 🤖Skip Changelog

#1859 [v4] Remove deprecation message regarding Page Header icon
  locales/de.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/it.json
  locales/ja.json
  locales/ms.json
  locales/nl.json
  locales/pt-BR.json
  locales/zh-CN.json
  locales/zh-TW.json
  src/components/Page/components/Header/Header.tsx
  src/components/Page/components/Header/tests/Header.test.tsx
Labels: 🤖Skip Changelog

#1855 [v4] Fix "Function components do not support contextType" error in tests
  package.json
  src/utilities/with-app-provider.tsx
  yarn.lock
Labels: 🤖Skip Changelog

#1808 [v4] Fixed popover overlay positioning
  src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx
  src/components/PositionedOverlay/PositionedOverlay.tsx
Labels: 🤖Skip Changelog

#1862 [v4] Remove unused type defintions
  UNRELEASED-V4.md
  config/typescript/images.d.ts
  config/typescript/modules.d.ts
  config/typescript/prop-types.d.ts
Labels: 🤖Skip Changelog

#1580 Create isObjectsEqual to replace _.isEqual
  UNRELEASED-V4.md
  src/components/DataTable/DataTable.tsx
  src/components/Focus/Focus.tsx
  src/components/Modal/Modal.tsx
  src/components/Page/Page.tsx
  src/components/RangeSlider/components/DualThumb/DualThumb.tsx
  src/components/ResourceList/components/Item/Item.tsx
  src/components/ResourcePicker/ResourcePicker.tsx
  src/components/ThemeProvider/ThemeProvider.tsx
  src/utilities/is-objects-equal.ts
  src/utilities/tests/isObjectsEqual.test.ts
  src/utilities/theme/tests/hooks.test.tsx
  src/utilities/use-deep-compare-ref.tsx
Labels: 🤖Skip Changelog

#1875 [v4][Collapsible] Fix collapsible regression
  src/components/Collapsible/Collapsible.scss
  src/components/Collapsible/Collapsible.tsx
Labels: 🤖Skip Changelog

#1876 Bump sewing-kit to latest
  package.json
  yarn.lock
Labels: 🤖Skip Changelog

#1872 Add translations: default
  src/locales/ms.json
Labels: 🤖Skip Changelog

#1879 [v4] Improve testing
  package.json
  src/components/ContextualSaveBar/tests/ContextualSaveBar.test.tsx
  src/components/Frame/components/ContextualSaveBar/tests/ContextualSaveBar.test.tsx
  src/components/Frame/index.ts
  src/components/Frame/utilities/createFrameContext/createFrameContext.ts
  src/components/Frame/utilities/createFrameContext/index.ts
  src/components/Frame/utilities/createFrameContext/tests/createFrameContext.test.ts
  src/components/Frame/utilities/index.ts
  src/components/Loading/tests/Loading.test.tsx
  src/components/RadioButton/tests/RadioButton.test.tsx
  src/components/Toast/tests/Toast.test.tsx
  src/components/TopBar/tests/TopBar.test.tsx
  src/test-utilities/PolarisTestProvider.tsx
  src/test-utilities/legacy.tsx
  src/test-utilities/react-testing.tsx
  src/test-utilities/types.ts
  src/utilities/app-bridge/tests/hooks.test.tsx
  src/utilities/i18n/tests/hooks.test.tsx
  src/utilities/link/tests/hooks.test.tsx
  src/utilities/scroll-lock-manager/tests/hooks.test.tsx
  src/utilities/sticky-manager/tests/hooks.test.tsx
  src/utilities/theme/index.ts
  src/utilities/theme/tests/hooks.test.tsx
  src/utilities/theme/utils.ts
  yarn.lock
Labels: 🤖Skip Changelog

#1883 Improve tsconfig
  UNRELEASED-V4.md
  src/components/Autocomplete/tests/Autocomplete.test.tsx
  src/utilities/app-bridge/tests/app-bridge.test.ts
  src/utilities/tests/app-bridge-transformers.test.ts
  tsconfig.json
Labels: 🤖Skip Changelog

#1877 [v4] Updated appbridge example to use new context
  UNRELEASED-V4.md
  src/components/AppProvider/README.md
  src/index.ts
Labels: 🤖Skip Changelog

#1870 [scripts] Only add prod asset checklist to post-release upgrade PRs in web
  scripts/new-version-pr-generator.js
Labels: 🤖Skip Changelog

#1900 Use act in Navigation Item test to fix warning
  src/components/Navigation/components/Item/tests/Item.test.tsx
  src/test-utilities/legacy.tsx
Labels: 🤖Skip Changelog

#1899 Remove Modal.Dialog and Tabs.Panel public subcomponents
  UNRELEASED-V4.md
  src/components/Modal/Modal.tsx
  src/components/Modal/tests/Modal.test.tsx
  src/components/Tabs/Tabs.tsx
Labels: 🤖Skip Changelog
