Repository Shopify/polaris, pull requests merged in 2019-01, with the labels that each got.

#780 Update browser tophatting guide
  documentation/Tophatting.md
Labels: Skip Changelog

#817 Restore dev test
  dev.yml
Labels: Skip Changelog

#843 [RangeSlider] Remove accessiblityInputs
  src/components/RangeSlider/components/DualThumb/DualThumb.scss
  src/components/RangeSlider/components/DualThumb/DualThumb.tsx
  src/components/RangeSlider/components/DualThumb/tests/DualThumb.test.tsx
  src/components/RangeSlider/types.ts
Labels: RangeSlider, Skip Changelog

#850 [RangeSlider] event handler cleanup
  src/components/RangeSlider/components/DualThumb/DualThumb.tsx
Labels: Skip Changelog

#857 Remove the last vestiges of Indicator from Button
  src/components/Button/Button.tsx
Labels: Skip Changelog

#861 Version bumps storybook and fix README hotreloading
  .storybook/config.js
  .storybook/stories-from-readme.js
  package.json
  yarn.lock
Labels: Skip Changelog

#866 [Range slider] better sanitization and tests
  src/components/RangeSlider/RangeSlider.tsx
  src/components/RangeSlider/components/DualThumb/DualThumb.scss
  src/components/RangeSlider/components/DualThumb/DualThumb.tsx
  src/components/RangeSlider/components/DualThumb/tests/DualThumb.test.tsx
  src/components/RangeSlider/types.ts
Labels: RangeSlider, Skip Changelog

#893 [Tabs] Accessibility
  UNRELEASED.md
  src/components/Tabs/README.md
Labels: #accessibility, Accessibility

#900 [Banner] [Card] [Modal] convert banner legacy context API to use create context
  UNRELEASED-V4.md
  src/components/Banner/Banner.tsx
  src/components/Banner/tests/Banner.test.tsx
  src/components/Card/Card.tsx
  src/components/Card/tests/Card.test.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/tests/Modal.test.tsx
  src/components/WithinContentContext/WithinContentContext.tsx
  src/components/WithinContentContext/index.ts
  src/types.ts
Labels: Skip Changelog

#894 [Range slider] test dual thumb key press
  src/components/RangeSlider/components/DualThumb/DualThumb.tsx
  src/components/RangeSlider/components/DualThumb/tests/DualThumb.test.tsx
Labels: RangeSlider, Skip Changelog

#878 Adds example to deprecation guidelines
  documentation/Deprecation guidelines.md
Labels: Skip Changelog

#772 [Stack.Item] Add Stack.Item properties to style guide documentation
  UNRELEASED.md
  src/components/Stack/README.md
  src/components/Stack/components/Item/Item.tsx
Labels: Documentation, Good first issue, Priority: Low

#916 [Popover] Remove duplicate `activatorWrapper` prop
  UNRELEASED.md
  src/components/Popover/Popover.tsx
Labels: Difficulty: Low, Priority: Low

#909 Remove react-html
  package.json
  yarn.lock
Labels: Skip Changelog

#922 Removes redundant Navigation/UserMenu.scss file
  src/components/Navigation/components/UserMenu/UserMenu.scss
Labels: Skip Changelog

#891 Don't use math on colors as it is deprecated
  src/styles/foundation/colors.scss
Labels: Skip Changelog

#895 Specify babel config in babel.config.js
  .storybook/.babelrc
  .storybook/webpack.config.js
  babel.config.js
  scripts/build.js
  sewing-kit.config.ts
Labels: Skip Changelog

#938 fixes typescript/react.d.ts not found error in Consumer.d.ts
  src/components/TopBar/components/UserMenu/context/Consumer.ts
Labels: Skip Changelog

#941 Remove a deep-link to an example as the styleguide doesn't support them
  src/components/Stack/README.md
Labels: Skip Changelog

#943 Improve Stack vertical alignment example
  src/components/Stack/README.md
Labels: Skip Changelog
