Repository Shopify/polaris, pull requests merged in 2019-10, with the labels that each got.

#2229 [Color system] default features to empty object in test environment and export use features hook
  src/components/PolarisTestProvider/PolarisTestProvider.tsx
  src/utilities/features/index.ts
Labels: 🤖Skip Changelog

#2235 [i18n] Add new beta and future supported languages
  translation.yml
Labels: 🌐 International

#2238 [package.json] Point homepage field to polaris.shopify.com
  package.json
Labels: 🤖Skip Changelog

#1917 [Color system] Build color variant generation factory
  src/components/ThemeProvider/ThemeProvider.tsx
  src/components/ThemeProvider/tests/ThemeProvider.test.tsx
  src/utilities/theme/tests/utils.test.ts
  src/utilities/theme/types.ts
  src/utilities/theme/utils.ts
Labels: 🤖Skip Changelog

#2240 [Color system] fix default topbar colors
  src/components/ThemeProvider/tests/ThemeProvider.test.tsx
  src/utilities/theme/utils.ts
Labels: 🤖Skip Changelog

#2232 Ensuring tabs collapse in small screens on <iOS 13
  UNRELEASED.md
  src/components/Tabs/Tabs.scss
Labels: 🐛Bug

#2223 [RangeSlider] Fix example spacing; specify dual range slider example as web only
  src/components/RangeSlider/README.md
Labels: 🤖Skip Changelog

#2257 Removed log from example
  src/components/Frame/README.md
Labels: 🤖Skip Changelog

#2252 [Button][Color system] Apply color system
  src/components/Button/Button.scss
  src/styles/_common.scss
  src/styles/foundation.scss
  src/styles/foundation/_focus-ring.scss
  src/styles/shared/_buttons.scss
  src/styles/shared/_typography.scss
  src/utilities/theme/utils.ts
Labels: 🤖Skip Changelog

#2268 [Color system] don't output legacy custom properties when global theming is enabled
  src/utilities/theme/tests/utils.test.ts
  src/utilities/theme/utils.ts
Labels: 🤖Skip Changelog

#2203 [useEventListener][useComponentDidMount] Add useComponentDidMount & useEventListener
  src/utilities/tests/use-component-did-mount.test.tsx
  src/utilities/tests/use-event-listener.test.tsx
  src/utilities/use-component-did-mount.ts
  src/utilities/use-event-listener.ts
Labels: 🤖Skip Changelog

#2269 [Color system] move background color and text color from body to theme provider node, and apply color system
  src/components/ThemeProvider/ThemeProvider.tsx
  src/components/ThemeProvider/tests/ThemeProvider.test.tsx
  src/styles/shared/_typography.scss
Labels: 🤖Skip Changelog

#2278 fix typos
  CHANGELOG.md
  src/utilities/tests/use-event-listener.test.tsx
Labels: 🤖Skip Changelog

#2276 [Color system] Initial pass at applying the color system
  src/components/Badge/Badge.scss
  src/components/Badge/Badge.tsx
  src/components/Banner/Banner.scss
  src/components/Card/Card.scss
  src/components/Frame/Frame.scss
  src/components/Navigation/Navigation.scss
  src/components/Popover/Popover.scss
  src/components/TopBar/TopBar.scss
  src/components/TopBar/components/Menu/Menu.scss
  src/components/TopBar/components/SearchField/SearchField.scss
  src/components/TopBar/components/UserMenu/UserMenu.scss
  src/utilities/theme/utils.ts
Labels: 🤖Skip Changelog

#2279 [Color system] Apply color system to navigation
  src/components/Navigation/Navigation.scss
  src/components/Navigation/_variables.scss
  src/styles/foundation/_focus-ring.scss
  src/utilities/theme/tests/utils.test.ts
  src/utilities/theme/utils.ts
Labels: 🤖Skip Changelog

#2275 Use functional components in tests
  src/components/Banner/tests/Banner.test.tsx
  src/components/Popover/tests/Popover.test.tsx
  src/components/Portal/tests/Portal.test.tsx
  src/components/ScrollLock/tests/ScrollLock.test.tsx
Labels: 🤖Skip Changelog

#2285 [Color system] add critical action variants, simplify neutral actions, add surface actions
  src/components/Badge/Badge.scss
  src/components/Navigation/Navigation.scss
  src/components/Navigation/_variables.scss
  src/components/TopBar/components/SearchField/SearchField.scss
  src/styles/shared/_buttons.scss
  src/utilities/theme/tests/utils.test.ts
  src/utilities/theme/types.ts
  src/utilities/theme/utils.ts
Labels: 🤖Skip Changelog

#2289 [Color system] apply color system to critical button
  src/components/Button/Button.scss
Labels: 🤖Skip Changelog

#2288 [Color system] Name cleanup
  src/components/Navigation/Navigation.scss
  src/components/Navigation/_variables.scss
  src/styles/foundation/_focus-ring.scss
  src/styles/shared/_buttons.scss
  src/utilities/theme/utils.ts
Labels: 🤖Skip Changelog

#2290 [Color system] Fix surface role name
  src/utilities/theme/tests/utils.test.ts
  src/utilities/theme/utils.ts
Labels: 🤖Skip Changelog

#2291 [Color system] Move hex values to an enum and export it
  src/types.ts
  src/utilities/theme/index.ts
  src/utilities/theme/utils.ts
Labels: 🤖Skip Changelog

#2298 🐛[Sass] Fix recolor-icon mixin
  UNRELEASED.md
  src/styles/shared/_icons.scss
Labels: 🐛Bug

#2300 Remove custom css from `OptionList` section title
  UNRELEASED.md
  src/components/OptionList/OptionList.scss
Labels: 🎨 Design

#2144 [Content] Clarify use cases for buttons and links
  src/components/Button/README.md
  src/components/Link/README.md
Labels: 🤖Skip Changelog

#2311 [Popover] Bring back pass through classes
  src/components/PositionedOverlay/PositionedOverlay.tsx
Labels: 🤖Skip Changelog

#2318 [Color system] apply surface and divider colors to modal
  src/components/Modal/components/Dialog/Dialog.scss
  src/components/Modal/components/Footer/Footer.scss
  src/components/Modal/components/Header/Header.scss
Labels: 🤖Skip Changelog

#2322 4.6.1
  CHANGELOG.md
  README.md
  package.json
  src/components/README.md
Labels: 🤖Skip Changelog

#2323 Run pa11y tests over Global Themeing light mode
  scripts/pa11y.js
Labels: 🤖Skip Changelog

#2327 [Color system][Portal] Remove style attribute from portal node when custom properties are undefined
  src/components/Portal/Portal.tsx
Labels: 🤖Skip Changelog

#2337 [Color system] Add tests for adding and removing styles
  src/components/Portal/tests/Portal.test.tsx
Labels: 🤖Skip Changelog

#2335 [Color system] backwards compatibly implement color system for plain button
  src/components/Button/Button.scss
Labels: 🤖Skip Changelog

#2313 Add vertical adjustment to `OptionList` control items
  UNRELEASED.md
  src/components/Choice/Choice.scss
  src/components/OptionList/components/Option/Option.scss
Labels: 🐛Bug

#2342 [Color system] backwards compatibly implement color system for link
  src/components/Link/Link.scss
Labels: 🤖Skip Changelog

#2344 [Color system] implement color system in sheet, and simplify sheet example
  src/components/Sheet/README.md
  src/components/Sheet/Sheet.scss
Labels: 🤖Skip Changelog

#2348 [Color system] Update surface colors for resource list
  src/components/ResourceList/ResourceList.scss
  src/components/ResourceList/components/CheckableButton/CheckableButton.scss
Labels: 🤖Skip Changelog

#2353 Fix PR link and verb tense
  CHANGELOG.md
Labels: 🤖Skip Changelog

#2345 [Color system] Flatten interaction states
  src/components/ActionList/ActionList.scss
  src/components/Filters/Filters.scss
  src/components/OptionList/components/Option/Option.scss
  src/components/ResourceItem/ResourceItem.scss
  src/components/Tabs/Tabs.scss
Labels: 🤖Skip Changelog

#2347 [Color system] Update surface colors for data table
  src/components/DataTable/DataTable.scss
  src/utilities/theme/tests/utils.test.ts
  src/utilities/theme/utils.ts
Labels: 🤖Skip Changelog

#2365 [Color system] implement color system backwards compatibly for border mixin
  src/styles/foundation/_borders.scss
Labels: 🤖Skip Changelog

#2354 [Color system] implement color system in button round 2
  src/components/Button/Button.scss
  src/components/Button/Button.tsx
  src/components/Button/tests/Button.test.tsx
  src/styles/shared/_buttons.scss
  src/utilities/theme/tests/utils.test.ts
  src/utilities/theme/utils.ts
Labels: 🤖Skip Changelog

#2367 [Color system] backwards compatibly implement color system in action list
  src/components/ActionList/ActionList.scss
  src/components/ActionList/ActionList.tsx
  src/components/ActionList/components/Item/Item.tsx
  src/components/ActionList/components/Item/tests/Item.test.tsx
  src/components/ActionList/tests/ActionList.test.tsx
  src/components/Popover/Popover.scss
  src/utilities/theme/color-adjustments.json
  src/utilities/theme/tests/utils.test.ts
Labels: 🤖Skip Changelog
