Repository Shopify/polaris, pull requests merged in 2019-05, with the labels that each got.

#1384 [documentation] Empty state: fix mobile example
  src/components/EmptyState/README.md
Labels: 🤖Skip Changelog

#1404 [a11y] Icon accessibility docs
  UNRELEASED.md
  src/components/Icon/README.md
Labels: 📓 Documentation

#1397 Applying font-family to button elements
  UNRELEASED.md
  src/styles/global/elements.scss
Labels: ⚗️ Development, 🐛Bug

#1253 [Scrollable] Update context api
  UNRELEASED-V4.md
  src/components/Scrollable/Scrollable.tsx
  src/components/Scrollable/components/Context/Context.ts
  src/components/Scrollable/components/Context/index.ts
  src/components/Scrollable/components/ScrollTo/ScrollTo.tsx
  src/components/Scrollable/components/ScrollTo/tests/ScrollTo.test.tsx
  src/components/Scrollable/components/index.ts
  src/components/Scrollable/tests/Scrollable.test.tsx
  src/components/Scrollable/types.ts
Labels: 🤖Skip Changelog

#1403 [AutoComplete] Use new context api
  UNRELEASED-V4.md
  src/components/Autocomplete/components/ComboBox/ComboBox.tsx
  src/components/Autocomplete/components/ComboBox/components/Context/Context.tsx
  src/components/Autocomplete/components/ComboBox/components/Context/index.ts
  src/components/Autocomplete/components/ComboBox/components/TextField/TextField.tsx
  src/components/Autocomplete/components/ComboBox/components/index.ts
  src/components/Autocomplete/components/types.ts
Labels: 🤖Skip Changelog

#1402 [Navigation] Use new context api
  UNRELEASED-V4.md
  src/components/Navigation/Navigation.tsx
  src/components/Navigation/components/Context/Context.tsx
  src/components/Navigation/components/Context/index.ts
  src/components/Navigation/components/Item/Item.tsx
  src/components/Navigation/components/Item/tests/Item.test.tsx
  src/components/Navigation/components/Section/Section.tsx
  src/components/Navigation/components/Section/tests/Section.test.tsx
  src/components/Navigation/components/index.ts
  src/components/Navigation/tests/Navigation.test.tsx
  src/components/Navigation/types.ts
Labels: 🤖Skip Changelog

#1277 [Pagination] Fix styling for Pagination buttons with tooltips
  UNRELEASED.md
  src/components/Pagination/Pagination.scss
  src/components/Pagination/Pagination.tsx
Labels: 🎨 Design

#1357 [TextContainer] Fix child specificity for margin-top
  UNRELEASED.md
  src/components/TextContainer/TextContainer.scss
Labels: 🎨 Design

#1414 [ColorPicker] Improve touch interactions
  UNRELEASED.md
  src/components/ColorPicker/components/Slidable/Slidable.tsx
  src/components/ColorPicker/tests/ColorPicker.test.tsx
Labels: 🐛Bug

#1408 [a11y] Popover accessibility docs
  UNRELEASED.md
  src/components/Popover/README.md
Labels: 📓 Documentation

#1427 [ColorPicker] Do not call `window` if "undefined"
  UNRELEASED.md
  src/components/ColorPicker/components/Slidable/Slidable.tsx
  src/components/ColorPicker/tests/ColorPicker.test.tsx
Labels: 🐛Bug

#1442 [Range slider] Fix disabled state
  src/components/RangeSlider/README.md
  src/components/RangeSlider/components/DualThumb/DualThumb.tsx
  src/components/RangeSlider/components/DualThumb/tests/DualThumb.test.tsx
Labels: cla-needed

#1441 [Range slider] Fix styles
  src/components/RangeSlider/components/DualThumb/DualThumb.scss
  src/components/RangeSlider/components/SingleThumb/SingleThumb.scss
Labels: cla-needed

#1323 Automate backlog with GitHub actions
  .github/main.workflow
Labels: Tooling, 🤖Skip Changelog

#1435 PR generator script: remove ping to non-existent team
  scripts/new-version-pr-generator.js
Labels: 🤖Skip Changelog

#1304 [Navigation] - Fix active page highlighted state
  UNRELEASED.md
  src/components/Navigation/Navigation.scss
  src/components/Navigation/variables.scss
Labels: Accessibility

#1361 Clarify instructions for tophatting
  README.md
Labels: 🎁 Content

#1457 Add translations: default
  src/locales/de.json
  src/locales/es.json
  src/locales/fr.json
  src/locales/hi.json
  src/locales/it.json
  src/locales/ja.json
  src/locales/ms.json
  src/locales/nl.json
  src/locales/pt-BR.json
  src/locales/zh-CN.json
  src/locales/zh-TW.json
Labels: 🤖Skip Changelog

#1465 [TextField] Set alignment values in a logical order
  src/components/TextField/TextField.tsx
Labels: 🤖Skip Changelog

#1466 Fix issue where tsx would copy the package.json file where it shouldn't
  README.md
  package.json
  src/components/README.md
  tsconfig.json
Labels: 🐛Bug, 💣Blocking web, 🤖Skip Changelog

#1471 [Navigation] fix hover regression on navigation items on rails views
  src/components/Navigation/variables.scss
Labels: 🤖Skip Changelog

#1463 Update best practice for Select options
  src/components/Select/README.md
Labels: 🤖Skip Changelog

#1436 [Range slider] Dual range slider
  UNRELEASED.md
  src/components/RangeSlider/README.md
  src/components/RangeSlider/RangeSlider.tsx
  src/components/RangeSlider/components/DualThumb/DualThumb.scss
  src/components/RangeSlider/components/DualThumb/DualThumb.tsx
  src/components/RangeSlider/components/DualThumb/index.ts
  src/components/RangeSlider/components/DualThumb/tests/DualThumb.test.tsx
  src/components/RangeSlider/components/SingleThumb/SingleThumb.scss
  src/components/RangeSlider/components/SingleThumb/SingleThumb.tsx
  src/components/RangeSlider/components/SingleThumb/index.ts
  src/components/RangeSlider/components/SingleThumb/tests/SingleThumb.test.tsx
  src/components/RangeSlider/components/index.ts
  src/components/RangeSlider/index.ts
  src/components/RangeSlider/tests/RangeSlider.test.tsx
  src/components/RangeSlider/types.ts
  src/components/RangeSlider/utilities/index.ts
  src/components/RangeSlider/utilities/invertNumber.ts
  src/components/RangeSlider/utilities/tests/invertNumber.test.ts
  src/utilities/clamp.ts
  src/utilities/tests/clamp.test.ts
Labels: cla-needed

#1476 [Navigation] Remove deprecated UserMenu option for styleguide
  src/components/Navigation/README.md
Labels: 📓 Documentation, 🤖Skip Changelog

#1482 [v4] Add usePolaris/AppBridge
  src/components/index.ts
  src/hooks/index.ts
  src/hooks/use-app-bridge/index.ts
  src/hooks/use-app-bridge/tests/use-app-bridge.test.tsx
  src/hooks/use-app-bridge/use-app-bridge.tsx
  src/hooks/use-polaris/index.ts
  src/hooks/use-polaris/tests/use-polaris.test.tsx
  src/hooks/use-polaris/use-polaris.tsx
Labels: 🤖Skip Changelog

#1447 Remove testID warning
  UNRELEASED-V4.md
  tests/setup.ts
Labels: 🤖Skip Changelog

#1509 improve code coverage
  src/components/ExceptionList/tests/ExceptionList.test.tsx
  src/components/Image/tests/Image.test.tsx
  src/components/SkeletonPage/tests/SkeletonPage.test.tsx
  src/components/Spinner/tests/Spinner.test.tsx
Labels: 🤖Skip Changelog

#1516 improve code coverage round 2
  src/components/ActionList/tests/ActionList.test.tsx
  src/components/CalloutCard/tests/CalloutCard.test.tsx
  src/components/Card/tests/Card.test.tsx
  src/components/RadioButton/RadioButton.tsx
  src/components/RangeSlider/components/SingleThumb/SingleThumb.tsx
Labels: 🤖Skip Changelog

#1517 improve code coverage round 3
  src/components/DropZone/tests/DropZone.test.tsx
  src/components/EmptyState/tests/EmptyState.test.tsx
  src/components/Frame/components/Loading/tests/Loading.test.tsx
  src/components/KeyboardKey/tests/KeyboardKey.test.tsx
  src/components/Loading/tests/Loading.test.tsx
  src/components/Modal/tests/Modal.test.tsx
  src/components/ProgressBar/tests/ProgressBar.test.tsx
  src/components/Sticky/tests/Sticky.test.tsx
  src/components/TextField/TextField.tsx
  src/components/TextField/components/Resizer/tests/Resizer.test.tsx
Labels: 🤖Skip Changelog

#1505 [v4] Remove prop types
  UNRELEASED-V4.md
  package.json
  src/components/Navigation/types.ts
  src/components/ThemeProvider/index.ts
  src/components/ThemeProvider/types.ts
  yarn.lock
Labels: 🤖Skip Changelog

#1494 [v4][Toast] Remove withContext
  UNRELEASED-V4.md
  src/components/Toast/Toast.tsx
Labels: 🤖Skip Changelog

#1497 [v4][Loading] Remove withContext
  UNRELEASED-V4.md
  src/components/Loading/Loading.tsx
Labels: 🤖Skip Changelog

#1501 [v4][UnstyledLink] Remove withRef
  UNRELEASED-V4.md
  src/components/Link/tests/Link.test.tsx
  src/components/Navigation/components/Item/tests/Item.test.tsx
  src/components/UnstyledLink/UnstyledLink.tsx
  src/hooks/use-app-bridge/use-app-bridge.tsx
  src/hooks/use-polaris/use-polaris.tsx
Labels: 🤖Skip Changelog

#1526 improve code coverage round 4
  src/components/TrapFocus/tests/TrapFocus.test.tsx
Labels: 🤖Skip Changelog

#1527 code coverage round 5
  src/components/TrapFocus/tests/TrapFocus.test.tsx
Labels: 🤖Skip Changelog

#1508 Add translations: default
  src/locales/ja.json
  src/locales/zh-CN.json
Labels: 🤖Skip Changelog

#1525 Increase react and react-dom peer dependencies to 16.8.6
  UNRELEASED-V4.md
  package.json
Labels: 🤖Skip Changelog

#1491 [v4][FileUpload] Remove withContext/withRef
  UNRELEASED-V4.md
  src/components/DropZone/components/FileUpload/FileUpload.tsx
Labels: 🤖Skip Changelog

#1549 Add translations: default
  src/locales/zh-CN.json
Labels: 🤖Skip Changelog

#1555 [Range slider] Fix types and styles
  src/components/RangeSlider/RangeSlider.scss
  src/components/RangeSlider/RangeSlider.tsx
  src/components/RangeSlider/components/DualThumb/DualThumb.tsx
  src/components/RangeSlider/components/SingleThumb/SingleThumb.tsx
  src/components/RangeSlider/index.ts
  src/components/RangeSlider/types.ts
  src/components/index.ts
Labels: 🤖Skip Changelog

#1560 Add translations: default
  src/locales/zh-CN.json
Labels: 🤖Skip Changelog

#1557 [v4][OptionList] Remove componentWillReceiveProps
  UNRELEASED-V4.md
  src/components/OptionList/OptionList.tsx
  src/components/OptionList/tests/OptionList.test.tsx
  src/hooks/index.ts
  src/hooks/use-deep-compare/index.ts
  src/hooks/use-deep-compare/use-deep-compare.tsx
Labels: 🤖Skip Changelog

#1547 Upgrade storybook to v5.1.0-rc.0
  package.json
  yarn.lock
Labels: 🤖Skip Changelog

#1490 [Card] Apply content strategy syntax guidelines in documentation
  src/components/Card/README.md
Labels: 🤖Skip Changelog

#1531 [Icon] Documentation fixes on props
  src/components/Icon/Icon.tsx
Labels: 🤖Skip Changelog

#1575 Make choicelist title required
  UNRELEASED-V4.md
  src/components/ChoiceList/ChoiceList.tsx
  src/components/ChoiceList/tests/ChoiceList.test.tsx
Labels: 🤖Skip Changelog

#1571 [Navigation] withinContentContext fix
  src/components/Navigation/Navigation.tsx
  src/components/Navigation/tests/Navigation.test.tsx
Labels: 🤖Skip Changelog

#1500 [v4][ResourceList.FilterControl] Remove withContext
  UNRELEASED-V4.md
  src/components/ResourceList/components/FilterControl/FilterControl.tsx
Labels: 🤖Skip Changelog

#1503 [v4][ResourceList.Item] Remove withContext
  UNRELEASED-V4.md
  src/components/ResourceList/components/Item/Item.tsx
Labels: 🤖Skip Changelog

#1502 [v4][Navigation.Item] Remove withRef
  UNRELEASED-V4.md
  src/components/Navigation/components/Item/Item.tsx
  src/components/Navigation/components/Item/tests/Item.test.tsx
Labels: 🤖Skip Changelog

#1565 Fixing accessibility issues in shitlist
  UNRELEASED.md
  a11y_shitlist.json
  src/components/DropZone/DropZone.tsx
  src/components/DropZone/tests/DropZone.test.tsx
  src/components/Form/Form.tsx
  src/components/Layout/README.md
  src/components/Modal/README.md
  src/components/Modal/components/CloseButton/CloseButton.tsx
  src/components/Navigation/components/Section/Section.tsx
  src/components/OptionList/OptionList.tsx
  src/components/Page/components/Header/Header.tsx
  src/components/Sheet/README.md
  src/components/Tabs/Tabs.tsx
  src/components/TextField/README.md
  src/components/TextField/TextField.tsx
  src/components/TopBar/components/SearchField/SearchField.tsx
  src/locales/de.json
  src/locales/en.json
  src/locales/es.json
  src/locales/fr.json
  src/locales/hi.json
  src/locales/it.json
  src/locales/ja.json
  src/locales/ms.json
  src/locales/nl.json
  src/locales/pt-BR.json
  src/locales/zh-CN.json
  src/locales/zh-TW.json
Labels: Accessibility

#1498 [v4][ContextualSaveBar] Remove withContext
  UNRELEASED-V4.md
  src/components/ContextualSaveBar/ContextualSaveBar.tsx
  src/components/ContextualSaveBar/tests/ContextualSaveBar.test.tsx
Labels: 🤖Skip Changelog

#1595 Remove delay from DropZone test
  src/components/DropZone/tests/DropZone.test.tsx
Labels: 🤖Skip Changelog

#1594 Add translations: default
  src/locales/de.json
  src/locales/es.json
  src/locales/fr.json
  src/locales/hi.json
  src/locales/it.json
  src/locales/ja.json
  src/locales/ms.json
  src/locales/nl.json
  src/locales/pt-BR.json
  src/locales/zh-CN.json
  src/locales/zh-TW.json
Labels: 🤖Skip Changelog

#1610 [v4] Remove WithRef component and react-compose utility
  UNRELEASED-V4.md
  package.json
  src/components/WithRef/WithRef.tsx
  src/components/WithRef/components/Context/Context.tsx
  src/components/WithRef/components/Context/index.ts
  src/components/WithRef/components/index.ts
  src/components/WithRef/index.ts
  src/components/index.ts
  src/utilities/react-compose.tsx
  yarn.lock
Labels: 🤖Skip Changelog
