Repository Shopify/polaris, pull requests merged in 2019-06, with the labels that each got.

#1613 [Code Quality] Replace rem(8px) with spacing(tight)
  src/components/Button/Button.scss
  src/components/Select/Select.scss
Labels: ⚗️ Development, 🤖Skip Changelog

#1604 [v4] Deprecate icon source
  UNRELEASED-V4.md
  src/components/Button/tests/Button.test.tsx
  src/components/Icon/Icon.tsx
  src/components/Icon/tests/Icon.test.tsx
Labels: 🤖Skip Changelog

#1612 Add translations: default
  src/locales/hi.json
Labels: 🤖Skip Changelog

#1623 [Content] Change template and heading for required components
  .github/ISSUE_TEMPLATE/NEW_COMPONENT.md
  src/components/Navigation/README.md
  src/components/TopBar/README.md
Labels: 🤖Skip Changelog

#1602 [v4] Simplify withinContentContext
  UNRELEASED-V4.md
  src/components/Banner/Banner.tsx
  src/components/Banner/tests/Banner.test.tsx
  src/components/Card/Card.tsx
  src/components/Card/tests/Card.test.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/tests/Modal.test.tsx
  src/components/Navigation/Navigation.tsx
  src/components/Navigation/tests/Navigation.test.tsx
  src/components/WithinContentContext/context.tsx
  src/components/WithinContentContext/index.ts
Labels: 🤖Skip Changelog

#1628 [v4][WithinContentContext]Export WithinContentContext
  src/components/index.ts
Labels: 🤖Skip Changelog

#1631 [a11y] Collapsible a11y docs
  UNRELEASED.md
  src/components/Collapsible/README.md
Labels: 📓 Documentation

#1630 [a11y] Range slider a11y docs
  UNRELEASED.md
  src/components/RangeSlider/README.md
Labels: 📓 Documentation

#1599 [v4] Remove Navigation.UserMenu
  src/components/Frame/Frame.tsx
  src/components/Frame/README.md
  src/components/Frame/tests/Frame.test.tsx
  src/components/Navigation/Navigation.tsx
  src/components/Navigation/README.md
  src/components/Navigation/components/UserMenu/UserMenu.tsx
  src/components/Navigation/components/UserMenu/index.ts
  src/components/Navigation/components/UserMenu/tests/User.test.tsx
  src/components/Navigation/components/index.ts
  src/components/Navigation/tests/Navigation.test.tsx
  src/components/TopBar/components/UserMenu/UserMenu.scss
  src/components/TopBar/components/UserMenu/UserMenu.tsx
  src/components/TopBar/components/UserMenu/components/UserMenu/UserMenu.tsx
  src/components/TopBar/components/UserMenu/components/UserMenu/index.ts
  src/components/TopBar/components/UserMenu/components/UserMenu/tests/UserMenu.test.tsx
  src/components/TopBar/components/UserMenu/components/index.ts
  src/components/TopBar/components/UserMenu/context/Consumer.ts
  src/components/TopBar/components/UserMenu/context/Modifier.tsx
  src/components/TopBar/components/UserMenu/context/Provider.tsx
  src/components/TopBar/components/UserMenu/context/context.ts
  src/components/TopBar/components/UserMenu/context/index.ts
  src/components/TopBar/components/UserMenu/context/tests/Modifier.test.tsx
  src/components/TopBar/components/UserMenu/context/tests/Provider.test.tsx
  src/components/TopBar/components/UserMenu/index.ts
  src/components/TopBar/components/UserMenu/tests/UserMenu.test.tsx
  src/components/TopBar/components/index.ts
  src/components/TopBar/index.ts
Labels: 🤖Skip Changelog

#1641 [v4] Remove withContext
  UNRELEASED-V4.md
  src/components/WithContext/WithContext.tsx
  src/components/WithContext/index.ts
  src/components/WithContext/tests/WithContext.test.tsx
  src/components/index.ts
Labels: 🤖Skip Changelog

#1530 Make i18n required
  .storybook/stories-from-readme.js
  README.md
  UNRELEASED-V4.md
  a11y_shitlist.json
  locales/de.json
  locales/en.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/it.json
  locales/ja.json
  locales/ms.json
  locales/nl.json
  locales/pt-BR.json
  locales/zh-CN.json
  locales/zh-TW.json
  package.json
  src/components/AppProvider/README.md
  src/components/AppProvider/tests/AppProvider.test.tsx
  src/components/AppProvider/types.ts
  src/components/AppProvider/utilities/Intl/Intl.ts
  src/components/AppProvider/utilities/createAppProviderContext/createAppProviderContext.ts
  src/components/AppProvider/utilities/createAppProviderContext/tests/createAppProviderContext.test.tsx
  src/components/ContextualSaveBar/README.md
  src/components/Frame/README.md
  src/components/Link/tests/Link.test.tsx
  src/components/Loading/README.md
  src/components/Modal/README.md
  src/components/Page/README.md
  src/components/README.md
  src/components/ResourceList/components/FilterControl/FilterControl.tsx
  src/components/ResourceList/components/FilterControl/components/FilterCreator/FilterCreator.tsx
  src/components/ResourceList/components/FilterControl/tests/FilterControl.test.tsx
  src/components/ResourceList/context.tsx
  src/components/ResourcePicker/README.md
  src/components/Sheet/README.md
  src/components/Sheet/tests/Sheet.test.tsx
  src/components/Toast/README.md
  src/components/TopBar/README.md
  src/hooks/use-polaris/tests/use-polaris.test.tsx
  src/locales/index.ts
  src/test-utilities/legacy.tsx
Labels: 🤖Skip Changelog

#1640 [a11y] Add keyboard key docs
  UNRELEASED.md
  src/components/KeyboardKey/README.md
Labels: 📓 Documentation

#1606 [v4][Page] Narrow width page
  UNRELEASED-V4.md
  src/components/Page/Page.scss
  src/components/Page/Page.tsx
  src/components/Page/README.md
  src/components/Page/tests/Page.test.tsx
  src/components/Sheet/README.md
  src/components/SkeletonPage/SkeletonPage.scss
  src/components/SkeletonPage/SkeletonPage.tsx
  src/components/SkeletonPage/tests/SkeletonPage.test.tsx
Labels: 🤖Skip Changelog

#1635 [a11y] Exception list a11y docs
  UNRELEASED.md
  src/components/ExceptionList/README.md
Labels: 📓 Documentation

#1645 Enable color contrast test in pa11y
  UNRELEASED.md
  scripts/pa11y.js
  yarn.lock
Labels: Accessibility

#1636 [a11y] Form a11y docs
  UNRELEASED.md
  src/components/Form/README.md
Labels: 📓 Documentation

#1646 Bump tokens version
  package.json
Labels: 🤖Skip Changelog

#1634 [a11y] Description list a11y docs
  UNRELEASED.md
  src/components/DescriptionList/README.md
Labels: 📓 Documentation

#1654 Update lock file
  yarn.lock
Labels: 🤖Skip Changelog

#1655 Add translations: default
  src/locales/it.json
  src/locales/zh-CN.json
Labels: 🤖Skip Changelog

#1648 [a11y] Adds docs for the modal
  UNRELEASED.md
  src/components/Modal/README.md
Labels: 📓 Documentation

#1647 [a11y] Docs for the tag component
  UNRELEASED.md
  src/components/Tag/README.md
Labels: 📓 Documentation

#1668 Add translations: default
  src/locales/fr.json
Labels: 🤖Skip Changelog

#1665 Adds support for function component examples and React hooks
  .storybook/polaris-readme-loader.js
  src/components/TextField/README.md
Labels: Tooling, 📓 Documentation, 🤖Skip Changelog

#1653 🏗 [ActionMenu] Extract `Page > Header` code into its own component
  UNRELEASED.md
  src/components/ActionList/ActionList.tsx
  src/components/ActionList/components/Item/Item.tsx
  src/components/ActionList/components/Item/tests/Item.test.tsx
  src/components/ActionMenu/ActionMenu.scss
  src/components/ActionMenu/ActionMenu.tsx
  src/components/ActionMenu/components/MenuAction/MenuAction.scss
  src/components/ActionMenu/components/MenuAction/MenuAction.tsx
  src/components/ActionMenu/components/MenuAction/index.ts
  src/components/ActionMenu/components/MenuAction/tests/MenuAction.test.tsx
  src/components/ActionMenu/components/MenuGroup/MenuGroup.scss
  src/components/ActionMenu/components/MenuGroup/MenuGroup.tsx
  src/components/ActionMenu/components/MenuGroup/index.ts
  src/components/ActionMenu/components/MenuGroup/tests/MenuGroup.test.tsx
  src/components/ActionMenu/components/RollupActions/RollupActions.scss
  src/components/ActionMenu/components/RollupActions/RollupActions.tsx
  src/components/ActionMenu/components/RollupActions/index.ts
  src/components/ActionMenu/components/RollupActions/tests/RollupActions.test.tsx
  src/components/ActionMenu/components/index.ts
  src/components/ActionMenu/index.ts
  src/components/ActionMenu/tests/ActionMenu.test.tsx
  src/components/ActionMenu/tokens.scss
  src/components/Breadcrumbs/Breadcrumbs.scss
  src/components/Page/README.md
  src/components/Page/components/Header/Header.scss
  src/components/Page/components/Header/Header.tsx
  src/components/Page/components/Header/components/Action/Action.tsx
  src/components/Page/components/Header/components/Action/index.ts
  src/components/Page/components/Header/components/Action/tests/Action.test.tsx
  src/components/Page/components/Header/components/ActionGroup/ActionGroup.scss
  src/components/Page/components/Header/components/ActionGroup/ActionGroup.tsx
  src/components/Page/components/Header/components/ActionGroup/index.ts
  src/components/Page/components/Header/components/ActionGroup/tests/ActionGroup.test.tsx
  src/components/Page/components/Header/components/ActionGroup/types.ts
  src/components/Page/components/Header/components/index.ts
  src/components/Page/components/Header/tests/Header.test.tsx
  src/components/Page/index.ts
  src/components/Page/tests/Page.test.tsx
  src/components/Page/types.ts
  src/components/index.ts
  src/locales/en.json
  src/types.ts
  src/utilities/app-bridge-transformers.ts
Labels: ⚗️ Development

#1672 [v4][TextField] Fix textfield examples
  .storybook/polaris-readme-loader.js
  UNRELEASED-V4.md
  src/components/TextField/README.md
Labels: 🤖Skip Changelog

#1674 [v4] Follow strict naming convention and alphabetize component exports
  UNRELEASED-V4.md
  src/components/Frame/Frame.tsx
  src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.tsx
  src/components/Pagination/Pagination.tsx
  src/components/TopBar/TopBar.tsx
  src/components/index.ts
  src/utilities/get-width.ts
  src/utilities/is-input-focused.ts
  src/utilities/is-object.ts
  src/utilities/pluck-deep.ts
  src/utilities/set-root-property.ts
  src/utilities/tests/get-width.test.ts
  src/utilities/tests/is-input-focused.test.tsx
  src/utilities/tests/is-object.test.ts
  src/utilities/tests/pluck-deep.test.ts
  src/utilities/tests/set-root-property.test.ts
Labels: 🤖Skip Changelog

#1590 [v4] Don’t try to size html to 10px
  UNRELEASED-V4.md
  src/components/Sheet/README.md
  src/styles/foundation/utilities.scss
  src/styles/global/elements.scss
Labels: 🤖Skip Changelog

#1684 Add translations: default
  src/locales/de.json
  src/locales/es.json
  src/locales/fr.json
  src/locales/hi.json
  src/locales/it.json
  src/locales/ja.json
  src/locales/ms.json
  src/locales/nl.json
  src/locales/pt-BR.json
  src/locales/zh-CN.json
  src/locales/zh-TW.json
Labels: 🤖Skip Changelog

#1679 [Card] Fix example / content assignment
  src/components/Card/README.md
Labels: 🤖Skip Changelog

#1685 Add translations: default
  src/locales/hi.json
  src/locales/pt-BR.json
Labels: 🤖Skip Changelog

#1621 [v4][PositionedOverlay] Remove component will receive props
  .eslintignore
  UNRELEASED-V4.md
  src/components/PositionedOverlay/PositionedOverlay.tsx
  tests/setup.ts
  tests/shims/mutation-observer.ts
Labels: 🤖Skip Changelog

#1688 [Button] Update plain monochrome Button example
  src/components/Button/README.md
Labels: 🤖Skip Changelog

#1670 [v4][Collapsible] Remove componentWillReceiveProp from Collapsible
  UNRELEASED-V4.md
  src/components/Collapsible/Collapsible.scss
  src/components/Collapsible/Collapsible.tsx
  src/components/Collapsible/tests/Collapsible.test.tsx
Labels: 🤖Skip Changelog

#1695 [v4] Update no unsafe eslint rule
  .eslintrc
  UNRELEASED-V4.md
Labels: 🤖Skip Changelog

#1696 [v4] Removed all usage of findDOMNode
  UNRELEASED-V4.md
  src/components/Focus/Focus.tsx
  src/components/Focus/tests/Focus.test.tsx
  src/components/ResourceList/components/BulkActions/components/BulkActionButton/BulkActionButton.tsx
  src/components/Tabs/components/TabMeasurer/TabMeasurer.tsx
  src/components/TrapFocus/TrapFocus.tsx
  src/types.ts
Labels: 🤖Skip Changelog

#1394 [TextField] `prefix/suffix` props: Allow clickable actions but retain unselectable text
  UNRELEASED.md
  src/components/TextField/TextField.scss
  src/components/TextField/TextField.tsx
  src/components/TextField/tests/TextField.test.tsx
Labels: ⚗️ Development

#1714 Export classes immediatly instead of in a trailing line
  src/components/ContextualSaveBar/ContextualSaveBar.tsx
  src/components/InlineError/InlineError.tsx
  src/components/List/List.tsx
Labels: 🤖Skip Changelog

#1713 Update sewing-kit
  examples/browserify/src/App.js
  examples/create-react-app/src/App.js
  examples/webpack/src/App.js
  package.json
  src/components/AppProvider/AppProvider.tsx
  src/components/Card/tests/Card.test.tsx
  src/components/Collapsible/Collapsible.tsx
  src/components/DropZone/DropZone.tsx
  src/components/DropZone/components/FileUpload/FileUpload.tsx
  src/components/Modal/tests/Modal.test.tsx
  src/components/Navigation/tests/Navigation.test.tsx
  src/components/OptionList/OptionList.tsx
  src/components/ResourceList/ResourceList.tsx
  src/components/ScrollLock/tests/ScrollLock.test.tsx
  src/components/Scrollable/tests/Scrollable.test.tsx
  src/components/TextField/TextField.tsx
  src/components/ThemeProvider/ThemeProvider.tsx
  src/components/TopBar/components/UserMenu/context/Provider.tsx
  tests/build.test.js
  yarn.lock
Labels: 🤖Skip Changelog

#1717 [v4] Removed default exports from utils
  UNRELEASED-V4.md
  examples/create-react-app/src/tests/utils/enzyme.js
  src/components/AppProvider/utilities/Intl/Intl.ts
  src/components/Banner/Banner.tsx
  src/components/Banner/tests/Banner.test.tsx
  src/components/DropZone/DropZone.tsx
  src/components/DropZone/components/FileUpload/FileUpload.tsx
  src/components/Frame/components/ContextualSaveBar/tests/ContextualSaveBar.test.tsx
  src/components/Link/Link.tsx
  src/components/Modal/Modal.tsx
  src/components/Page/Page.tsx
  src/components/Pagination/Pagination.tsx
  src/components/RangeSlider/components/SingleThumb/SingleThumb.tsx
  src/components/TopBar/tests/TopBar.test.tsx
  src/test-utilities/document-has-style.ts
  src/test-utilities/index.ts
  src/test-utilities/legacy.tsx
  src/test-utilities/react-testing.tsx
  src/utilities/banner-context.tsx
  src/utilities/capitalize.ts
  src/utilities/clamp.ts
  src/utilities/is-input-focused.ts
  src/utilities/merge.ts
  src/utilities/pick.ts
  src/utilities/tests/capitalize.test.ts
  src/utilities/tests/clamp.test.ts
  src/utilities/tests/is-input-focused.test.tsx
  src/utilities/tests/merge.test.ts
  src/utilities/tests/pick.test.ts
Labels: 🤖Skip Changelog

#1716 Autocomplete: Make TextField a subcomponent of AutoComplete
  src/components/Autocomplete/Autocomplete.tsx
  src/components/Autocomplete/components/ComboBox/ComboBox.tsx
  src/components/Autocomplete/components/ComboBox/components/index.ts
  src/components/Autocomplete/components/ComboBox/tests/ComboBox.test.tsx
  src/components/Autocomplete/components/TextField/TextField.tsx
  src/components/Autocomplete/components/TextField/index.ts
  src/components/Autocomplete/components/index.ts
Labels: 🤖Skip Changelog

#1712 [Content] Add related guidelines section to icon component page
  src/components/Icon/README.md
Labels: 🤖Skip Changelog

#1725 [ActionMenu] Move margin-top to Page > Header.scss
  src/components/ActionMenu/ActionMenu.scss
  src/components/ActionMenu/ActionMenu.tsx
  src/components/Page/components/Header/Header.scss
Labels: 🐛Bug, 🤖Skip Changelog

#1715 [v4] Removed test errors / warning
  UNRELEASED-V4.md
  package.json
  src/components/Frame/components/Toast/tests/Toast.test.tsx
  src/components/Modal/tests/Modal.test.tsx
  src/components/Navigation/components/Item/tests/Item.test.tsx
  src/components/Popover/components/Pane/tests/Pane.test.tsx
  src/components/ProgressBar/tests/ProgressBar.test.tsx
  src/components/ResourceList/components/BulkActions/tests/BulkActions.test.tsx
  src/components/ResourceList/tests/ResourceList.test.tsx
  src/components/ScrollLock/tests/ScrollLock.test.tsx
  src/components/Select/tests/Select.test.tsx
  src/components/Sheet/tests/Sheet.test.tsx
  src/components/Spinner/tests/Spinner.test.tsx
  src/components/Tabs/components/Item/Item.tsx
  src/components/TextField/tests/TextField.test.tsx
  yarn.lock
Labels: 🤖Skip Changelog

#1709 [v4] Enable strict mode
  .storybook/config.js
  UNRELEASED-V4.md
  src/components/Page/components/Header/tests/Header.test.tsx
  src/test-utilities/legacy.tsx
  src/test-utilities/react-testing.tsx
  src/test-utilities/tests/legacy.test.tsx
  src/test-utilities/tests/react-testing.test.tsx
Labels: 🤖Skip Changelog

#1730 Add translations: default
  src/locales/ms.json
Labels: 🤖Skip Changelog

#1728 Upgrade storybook to the latest version
  package.json
  yarn.lock
Labels: 🤖Skip Changelog

#1738 Remove mutation observer shim
  package.json
  tests/setup.ts
  tests/shims/mutation-observer.ts
  yarn.lock
Labels: 🤖Skip Changelog

#1742 [Modal] Fix example so the modal closes
  src/components/Modal/README.md
Labels: 🤖Skip Changelog

#1750 Hide GitHub automations from Shipit
  shipit.yml
Labels: 🤖Skip Changelog

#1751 Add translations: default
  src/locales/de.json
  src/locales/es.json
  src/locales/fr.json
  src/locales/hi.json
  src/locales/it.json
  src/locales/ja.json
  src/locales/ms.json
  src/locales/nl.json
  src/locales/pt-BR.json
  src/locales/zh-CN.json
  src/locales/zh-TW.json
Labels: 🤖Skip Changelog

#1752 Fix "path not found in tokens" notice on build
  src/components/ActionMenu/ActionMenu.scss
  src/components/ActionMenu/components/MenuAction/MenuAction.scss
  src/components/ActionMenu/variables.scss
Labels: 🤖Skip Changelog
