Repository Shopify/polaris, pull requests merged in 2019-08, with the labels that each got.

#1911 Move PolarisTestProvider into components
  src/components/PolarisTestProvider/PolarisTestProvider.tsx
  src/components/PolarisTestProvider/index.ts
  src/components/PolarisTestProvider/tests/PolarisTestProvider.test.tsx
  src/components/index.ts
  src/index.ts
  src/test-utilities/legacy.tsx
  src/test-utilities/react-testing.tsx
Labels: 🤖Skip Changelog

#1908 [v4] Override StickyManager context in Scrollable
  src/components/Scrollable/Scrollable.tsx
  src/components/Scrollable/components/ScrollTo/ScrollTo.tsx
  src/components/Scrollable/components/ScrollTo/tests/ScrollTo.test.tsx
  src/components/Scrollable/context.ts
  src/components/Scrollable/tests/Scrollable.test.tsx
  src/utilities/with-app-provider.tsx
Labels: 🤖Skip Changelog

#1909 [v4] Use named exports for contexts and utilities
  src/components/Autocomplete/components/ComboBox/ComboBox.tsx
  src/components/Autocomplete/components/ComboBox/context.tsx
  src/components/Autocomplete/components/TextField/TextField.tsx
  src/components/DropZone/DropZone.tsx
  src/components/DropZone/components/FileUpload/FileUpload.tsx
  src/components/DropZone/components/FileUpload/tests/FileUpload.test.tsx
  src/components/DropZone/context.tsx
  src/components/Filters/Filters.tsx
  src/components/Navigation/Navigation.tsx
  src/components/Navigation/components/Item/Item.tsx
  src/components/Navigation/components/Item/tests/Item.test.tsx
  src/components/Navigation/components/Section/tests/Section.test.tsx
  src/components/Navigation/context.tsx
  src/components/Navigation/tests/Navigation.test.tsx
  src/components/RangeSlider/utilities/index.ts
  src/components/RangeSlider/utilities/invertNumber.ts
  src/components/ResourceList/ResourceList.tsx
  src/components/ResourceList/components/FilterControl/FilterControl.tsx
  src/components/ResourceList/components/FilterControl/tests/FilterControl.test.tsx
  src/components/ResourceList/components/Item/Item.tsx
  src/components/ResourceList/components/Item/tests/Item.test.tsx
  src/components/ResourceList/context.tsx
  src/components/ResourceList/index.ts
  src/types.ts
Labels: 🤖Skip Changelog

#1913 [v4][ResourceList] Add existence check to ref
  UNRELEASED-V4.md
  src/components/ResourceList/components/BulkActions/components/BulkActionButton/BulkActionButton.tsx
Labels: 🤖Skip Changelog

#1906 [v4] Update frame utilities & associated components
  src/components/ContextualSaveBar/ContextualSaveBar.tsx
  src/components/ContextualSaveBar/index.ts
  src/components/ContextualSaveBar/tests/ContextualSaveBar.test.tsx
  src/components/Frame/Frame.tsx
  src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.tsx
  src/components/Frame/components/Toast/Toast.tsx
  src/components/Frame/components/Toast/tests/Toast.test.tsx
  src/components/Frame/components/ToastManager/ToastManager.tsx
  src/components/Frame/index.ts
  src/components/Loading/Loading.tsx
  src/components/PolarisTestProvider/PolarisTestProvider.tsx
  src/components/Toast/Toast.tsx
  src/components/Toast/index.ts
  src/components/index.ts
  src/utilities/frame/context.ts
  src/utilities/frame/hooks.ts
  src/utilities/frame/index.ts
  src/utilities/frame/tests/hooks.test.tsx
  src/utilities/frame/types.ts
Labels: 🤖Skip Changelog

#1927 [v4] Minor changes to bump test coverage slightly
  UNRELEASED-V4.md
  src/components/DropZone/tests/DropZone.test.tsx
  src/components/Frame/Frame.tsx
  src/components/Icon/Icon.tsx
  src/components/Loading/Loading.tsx
Labels: 🤖Skip Changelog

#1929 [v4][Collapsible] Polish - resize bug/test
  UNRELEASED-V4.md
  src/components/Collapsible/Collapsible.tsx
  src/components/Collapsible/tests/Collapsible.test.tsx
Labels: 🤖Skip Changelog

#1934 Remove error log in tab test by adding _ref prop and forwardRef
  src/components/UnstyledLink/UnstyledLink.tsx
Labels: 🤖Skip Changelog

#1936 Remove unused spread operator
  src/components/Page/components/Header/tests/Header.test.tsx
Labels: 🤖Skip Changelog

#1923 [ResourceList.FilterControl] Add placeholder to prop list
  src/components/ResourceList/README.md
Labels: 🤖Skip Changelog

#1940 [Navigation] Remove duplicate line from docs
  src/components/Navigation/README.md
Labels: 🤖Skip Changelog

#1938 Renamed useDeepCompare to useDeepEffect
  src/components/Frame/components/ToastManager/ToastManager.tsx
  src/components/OptionList/OptionList.tsx
  src/components/Toast/Toast.tsx
  src/utilities/use-deep-effect.tsx
Labels: 🤖Skip Changelog

#1941 Remove duplicated example for navigation with separator
  src/components/Navigation/README.md
Labels: 🤖Skip Changelog

#1953 Renamed useDeepCompare
  src/components/Frame/components/ToastManager/ToastManager.tsx
  src/components/OptionList/OptionList.tsx
  src/components/Toast/Toast.tsx
  src/utilities/use-deep-effect.tsx
Labels: 🤖Skip Changelog

#1954 [ContextualSaveBar] Changed useEffect to useDeepEffect
  src/components/ContextualSaveBar/ContextualSaveBar.tsx
Labels: 🤖Skip Changelog

#1956 Prep v3.21.1
  CHANGELOG.md
  src/components/Filters/Filters.tsx
  src/components/Filters/tests/Filters.test.tsx
Labels: 🤖Skip Changelog

#1961 [Collapsible] Fixed nested Collapsible animation
  src/components/Collapsible/Collapsible.scss
  src/components/Collapsible/Collapsible.tsx
  src/components/Collapsible/tests/Collapsible.test.tsx
Labels: 🤖Skip Changelog

#1957 Add minified styles to npm package
  .eslintignore
  .gitignore
  .prettierignore
  .stylelintignore
  .vscode/settings.json
  package.json
  scripts/build.js
  tests/build.test.js
Labels: 🤖Skip Changelog

#1964 [Unreleased] fix typo in unreleased
  UNRELEASED.md
Labels: 📓 Documentation

#1965 Fixed getDerivedStateFromProp type with cast
  src/components/Collapsible/Collapsible.tsx
Labels: 🤖Skip Changelog

#1971 Move @types/hoist-non-react-statics into dependencies
  package.json
Labels: 🤖Skip Changelog

#1968 [ContextualSaveBar] Replace RTG
  src/components/Frame/Frame.scss
  src/components/Frame/Frame.tsx
  src/components/Frame/components/CSSAnimation/CSSAnimation.scss
  src/components/Frame/components/CSSAnimation/CSSAnimation.tsx
  src/components/Frame/components/CSSAnimation/index.ts
  src/components/Frame/components/index.ts
Labels: 🤖Skip Changelog

#1974 Stop exporting State interfaces
  src/components/Autocomplete/components/ComboBox/ComboBox.tsx
  src/components/Avatar/Avatar.tsx
  src/components/ButtonGroup/components/Item/Item.tsx
  src/components/Card/Card.tsx
  src/components/Collapsible/Collapsible.tsx
  src/components/ColorPicker/ColorPicker.tsx
  src/components/ColorPicker/components/AlphaPicker/AlphaPicker.tsx
  src/components/ColorPicker/components/HuePicker/HuePicker.tsx
  src/components/ColorPicker/components/Slidable/Slidable.tsx
  src/components/Connected/Connected.tsx
  src/components/Connected/components/Item/Item.tsx
  src/components/DatePicker/DatePicker.tsx
  src/components/DropZone/DropZone.tsx
  src/components/Filters/components/ConnectedFilterControl/components/Item/Item.tsx
  src/components/Frame/Frame.tsx
  src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.tsx
  src/components/Frame/components/Loading/Loading.tsx
  src/components/Modal/Modal.tsx
  src/components/OptionList/OptionList.tsx
  src/components/OptionList/components/Option/Option.tsx
  src/components/Popover/Popover.tsx
  src/components/Portal/Portal.tsx
  src/components/PositionedOverlay/PositionedOverlay.tsx
  src/components/RangeSlider/components/DualThumb/DualThumb.tsx
  src/components/ResourceList/ResourceList.tsx
  src/components/ResourceList/components/BulkActions/BulkActions.tsx
  src/components/ResourceList/components/FilterControl/components/FilterCreator/FilterCreator.tsx
  src/components/ResourceList/components/Item/Item.tsx
  src/components/Scrollable/Scrollable.tsx
  src/components/Sheet/Sheet.tsx
  src/components/Sticky/Sticky.tsx
  src/components/Tabs/Tabs.tsx
  src/components/TextField/TextField.tsx
  src/components/Tooltip/Tooltip.tsx
  src/components/TopBar/TopBar.tsx
  src/components/TrapFocus/TrapFocus.tsx
Labels: 🤖Skip Changelog

#1976 Add translation setup in READMEs
  README.md
  src/components/AppProvider/README.md
  src/components/README.md
Labels: 🤖Skip Changelog

#1984 Remove empty types file
  src/components/types.ts
Labels: 🤖Skip Changelog

#1545 [Button] Remove tap-highlight-color for buttons
  UNRELEASED.md
  src/styles/shared/_buttons.scss
Labels: 🎨 Design

#1986 [Resource list] Hide inline label on small screen
  src/components/ResourceList/ResourceList.tsx
  src/components/ResourceList/tests/ResourceList.test.tsx
Labels: 🤖Skip Changelog

#1987 [Resource list] Remove unused styles
  src/components/ResourceList/ResourceList.scss
Labels: 🤖Skip Changelog
