Repository Shopify/polaris, pull requests merged in 2019-03, with the labels that each got.

#1082 [Card] Fix subdued section spacing issues
  UNRELEASED.md
  src/components/Card/Card.scss
Labels: cla-needed

#1024 [Stack] Remove margin from vertical
  UNRELEASED.md
  src/components/Stack/Stack.scss
Labels: cla-needed

#1141 [SkeletonThumbnail] Align sizes with Thumbnail
  UNRELEASED.md
  src/components/SkeletonThumbnail/SkeletonThumbnail.scss
  src/components/Thumbnail/Thumbnail.scss
  src/styles/shared/skeleton.scss
Labels: Bug fix

#1145 [a11y] Docs for checkbox, radio button, and choice list
  UNRELEASED.md
  src/components/Checkbox/README.md
  src/components/ChoiceList/README.md
  src/components/RadioButton/README.md
Labels: Documentation

#1111 [SearchField] Update search field to be 694px max-width
  UNRELEASED.md
  src/components/TopBar/components/SearchField/SearchField.scss
Labels: Sass

#1114 [Collapsible] Remove context
  UNRELEASED.md
  src/components/Collapsible/Collapsible.tsx
Labels: Component enhancement

#919 [Toast] Add `action` prop
  UNRELEASED.md
  src/components/Frame/components/Toast/Toast.scss
  src/components/Frame/components/Toast/Toast.tsx
  src/components/Frame/components/Toast/index.ts
  src/components/Frame/components/Toast/tests/Toast.test.tsx
  src/components/Frame/components/index.ts
  src/components/Frame/index.ts
  src/components/Frame/types.ts
  src/components/Toast/README.md
  src/components/index.ts
Labels: cla-needed

#1018 Remove lodash merge
  UNRELEASED.md
  src/components/AppProvider/utilities/Intl/Intl.ts
  src/components/AppProvider/utilities/withAppProvider/withAppProvider.tsx
  src/components/AppProvider/utilities/withSticky/withSticky.tsx
  src/test-utilities/enzyme.tsx
  src/utilities/merge.ts
  src/utilities/tests/merge.test.ts
Labels: Skip Changelog

#1259 [TextField] Allow autoComplete prop of TextField to accept string values
  UNRELEASED.md
  src/components/TextField/TextField.tsx
  src/components/TextField/tests/TextField.test.tsx
Labels: Autocomplete, Bug fix
