Repository Shopify/polaris, pull requests merged in 2020-10, with the labels that each got.

#3351 [Actions] Remove disable exhaustive deps lint
  src/components/ActionMenu/components/Actions/Actions.tsx
Labels: 🤖Skip Changelog

#3349 [Banner] Fix primary action colors
  package.json
  src/components/Banner/Banner.scss
  yarn.lock
Labels: 🤖Skip Changelog

#3344 Update background-color & border radius for new design language
  src/components/Tag/Tag.scss
Labels: 🤖Skip Changelog

#3346 Square badge border radius within filter for new design language
  src/components/Badge/Badge.scss
  src/components/Badge/Badge.tsx
  src/components/Filters/Filters.tsx
  src/components/Filters/tests/Filters.test.tsx
  src/utilities/within-filter-context.tsx
Labels: 🤖Skip Changelog

#3353 Update color docs
  documentation/Color system.md
Labels: 🤖Skip Changelog

#3355 [Banner] Adjusting spacing
  src/components/Banner/Banner.scss
Labels: 🤖Skip Changelog

#3360 DescriptionList - make spacing optional prop
  src/components/DescriptionList/DescriptionList.tsx
Labels: 🤖Skip Changelog

#3365 Use React.Children.toArray to remove child component key warning logs
  src/components/ResourceItem/ResourceItem.tsx
  src/components/ResourceList/ResourceList.tsx
Labels: 🤖Skip Changelog

#3371 Fix build failure
  src/components/ResourceList/ResourceList.tsx
  src/components/ResourceList/tests/ResourceList.test.tsx
Labels: 🤖Skip Changelog

#3369 [Page header] Vertically center header title
  src/components/Page/components/Header/Header.scss
Labels: 🤖Skip Changelog

#3367 Fix tag background
  src/components/Tag/README.md
  src/components/Tag/Tag.scss
Labels: 🤖Skip Changelog

#3362 Bugfix: Bump up Polaris to 5.1.0 in Examples to Fix Broken Builds
  examples/create-react-app-ts-react-testing/package.json
  examples/create-react-app-ts-react-testing/yarn.lock
  examples/create-react-app/package.json
  examples/create-react-app/yarn.lock
  examples/next.js/package.json
  examples/next.js/yarn.lock
  examples/webpack/package.json
  examples/webpack/yarn.lock
Labels: 🤖Skip Changelog

#3374 [Page Header] Fix mobile layout
  src/components/Page/components/Header/Header.scss
Labels: 🤖Skip Changelog

#3375 Update polaris-icons, add divider to navigation
  package.json
  src/components/Navigation/Navigation.scss
  src/components/Select/Select.tsx
  yarn.lock
Labels: 🤖Skip Changelog

#3376 Target links as well as buttons
  src/components/ActionMenu/components/SecondaryAction/SecondaryAction.scss
Labels: 🤖Skip Changelog

#3361 Polaris v5.5.0
  CHANGELOG.md
  README.md
  UNRELEASED.md
  documentation/Color system.md
  package.json
  src/components/README.md
Labels: 🤖Skip Changelog

#3379 [Button / Slim] Fix an issue where icons would vertically stretch the button
  src/components/Button/Button.scss
Labels: 🤖Skip Changelog

#3388 Align pagination when no actions are present
  src/components/Page/components/Header/Header.scss
Labels: 🤖Skip Changelog

#3389 [BulkActions][NDL] Fix spacing
  src/components/CheckableButton/CheckableButton.scss
Labels: 🤖Skip Changelog

#3392 [Button] Fix width so that it stays the same when loading
  src/components/Button/Button.scss
  src/components/Button/Button.tsx
Labels: 🤖Skip Changelog

#3391 Prevent having 2 box-shadow properties when the banner is "In page" context
  src/components/Banner/Banner.scss
Labels: 🤖Skip Changelog

#3394 Bug fix: content and dismiss overlap for banner
  src/components/Banner/Banner.scss
Labels: 🤖Skip Changelog

#3400 Button loading icon
  src/components/Button/Button.scss
Labels: 🤖Skip Changelog

#3399 [SecondaryAction] Pass on Action to onClick handler
  playground/DetailsPage.tsx
  src/components/ActionMenu/components/SecondaryAction/SecondaryAction.tsx
Labels: 🤖Skip Changelog

#3378 [TextField][Select] Tweak colors
  src/components/Select/Select.scss
  src/components/TextField/TextField.scss
Labels: 🤖Skip Changelog

#3427 🎨 [Button] Remove the inline style from plain monochrome example
  src/components/Button/README.md
Labels: 📓 Documentation, 🤖Skip Changelog

#3426 [Page Header] Fix some layout issues on mobile and large screens
  src/components/Page/components/Header/Header.scss
  src/components/Page/components/Header/Header.tsx
  src/components/Page/components/Header/tests/Header.test.tsx
Labels: 🤖Skip Changelog

#3430 Update search input and results to new design language
  playground/DetailsPage.tsx
  src/components/Frame/README.md
  src/components/TopBar/README.md
  src/components/TopBar/_variables.scss
  src/components/TopBar/components/Search/Search.scss
  src/components/TopBar/components/Search/Search.tsx
  src/components/TopBar/components/SearchDismissOverlay/SearchDismissOverlay.scss
  src/components/TopBar/components/SearchDismissOverlay/SearchDismissOverlay.tsx
  src/components/TopBar/components/SearchField/SearchField.scss
Labels: 🤖Skip Changelog

#3437 Fix Alex sillyness
  src/components/Connected/Connected.scss
Labels: 🤖Skip Changelog

#3439 Update Disabled textfield appearance
  src/components/TextField/TextField.scss
Labels: 🤖Skip Changelog

#3442 [TextField] Updated number field spinner bg
  src/components/TextField/TextField.scss
Labels: 🤖Skip Changelog

#3441 [Badge] Adjust font-weight and remove border
  documentation/Color system.md
  src/components/Badge/Badge.scss
  src/utilities/theme/tokens.ts
Labels: 🤖Skip Changelog

#3436 [new DL] Tweak topbar search input colors
  src/components/TopBar/components/SearchField/SearchField.scss
Labels: 🤖Skip Changelog

#3447 [PageActions] Add test for PageActions ComplexAction
  src/components/PageActions/tests/PageActions.test.tsx
Labels: 🤖Skip Changelog

#3450 Fixes bulk actions from hiding actions when on small screen sizes
  src/components/BulkActions/BulkActions.tsx
Labels: 🤖Skip Changelog

#3454 v5.6.1
  CHANGELOG.md
  README.md
  package.json
  src/components/README.md
Labels: 🤖Skip Changelog

#3420 Actions rollup menu groups
  locales/en.json
  playground/DetailsPage.tsx
  src/components/ActionMenu/components/Actions/Actions.tsx
  src/components/ActionMenu/components/Actions/tests/Actions.test.tsx
  src/components/ActionMenu/components/MenuGroup/MenuGroup.tsx
  src/components/ActionMenu/components/MenuGroup/tests/MenuGroup.test.tsx
  src/components/ActionMenu/tests/ActionMenu.test.tsx
  src/components/ActionMenu/tests/utilities.test.ts
  src/components/ActionMenu/utilities.ts
  src/components/Page/components/Header/Header.scss
  src/components/Page/components/Header/Header.tsx
Labels: 🤖Skip Changelog

#3458 [Page] Fix up print styles
  src/components/Page/components/Header/Header.scss
  src/components/Page/components/Header/Header.tsx
Labels: 🤖Skip Changelog

#3459 Remove unstyled button styles
  src/components/UnstyledButton/UnstyledButton.scss
  src/components/UnstyledButton/UnstyledButton.tsx
Labels: 🤖Skip Changelog

#3461 [ButtonGroup] Fix missing rounded corners on single buttons in button group
  src/components/Button/Button.scss
Labels: 🤖Skip Changelog

#3464 [ActionMenu] Remove hide from print wrapper
  src/components/ActionMenu/ActionMenu.scss
  src/components/Page/components/Header/Header.scss
  src/components/Page/components/Header/Header.tsx
Labels: 🤖Skip Changelog

#3462 [Badge] Set border width to 0 in new design language
  src/components/Badge/Badge.scss
Labels: 🤖Skip Changelog

#3466 [Rollup Actions] Right alignment
  src/components/ActionMenu/components/RollupActions/RollupActions.scss
Labels: 🤖Skip Changelog

#3468 Change breakpoint for page title
  src/components/Page/components/Header/components/Title/Title.scss
  src/components/Page/components/Header/components/Title/Title.tsx
Labels: 🤖Skip Changelog

#3483 [Page] Only re-render actions when needed
  src/components/ActionMenu/components/Actions/Actions.tsx
Labels: 🤖Skip Changelog

#3452 [AutoSuggest] Add options as dependency to useCallback function
  src/components/Autocomplete/README.md
Labels: 🤖Skip Changelog

#3489 [new DL][Navigation] Apply background treatment to hover/focus/active states, make disabled state look more… disabled
  .storybook/polaris-readme-loader.js
  src/components/Navigation/Navigation.scss
  src/components/Navigation/README.md
  src/components/Navigation/_variables.scss
  src/styles/shared/_icons.scss
Labels: 🤖Skip Changelog

#3475 [new DL] Change actionlist colors
  src/components/ActionList/ActionList.scss
  src/components/ActionList/components/Item/Item.tsx
Labels: 🤖Skip Changelog

#3497 [Page header] fix layout refresh bug
  src/components/ActionMenu/ActionMenu.scss
  src/components/ActionMenu/ActionMenu.tsx
  src/components/ActionMenu/components/Actions/Actions.scss
  src/components/Page/components/Header/Header.scss
Labels: 🤖Skip Changelog

#3495 Add type-check to build
  .travis.yml
  src/components/Banner/tests/Banner.test.tsx
  src/components/BulkActions/BulkActions.tsx
  src/components/BulkActions/tests/BulkActions.test.tsx
  src/components/ResourceList/tests/ResourceList.test.tsx
Labels: 🤖Skip Changelog

#3499 [Card] Fix border radius on section
  src/components/Card/Card.scss
Labels: 🤖Skip Changelog

#3501 [Tabs] Update styling
  src/components/Tabs/Tabs.scss
Labels: 🤖Skip Changelog

#3504 [Frame] Update page loading indicator
  src/components/Frame/components/Loading/Loading.scss
Labels: 🤖Skip Changelog

#3507 [Fix types] Change aliased import to relative path
  src/components/TopBar/components/Menu/Menu.tsx
  src/components/TopBar/components/UserMenu/UserMenu.tsx
Labels: 🤖Skip Changelog

#3509 [new DL] Adjust ActionList pressed state color
  src/components/ActionList/ActionList.scss
Labels: 🤖Skip Changelog

#3510 [new DL][ActionList] Force color and no text decoration
  src/components/ActionList/ActionList.scss
Labels: 🤖Skip Changelog

#3511 ActionList pressed color
  src/components/ActionList/ActionList.scss
Labels: 🤖Skip Changelog

#3520 [DatePicker] Fix selector order
  src/components/DatePicker/DatePicker.scss
Labels: 🤖Skip Changelog

#3521 [TextField] Fix prefix and suffix text color
  src/components/TextField/TextField.scss
Labels: 🤖Skip Changelog

#3525 Update ThemeProvider.tsx
  src/components/ThemeProvider/ThemeProvider.tsx
Labels: 🤖Skip Changelog

#3517 Allow type override for components like StackItem
  src/utilities/components.tsx
Labels: 🤖Skip Changelog

#3533 memoize buildCustomProperties function
  src/utilities/theme/utils.ts
Labels: 🤖Skip Changelog

#3555 Remove background from printed pages
  src/components/AppProvider/AppProvider.scss
  src/components/Frame/Frame.scss
Labels: 🤖Skip Changelog

#3494 🎨 [Button] Simplify code by utilizing more of UnstyledButton
  UNRELEASED.md
  src/components/Button/Button.tsx
  src/components/Button/tests/Button.test.tsx
  src/components/ResourceItem/tests/ResourceItem.test.tsx
  src/components/UnstyledButton/UnstyledButton.tsx
  src/components/UnstyledButton/tests/UnstyledButton.test.tsx
  src/types.ts
  src/utilities/focus.ts
Labels: ⚗️ Development

#3554 [Link] Fix focus state bug of multi-line link
  src/components/Link/Link.scss
Labels: Accessibility, 🤖Skip Changelog

#3563 [Navigation] Hide list item overflow
  src/components/Navigation/Navigation.scss
Labels: 🤖Skip Changelog

#3573 [Navigation] Fix sub nav item spacing when no icon is present
  src/components/Navigation/Navigation.scss
Labels: 🤖Skip Changelog

#3574 [Page actions] Style updates
  src/components/ActionMenu/components/Actions/Actions.tsx
  src/components/ActionMenu/components/SecondaryAction/SecondaryAction.scss
  src/components/Page/components/Header/Header.scss
Labels: 🤖Skip Changelog

#3583 [Page actions] Always render single action
  src/components/ActionMenu/components/Actions/Actions.tsx
Labels: 🤖Skip Changelog
