Repository Shopify/polaris, pull requests merged in 2020-09, with the labels that each got.

#3201 DropZone replace illustration
  src/components/DropZone/components/FileUpload/FileUpload.scss
  src/components/DropZone/components/FileUpload/FileUpload.tsx
  src/components/DropZone/components/FileUpload/tests/FileUpload.test.tsx
  src/components/DropZone/images/file-upload.svg
  src/components/DropZone/images/image-upload.svg
  src/components/DropZone/images/index.ts
  src/components/DropZone/images/upload-arrow.svg
  src/components/TopBar/tests/TopBar.test.tsx
Labels: 🤖Skip Changelog

#3224 Bump polaris-tokens to 2.12.5
  package.json
  yarn.lock
Labels: 🤖Skip Changelog

#3202 [Button] Update default / secondary styles
  documentation/Color system.md
  src/components/Select/Select.scss
  src/styles/shared/_buttons.scss
  src/utilities/theme/tokens.ts
Labels: 🤖Skip Changelog

#3227 [Button] Add -1 layer shadow for pressed state
  documentation/Color system.md
  src/styles/shared/_buttons.scss
  src/utilities/theme/tokens.ts
Labels: 🤖Skip Changelog

#3222 [TextField] Support `inputMode` attribute
  UNRELEASED.md
  src/components/TextField/README.md
  src/components/TextField/TextField.tsx
  src/components/TextField/tests/TextField.test.tsx
Labels: ⚗️ Development

#3229 Adjust pressed inner shadow token
  documentation/Color system.md
  src/utilities/theme/tokens.ts
Labels: 🤖Skip Changelog

#3199 [Banner] Refactor to a functional component and fix its `id` server/client mismatch
  UNRELEASED.md
  src/components/Banner/Banner.tsx
  src/components/Banner/tests/Banner.test.tsx
Labels: ⚗️ Development, 🐛Bug

#3236 [Button] Update depressed style
  documentation/Color system.md
  package.json
  src/styles/shared/_buttons.scss
  src/utilities/theme/tokens.ts
  yarn.lock
Labels: 🤖Skip Changelog

#3232 [Navigation] Update filter colors for channel icons and update tokens
  playground/DetailsPage.tsx
  src/components/Navigation/Navigation.scss
  src/components/Navigation/_variables.scss
Labels: 🤖Skip Changelog

#3228 [Topbar SearchField] Update the polaris-token version and modify searchBar background
  src/components/TopBar/components/SearchField/SearchField.scss
Labels: 🤖Skip Changelog

#3240 [Navigation] reduce left and right padding by 0.4rem
  playground/DetailsPage.scss
  src/components/Navigation/Navigation.scss
  src/components/Navigation/_variables.scss
Labels: 🤖Skip Changelog

#3247 Update _interaction-state.scss to use ndl
  src/styles/shared/_interaction-state.scss
Labels: 🤖Skip Changelog

#3253 [Popover]Fix mismatch in hide on print style
  src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx
Labels: 🤖Skip Changelog

#3238 [Filters] Fix spacing issues with filters button group
  src/components/Filters/components/ConnectedFilterControl/ConnectedFilterControl.scss
Labels: 🤖Skip Changelog

#3268 Move discard modal out of theme provider
  playground/DetailsPage.tsx
  src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.tsx
Labels: 🤖Skip Changelog

#3272 [Breadcrumbs] Render content as a visually hidden label if new design language is enabled
  src/components/Breadcrumbs/Breadcrumbs.tsx
  src/components/Breadcrumbs/tests/Breadcrumbs.test.tsx
Labels: 🤖Skip Changelog

#3262 [Button] Update disabled states
  src/components/Button/Button.scss
  src/components/Button/README.md
  src/styles/shared/_buttons.scss
Labels: 🤖Skip Changelog

#3263 [ButtonGroup] Fix Segmented Button Gap Fix
  documentation/Color system.md
  src/components/ButtonGroup/ButtonGroup.scss
  src/utilities/theme/tokens.ts
Labels: 🤖Skip Changelog

#3276 [Navigation] Fix larger nav items on mobile
  src/components/Navigation/_variables.scss
Labels: 🤖Skip Changelog

#3274 [Banner] Fix focus ring border radius on in-content banners
  src/components/Banner/Banner.scss
Labels: 🤖Skip Changelog

#3293 Use contrasting colors in theming examples
  src/components/AppProvider/README.md
  src/components/Frame/README.md
  src/components/TopBar/README.md
Labels: 🤖Skip Changelog

#3288 Adjust border radius for new design language
  src/components/ProgressBar/ProgressBar.scss
Labels: 🤖Skip Changelog

#3301 TopBar alignment with page
  src/components/TopBar/TopBar.scss
Labels: 🤖Skip Changelog

#3294 Add button style to CheckableButton
  src/components/ResourceList/components/CheckableButton/CheckableButton.scss
Labels: 🤖Skip Changelog

#3305 Storybook bump to 6.0.21
  package.json
  yarn.lock
Labels: 🤖Skip Changelog

#3296 Fix issues related to action list in new design language
  src/components/ActionList/ActionList.scss
  src/components/ActionList/README.md
  src/components/ActionList/components/Section/Section.tsx
Labels: 🤖Skip Changelog

#3300 Update tag background
  src/components/Tag/Tag.scss
Labels: 🤖Skip Changelog

#3299 Remove border from page with ndl
  src/components/Page/components/Header/Header.scss
Labels: 🤖Skip Changelog

#3298 Applied divider border to components
  src/components/ActionList/ActionList.scss
  src/components/Card/Card.scss
  src/components/DataTable/DataTable.scss
  src/components/DescriptionList/DescriptionList.scss
  src/components/Filters/Filters.scss
  src/components/Layout/Layout.scss
  src/components/Modal/components/Footer/Footer.scss
  src/components/Navigation/Navigation.scss
  src/components/PageActions/PageActions.scss
  src/components/Popover/Popover.scss
  src/components/ResourceList/ResourceList.scss
  src/components/TopBar/components/Menu/Menu.scss
  src/components/TopBar/components/Menu/components/Message/Message.scss
  src/styles/foundation/_borders.scss
Labels: 🤖Skip Changelog

#3312 v5.4.0
  CHANGELOG.md
  README.md
  UNRELEASED.md
  package.json
  src/components/README.md
  src/styles/shared/_buttons.scss
Labels: 🤖Skip Changelog

#3316 Rangeslider focus
  src/components/RangeSlider/components/DualThumb/DualThumb.scss
  src/components/RangeSlider/components/DualThumb/DualThumb.tsx
  src/components/RangeSlider/components/SingleThumb/SingleThumb.scss
  src/components/RangeSlider/components/SingleThumb/SingleThumb.tsx
Labels: 🤖Skip Changelog

#3318 Update Thumbnail.scss
  src/components/Thumbnail/Thumbnail.scss
Labels: 🤖Skip Changelog

#3315 Fixes Badge when it becomes 2 lines due to small viewport.
  UNRELEASED.md
  src/components/Badge/Badge.scss
Labels: ⚗️ Development

#3333 *Expose* bulk actions checkable button
  scripts/build-validate.js
  src/components/BulkActions/BulkActions.scss
  src/components/BulkActions/BulkActions.tsx
  src/components/BulkActions/components/BulkActionButton/BulkActionButton.tsx
  src/components/BulkActions/components/BulkActionButton/index.ts
  src/components/BulkActions/components/index.ts
  src/components/BulkActions/index.ts
  src/components/BulkActions/tests/BulkActions.test.tsx
  src/components/CheckableButton/CheckableButton.scss
  src/components/CheckableButton/CheckableButton.tsx
  src/components/CheckableButton/index.ts
  src/components/CheckableButton/tests/CheckableButton.test.tsx
  src/components/ResourceList/ResourceList.tsx
  src/components/ResourceList/_variables.scss
  src/components/ResourceList/components/index.ts
  src/components/ResourceList/tests/ResourceList.test.tsx
  src/components/index.ts
  src/styles/_common.scss
  src/styles/shared/_private-breakpoints.scss
Labels: 🤖Skip Changelog

#3337 [ButtonGroup] Fix segmented outline button styles
  src/components/Button/Button.scss
  src/components/ButtonGroup/README.md
  src/styles/shared/_buttons.scss
Labels: 🤖Skip Changelog

#3339 Adjust connected filter control spacing
  src/components/Filters/components/ConnectedFilterControl/ConnectedFilterControl.scss
Labels: 🤖Skip Changelog

#3347 Adjust border radius for new design language
  src/components/Popover/Popover.scss
Labels: 🤖Skip Changelog

#3308 [Page header] Single row layout
  UNRELEASED.md
  documentation/Color system.md
  playground/DetailsPage.tsx
  src/components/ActionMenu/components/Actions/Actions.scss
  src/components/ActionMenu/components/Actions/Actions.tsx
  src/components/ActionMenu/components/MenuGroup/MenuGroup.tsx
  src/components/ActionMenu/components/RollupActions/RollupActions.scss
  src/components/ActionMenu/components/RollupActions/RollupActions.tsx
  src/components/ActionMenu/components/SecondaryAction/SecondaryAction.scss
  src/components/ActionMenu/components/SecondaryAction/SecondaryAction.tsx
  src/components/ActionMenu/components/SecondaryAction/index.ts
  src/components/ActionMenu/components/index.ts
  src/components/Breadcrumbs/Breadcrumbs.scss
  src/components/ButtonGroup/ButtonGroup.scss
  src/components/ButtonGroup/ButtonGroup.tsx
  src/components/Page/components/Header/Header.scss
  src/components/Page/components/Header/Header.tsx
  src/components/Page/components/Header/components/Title/Title.scss
  src/components/Page/components/Header/components/Title/Title.tsx
  src/components/Page/components/Header/tests/Header.test.tsx
  src/components/Pagination/Pagination.tsx
  src/styles/shared/_buttons.scss
  src/styles/shared/_page.scss
  src/utilities/theme/tokens.ts
Labels: 🤖Skip Changelog
