Repository Shopify/polaris, pull requests merged in 2020-12, with the labels that each got.

#3676 Revert "[Actions] Do not re-measure on every re-render"
  playground/DetailsPage.tsx
  src/components/ActionMenu/components/Actions/Actions.tsx
Labels: 🤖Skip Changelog

#3679 Fix typo in example manifest.json
  examples/create-react-app-ts-react-testing/public/manifest.json
Labels: 🤖Skip Changelog

#3619 [ActionList] Align ActionList ::before indicator with OptionList
  UNRELEASED.md
  src/components/ActionList/ActionList.scss
  src/components/OptionList/components/Option/Option.scss
  src/styles/shared/_interaction-state.scss
Labels: 🐛Bug

#3693 [DataTable] Add focus ring to heading
  src/components/DataTable/DataTable.scss
Labels: 🤖Skip Changelog

#3675 [Tabs][a11y]: implement focus ring for disclosure and fix high contrast mode on focus and hover
  UNRELEASED.md
  src/components/DatePicker/DatePicker.scss
  src/components/DropZone/DropZone.scss
  src/components/Filters/Filters.scss
  src/components/Tabs/Tabs.scss
  src/components/Tag/Tag.scss
  src/styles/foundation/_accessibility.scss
  src/styles/foundation/_focus-ring.scss
  src/styles/shared/_buttons.scss
Labels: Accessibility

#3049 [Filters] Added the ability to hide the clear filter button
  UNRELEASED.md
  src/components/Filters/Filters.tsx
  src/components/Filters/README.md
  src/components/Filters/tests/Filters.test.tsx
Labels: cla-needed

#3720 fix: image url in mediacard and thumbnail example
  src/components/MediaCard/README.md
  src/components/VideoThumbnail/README.md
Labels: 🤖Skip Changelog

#3728 Investigate a11y fails
  scripts/accessibility-check.js
Labels: 🤖Skip Changelog

#3688 [TextField] Include focus-ring on clear button && Fix clear button in popovers
  UNRELEASED.md
  src/components/Filters/Filters.tsx
  src/components/Filters/components/TagsWrapper/TagsWrapper.tsx
  src/components/Filters/components/TagsWrapper/index.ts
  src/components/Filters/components/TagsWrapper/tests/TagsWrapper.test.tsx
  src/components/Filters/components/index.ts
  src/components/Filters/tests/Filters.test.tsx
  src/components/TextField/TextField.scss
  src/components/TextField/TextField.tsx
  src/components/TextField/tests/TextField.test.tsx
Labels: Accessibility

#3741 🏷️ [OptionList] Export types
  UNRELEASED.md
  src/components/OptionList/OptionList.tsx
  src/components/index.ts
Labels: ⚗️ Development

#3742 Fix navigation text contrast
  UNRELEASED.md
  documentation/Color system.md
  package.json
  src/components/Navigation/Navigation.scss
  yarn.lock
Labels: Accessibility

#3715 [Badge] Remove css fallbacks
  src/components/Badge/Badge.scss
Labels: 🤖Skip Changelog

#3746 Update Navigation.scss
  src/components/Navigation/Navigation.scss
Labels: 🤖Skip Changelog

#3714 [Card] Remove references to NDL
  src/components/Card/Card.scss
  src/components/Card/Card.tsx
Labels: 🤖Skip Changelog

#3719 Avatar remove new dl fallbacks
  src/components/Avatar/Avatar.scss
  src/components/Avatar/Avatar.tsx
  src/components/Avatar/tests/Avatar.test.tsx
Labels: 🤖Skip Changelog

#3752 Get base_ref for Percy in pull request
  .github/workflows/ci-on-push.yml
  .github/workflows/ci.yml
Labels: 🤖Skip Changelog

#3753 [Tooltip] Remove new DL fallbacks
  src/components/Tooltip/Tooltip.scss
Labels: 🤖Skip Changelog

#3711 [FooterHelp] Remove all references to newDesignLanguage
  src/components/FooterHelp/FooterHelp.scss
  src/components/FooterHelp/FooterHelp.tsx
  src/components/FooterHelp/tests/FooterHelp.test.tsx
Labels: 🤖Skip Changelog

#3748 Remove NDL from ActionList
  src/components/ActionList/ActionList.scss
  src/components/ActionList/ActionList.tsx
  src/components/ActionList/tests/ActionList.test.tsx
Labels: 🤖Skip Changelog
