Repository Shopify/polaris, pull requests merged in 2020-02, with the labels that each got.

#2703 [Design Lang 🎨] Fix focus-ring Sass compile error
  src/styles/foundation/_focus-ring.scss
Labels: 🤖Skip Changelog

#2622 [DetailsPage] Add context control
  playground/DetailsPage.scss
  playground/DetailsPage.tsx
  scripts/tsconfig.json
  src/utilities/theme/tokens.ts
  tsconfig.json
Labels: 🤖Skip Changelog

#2678 [Select] Apply design language to Select
  src/components/Select/Select.scss
  src/components/Select/Select.tsx
  src/components/Select/tests/Select.test.tsx
Labels: 🤖Skip Changelog

#2712 High contrast border for button
  UNRELEASED.md
  src/styles/shared/_buttons.scss
Labels: Accessibility, 🎨 Design

#2716 [Color system] clean up missed globalTheming class names
  src/components/Select/Select.scss
Labels: 🤖Skip Changelog

#2691 [ContextualSaveBar] Apply design language
  documentation/Color system.md
  playground/DetailsPage.tsx
  src/components/Frame/Frame.scss
  src/components/Frame/Frame.tsx
  src/components/Frame/components/CSSAnimation/CSSAnimation.scss
  src/components/Frame/components/CSSAnimation/CSSAnimation.tsx
  src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.scss
  src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.tsx
  src/components/Frame/components/ContextualSaveBar/tests/ContextualSaveBar.test.tsx
  src/components/Frame/tests/Frame.test.tsx
  src/utilities/theme/tokens.ts
Labels: 🤖Skip Changelog

#2713 High contrast actionlist hover
  UNRELEASED.md
  src/components/ActionList/ActionList.scss
Labels: Accessibility

#2696 Navigation.Section: Use useUniqueId
  src/components/Navigation/components/Section/Section.tsx
Labels: 🤖Skip Changelog

#2715 [Color system] Require newDesignLanguage feature flag
  src/components/ActionList/ActionList.tsx
  src/components/ActionList/components/Item/Item.tsx
  src/components/AppProvider/AppProvider.tsx
  src/components/Avatar/Avatar.tsx
  src/components/Button/Button.tsx
  src/components/Checkbox/Checkbox.tsx
  src/components/Navigation/Navigation.tsx
  src/components/PolarisTestProvider/PolarisTestProvider.tsx
  src/components/RadioButton/RadioButton.tsx
  src/components/ResourceList/components/CheckableButton/CheckableButton.tsx
  src/components/Select/Select.tsx
  src/components/TextField/TextField.tsx
  src/components/ThemeProvider/ThemeProvider.tsx
  src/components/TopBar/TopBar.tsx
  src/components/TopBar/components/SearchField/SearchField.tsx
  src/utilities/features/types.ts
Labels: 🤖Skip Changelog

#2724 [Color system] update to latest polaris tokens beta, and change variant names to reflect changes in tokens
  documentation/Color system.md
  package.json
  src/components/ActionList/ActionList.scss
  src/components/Button/Button.scss
  src/components/DropZone/components/FileUpload/FileUpload.scss
  src/components/Link/Link.scss
  src/components/Navigation/Navigation.scss
  src/components/RadioButton/RadioButton.scss
  src/components/RangeSlider/components/DualThumb/DualThumb.scss
  src/components/RangeSlider/components/SingleThumb/SingleThumb.scss
  src/components/Select/Select.scss
  src/components/ThemeProvider/tests/ThemeProvider.test.tsx
  src/components/TopBar/components/SearchField/SearchField.scss
  src/styles/shared/_buttons.scss
  src/styles/shared/_controls.scss
  yarn.lock
Labels: 🤖Skip Changelog

#2723 [TextField] Flatten focus ring on connected TextField
  src/components/TextField/TextField.scss
  src/components/TextField/TextField.tsx
  src/components/TextField/tests/TextField.test.tsx
Labels: 🤖Skip Changelog

#2709 [OptionList] Apply design language
  src/components/Card/Card.scss
  src/components/OptionList/OptionList.scss
  src/components/OptionList/OptionList.tsx
  src/components/OptionList/components/Checkbox/Checkbox.scss
  src/components/OptionList/components/Checkbox/Checkbox.tsx
  src/components/OptionList/components/Checkbox/tests/Checkbox.test.tsx
  src/components/OptionList/components/Option/Option.scss
  src/components/OptionList/components/Option/Option.tsx
  src/components/OptionList/components/Option/tests/Option.test.tsx
  src/components/OptionList/tests/OptionList.test.tsx
Labels: 🤖Skip Changelog

#2758 Allow failures on new pipeline
  shipit.yml
Labels: 🤖Skip Changelog

#2728 [Tag, Tabs] Fix high contrast mode
  src/components/Tabs/Tabs.scss
  src/components/Tag/Tag.scss
Labels: Accessibility, 🤖Skip Changelog

#2746 [Button] New design language
  src/components/Button/Button.scss
  src/styles/shared/_buttons.scss
Labels: 🤖Skip Changelog

#2766 Update import paths
  documentation/Color system.md
  scripts/color-system-docs.js
Labels: 🤖Skip Changelog

#2753 [Modal] Fix shadow
  documentation/Color system.md
  src/utilities/theme/tokens.ts
Labels: 🤖Skip Changelog

#2768 [Color system] use design language on checkers
  src/components/ColorPicker/ColorPicker.scss
Labels: 🤖Skip Changelog

#2771 [Color system] finish applying color system to datatable
  src/components/DataTable/DataTable.scss
Labels: 🤖Skip Changelog

#2721 Applied design language to Filters
  src/components/Filters/Filters.scss
  src/components/Filters/Filters.tsx
  src/components/Filters/components/ConnectedFilterControl/ConnectedFilterControl.scss
  src/components/Filters/tests/Filters.test.tsx
Labels: 🤖Skip Changelog

#2776 Added high contrast outline to focus ring mixin
  src/styles/_common.scss
  src/styles/foundation/_accessibility.scss
  src/styles/foundation/_focus-ring.scss
Labels: 🤖Skip Changelog

#2785 [EmptyState] Update image url for in-context example
  src/components/EmptyState/README.md
Labels: 🤖Skip Changelog

#2787 [Color system] fix menu action test
  src/components/ActionMenu/components/MenuAction/tests/MenuAction.test.tsx
Labels: 🤖Skip Changelog

#2655 [RangeSlider] Apply color system to thumb
  src/components/RangeSlider/RangeSlider.scss
  src/components/RangeSlider/components/DualThumb/DualThumb.scss
  src/components/RangeSlider/components/DualThumb/DualThumb.tsx
  src/components/RangeSlider/components/DualThumb/tests/DualThumb.test.tsx
  src/components/RangeSlider/components/SingleThumb/SingleThumb.scss
  src/utilities/theme/tokens.ts
Labels: 🤖Skip Changelog

#2788 [Color system] Upgrade tokens
  documentation/Color system.md
  package.json
  src/components/ThemeProvider/tests/ThemeProvider.test.tsx
  yarn.lock
Labels: 🤖Skip Changelog

#2795 [ThemeProvider] Allow passing in a custom config
  package.json
  src/utilities/theme/types.ts
  src/utilities/theme/utils.ts
  yarn.lock
Labels: 🤖Skip Changelog

#2799 Removed linear-gradient from var
  src/components/Filters/Filters.scss
Labels: 🤖Skip Changelog
