Repository Shopify/polaris, pull requests merged in 2020-11, with the labels that each got.

#3592 Fix test assertion in thumbnail test
  src/components/Thumbnail/tests/Thumbnail.test.tsx
Labels: 🤖Skip Changelog

#3596 [ResourceItem] Fix border-radius on last element
  src/components/ResourceItem/ResourceItem.scss
Labels: 🤖Skip Changelog

#3561 🚚 [Utilities] Move isNewDesignLanguageColor to a new file
  src/components/Icon/Icon.tsx
  src/index.ts
  src/types.ts
  src/utilities/color-new-design-language.ts
Labels: Good first issue, 🤖Skip Changelog

#3590 ✨ [Button] Add new role prop
  UNRELEASED.md
  scripts/accessibility-check.js
  src/components/Button/Button.tsx
  src/components/Button/tests/Button.test.tsx
  src/components/UnstyledButton/UnstyledButton.tsx
  src/components/UnstyledButton/tests/UnstyledButton.test.tsx
  src/types.ts
Labels: ⚗️ Development

#3603 [Avatar] Fix background color
  src/components/Avatar/Avatar.scss
Labels: 🤖Skip Changelog

#3621 [color-transformers > rgbToHsbl] Fix brightness precision of HSB conversions by increasing from 2 decimal digits to 4
  UNRELEASED.md
  src/utilities/color-transformers.ts
  src/utilities/tests/color-transformers.test.ts
Labels: 🐛Bug

#3626 💄 [SCSS] Apply old design language color fallback to focus-ring
  UNRELEASED.md
  src/styles/foundation/_focus-ring.scss
Labels: ⚗️ Development

#3620 [Actions] Do not re-measure on every re-render
  playground/DetailsPage.tsx
  src/components/ActionMenu/components/Actions/Actions.tsx
Labels: 🤖Skip Changelog

#3599 [Frame] Change skip to content from button to anchor tag
  src/components/Frame/Frame.scss
  src/components/Frame/Frame.tsx
  src/components/Frame/tests/Frame.test.tsx
Labels: 🤖Skip Changelog

#3640 [color-transformers > Hsbl] Increase precision of hue, saturation, lightness, and alpha
  UNRELEASED.md
  src/components/ThemeProvider/tests/ThemeProvider.test.tsx
  src/utilities/color-transformers.ts
  src/utilities/roundNumberToDecimalPlaces.ts
  src/utilities/tests/color-transformers.test.ts
  src/utilities/tests/roundNumberToDecimals.test.ts
Labels: 🐛Bug
