Repository Shopify/polaris, pull requests merged in 2021-06, with the labels that each got.

#4243 Fix links in contributing.md
  .github/CONTRIBUTING.md
  documentation/Testing.md
Labels: 🤖Skip Changelog

#4249 [DataTable] Fix console warnings caused by setting state after unmount
  UNRELEASED.md
  src/components/DataTable/DataTable.tsx
  src/components/DataTable/tests/DataTable.test.tsx
Labels: 🐛Bug

#4191 Upgrade to node v12
  .github/workflows/ci.yml
  .nvmrc
  UNRELEASED.md
  dev.yml
  examples/create-react-app-ts-react-testing/yarn.lock
  examples/create-react-app/yarn.lock
  examples/webpack/yarn.lock
  yarn.lock
Labels: v7.0.0

#4258 Deploy storybook
  .shopify-build/polaris-react.yml
  config/secrets.production.ejson
  infrastructure/runtimes/production-unrestricted-4b2e/manifest.yaml
  infrastructure/runtimes/production-unrestricted-4b2e/manifest.yaml.lock
  package.json
Labels: 🤖Skip Changelog

#4279 Bump react and react-dom to v16.14.0
  UNRELEASED.md
  package.json
  yarn.lock
Labels: v7.0.0

#4267 [TextField] Make autoComplete prop a required string
  UNRELEASED.md
  examples/create-react-app-ts-react-testing/src/App.tsx
  examples/create-react-app/src/App.js
  examples/next.js/pages/index.js
  examples/webpack/src/App.js
  playground/DetailsPage.tsx
  src/components/Autocomplete/components/ComboBox/tests/ComboBox.test.tsx
  src/components/Autocomplete/components/TextField/TextField.tsx
  src/components/Autocomplete/tests/Autocomplete.test.tsx
  src/components/ChoiceList/README.md
  src/components/Filters/Filters.tsx
  src/components/Filters/README.md
  src/components/Form/README.md
  src/components/FormLayout/README.md
  src/components/FormLayout/components/Group/tests/Group.test.tsx
  src/components/FormLayout/components/Item/tests/Item.test.tsx
  src/components/FormLayout/tests/FormLayout.test.tsx
  src/components/Frame/README.md
  src/components/IndexTable/README.md
  src/components/Layout/README.md
  src/components/Modal/README.md
  src/components/Pagination/tests/Pagination.test.tsx
  src/components/Popover/README.md
  src/components/Popover/components/PopoverOverlay/tests/PopoverOverlay.test.tsx
  src/components/RangeSlider/README.md
  src/components/ResourceList/README.md
  src/components/ResourceList/components/FilterControl/FilterControl.tsx
  src/components/ResourceList/components/FilterControl/components/DateSelector/DateSelector.tsx
  src/components/ResourceList/components/FilterControl/components/FilterValueSelector/FilterValueSelector.tsx
  src/components/Select/README.md
  src/components/Spinner/README.md
  src/components/TextField/README.md
  src/components/TextField/TextField.tsx
  src/components/TextField/tests/TextField.test.tsx
  src/components/Tooltip/README.md
  src/components/TrapFocus/tests/TrapFocus.test.tsx
  src/components/VisuallyHidden/README.md
Labels: v7.0.0
