Repository Shopify/polaris, pull requests merged in 2021-01, with the labels that each got.

#3766 Update @google-cloud/storage
  package.json
  yarn.lock
Labels: 🤖Skip Changelog

#3773 Use vendor-provided actions for Chromatic and Percy
  .github/workflows/ci.yml
  package.json
  yarn.lock
Labels: 🤖Skip Changelog

#3780 [DataTable] Remove new DL fallbacks
  src/components/DataTable/DataTable.scss
Labels: 🤖Skip Changelog

#3783 [Progress Bar] Remove new DL fallbacks
  src/components/ProgressBar/ProgressBar.scss
Labels: 🤖Skip Changelog

#3782 [ExceptionList] Remove new DL fallbacks
  src/components/ExceptionList/ExceptionList.scss
Labels: 🤖Skip Changelog

#3786 Fixing shrink ray PR check
  .github/workflows/ci.yml
  scripts/build-shrink-ray.js
Labels: 🤖Skip Changelog

#3760 [Banner] Remove NDL fallbacks
  src/components/Banner/Banner.scss
  src/components/Banner/Banner.tsx
  src/components/Banner/tests/Banner.test.tsx
Labels: 🤖Skip Changelog

#3781 [Keyboard key] Remove new DL fallbacks
  src/components/KeyboardKey/KeyboardKey.scss
Labels: 🤖Skip Changelog

#3771 [ResourceList] Remove NDL fallbacks
  src/components/ResourceList/ResourceList.scss
  src/components/ResourceList/_variables.scss
Labels: 🤖Skip Changelog

#3768 [Checkbox] Remove NDL fallbacks
  src/components/Checkbox/Checkbox.scss
  src/components/Checkbox/Checkbox.tsx
  src/components/Checkbox/tests/Checkbox.test.tsx
Labels: 🤖Skip Changelog

#3778 [WIP] Remove newDesignLanguageColor type and more newDL fallbacks in Spinner and Icon
  locales/en.json
  src/components/Autocomplete/README.md
  src/components/Button/Button.tsx
  src/components/DropZone/DropZone.tsx
  src/components/Icon/Icon.scss
  src/components/Icon/Icon.tsx
  src/components/Icon/tests/Icon.test.tsx
  src/components/Modal/components/CloseButton/CloseButton.tsx
  src/components/ResourceList/components/FilterControl/FilterControl.tsx
  src/components/ResourceList/components/FilterControl/components/DateSelector/DateSelector.tsx
  src/components/Spinner/README.md
  src/components/Spinner/Spinner.scss
  src/components/Spinner/Spinner.tsx
  src/components/Spinner/tests/Spinner.test.tsx
  src/components/TextField/TextField.tsx
  src/index.ts
  src/types.ts
  src/utilities/color-new-design-language.ts
Labels: 🤖Skip Changelog

#3767 [ResourceItem] Remove new DL references and fallbacks
  src/components/ResourceItem/ResourceItem.scss
  src/components/ResourceItem/ResourceItem.tsx
  src/components/ResourceItem/tests/ResourceItem.test.tsx
Labels: 🤖Skip Changelog

#3763 [VideoThumbnail] Remove new DL fallbacks
  src/components/VideoThumbnail/VideoThumbnail.scss
Labels: 🤖Skip Changelog

#3755 [Popover] Remove new DL fallbacks
  src/components/Popover/Popover.scss
Labels: 🤖Skip Changelog

#3764 [Thumbnail] Remove new DL fallbacks
  src/components/Thumbnail/Thumbnail.scss
Labels: 🤖Skip Changelog

#3784 [Date picker] Remove NDL fallbacks
  src/components/DatePicker/DatePicker.scss
  src/components/DatePicker/DatePicker.tsx
  src/components/DatePicker/tests/DatePicker.test.tsx
Labels: 🤖Skip Changelog

#3791 [SkeletonPage] Remove new DL fallbacks
  src/components/PositionedOverlay/tests/PositionedOverlay.test.tsx
  src/components/SkeletonPage/SkeletonPage.scss
  src/components/SkeletonPage/SkeletonPage.tsx
  src/components/SkeletonPage/tests/SkeletonPage.test.tsx
Labels: 🤖Skip Changelog

#3801 [TextStyle] Remove new DL fallbacks
  src/components/TextStyle/TextStyle.scss
Labels: 🤖Skip Changelog

#3798 [Link] Remove new DL and fallbacks
  src/components/Link/Link.scss
  src/components/Link/Link.tsx
  src/components/Link/tests/Link.test.tsx
Labels: 🤖Skip Changelog

#3799 [Modal] Remove new DL fallbacks
  src/components/Modal/components/CloseButton/CloseButton.scss
  src/components/Modal/components/Dialog/Dialog.scss
  src/components/Modal/components/Section/Section.scss
Labels: 🤖Skip Changelog

#3796 [Page, Header] remove new DL
  src/components/Page/Page.tsx
  src/components/Page/components/Header/Header.scss
  src/components/Page/components/Header/Header.tsx
  src/components/Page/components/Header/components/Title/Title.scss
  src/components/Page/components/Header/components/Title/Title.tsx
  src/components/Page/components/Header/components/Title/tests/Title.test.tsx
  src/components/Page/components/Header/tests/Header.test.tsx
  src/styles/shared/_page.scss
Labels: 🤖Skip Changelog

#3805 [Navigation] Remove outline on focus
  src/components/Navigation/Navigation.scss
Labels: 🤖Skip Changelog

#3802 [Color picker] Remove NDL fallback
  src/components/ColorPicker/ColorPicker.scss
Labels: 🤖Skip Changelog

#3794 Undo high contrast media query name change
  src/components/DatePicker/DatePicker.scss
  src/components/DropZone/DropZone.scss
  src/components/Filters/Filters.scss
  src/components/Tabs/Tabs.scss
  src/components/Tag/Tag.scss
  src/styles/foundation/_accessibility.scss
  src/styles/foundation/_focus-ring.scss
  src/styles/shared/_buttons.scss
Labels: 🤖Skip Changelog

#3709 🐛 + ✨ [Button] Bug fixes, small improvements, new "select" disclosure
  UNRELEASED.md
  src/components/Button/Button.scss
  src/components/Button/Button.tsx
  src/components/Button/README.md
  src/components/Button/tests/Button.test.tsx
  src/styles/shared/_buttons.scss
  src/types.ts
Labels: 🐛Bug

#3810 [Tags] Fix invalid ms-high-contrast media query css without selector in Tags
  UNRELEASED.md
  src/components/Tag/Tag.scss
Labels: Accessibility, 🐛Bug

#3818 Fix broken tab role
  src/components/Tabs/components/Tab/Tab.tsx
Labels: 🤖Skip Changelog

#3814 [Inline error] Remove ndl fallback
  src/components/InlineError/InlineError.scss
Labels: 🤖Skip Changelog

#3823 [Collapsible] Do not render children when fully closed
  src/components/Collapsible/Collapsible.tsx
  src/components/Collapsible/tests/Collapsible.test.tsx
Labels: 🤖Skip Changelog

#3819 [Scrollable] Remove new DL fallbacks
  src/components/Scrollable/Scrollable.scss
Labels: 🤖Skip Changelog

#3797 [EmptyState] Remove new DL
  src/components/EmptyState/EmptyState.scss
  src/components/EmptyState/EmptyState.tsx
  src/components/EmptyState/tests/EmptyState.test.tsx
Labels: 🤖Skip Changelog

#3808 [DropZone] Remove new DL references and fallbacks
  src/components/DropZone/DropZone.scss
  src/components/DropZone/DropZone.tsx
  src/components/DropZone/components/FileUpload/FileUpload.scss
  src/components/DropZone/components/FileUpload/FileUpload.tsx
  src/components/DropZone/components/FileUpload/tests/FileUpload.test.tsx
  src/components/DropZone/tests/DropZone.test.tsx
Labels: 🤖Skip Changelog

#3762 [Navigation] Remove new DL references and fallbacks
  src/components/Navigation/Navigation.scss
  src/components/Navigation/Navigation.tsx
  src/components/Navigation/_variables.scss
  src/components/Navigation/tests/Navigation.test.tsx
Labels: 🤖Skip Changelog

#3807 [Toast] Remove new design language fallbacks
  src/components/Frame/components/Toast/Toast.scss
Labels: 🤖Skip Changelog

#3828 [Scrollable] Remove focus outline
  src/components/Scrollable/Scrollable.scss
Labels: 🤖Skip Changelog

#3821 [Layout ] Remove new design language fallbacks
  src/components/Layout/Layout.scss
  src/components/Layout/Layout.tsx
Labels: 🤖Skip Changelog

#3813 [Filters] Remove new design language fallbacks
  src/components/Filters/Filters.scss
  src/components/Filters/Filters.tsx
  src/components/Popover/Popover.scss
Labels: 🤖Skip Changelog

#3787 [Label, Labelled] Change `label` prop type to `React.ReactNode`
  UNRELEASED.md
  src/components/DropZone/DropZone.tsx
  src/components/Label/Label.tsx
  src/components/Labelled/Labelled.tsx
  src/components/RangeSlider/types.ts
  src/components/Select/Select.tsx
  src/components/TextField/TextField.tsx
Labels: ⚗️ Development

#3833 [Pagination] Remove NDL fallbacks
  src/components/Page/components/Header/Header.tsx
  src/components/Page/components/Header/tests/Header.test.tsx
  src/components/Pagination/Pagination.scss
  src/components/Pagination/Pagination.tsx
  src/components/Pagination/tests/Pagination.test.tsx
Labels: 🤖Skip Changelog

#3836 [Breadcrumbs] Remove new DL
  src/components/Breadcrumbs/Breadcrumbs.scss
  src/components/Breadcrumbs/Breadcrumbs.tsx
  src/components/Breadcrumbs/tests/Breadcrumbs.test.tsx
  src/components/Page/components/Header/Header.scss
  src/components/Page/components/Header/components/Title/Title.scss
Labels: 🤖Skip Changelog

#3850 [Sheet] Remove new DL fallbacks
  src/components/Sheet/Sheet.scss
Labels: 🤖Skip Changelog

#3845 [Frame] Remove all references to new DL
  src/components/Frame/Frame.scss
  src/components/Frame/Frame.tsx
  src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.scss
  src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.tsx
  src/components/Frame/components/ContextualSaveBar/tests/ContextualSaveBar.test.tsx
  src/components/Frame/components/Loading/Loading.scss
  src/components/Frame/components/ToastManager/ToastManager.scss
  src/components/Frame/tests/Frame.test.tsx
  src/components/TopBar/TopBar.scss
  src/components/TopBar/TopBar.tsx
  src/components/TopBar/_variables.scss
  src/components/TopBar/components/Menu/Menu.scss
  src/components/TopBar/components/Search/Search.scss
  src/components/TopBar/components/Search/Search.tsx
  src/components/TopBar/components/SearchDismissOverlay/SearchDismissOverlay.scss
  src/components/TopBar/components/SearchDismissOverlay/SearchDismissOverlay.tsx
  src/components/TopBar/components/SearchField/SearchField.scss
  src/components/TopBar/components/SearchField/SearchField.tsx
  src/components/TopBar/components/SearchField/tests/SearchField.test.tsx
  src/components/TopBar/tests/TopBar.test.tsx
Labels: 🤖Skip Changelog

#3837 [ToastManager] Change aria-live to assertive for accessibility
  UNRELEASED.md
  src/components/Frame/components/ToastManager/ToastManager.tsx
  src/components/Frame/components/ToastManager/tests/ToastManager.test.tsx
Labels: Accessibility

#3749 Update storybook to 6.1
  package.json
  yarn.lock
Labels: 🤖Skip Changelog

#3825 [Tabs] Remove new DL references and fallbacks
  src/components/Tabs/Tabs.scss
  src/components/Tabs/Tabs.tsx
  src/components/Tabs/components/Item/Item.tsx
  src/components/Tabs/components/Item/tests/Item.test.tsx
  src/components/Tabs/components/List/List.tsx
  src/components/Tabs/components/List/tests/List.test.tsx
  src/components/Tabs/components/Tab/Tab.tsx
  src/components/Tabs/components/Tab/tests/Tab.test.tsx
  src/components/Tabs/tests/Tabs.test.tsx
Labels: 🤖Skip Changelog

#3855 [Select] Remove new DL fallbacks
  src/components/Select/Select.scss
  src/components/Select/Select.tsx
  src/components/Select/tests/Select.test.tsx
Labels: 🤖Skip Changelog

#3710 [Tags] Remove all references to newDesignLanguage
  src/components/Tag/Tag.scss
  src/components/Tag/Tag.tsx
  src/components/Tag/tests/Tag.test.tsx
Labels: 🤖Skip Changelog

#3861 [TextField] remove ndl fallbacks
  src/components/TextField/TextField.scss
  src/components/TextField/TextField.tsx
  src/components/TextField/tests/TextField.test.tsx
  src/styles/shared/_typography.scss
Labels: 🤖Skip Changelog

#3854 [ActionList] Remove child selector from .active styles
  UNRELEASED.md
  src/components/ActionList/ActionList.scss
Labels: 🐛Bug

#3863 Update translations: default
  locales/fr.json
Labels: cla-needed

#3842 [Range slider] Remove ndl fallbacks
  src/components/RangeSlider/RangeSlider.scss
  src/components/RangeSlider/components/DualThumb/DualThumb.scss
  src/components/RangeSlider/components/DualThumb/DualThumb.tsx
  src/components/RangeSlider/components/DualThumb/tests/DualThumb.test.tsx
  src/components/RangeSlider/components/SingleThumb/SingleThumb.scss
  src/components/RangeSlider/components/SingleThumb/SingleThumb.tsx
Labels: 🤖Skip Changelog

#3862 [OptionList] Remove ndl fallbacks
  src/components/Checkbox/Checkbox.scss
  src/components/OptionList/components/Checkbox/Checkbox.scss
  src/components/OptionList/components/Checkbox/Checkbox.tsx
  src/components/OptionList/components/Checkbox/tests/Checkbox.test.tsx
  src/components/OptionList/components/Option/Option.scss
  src/components/OptionList/components/Option/Option.tsx
  src/components/OptionList/components/Option/tests/Option.test.tsx
  src/styles/shared/_controls.scss
Labels: 🤖Skip Changelog

#3754 [Filters] Fix loss of focus after clicking clear all filters
  UNRELEASED.md
  src/components/Filters/Filters.tsx
  src/components/Filters/tests/Filters.test.tsx
Labels: Accessibility

#3857 [Radio] Remove ndl fallbacks
  src/components/RadioButton/RadioButton.scss
  src/components/RadioButton/RadioButton.tsx
  src/components/RadioButton/tests/RadioButton.test.tsx
Labels: 🤖Skip Changelog

#3870 [ActionList] Remove ndl fallbacks
  src/components/ActionList/components/Item/Item.tsx
  src/components/ActionList/components/Item/tests/Item.test.tsx
  src/components/ActionList/components/Section/Section.tsx
Labels: 🤖Skip Changelog

#3878 [Tabs] ndl cleanup
  src/components/Tabs/Tabs.tsx
Labels: 🤖Skip Changelog

#3881 [ToolTip] Clean up and fixes for a11y test
  src/components/Tooltip/Tooltip.tsx
  src/components/Tooltip/components/TooltipOverlay/TooltipOverlay.scss
  src/components/Tooltip/components/TooltipOverlay/TooltipOverlay.tsx
  src/components/Tooltip/tests/Tooltip.test.tsx
Labels: 🤖Skip Changelog

#3877 [Spinner] ndl fallback cleanup
  src/components/Spinner/Spinner.tsx
Labels: 🤖Skip Changelog

#3874 [Connected] Remove ndl fallbacks
  src/components/Connected/Connected.scss
  src/components/Connected/Connected.tsx
Labels: 🤖Skip Changelog

#3875 [OptionList] remove ndl fallbacks
  src/components/OptionList/OptionList.scss
  src/components/OptionList/OptionList.tsx
  src/components/OptionList/tests/OptionList.test.tsx
Labels: 🤖Skip Changelog

#3871 [CheckableButton] Remove ndl fallbacks
  src/components/CheckableButton/CheckableButton.scss
  src/components/CheckableButton/CheckableButton.tsx
  src/components/CheckableButton/tests/CheckableButton.test.tsx
Labels: 🤖Skip Changelog

#3885 V6 ndl true
  src/components/AppProvider/AppProvider.tsx
Labels: 🤖Skip Changelog

#3873 [Filters] Remove ndl fallbacks
  src/components/Filters/Filters.tsx
  src/components/Filters/components/ConnectedFilterControl/ConnectedFilterControl.scss
  src/components/Filters/components/ConnectedFilterControl/ConnectedFilterControl.tsx
Labels: 🤖Skip Changelog

#3887 Remove some mentions of new DL in tests
  src/components/Filters/tests/Filters.test.tsx
  src/components/OptionList/components/Checkbox/tests/Checkbox.test.tsx
  src/components/Page/tests/Page.test.tsx
Labels: 🤖Skip Changelog

#3888 Clean up fallbacks
  src/components/Card/Card.scss
  src/components/CheckableButton/CheckableButton.scss
  src/components/Frame/Frame.scss
  src/components/Tag/Tag.scss
  src/components/TopBar/components/SearchField/SearchField.scss
  src/styles/foundation/_borders.scss
  src/styles/foundation/_focus-ring.scss
  src/styles/shared/_interaction-state.scss
  src/styles/shared/_typography.scss
Labels: 🤖Skip Changelog

#3849 [AppProvider & ThemeProvider] remove ndl
  .storybook/preview.js
  src/components/AppProvider/AppProvider.tsx
  src/components/AppProvider/README.md
  src/components/Button/Button.tsx
  src/components/Button/tests/Button.test.tsx
  src/components/PolarisTestProvider/PolarisTestProvider.tsx
  src/components/Popover/Popover.tsx
  src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx
  src/components/ThemeProvider/README.md
  src/components/ThemeProvider/ThemeProvider.tsx
  src/components/ThemeProvider/tests/ThemeProvider.test.tsx
  src/components/TopBar/components/Menu/Menu.tsx
  src/components/TopBar/components/UserMenu/UserMenu.tsx
  src/utilities/color-manipulation.ts
  src/utilities/color-names.ts
  src/utilities/color-transformers.ts
  src/utilities/features/tests/hooks.test.tsx
  src/utilities/features/types.ts
  src/utilities/tests/color-manipulation.test.ts
  src/utilities/tests/color-names.test.ts
  src/utilities/theme/config.ts
  src/utilities/theme/index.ts
  src/utilities/theme/tests/utils.test.ts
  src/utilities/theme/types.ts
  src/utilities/theme/utils.ts
Labels: 🤖Skip Changelog

#3890 Clean up banner mixin
  src/components/Banner/Banner.scss
Labels: 🤖Skip Changelog

#3889 Add missing fallbacks, remove unused vars and mixins
  UNRELEASED.md
  src/components/Choice/Choice.scss
  src/components/DropZone/components/FileUpload/FileUpload.scss
  src/components/Frame/Frame.scss
  src/components/TopBar/components/SearchDismissOverlay/SearchDismissOverlay.scss
  src/components/VideoThumbnail/VideoThumbnail.scss
  src/styles/shared/_skeleton.scss
  src/styles/shared/_typography.scss
Labels: 🤖Skip Changelog

#3817 [Button] Remove ndl fallbacks
  UNRELEASED.md
  src/components/Button/Button.scss
  src/components/Button/Button.tsx
  src/components/Button/tests/Button.test.tsx
  src/styles/shared/_buttons.scss
Labels: 🤖Skip Changelog

#3891 [Range Slider] Add test comments
  src/components/RangeSlider/components/DualThumb/tests/DualThumb.test.tsx
Labels: 🤖Skip Changelog

#3876 Update translations: default
  locales/nl.json
Labels: cla-needed

#3880 Fixes tests & change API & other changes
  locales/en.json
  src/components/Autocomplete/Autocomplete.tsx
  src/components/Autocomplete/components/ComboBox/ComboBox.tsx
  src/components/Autocomplete/components/ComboBox/components/TextField/TextField.tsx
  src/components/Autocomplete/components/ComboBox/components/TextField/tests/TextField.test.tsx
  src/components/Autocomplete/components/ComboBox/index.ts
  src/components/Autocomplete/components/ComboBox/tests/ComboBox.test.tsx
  src/components/Autocomplete/components/ComboBox/utilities/combo-box/index.ts
  src/components/Autocomplete/components/ComboBox/utilities/index.ts
  src/components/Autocomplete/components/ComboBoxOld/ComboBox.scss
  src/components/Autocomplete/components/ComboBoxOld/ComboBox.tsx
  src/components/Autocomplete/components/ComboBoxOld/context.tsx
  src/components/Autocomplete/components/ComboBoxOld/index.ts
  src/components/Autocomplete/components/ComboBoxOld/tests/ComboBox.test.tsx
  src/components/Autocomplete/components/ListBox/ListBox.tsx
  src/components/Autocomplete/components/ListBox/components/Action/Action.tsx
  src/components/Autocomplete/components/ListBox/components/Action/tests/Action.test.tsx
  src/components/Autocomplete/components/ListBox/components/Header/Header.scss
  src/components/Autocomplete/components/ListBox/components/Header/tests/Header.test.tsx
  src/components/Autocomplete/components/ListBox/components/Loading/Loading.tsx
  src/components/Autocomplete/components/ListBox/components/Loading/tests/Loading.test.tsx
  src/components/Autocomplete/components/ListBox/components/Option/Option.scss
  src/components/Autocomplete/components/ListBox/components/Option/Option.tsx
  src/components/Autocomplete/components/ListBox/components/Option/index.ts
  src/components/Autocomplete/components/ListBox/components/Option/tests/Option.test.tsx
  src/components/Autocomplete/components/ListBox/components/Section/tests/Section.test.tsx
  src/components/Autocomplete/components/ListBox/components/TextOption/TextOption.scss
  src/components/Autocomplete/components/ListBox/components/TextOption/TextOption.tsx
  src/components/Autocomplete/components/ListBox/components/TextOption/tests/TextOption.test.tsx
  src/components/Autocomplete/components/ListBox/index.ts
  src/components/Autocomplete/components/ListBox/tests/ListBox.test.tsx
  src/components/Autocomplete/components/ListBox/utilities/context/list-box.ts
  src/components/Autocomplete/components/ListBox/utilities/scroll-into-view.ts
  src/components/Autocomplete/components/MappedAction/MappedAction.scss
  src/components/Autocomplete/components/MappedAction/MappedAction.tsx
  src/components/Autocomplete/components/MappedAction/index.ts
  src/components/Autocomplete/components/MappedAction/tests/MappedAction.test.tsx
  src/components/Autocomplete/components/MappedOption/MappedOption.tsx
  src/components/Autocomplete/components/MappedOption/tests/MappedOption.test.tsx
  src/components/Autocomplete/components/index.ts
  src/components/Autocomplete/context.ts
  src/components/Autocomplete/tests/Autocomplete.test.tsx
  src/test-utilities/list-box.tsx
  src/test-utilities/react-testing.tsx
  src/utilities/closest-parent-match.ts
  src/utilities/combo-box/context.tsx
  src/utilities/combo-box/hooks.tsx
  src/utilities/combo-box/index.ts
  src/utilities/combo-box/tests/hook.test.tsx
  src/utilities/list-box/context.ts
  src/utilities/list-box/hooks.ts
  src/utilities/list-box/index.ts
  src/utilities/list-box/types.ts
  src/utilities/scroll-into-view.ts
  src/utilities/tests/closest-parent-match.test.ts
  tests/setup.ts
Labels: 🤖Skip Changelog

#3911 Fix up backdrops in new design language
  UNRELEASED.md
  src/components/Icon/Icon.scss
  src/components/Icon/Icon.tsx
Labels: 🤖Skip Changelog

#3916 Remove Icon backdrop warning message
  locales/cs.json
  locales/da.json
  locales/de.json
  locales/en.json
  locales/es.json
  locales/fi.json
  locales/fr.json
  locales/hi.json
  locales/it.json
  locales/ja.json
  locales/ko.json
  locales/ms.json
  locales/nb.json
  locales/nl.json
  locales/pl.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/sv.json
  locales/th.json
  locales/tr.json
  locales/vi.json
  locales/zh-CN.json
  locales/zh-TW.json
  src/components/Icon/Icon.tsx
Labels: 🤖Skip Changelog

#3917 Default to new Design Language in storybook
  .storybook/preview.js
  scripts/accessibility-check.js
Labels: 🤖Skip Changelog

#3922 Test async translations [should be reverted]
  locales/en.json
Labels: 🤖Skip Changelog

#3930 Create migrating-from-v5-to-v6.md
  documentation/guides/migrating-from-v5-to-v6.md
Labels: 🤖Skip Changelog

#3927 Add title for deprecated CSS variables
  documentation/Color system.md
  scripts/color-system-docs.js
Labels: 🤖Skip Changelog

#3929 Add information for CSS usage with CSS variables
  src/components/README.md
Labels: 🤖Skip Changelog

#3945 Rename CSS class in Icon
  src/components/Icon/Icon.scss
  src/components/Icon/Icon.tsx
  src/components/Icon/tests/Icon.test.tsx
Labels: 🤖Skip Changelog

#2987 [Tag] Clarify that onClick and onRemove are mutually exclusive
  UNRELEASED.md
  src/components/Tag/README.md
  src/components/Tag/Tag.tsx
Labels: 📓 Documentation

#3948 Use prepublishOnly step instead of prepublish
  package.json
Labels: 🤖Skip Changelog

#3947 Revert "Test async translations [should be reverted]"
  locales/en.json
Labels: 🤖Skip Changelog
