Repository Shopify/polaris, pull requests merged in 2021-12, with the labels that each got.

#4770 Remove unused custom properties
  UNRELEASED-v8.md
  src/utilities/custom-properties/README.md
  src/utilities/custom-properties/custom-properties.ts
  src/utilities/custom-properties/index.ts
  src/utilities/custom-properties/tsconfig.json
Labels: 🤖Skip Changelog

#4774 Rename misc custom properties
  src/components/ActionMenu/components/SecondaryAction/SecondaryAction.scss
  src/components/Avatar/Avatar.scss
  src/components/Breadcrumbs/Breadcrumbs.scss
Labels: 🤖Skip Changelog

#4775 Replace hardcoded spacing values with tokens
  UNRELEASED-v8.md
  src/components/Banner/Banner.scss
  src/components/DropZone/DropZone.scss
  src/components/DropZone/components/FileUpload/FileUpload.scss
  src/components/Filters/Filters.scss
  src/components/IndexTable/IndexTable.scss
  src/components/Navigation/Navigation.scss
  src/components/Navigation/_variables.scss
  src/components/ResourceList/_variables.scss
  src/components/ResourceList/components/FilterControl/FilterControl.scss
  src/components/Select/Select.scss
  src/components/TopBar/components/Menu/Menu.scss
Labels: 🤖Skip Changelog, Get admin on Polaris mainline

#4790 Align easing tokens and values with CSS defaults (Easing Tokens Phase 1)
  UNRELEASED-v8.md
  src/components/README.md
  src/tokens/_motion.ts
Labels: 🤖Skip Changelog, Get admin on Polaris mainline

#4778 Bump node to v16
  .github/workflows/ci.yml
  .github/workflows/size-limit.yml
  .nvmrc
  UNRELEASED-v8.md
  dev.yml
  package.json
  playground/DetailsPage.tsx
  scripts/build-validate.js
  yarn.lock
Labels: 🤖Skip Changelog

#4791 Theme and update storybook
  .storybook/manager.js
Labels: 🤖Skip Changelog

#4795 Loom linter plugin updates
  package.json
  playground/KitchenSink.tsx
  src/components/Banner/Banner.tsx
  src/components/BulkActions/BulkActions.tsx
  src/components/BulkActions/tests/BulkActions.test.tsx
  src/components/Button/Button.tsx
  src/components/Combobox/components/TextField/TextField.tsx
  src/components/DatePicker/components/Month/Month.tsx
  src/components/DropZone/components/FileUpload/FileUpload.tsx
  src/components/Filters/components/ConnectedFilterControl/ConnectedFilterControl.tsx
  src/components/FocusManager/FocusManager.tsx
  src/components/Frame/Frame.tsx
  src/components/IndexTable/IndexTable.tsx
  src/components/IndexTable/components/Checkbox/tests/Checkbox.test.tsx
  src/components/IndexTable/components/ScrollContainer/ScrollContainer.tsx
  src/components/IndexTable/tests/IndexTable.test.tsx
  src/components/IndexTable/utilities/tests/utilities.test.ts
  src/components/Layout/tests/Layout.test.tsx
  src/components/Listbox/Listbox.tsx
  src/components/Listbox/components/Option/Option.tsx
  src/components/Popover/tests/Popover.test.tsx
  src/components/Portal/tests/Portal.test.tsx
  src/components/PortalsManager/PortalsManager.tsx
  src/components/PositionedOverlay/PositionedOverlay.tsx
  src/components/ResourceList/components/FilterControl/components/FilterCreator/FilterCreator.tsx
  src/components/Tooltip/Tooltip.tsx
  src/utilities/combobox/context.tsx
  src/utilities/components.tsx
  src/utilities/duration.ts
  src/utilities/frame/types.ts
  src/utilities/index-table/context.ts
  src/utilities/index-table/tests/hooks-useContainerScroll.test.tsx
  src/utilities/tests/use-index-resource-state.test.tsx
  yarn.lock
Labels: 🤖Skip Changelog

#4784 Set root font size to 100%
  .storybook/preview-body.html
  config/postcss-plugins.js
  src/components/AppProvider/AppProvider.scss
  src/components/DropZone/components/FileUpload/FileUpload.scss
  src/components/IndexTable/IndexTable.scss
  src/components/IndexTable/README.md
  src/components/Layout/Layout.scss
  src/components/Sheet/README.md
  src/components/Subheading/Subheading.scss
  src/tokens/_legacy-tokens.ts
Labels: 🤖Skip Changelog, Get admin on Polaris mainline

#4808 Use rems in tokens
  src/tokens/_shape.ts
  src/tokens/_spacing.ts
  src/tokens/utilities.ts
Labels: 🤖Skip Changelog

#4728 Remove @shopify/polaris-tokens
  .eslintignore
  .gitignore
  .prettierignore
  .stylelintignore
  UNRELEASED-v8.md
  loom.config.ts
  package.json
  src/components/BulkActions/BulkActions.tsx
  src/components/Frame/Frame.tsx
  src/components/IndexTable/IndexTable.tsx
  src/components/Modal/components/Dialog/Dialog.tsx
  src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx
  src/components/Sheet/Sheet.tsx
  src/utilities/sticky-manager/sticky-manager.ts
  yarn.lock
Labels: 🤖Skip Changelog

#4505 [ActionList] add arrow navigation and menu role support
  UNRELEASED.md
  src/components/ActionList/ActionList.scss
  src/components/ActionList/ActionList.tsx
  src/components/ActionList/README.md
  src/components/ActionList/components/Item/Item.tsx
  src/components/ActionList/components/Section/Section.tsx
  src/components/ActionList/tests/ActionList.test.tsx
  src/components/Popover/README.md
  src/utilities/focus.ts
Labels: 🐛Bug

#4823 Replace shadow() function with tokens
  UNRELEASED-v8.md
  src/components/Button/Button.scss
  src/components/Card/Card.scss
  src/components/CustomProperties/README.md
  src/components/CustomProperties/tests/CustomProperties.test.tsx
  src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.scss
  src/components/IndexTable/IndexTable.scss
  src/components/Modal/components/Dialog/Dialog.scss
  src/components/Popover/Popover.scss
  src/components/README.md
  src/components/RangeSlider/components/DualThumb/DualThumb.scss
  src/components/RangeSlider/components/SingleThumb/SingleThumb.scss
  src/components/ResourceList/ResourceList.scss
  src/components/Scrollable/Scrollable.scss
  src/components/Sheet/Sheet.scss
  src/components/Tooltip/components/TooltipOverlay/TooltipOverlay.scss
  src/components/TopBar/TopBar.scss
  src/components/TopBar/components/Search/Search.scss
  src/styles/_common.scss
  src/styles/_public-api.scss
  src/styles/foundation/_shadows.scss
  src/styles/shared/_buttons.scss
  src/tokens/_depth.ts
  src/tokens/_legacy-tokens.ts
  src/tokens/tokens.ts
Labels: 🤖Skip Changelog, Get admin on Polaris mainline

#4818 feat: Extract design tokens to JSON
  .github/workflows/ci.yml
  package.json
  tokens/color.dark.json
  tokens/color.light.json
  tokens/legacy-tokens.json
  tokens/motion.json
  tokens/schemas/token-group.json
  tokens/shape.json
  tokens/spacing.json
  tokens/typography.json
  tokens/z-index.json
  yarn.lock
Labels: 🤖Skip Changelog, Get admin on Polaris mainline

#4822 feat: Update CustomProperties component to use JSON tokens
  loom.config.ts
  package.json
  src/components/IndexTable/README.md
  src/tokens/_color.ts
  src/tokens/_depth.ts
  src/tokens/_legacy-tokens.ts
  src/tokens/_motion.ts
  src/tokens/_shape.ts
  src/tokens/_spacing.ts
  src/tokens/_typography.ts
  src/tokens/_z-index.ts
  src/tokens/schemas/token-group.json
  src/tokens/token-groups/color.dark.json
  src/tokens/token-groups/color.light.json
  src/tokens/token-groups/depth.json
  src/tokens/token-groups/legacy-tokens.json
  src/tokens/token-groups/motion.json
  src/tokens/token-groups/shape.json
  src/tokens/token-groups/spacing.json
  src/tokens/token-groups/typography.json
  src/tokens/token-groups/z-index.json
  src/tokens/tokens.ts
  src/tokens/utilities.ts
  tokens/legacy-tokens.json
  yarn.lock
Labels: 🤖Skip Changelog, Get admin on Polaris mainline

#4828 feat: Update the custom Stylelint plugin to use JSON tokens
  .stylelintrc.js
  loom.config.ts
  src/components/Frame/README.md
  src/token-list.ts
Labels: 🤖Skip Changelog, Get admin on Polaris mainline

#4847 Test (16.10.0)
  shipit.yml
Labels: 🤖Skip Changelog

#4852 Line height tokens
  src/components/ActionList/ActionList.scss
  src/components/Autocomplete/components/MappedAction/MappedAction.scss
  src/components/Badge/Badge.scss
  src/components/Banner/Banner.scss
  src/components/Button/Button.scss
  src/components/CheckableButton/CheckableButton.scss
  src/components/CustomProperties/tests/CustomProperties.test.tsx
  src/components/DropZone/components/FileUpload/FileUpload.scss
  src/components/Page/Page.scss
  src/components/SkeletonDisplayText/SkeletonDisplayText.scss
  src/components/TopBar/components/UserMenu/UserMenu.scss
  src/styles/foundation/_typography.scss
  src/styles/shared/_buttons.scss
  src/styles/shared/_controls.scss
  src/styles/shared/_typography.scss
  src/tokens/token-groups/line-height.json
  src/tokens/tokens.ts
Labels: 🤖Skip Changelog, Get admin on Polaris mainline

#4854 Update documentation
  src/components/README.md
Labels: 📓 Documentation, 🤖Skip Changelog

#4857 Replace `font-size()` with tokens
  src/components/Badge/Badge.scss
  src/components/CheckableButton/CheckableButton.scss
  src/components/CustomProperties/tests/CustomProperties.test.tsx
  src/components/Filters/Filters.scss
  src/components/Navigation/Navigation.scss
  src/styles/foundation/_typography.scss
  src/styles/shared/_typography.scss
  src/tokens/token-groups/font-size.json
  src/tokens/tokens.ts
Labels: 🤖Skip Changelog, Get admin on Polaris mainline

#4859 Fix kitchen sink
  src/components/AppProvider/README.md
Labels: 🤖Skip Changelog

#4860 Remove root level control height
  src/components/Banner/Banner.scss
  src/components/Button/Button.scss
  src/styles/shared/_controls.scss
Labels: 🤖Skip Changelog
