Repository Shopify/polaris, pull requests merged in 2021-11, with the labels that each got.

#4626 [ActionList] Fix base padding when there are multiple sections
  .storybook/polaris-readme-loader.js
  src/components/ActionList/ActionList.scss
  src/components/ActionList/README.md
Labels: 🤖Skip Changelog

#4620 Remove miscellaneous css custom properties
  UNRELEASED.md
  documentation/Color system.md
  src/components/Badge/Badge.scss
  src/components/Banner/Banner.scss
  src/components/Breadcrumbs/Breadcrumbs.scss
  src/components/Breadcrumbs/Breadcrumbs.tsx
  src/components/Choice/Choice.scss
  src/components/Filters/components/ConnectedFilterControl/ConnectedFilterControl.scss
  src/components/FooterHelp/FooterHelp.scss
  src/components/Frame/Frame.scss
  src/components/Frame/components/Toast/Toast.scss
  src/components/Link/Link.scss
  src/components/Modal/components/CloseButton/CloseButton.scss
  src/components/Navigation/Navigation.scss
  src/components/README.md
  src/components/RangeSlider/components/DualThumb/DualThumb.scss
  src/components/RangeSlider/components/SingleThumb/SingleThumb.scss
  src/components/Select/Select.scss
  src/components/ThemeProvider/tests/ThemeProvider.test.tsx
  src/components/TopBar/TopBar.scss
  src/components/TopBar/components/Menu/Menu.scss
  src/utilities/theme/tokens.ts
Labels: Get admin on Polaris mainline

#4648 Remove custom and unnecessary font weight properties
  UNRELEASED.md
  documentation/Color system.md
  src/components/Badge/Badge.scss
  src/components/README.md
  src/components/TextField/TextField.scss
  src/styles/shared/_typography.scss
  src/utilities/theme/tokens.ts
Labels: Get admin on Polaris mainline

#4664 [Navigation] Fix icon filter colors
  src/components/Navigation/Navigation.scss
  src/components/Navigation/README.md
  src/components/Navigation/_variables.scss
Labels: 🤖Skip Changelog

#4665 [DropZone] Adjusting FileUpload padding
  src/components/DropZone/components/FileUpload/FileUpload.scss
  src/components/DropZone/components/FileUpload/FileUpload.tsx
  src/components/DropZone/components/FileUpload/tests/FileUpload.test.tsx
Labels: 🤖Skip Changelog

#4679 Revert removal of misc tokens
  documentation/Color system.md
  src/utilities/theme/tokens.ts
Labels: 🤖Skip Changelog

#4668 Replace font weight values with tokens
  UNRELEASED.md
  documentation/Color system.md
  playground/DetailsPage.scss
  src/components/AppProvider/AppProvider.scss
  src/components/Badge/Badge.scss
  src/components/Button/Button.scss
  src/components/CheckableButton/CheckableButton.scss
  src/components/DatePicker/DatePicker.scss
  src/components/ExceptionList/ExceptionList.scss
  src/components/IndexTable/IndexTable.scss
  src/components/KeyboardKey/KeyboardKey.scss
  src/components/Navigation/Navigation.scss
  src/components/Navigation/_variables.scss
  src/components/README.md
  src/components/TopBar/components/UserMenu/UserMenu.scss
  src/styles/shared/_typography.scss
  src/utilities/theme/tokens.ts
Labels: Get admin on Polaris mainline

#4080 [Page] Improve the accessibility of the rollup actions
  UNRELEASED.md
  locales/cs.json
  locales/da.json
  locales/de.json
  locales/en.json
  locales/es.json
  locales/fi.json
  locales/fr.json
  locales/it.json
  locales/ja.json
  locales/ko.json
  locales/nb.json
  locales/nl.json
  locales/pl.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/sv.json
  locales/th.json
  locales/tr.json
  locales/vi.json
  locales/zh-CN.json
  locales/zh-TW.json
  src/components/ActionMenu/ActionMenu.tsx
  src/components/ActionMenu/components/Actions/Actions.tsx
  src/components/ActionMenu/components/RollupActions/RollupActions.tsx
  src/components/ActionMenu/components/RollupActions/tests/RollupActions.test.tsx
  src/components/Page/components/Header/Header.tsx
Labels: Accessibility, Feature request

#4686 Remove misc tokens
  UNRELEASED.md
  documentation/Color system.md
  src/utilities/theme/tokens.ts
Labels: Get admin on Polaris mainline

#4462 Remove skeleton motion
  UNRELEASED.md
  src/components/AppProvider/AppProvider.scss
  src/components/SkeletonBodyText/SkeletonBodyText.scss
  src/components/SkeletonDisplayText/SkeletonDisplayText.scss
  src/components/SkeletonPage/SkeletonPage.scss
  src/components/SkeletonThumbnail/SkeletonThumbnail.scss
  src/styles/shared/_skeleton.scss
Labels: 🤖Skip Changelog, cla-needed

#4655 Remove remaining color sass function uses
  src/components/Button/Button.scss
  src/components/Navigation/_variables.scss
  src/styles/shared/_buttons.scss
Labels: 🤖Skip Changelog

#4631 [Checkbox] properly support screen readers
  UNRELEASED.md
  src/components/CheckableButton/tests/CheckableButton.test.tsx
  src/components/Checkbox/Checkbox.tsx
  src/components/Checkbox/tests/Checkbox.test.tsx
  src/components/ChoiceList/tests/ChoiceList.test.tsx
  src/components/IndexTable/components/Checkbox/Checkbox.tsx
  src/components/IndexTable/components/Checkbox/tests/Checkbox.test.tsx
  src/components/IndexTable/components/Row/Row.tsx
Labels: 🐛Bug

#4711 Remove addon-knobs package
  .storybook/main.js
  package.json
  yarn.lock
Labels: 🤖Skip Changelog

#4642 feat: Simplify ThemeProvider
  .storybook/polaris-readme-loader.js
  .storybook/preview.js
  UNRELEASED-v8.md
  src/components/AppProvider/AppProvider.tsx
  src/components/AppProvider/README.md
  src/components/CustomProperties/CustomProperties.tsx
  src/components/CustomProperties/README.md
  src/components/CustomProperties/index.ts
  src/components/CustomProperties/styles.ts
  src/components/CustomProperties/tests/CustomProperties.test.tsx
  src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.tsx
  src/components/Frame/components/ContextualSaveBar/tests/ContextualSaveBar.test.tsx
  src/components/Frame/components/Toast/Toast.tsx
  src/components/Navigation/Navigation.tsx
  src/components/Navigation/tests/Navigation.test.tsx
  src/components/Pagination/tests/Pagination.test.tsx
  src/components/PolarisTestProvider/PolarisTestProvider.tsx
  src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx
  src/components/ThemeProvider/README.md
  src/components/ThemeProvider/ThemeProvider.tsx
  src/components/ThemeProvider/index.ts
  src/components/ThemeProvider/tests/ThemeProvider.test.tsx
  src/components/TopBar/TopBar.tsx
  src/components/TopBar/components/Search/Search.tsx
  src/components/TopBar/tests/TopBar.test.tsx
  src/components/index.ts
  src/designTokens/colorSchemes.ts
  src/designTokens/designTokens.ts
  src/designTokens/index.ts
  src/designTokens/legacyTokens.ts
  src/designTokens/motion.ts
  src/designTokens/typography.ts
  src/utilities/theme/context.tsx
  src/utilities/theme/hooks.tsx
  src/utilities/theme/index.ts
  src/utilities/theme/tests/hooks.test.tsx
  src/utilities/theme/tests/utils.test.ts
  src/utilities/theme/types.ts
  src/utilities/theme/utils.ts
Labels: 🤖Skip Changelog, Get admin on Polaris mainline

#4715 Remove color-multiply scss function
  UNRELEASED-v8.md
  src/styles/foundation/_colors.scss
Labels: 🤖Skip Changelog

#4716 Remove src/utilities/theme/* and color system docs
  documentation/Color system.md
  package.json
  pre-commit
  scripts/color-system-docs.js
  src/index.ts
  src/utilities/custom-properties/custom-properties.ts
  src/utilities/theme/index.ts
  src/utilities/theme/tokens.ts
  src/utilities/theme/utils.ts
Labels: 🤖Skip Changelog

#4699 Replace duration() function with tokens
  UNRELEASED-v8.md
  src/components/Backdrop/Backdrop.scss
  src/components/Banner/Banner.scss
  src/components/BulkActions/BulkActions.scss
  src/components/DataTable/DataTable.scss
  src/components/Frame/Frame.scss
  src/components/Frame/components/CSSAnimation/CSSAnimation.scss
  src/components/Frame/components/Loading/Loading.scss
  src/components/Frame/components/ToastManager/ToastManager.scss
  src/components/IndexTable/IndexTable.scss
  src/components/Modal/components/Dialog/Dialog.scss
  src/components/ProgressBar/ProgressBar.scss
  src/components/README.md
  src/components/RangeSlider/components/SingleThumb/SingleThumb.scss
  src/components/ResourceItem/ResourceItem.scss
  src/components/ResourceList/ResourceList.scss
  src/components/Sheet/Sheet.scss
  src/components/Spinner/Spinner.scss
  src/components/Tooltip/components/TooltipOverlay/TooltipOverlay.scss
  src/components/TopBar/TopBar.scss
  src/components/TopBar/components/SearchField/SearchField.scss
  src/components/TopBar/components/UserMenu/UserMenu.scss
  src/components/VideoThumbnail/VideoThumbnail.scss
  src/styles/_common.scss
  src/styles/_public-api.scss
  src/styles/foundation/_duration.scss
  src/tokens/_motion.ts
Labels: 🤖Skip Changelog, Get admin on Polaris mainline

#4698 Replace easing() function with tokens
  UNRELEASED-v8.md
  src/components/Banner/Banner.scss
  src/components/BulkActions/BulkActions.scss
  src/components/Collapsible/Collapsible.scss
  src/components/DataTable/DataTable.scss
  src/components/Frame/Frame.scss
  src/components/Frame/components/CSSAnimation/CSSAnimation.scss
  src/components/IndexTable/IndexTable.scss
  src/components/Modal/components/Dialog/Dialog.scss
  src/components/Popover/Popover.scss
  src/components/ProgressBar/ProgressBar.scss
  src/components/README.md
  src/components/RangeSlider/components/SingleThumb/SingleThumb.scss
  src/components/ResourceItem/ResourceItem.scss
  src/components/ResourceList/ResourceList.scss
  src/components/Tooltip/components/TooltipOverlay/TooltipOverlay.scss
  src/components/TopBar/TopBar.scss
  src/components/TopBar/components/SearchField/SearchField.scss
  src/components/TopBar/components/UserMenu/UserMenu.scss
  src/components/VideoThumbnail/VideoThumbnail.scss
  src/styles/_common.scss
  src/styles/_public-api.scss
  src/styles/foundation/_easing.scss
  src/styles/shared/_controls.scss
  src/tokens/_motion.ts
Labels: 🤖Skip Changelog, Get admin on Polaris mainline

#4730 [Navigation] Move alt tag to img instead of UnstyledLink
  src/components/Navigation/Navigation.tsx
Labels: 🤖Skip Changelog

#4692 docs: Update migration guide with ThemeProvider changes
  documentation/guides/migrating-from-v7-to-v8.md
Labels: 🤖Skip Changelog, Get admin on Polaris mainline

#4731 feat: Remove prefers-color-scheme dark
  src/components/CustomProperties/styles.ts
Labels: 🤖Skip Changelog, Get admin on Polaris mainline

#4727 [Frame] Re-add offset
  UNRELEASED-v8.md
  src/components/Frame/Frame.tsx
  src/components/Frame/README.md
  src/components/Frame/tests/Frame.test.tsx
  src/components/IndexTable/components/Checkbox/Checkbox.tsx
  src/components/IndexTable/components/Checkbox/tests/Checkbox.test.tsx
  src/utilities/set-root-property.ts
  src/utilities/tests/set-root-property.test.ts
Labels: 🤖Skip Changelog

#4734 Only show console warnings in development
  src/components/Badge/Badge.tsx
  src/components/BulkActions/BulkActions.tsx
  src/components/Icon/Icon.tsx
  src/components/Icon/tests/Icon.test.tsx
  src/components/ResourceList/components/FilterControl/FilterControl.tsx
Labels: 🤖Skip Changelog

#4744 Update index.ts to include CustomProperties
  src/index.ts
Labels: 🤖Skip Changelog

#4742 [SkeletonPage] Remove secondaryAction
  UNRELEASED-v8.md
  src/components/SkeletonPage/SkeletonPage.tsx
  src/components/SkeletonPage/tests/SkeletonPage.test.tsx
Labels: 🤖Skip Changelog

#4751 Remove `px()` function from public sass
  UNRELEASED-v8.md
  src/styles/foundation/_utilities.scss
Labels: 🤖Skip Changelog, Get admin on Polaris mainline

#4753 Move z-indexes to tokens
  UNRELEASED-v8.md
  src/components/Backdrop/Backdrop.scss
  src/components/Button/Button.scss
  src/components/ButtonGroup/ButtonGroup.scss
  src/components/ColorPicker/ColorPicker.scss
  src/components/Connected/Connected.scss
  src/components/CustomProperties/tests/CustomProperties.test.tsx
  src/components/DropZone/DropZone.scss
  src/components/Filters/Filters.scss
  src/components/Filters/components/ConnectedFilterControl/ConnectedFilterControl.scss
  src/components/Frame/Frame.scss
  src/components/Frame/components/ToastManager/ToastManager.scss
  src/components/IndexTable/IndexTable.scss
  src/components/MediaCard/MediaCard.scss
  src/components/Modal/components/Dialog/Dialog.scss
  src/components/PositionedOverlay/PositionedOverlay.scss
  src/components/RangeSlider/components/DualThumb/DualThumb.scss
  src/components/RangeSlider/components/SingleThumb/SingleThumb.scss
  src/components/Select/Select.scss
  src/components/Sheet/Sheet.scss
  src/components/TextField/TextField.scss
  src/components/TopBar/TopBar.scss
  src/components/TopBar/components/Search/Search.scss
  src/components/TopBar/components/SearchDismissOverlay/SearchDismissOverlay.scss
  src/components/TopBar/components/SearchField/SearchField.scss
  src/styles/_common.scss
  src/styles/foundation/_z-index.scss
  src/tokens/_z-index.ts
  src/tokens/tokens.ts
Labels: 🤖Skip Changelog

#4769 Regex rem() removal
  src/components/Button/Button.scss
  src/components/CheckableButton/CheckableButton.scss
  src/components/DropZone/components/FileUpload/FileUpload.scss
  src/components/IndexTable/components/Checkbox/Checkbox.scss
  src/components/Indicator/Indicator.scss
  src/components/KeyboardKey/KeyboardKey.scss
  src/components/Layout/Layout.scss
  src/components/Link/Link.scss
  src/components/Listbox/components/Loading/Loading.scss
  src/components/MessageIndicator/MessageIndicator.scss
  src/components/Modal/Modal.scss
  src/components/Modal/components/Dialog/Dialog.scss
  src/components/Navigation/Navigation.scss
  src/components/Navigation/_variables.scss
  src/components/OptionList/components/Option/Option.scss
  src/components/Page/Page.scss
  src/components/Page/components/Header/Header.scss
  src/components/Page/components/Header/components/Title/Title.scss
  src/components/Popover/Popover.scss
  src/components/ProgressBar/ProgressBar.scss
  src/components/RadioButton/RadioButton.scss
  src/components/RangeSlider/RangeSlider.scss
  src/components/RangeSlider/components/DualThumb/DualThumb.scss
  src/components/RangeSlider/components/SingleThumb/SingleThumb.scss
  src/components/ResourceItem/ResourceItem.scss
  src/components/ResourceList/ResourceList.scss
  src/components/ResourceList/_variables.scss
  src/components/Scrollable/Scrollable.scss
  src/components/Select/Select.scss
  src/components/SettingAction/SettingAction.scss
  src/components/Sheet/Sheet.scss
  src/components/SkeletonBodyText/SkeletonBodyText.scss
  src/components/SkeletonDisplayText/SkeletonDisplayText.scss
  src/components/SkeletonPage/SkeletonPage.scss
  src/components/Spinner/Spinner.scss
  src/components/Tabs/Tabs.scss
  src/components/Tag/Tag.scss
  src/components/TextField/TextField.scss
  src/components/Tooltip/components/TooltipOverlay/TooltipOverlay.scss
  src/components/TopBar/TopBar.scss
  src/components/TopBar/_variables.scss
  src/components/TopBar/components/Menu/Menu.scss
  src/components/TopBar/components/Menu/components/Message/Message.scss
  src/components/TopBar/components/SearchField/SearchField.scss
  src/components/TopBar/components/UserMenu/UserMenu.scss
  src/components/VideoThumbnail/VideoThumbnail.scss
  src/styles/foundation/_border-width.scss
  src/styles/foundation/_focus-ring.scss
  src/styles/foundation/_layout.scss
  src/styles/foundation/_typography.scss
  src/styles/shared/_buttons.scss
  src/styles/shared/_controls.scss
  src/styles/shared/_icons.scss
  src/styles/shared/_interaction-state.scss
  src/styles/shared/_skeleton.scss
Labels: 🤖Skip Changelog
