Repository Shopify/polaris, pull requests merged in 2021-02, with the labels that each got.

#3952 Add prop docs to generated storybook docs pages
  .storybook/polaris-readme-loader.js
  scripts/accessibility-check.js
Labels: 🤖Skip Changelog

#3955 [EmptyState] Update readme layouts
  src/components/EmptyState/README.md
Labels: 🤖Skip Changelog

#3957 Update translations: default
  locales/da.json
  locales/es.json
  locales/fi.json
  locales/fr.json
  locales/it.json
  locales/ja.json
  locales/ko.json
  locales/nl.json
  locales/pl.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/sv.json
  locales/th.json
  locales/vi.json
  locales/zh-CN.json
  locales/zh-TW.json
Labels: cla-needed

#3971 [a11y][ActionList]: make items clearly discernible in high contrast mode
  UNRELEASED.md
  src/components/ActionList/ActionList.scss
  src/components/ActionList/README.md
Labels: Accessibility

#3977 Update yarn.lock
  yarn.lock
Labels: 🤖Skip Changelog

#3975 [ResourceItem] Add dataHref prop
  src/components/ResourceItem/ResourceItem.tsx
  src/components/ResourceItem/tests/ResourceItem.test.tsx
Labels: 🤖Skip Changelog

#3646 [IndexProvider/Table] Migrate from web - take 2
  .storybook/polaris-readme-loader.js
  locales/cs.json
  locales/da.json
  locales/de.json
  locales/en.json
  locales/es.json
  locales/fi.json
  locales/fr.json
  locales/it.json
  locales/ja.json
  locales/ko.json
  locales/nb.json
  locales/nl.json
  locales/pl.json
  locales/pt-BR.json
  locales/pt-PT.json
  locales/sv.json
  locales/th.json
  locales/tr.json
  locales/vi.json
  locales/zh-CN.json
  locales/zh-TW.json
  src/components/IndexProvider/IndexProvider.tsx
  src/components/IndexProvider/index.ts
  src/components/IndexProvider/tests/IndexProvider.test.tsx
  src/components/IndexTable/IndexTable.scss
  src/components/IndexTable/IndexTable.tsx
  src/components/IndexTable/README.md
  src/components/IndexTable/components/Cell/Cell.tsx
  src/components/IndexTable/components/Cell/index.ts
  src/components/IndexTable/components/Cell/tests/Cell.test.tsx
  src/components/IndexTable/components/Checkbox/Checkbox.scss
  src/components/IndexTable/components/Checkbox/Checkbox.tsx
  src/components/IndexTable/components/Checkbox/index.ts
  src/components/IndexTable/components/Checkbox/tests/Checkbox.test.tsx
  src/components/IndexTable/components/Row/Row.tsx
  src/components/IndexTable/components/Row/index.ts
  src/components/IndexTable/components/Row/tests/Row.test.tsx
  src/components/IndexTable/components/ScrollContainer/ScrollContainer.scss
  src/components/IndexTable/components/ScrollContainer/ScrollContainer.tsx
  src/components/IndexTable/components/ScrollContainer/index.ts
  src/components/IndexTable/components/index.ts
  src/components/IndexTable/index.ts
  src/components/IndexTable/tests/IndexTable.test.tsx
  src/components/index.ts
  src/index.ts
  src/types.ts
  src/utilities/custom-properties/custom-properties.ts
  src/utilities/index-provider/context.ts
  src/utilities/index-provider/hooks.ts
  src/utilities/index-provider/index.ts
  src/utilities/index-provider/tests/hooks.test.tsx
  src/utilities/index-provider/types.ts
  src/utilities/index-table/context.ts
  src/utilities/index-table/hooks.ts
  src/utilities/index-table/index.ts
  src/utilities/index-table/tests/hooks.test.tsx
  src/utilities/tests/use-index-resource-state.test.tsx
  src/utilities/use-index-resource-state.ts
  tests/setup.ts
Labels: 🤖Skip Changelog

#3912 Remove #AppFrameMainContent link and update SkipToContent link to target #AppFrameMain instead
  UNRELEASED.md
  src/components/Frame/Frame.tsx
  src/components/Frame/tests/Frame.test.tsx
Labels: Accessibility

#4003 [DisplayText] Content guidelines: use present tense consistently
  src/components/DisplayText/README.md
Labels: 🤖Skip Changelog

#4010 Update translations: default
  locales/pt-BR.json
Labels: cla-needed

#3962 [a11y]: Remove outline & border uses of ms-high-contrast
  UNRELEASED.md
  src/components/ActionList/ActionList.scss
  src/components/Avatar/Avatar.scss
  src/components/Banner/Banner.scss
  src/components/CheckableButton/CheckableButton.scss
  src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.scss
  src/components/Frame/components/Toast/Toast.scss
  src/components/Modal/components/Dialog/Dialog.scss
  src/components/Navigation/Navigation.scss
  src/components/ProgressBar/ProgressBar.scss
  src/components/RadioButton/RadioButton.scss
  src/components/RangeSlider/components/DualThumb/DualThumb.scss
  src/components/RangeSlider/components/SingleThumb/SingleThumb.scss
  src/components/Tag/Tag.scss
  src/styles/foundation/_accessibility.scss
  src/styles/shared/_forms.scss
Labels: Accessibility

#4018 [ComboBox] Use isomorphic layout effect
  src/components/Autocomplete/components/ComboBox/ComboBox.tsx
Labels: 🤖Skip Changelog
