Repository Shopify/polaris, pull requests merged in 2022-11, with the labels that each got.

#7604 [Layout foundations] Fix `Inline` component doc
  .changeset/curvy-dryers-hunt.md
  polaris.shopify.com/pages/examples/inline-with-vertical-alignment.tsx
Labels: #gsd:30116

#7589 Add constraints to `stylelint-polaris/coverage` disable comments
  .changeset/tidy-cougars-talk.md
  stylelint-polaris/plugins/coverage/index.js
  stylelint-polaris/plugins/coverage/index.test.js
Labels: #gsd:31276

#7621 [Box] Add border width support
  .changeset/gorgeous-dryers-wash.md
  polaris-react/src/components/Box/Box.scss
  polaris-react/src/components/Box/Box.stories.tsx
  polaris-react/src/components/Box/Box.tsx
  polaris-react/src/components/Box/tests/Box.test.tsx
  polaris-tokens/src/index.ts
  polaris-tokens/src/token-groups/colors.ts
  polaris-tokens/src/token-groups/shape.ts
  polaris.shopify.com/src/data/props.json
Labels: #gsd:30116

#7637 Remove Polaris for Figma plugin from monorepo
  .eslintrc.js
  README.md
  documentation/Releasing.md
  jest.config.js
  package.json
  polaris-for-figma/CHANGELOG.md
  polaris-for-figma/README.md
  polaris-for-figma/manifest.json
  polaris-for-figma/package.json
  polaris-for-figma/src/index.html
  polaris-for-figma/src/plugin.ts
  polaris-for-figma/src/styles.css
  polaris-for-figma/src/tokens/apiTokenColors.json
  polaris-for-figma/src/tokens/colorStyles.json
  polaris-for-figma/src/tokens/tokenScript.js
  polaris-for-figma/src/types.ts
  polaris-for-figma/src/ui.tsx
  polaris-for-figma/src/utils.ts
  polaris-for-figma/tsconfig.json
  polaris-for-figma/webpack.config.js
  polaris.shopify.com/content/contributing/shipping-your-contribution.md
  polaris.shopify.com/content/getting-started/index.md
  tsconfig.eslint.json
  yarn.lock
Labels: 🤖Skip Changelog

#7617 [stylelint-polaris] Categorize coverage rules
  .changeset/purple-knives-enjoy.md
  patches/stylelint+14.8.0.patch
  stylelint-polaris/configs/coverage.js
  stylelint-polaris/plugins/coverage/index.js
  stylelint-polaris/plugins/coverage/index.test.js
  stylelint-polaris/utils/index.js
Labels: #gsd:31276

#7712 Fix lb abbreviation
  .changeset/sixty-dancers-exercise.md
  polaris.shopify.com/content/content/grammar-and-mechanics.md
Labels: Contribution

#7700 Consolidate `stylelint-polaris` configs
  .stylelintrc.js
  polaris-react/src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.scss
  stylelint-polaris/configs/coverage.js
  stylelint-polaris/configs/internal.js
  stylelint-polaris/configs/shared.js
  stylelint-polaris/index.js
Labels: #gsd:31276

#7719 Remove Stylelint patches and upgrade version to `^14.15.0`
  package.json
  patches/stylelint+14.8.0.patch
  stylelint-polaris/package.json
  yarn.lock
Labels: #gsd:31276

#7710 [ActionList/Modal.Header] Fix spacing regressions
  .changeset/twenty-socks-count.md
  polaris-react/src/components/ActionList/ActionList.scss
  polaris-react/src/components/ActionList/ActionList.stories.tsx
  polaris-react/src/components/Modal/components/Header/Header.scss
Labels: #gsd:29805

#7697 [Box] Add support for responsive padding
  .changeset/small-gifts-hope.md
  polaris-react/src/components/Box/Box.scss
  polaris-react/src/components/Box/Box.stories.tsx
  polaris-react/src/components/Box/Box.tsx
  polaris-react/src/components/Box/tests/Box.test.tsx
  polaris-react/src/styles/_common.scss
  polaris-react/src/styles/shared/_responsive-props.scss
  polaris-react/src/utilities/css.ts
Labels: #gsd:30116

#7744 Fix TextStyle migration to use `fontWeight="semibold"` instead of `fontWeight="bold"`
  .changeset/tiny-ravens-sing.md
  polaris-migrator/src/migrations/react-replace-text-components/steps/replace-text-style.ts
  polaris-migrator/src/migrations/react-replace-text-components/tests/react-replace-text-components.output.tsx
  polaris-migrator/src/migrations/react-replace-text-components/tests/with-relative.output.tsx
  polaris.shopify.com/content/components/text-style.md
Labels: #gsd:29805

#7746 [Layout foundations] Remove `ContentBlock`
  .changeset/kind-boats-trade.md
  polaris-react/src/components/ContentBlock/ContentBlock.scss
  polaris-react/src/components/ContentBlock/ContentBlock.stories.tsx
  polaris-react/src/components/ContentBlock/ContentBlock.tsx
  polaris-react/src/components/ContentBlock/index.ts
  polaris-react/src/components/ContentBlock/tests/ContentBlock.test.tsx
  polaris-react/src/index.ts
  polaris.shopify.com/content/components/content-block.md
  polaris.shopify.com/pages/examples/content-block-width.tsx
  polaris.shopify.com/src/data/props.json
Labels: #gsd:30116

#7745 [polaris.shopify.com] Update alpha banner message
  .changeset/fresh-games-arrive.md
  polaris.shopify.com/content/components/alpha-card.md
  polaris.shopify.com/content/components/alpha-stack.md
  polaris.shopify.com/content/components/bleed.md
  polaris.shopify.com/content/components/box.md
  polaris.shopify.com/content/components/columns.md
  polaris.shopify.com/content/components/inline.md
  polaris.shopify.com/content/components/tiles.md
Labels: #gsd:30116

#7748 [Layout foundations] Rename `spacing` prop to `gap`
  .changeset/thin-bobcats-kneel.md
  polaris-react/src/components/AlphaCard/AlphaCard.stories.tsx
  polaris-react/src/components/AlphaStack/AlphaStack.scss
  polaris-react/src/components/AlphaStack/AlphaStack.stories.tsx
  polaris-react/src/components/AlphaStack/AlphaStack.tsx
  polaris-react/src/components/AlphaStack/tests/AlphaStack.test.tsx
  polaris-react/src/components/Columns/Columns.scss
  polaris-react/src/components/Columns/Columns.stories.tsx
  polaris-react/src/components/Columns/Columns.tsx
  polaris-react/src/components/Columns/tests/Columns.test.tsx
  polaris-react/src/components/Inline/Inline.scss
  polaris-react/src/components/Inline/Inline.stories.tsx
  polaris-react/src/components/Inline/Inline.tsx
  polaris-react/src/components/Tiles/Tiles.stories.tsx
  polaris.shopify.com/content/components/alpha-stack.md
  polaris.shopify.com/content/components/columns.md
  polaris.shopify.com/content/components/inline.md
  polaris.shopify.com/content/components/tiles.md
  polaris.shopify.com/pages/examples/alpha-card-with-varying-padding.tsx
  polaris.shopify.com/pages/examples/alpha-stack-with-align.tsx
  polaris.shopify.com/pages/examples/alpha-stack-with-gap.tsx
  polaris.shopify.com/pages/examples/bleed-specific-direction.tsx
  polaris.shopify.com/pages/examples/box-with-padding.tsx
  polaris.shopify.com/pages/examples/columns-with-set-number.tsx
  polaris.shopify.com/pages/examples/columns-with-varying-gap.tsx
  polaris.shopify.com/pages/examples/inline-with-gap.tsx
  polaris.shopify.com/pages/examples/inline-with-horizontal-alignment.tsx
  polaris.shopify.com/pages/examples/inline-with-vertical-alignment.tsx
  polaris.shopify.com/pages/examples/tiles-with-gap.tsx
  polaris.shopify.com/src/data/props.json
Labels: #gsd:30116

#7755 [Box] Add position and visibility properties
  .changeset/gorgeous-ants-hammer.md
  polaris-react/src/components/Box/Box.scss
  polaris-react/src/components/Box/Box.tsx
  polaris.shopify.com/src/data/props.json
Labels: #gsd:30116

#7754 [Layout] Add responsive `gap` support to `Inline`
  .changeset/ten-peaches-exist.md
  polaris-react/src/components/Inline/Inline.scss
  polaris-react/src/components/Inline/Inline.stories.tsx
  polaris-react/src/components/Inline/Inline.tsx
  polaris.shopify.com/src/data/props.json
Labels: #gsd:30116

#7768 [Layout foundations] Clean up storybook example names
  .changeset/calm-jobs-divide.md
  polaris-react/src/components/AlphaCard/AlphaCard.stories.tsx
  polaris-react/src/components/AlphaStack/AlphaStack.stories.tsx
  polaris-react/src/components/Box/Box.stories.tsx
  polaris-react/src/components/Inline/Inline.stories.tsx
  polaris-react/src/components/Tiles/Tiles.stories.tsx
Labels: #gsd:30116

#7775 [Layout foundations] Remove `Tiles`
  .changeset/kind-dogs-give.md
  polaris-react/src/components/Tiles/Tiles.scss
  polaris-react/src/components/Tiles/Tiles.stories.tsx
  polaris-react/src/components/Tiles/Tiles.tsx
  polaris-react/src/components/Tiles/index.ts
  polaris-react/src/components/Tiles/tests/Tiles.test.tsx
  polaris-react/src/index.ts
  polaris.shopify.com/content/components/tiles.md
  polaris.shopify.com/pages/examples/tiles-with-columns.tsx
  polaris.shopify.com/pages/examples/tiles-with-gap.tsx
  polaris.shopify.com/src/data/props.json
Labels: #gsd:30116

#7767 [Layout] Add suport for passing in aria attributes
  .changeset/slow-rocks-press.md
  polaris-react/src/components/AlphaStack/AlphaStack.tsx
  polaris-react/src/components/Box/Box.tsx
  polaris-react/src/components/Box/tests/Box.test.tsx
  polaris.shopify.com/src/data/props.json
Labels: #gsd:30116

#7779 [Bleed] Refactor props to use logical property names
  .changeset/two-fishes-join.md
  polaris-react/src/components/Bleed/Bleed.scss
  polaris-react/src/components/Bleed/Bleed.stories.tsx
  polaris-react/src/components/Bleed/Bleed.tsx
  polaris-react/src/components/Bleed/tests/Bleed.test.tsx
  polaris.shopify.com/pages/examples/bleed-all-directions.tsx
  polaris.shopify.com/pages/examples/bleed-horizontal.tsx
  polaris.shopify.com/pages/examples/bleed-specific-direction.tsx
  polaris.shopify.com/pages/examples/bleed-vertical.tsx
  polaris.shopify.com/src/data/props.json
Labels: #gsd:30116

#7788 [AlphaCard] Add subdued section storybook example
  .changeset/lazy-jokes-invent.md
  polaris-react/src/components/AlphaCard/AlphaCard.stories.tsx
Labels: #gsd:30116

#7790 [AlphaCard] Add support for responsive padding with defaults
  .changeset/purple-jeans-pretend.md
  polaris-react/src/components/AlphaCard/AlphaCard.stories.tsx
  polaris-react/src/components/AlphaCard/AlphaCard.tsx
  polaris.shopify.com/src/data/props.json
Labels: #gsd:30116

#7794 Updated `Bleed` to accept responsive spacing
  .changeset/moody-dolls-kneel.md
  polaris-react/src/components/Bleed/Bleed.scss
  polaris-react/src/components/Bleed/Bleed.stories.tsx
  polaris-react/src/components/Bleed/Bleed.tsx
  polaris-react/src/components/Bleed/tests/Bleed.test.tsx
  polaris.shopify.com/src/data/props.json
Labels: #gsd:30116

#7799 [Layout Foundation][Box] Add support for passing in role attribute
  .changeset/hip-grapes-build.md
  polaris-react/src/components/Box/Box.tsx
  polaris.shopify.com/src/data/props.json
Labels: #gsd:30116

#7699 [stylelint-polaris] Categorize disallowed units
  stylelint-polaris/index.js
Labels: #gsd:31276

#7806 [Layout] Update `Box` to support `li` and `tabIndex`
  .changeset/two-readers-arrive.md
  polaris-react/src/components/Box/Box.scss
  polaris-react/src/components/Box/Box.tsx
  polaris.shopify.com/src/data/props.json
Labels: #gsd:30116

#7811 Revert "[BulkActions] Update BulkActions and add in SelectAllActions"
  .changeset/odd-spoons-dance.md
  package.json
  polaris-react/locales/cs.json
  polaris-react/locales/da.json
  polaris-react/locales/de.json
  polaris-react/locales/en.json
  polaris-react/locales/es.json
  polaris-react/locales/fi.json
  polaris-react/locales/fr.json
  polaris-react/locales/it.json
  polaris-react/locales/ja.json
  polaris-react/locales/ko.json
  polaris-react/locales/nb.json
  polaris-react/locales/nl.json
  polaris-react/locales/pl.json
  polaris-react/locales/pt-BR.json
  polaris-react/locales/pt-PT.json
  polaris-react/locales/sv.json
  polaris-react/locales/tr.json
  polaris-react/locales/vi.json
  polaris-react/locales/zh-CN.json
  polaris-react/locales/zh-TW.json
  polaris-react/src/components/BulkActions/BulkActions.scss
  polaris-react/src/components/BulkActions/BulkActions.tsx
  polaris-react/src/components/BulkActions/hooks/index.ts
  polaris-react/src/components/BulkActions/hooks/tests/use-is-bulk-actions-sticky.test.tsx
  polaris-react/src/components/BulkActions/hooks/use-is-bulk-actions-sticky.ts
  polaris-react/src/components/BulkActions/index.ts
  polaris-react/src/components/BulkActions/tests/BulkActions.test.tsx
  polaris-react/src/components/CheckableButton/CheckableButton.scss
  polaris-react/src/components/CheckableButton/CheckableButton.tsx
  polaris-react/src/components/IndexTable/IndexTable.scss
  polaris-react/src/components/IndexTable/IndexTable.stories.tsx
  polaris-react/src/components/IndexTable/IndexTable.tsx
  polaris-react/src/components/IndexTable/tests/IndexTable.test.tsx
  polaris-react/src/components/ResourceList/ResourceList.scss
  polaris-react/src/components/ResourceList/ResourceList.stories.tsx
  polaris-react/src/components/ResourceList/ResourceList.tsx
  polaris-react/src/components/ResourceList/tests/ResourceList.test.tsx
  polaris-react/src/components/SelectAllActions/SelectAllActions.scss
  polaris-react/src/components/SelectAllActions/SelectAllActions.tsx
  polaris-react/src/components/SelectAllActions/index.ts
  polaris-react/src/components/SelectAllActions/tests/SelectAllActions.test.tsx
  polaris-react/src/index.ts
  polaris-react/src/utilities/resource-list/context.ts
  polaris-react/src/utilities/resource-list/index.ts
  polaris-react/src/utilities/resource-list/types.ts
Labels: 🤖Skip Changelog

#7819 Revert "Properly handle buttons with `aria-disabled` in focus helpers"
  .changeset/gentle-cobras-punch.md
  polaris-react/src/utilities/focus.ts
Labels: 🤖Skip Changelog
