Repository Shopify/polaris, pull requests merged in 2022-02, with the labels that each got.

#4989 Replace `@mixin state()` with value
  UNRELEASED-v9.md
  src/components/VideoThumbnail/VideoThumbnail.scss
  src/styles/shared/_interaction-state.scss
Labels: 🤖Skip Changelog, Get admin on Polaris mainline

#4990 feat: Replace `icon-size()` with tokens
  UNRELEASED-v9.md
  src/components/Banner/Banner.scss
  src/components/Button/Button.scss
  src/components/CalloutCard/CalloutCard.scss
  src/components/README.md
  src/components/RadioButton/RadioButton.scss
  src/styles/shared/_icons.scss
  src/tokens/token-groups/legacy-tokens.json
Labels: 🤖Skip Changelog, Get admin on Polaris mainline

#4994 feat: Remove `shared/_private-breakpoints.scss`
  src/components/BulkActions/BulkActions.scss
  src/components/CheckableButton/CheckableButton.scss
  src/components/ResourceList/_variables.scss
  src/styles/_common.scss
  src/styles/shared/_private-breakpoints.scss
Labels: 🤖Skip Changelog, Get admin on Polaris mainline

#4991 feat: Remove Skeleton mixins
  UNRELEASED-v9.md
  src/components/SkeletonPage/SkeletonPage.scss
  src/styles/shared/_skeleton.scss
Labels: 🤖Skip Changelog, Get admin on Polaris mainline

#4993 Remove public scss api
  UNRELEASED-v9.md
  documentation/guides/migrating-from-v8-to-v9.md
  loom.config.ts
  scripts/build-validate.js
  src/styles/_public-api.scss
Labels: 🤖Skip Changelog, #gsd:22300

#5011 Include migration guidance on css custom properties
  documentation/guides/migrating-from-v8-to-v9.md
Labels: 🤖Skip Changelog, #gsd:22300

#5047 Create migration guidance for `easing()` function
  documentation/guides/migrating-from-v8-to-v9.md
Labels: 🤖Skip Changelog, Get admin on Polaris mainline, #gsd:22300

#5049 Create migration guidance for `duration()` function
  documentation/guides/migrating-from-v8-to-v9.md
Labels: 🤖Skip Changelog, Get admin on Polaris mainline, #gsd:22300

#5051 Create migration guidance for `shadow()` function
  documentation/guides/migrating-from-v8-to-v9.md
Labels: 🤖Skip Changelog, Get admin on Polaris mainline, #gsd:22300

#5053 Create migration guidance for `ms-high-contrast-color()` function
  documentation/guides/migrating-from-v8-to-v9.md
Labels: 🤖Skip Changelog, Get admin on Polaris mainline, #gsd:22300

#5050 Polaris release v8.2.0
  CHANGELOG.md
  README.md
  UNRELEASED.md
  package.json
  src/components/README.md
Labels: 🤖Skip Changelog

#5081 Create migration guidance for `font-family()` function
  documentation/guides/migrating-from-v8-to-v9.md
Labels: 🤖Skip Changelog, Get admin on Polaris mainline, #gsd:22300

#5093 Create migration guidance for `unstyled-link()` and `unstyled-list()` mixins
  documentation/guides/migrating-from-v8-to-v9.md
Labels: 🤖Skip Changelog, Get admin on Polaris mainline, #gsd:22300

#5080 Create migration guidance for `border-radius()` function
  documentation/guides/migrating-from-v8-to-v9.md
Labels: 🤖Skip Changelog, Get admin on Polaris mainline, #gsd:22300

#5013 docs: Migration guide for the ThemeProvider/CustomProperties component
  documentation/guides/migrating-from-v8-to-v9.md
Labels: 🤖Skip Changelog, Get admin on Polaris mainline

#5112 Create migration guidance for `high-contrast-outline()` and `high-contrast-border()` mixins
  documentation/guides/migrating-from-v8-to-v9.md
Labels: 🤖Skip Changelog, Get admin on Polaris mainline, #gsd:22300

#5115 Create migration guidance for `border()` function
  documentation/guides/migrating-from-v8-to-v9.md
Labels: 🤖Skip Changelog, Get admin on Polaris mainline, #gsd:22300

#5114 Create migration guidance for `border-width()` function
  UNRELEASED-v9.md
  documentation/guides/migrating-from-v8-to-v9.md
Labels: 🤖Skip Changelog, Get admin on Polaris mainline, #gsd:22300

#5117 Add migration guidance for rem()
  documentation/guides/migrating-from-v8-to-v9.md
Labels: 🤖Skip Changelog, Get admin on Polaris mainline

#5121 Fix `border-divider` token
  src/tokens/token-groups/shape.json
Labels: 🤖Skip Changelog

#5120 Create migration guidance for `hidden-when-printing()`, `print-hidden()`, `when-not-printing()`, `when-printing()` functions
  documentation/guides/migrating-from-v8-to-v9.md
Labels: 🤖Skip Changelog

#5118 Create migration guidance for `icon-size()` function
  documentation/guides/migrating-from-v8-to-v9.md
Labels: 🤖Skip Changelog

#5137 Consolidate CSS custom properties into one table in the migration guide
  documentation/guides/migrating-from-v8-to-v9.md
Labels: 🤖Skip Changelog, Get admin on Polaris mainline, #gsd:22300

#5142 Collapse `filter()` table
  documentation/guides/migrating-from-v8-to-v9.md
Labels: 🤖Skip Changelog

#5123 Migration guide map extend
  documentation/guides/migrating-from-v8-to-v9.md
Labels: 🤖Skip Changelog, Get admin on Polaris mainline, #gsd:22300

#5161 Navigation design update
  src/components/Navigation/Navigation.scss
  src/components/Navigation/README.md
  src/components/Navigation/_variables.scss
Labels: 🤖Skip Changelog

#5163 Index table divider
  src/components/IndexTable/IndexTable.scss
Labels: 🤖Skip Changelog

#5139 Create migration guidance for `state()` mixin
  documentation/guides/migrating-from-v8-to-v9.md
Labels: 🤖Skip Changelog, Get admin on Polaris mainline, #gsd:22300

#5138 Add migration guidance for `polaris-tokens`
  documentation/guides/migrating-from-v8-to-v9.md
Labels: 🤖Skip Changelog

#5160 Create migration guidance for Sass global variables
  documentation/guides/migrating-from-v8-to-v9.md
Labels: 🤖Skip Changelog, Get admin on Polaris mainline, #gsd:22300

#5145 [`Button`] Prevent the `loading` spinner from overlapping a `monochrome` `outline` `Button`’s text
  UNRELEASED.md
  src/components/Button/Button.scss
Labels: 🐛Bug

#5166 Create a table of contents for the migration guide
  documentation/guides/migrating-from-v8-to-v9.md
Labels: 🤖Skip Changelog, Get admin on Polaris mainline, #gsd:22300

#5200 Add theme object migration to v8 to v9 guide
  documentation/guides/migrating-from-v8-to-v9.md
Labels: 🤖Skip Changelog, Get admin on Polaris mainline, #gsd:22300
