Repository Shopify/polaris, pull requests merged in 2022-03, with the labels that each got.

#5239 Replace divide operation with math.div in legacy Sass API file
  documentation/guides/migrating-from-v8-to-v9.md
Labels: 🤖Skip Changelog

#5229 Add SkeletonTabs component
  .storybook/polaris-readme-loader.js
  UNRELEASED.md
  src/components/SkeletonTabs/README.md
  src/components/SkeletonTabs/SkeletonTabs.scss
  src/components/SkeletonTabs/SkeletonTabs.tsx
  src/components/SkeletonTabs/index.ts
  src/components/Tabs/Tabs.scss
  src/index.ts
Labels: Get admin on Polaris mainline, Admin UI Kit

#5257 Redefine CSS tokens for each color scheme
  UNRELEASED.md
  src/tokens/token-groups/color.dark.json
  src/tokens/token-groups/color.light.json
Labels: 🐛Bug

#5271 Polaris v9.2.2 release
  CHANGELOG.md
  README.md
  UNRELEASED.md
  package.json
  src/components/README.md
Labels: Get admin on Polaris mainline

#5255 Add release steps to Versioning docs
  documentation/Versioning and changelog.md
Labels: 🤖Skip Changelog

#5291 fix: Remove deprecated shadow custom properties
  src/tokens/token-groups/color.dark.json
  src/tokens/token-groups/color.light.json
Labels: 🤖Skip Changelog, Get admin on Polaris mainline

#5320 Fix build-consumer.js script
  polaris-react/LICENSE.md
  polaris-react/scripts/build-consumer.js
Labels: 🐛Bug, 🤖Skip Changelog

#5297 [Listbox] Fix accessibility issues and logic to set active descendant
  polaris-react/UNRELEASED.md
  polaris-react/src/components/Listbox/Listbox.tsx
  polaris-react/src/components/Listbox/components/Option/Option.tsx
  polaris-react/src/components/Listbox/tests/Listbox.test.tsx
  polaris-react/src/utilities/listbox/types.ts
Labels: Multiselect, #gsd:23639

#5321 Update `Combobox` read.me documentation
  polaris-react/src/components/Combobox/README.md
Labels: 📓 Documentation, Multiselect, #gsd:23639

#5331 feat: Stylelint Polaris
  package.json
  polaris-react/.stylelintrc.js
  polaris-react/package.json
  polaris-react/stylelint/plugins/custom-properties-allowed-list/index.js
  stylelint-polaris/.gitignore
  stylelint-polaris/README.md
  stylelint-polaris/configs/internal.js
  stylelint-polaris/index.js
  stylelint-polaris/package.json
  stylelint-polaris/plugins/custom-properties-allowed-list/README.md
  stylelint-polaris/plugins/custom-properties-allowed-list/index.js
  stylelint-polaris/scripts/gen-polaris-vars.js
  stylelint-polaris/tsconfig.json
  stylelint-polaris/utils/index.js
Labels: 🤖Skip Changelog

#5384 Listbox readme updates
  polaris-react/src/components/Listbox/README.md
Labels: Base UI improvements, Multiselect, #gsd:23639

#5403 Add files key to package.json of Stylelint Polaris
  stylelint-polaris/package.json
Labels: 🤖Skip Changelog, Get admin on Polaris mainline
