Repository Shopify/polaris, pull requests merged in 2022-12, with the labels that each got.

#7805 [Layout] Update `ActionList` to use Layout primitives
  .changeset/serious-tomatoes-dress.md
  polaris-react/src/components/ActionList/ActionList.scss
  polaris-react/src/components/ActionList/ActionList.tsx
  polaris-react/src/components/ActionList/components/Item/Item.tsx
  polaris-react/src/components/ActionList/components/Section/Section.tsx
  polaris.shopify.com/src/data/props.json
Labels: #gsd:30116

#7726 [Polaris Lighthouse] Add migration to insert disable comments for @shopify/stylelint-polaris
  .changeset/funny-toys-buy.md
  polaris-migrator/README.md
  polaris-migrator/package.json
  polaris-migrator/src/migrations/styles-insert-stylelint-disable/styles-insert-stylelint-disable.ts
  polaris-migrator/src/migrations/styles-insert-stylelint-disable/tests/styles-insert-stylelint-disable.input.scss
  polaris-migrator/src/migrations/styles-insert-stylelint-disable/tests/styles-insert-stylelint-disable.output.scss
  polaris-migrator/src/migrations/styles-insert-stylelint-disable/tests/styles-insert-stylelint-disable.test.ts
  polaris-migrator/src/utilities/testUtils.ts
  yarn.lock
Labels: #gsd:31276

#7812 [Layout foundations] Add `Divider` component
  .changeset/thirty-boats-flow.md
  polaris-react/src/components/AlphaCard/AlphaCard.stories.tsx
  polaris-react/src/components/Bleed/Bleed.stories.tsx
  polaris-react/src/components/Divider/Divider.scss
  polaris-react/src/components/Divider/Divider.stories.tsx
  polaris-react/src/components/Divider/Divider.tsx
  polaris-react/src/components/Divider/index.ts
  polaris-react/src/components/Divider/tests/Divider.test.tsx
  polaris-react/src/index.ts
  polaris.shopify.com/content/components/divider.md
  polaris.shopify.com/pages/examples/divider-with-border-styles.tsx
  polaris.shopify.com/public/images/components/divider.png
  polaris.shopify.com/src/data/props.json
Labels: #gsd:30116

#7868 Update `stylelint-polaris` to define a single entry point
  .changeset/shaggy-squids-attack.md
  polaris-migrator/src/migrations/styles-insert-stylelint-disable/tests/test-config.js
  stylelint-polaris/package.json
Labels: #gsd:31276

#7114 Update index.md with details about list item title formatting
  .changeset/nasty-apples-laugh.md
  polaris.shopify.com/content/components/exception-list/index.md
Labels: Contribution, Documentation

#7956 [Layout] `Box` aria roles
  .changeset/sixty-squids-promise.md
  polaris-react/src/components/Box/Box.tsx
  polaris.shopify.com/src/data/props.json
Labels: #gsd:30116
