Repository Shopify/polaris, pull requests merged in 2022-09, with the labels that each got.

#7095 New badge update
  .changeset/beans-much-more.md
  polaris.shopify.com/content/foundations/patterns/new-badge/index.md
Labels: Contribution, Documentation, Enablement

#7106 [Layout foundations] Add tests for Stack
  polaris-react/src/components/AlphaStack/AlphaStack.tsx
  polaris-react/src/components/AlphaStack/tests/AlphaStack.test.tsx
Labels: #gsd:30116

#7118 Edit icons documentation
  .changeset/good-trains-teach.md
  polaris.shopify.com/content/foundations/design/icons/index.md
Labels: Contribution, Documentation

#7136 Fix async calls to `getCacheJson` script
  .changeset/metal-squids-dream.md
  polaris.shopify.com/scripts/gen-assets.mjs
  polaris.shopify.com/scripts/gen-cache-json.mjs
  polaris.shopify.com/scripts/watch-md.mjs
Labels: Bug

#7133 Bump size limit
  package.json
Labels: 🤖Skip Changelog

#7138 Revert "Fix async calls to `getCacheJson` script"
  .changeset/metal-squids-dream.md
  polaris.shopify.com/scripts/gen-assets.mjs
  polaris.shopify.com/scripts/gen-cache-json.mjs
  polaris.shopify.com/scripts/watch-md.mjs
Labels: 🤖Skip Changelog

#7154 added comment warning to keep generate avatar styling in multiple rep…
  polaris-react/src/components/Avatar/Avatar.tsx
Labels: 🤖Skip Changelog

#7179 [Text] Update headingXs variant to use semibold instead of bold
  .changeset/swift-hounds-sniff.md
  polaris-react/src/components/Text/Text.tsx
Labels: #gsd:29805, typography beta release

#7181 [Text] Add stories for Text component
  .changeset/brave-tomatoes-prove.md
  polaris-react/src/components/Text/Text.stories.tsx
Labels: #gsd:29805, typography beta release

#7029 [Layout foundations] Inline component prototype
  .changeset/fresh-dingos-press.md
  polaris-react/src/components/Inline/Inline.scss
  polaris-react/src/components/Inline/Inline.stories.tsx
  polaris-react/src/components/Inline/Inline.tsx
  polaris-react/src/components/Inline/index.ts
  polaris-react/src/components/Inline/tests/Inline.test.tsx
  polaris-react/src/index.ts
Labels: #gsd:30116

#7092 [Layout foundations] Add Tile component
  polaris-react/src/components/Tile/Tile.scss
  polaris-react/src/components/Tile/Tile.stories.tsx
  polaris-react/src/components/Tile/Tile.tsx
  polaris-react/src/components/Tile/index.ts
  polaris-react/src/components/Tile/tests/Tile.test.tsx
  polaris-react/src/index.ts
Labels: #gsd:30116

#7191 Fix static breakpoint mixin replacements
  documentation/guides/migrating-from-v9-to-v10.md
  polaris-migrator/src/migrations/replace-static-breakpoint-mixins/replace-static-breakpoint-mixins.ts
  polaris-migrator/src/migrations/replace-static-breakpoint-mixins/tests/replace-static-breakpoint-mixins.output.scss
Labels: 🤖Skip Changelog, #gsd:29805

#7235 [polaris.shopify.com] Remove text alignment guidance
  polaris.shopify.com/content/foundations/design/typography/index.md
Labels: 🤖Skip Changelog

#7218 Add plop migration generator
  polaris-migrator/package.json
  polaris-migrator/plopfile.mjs
  polaris-migrator/templates/sass-migration/{{kebabCase migrationName}}/tests/{{kebabCase migrationName}}.input.scss.hbs
  polaris-migrator/templates/sass-migration/{{kebabCase migrationName}}/tests/{{kebabCase migrationName}}.output.scss.hbs
  polaris-migrator/templates/sass-migration/{{kebabCase migrationName}}/tests/{{kebabCase migrationName}}.test.ts.hbs
  polaris-migrator/templates/sass-migration/{{kebabCase migrationName}}/{{kebabCase migrationName}}.ts.hbs
  polaris-migrator/templates/typescript-migration/{{kebabCase migrationName}}/tests/{{kebabCase migrationName}}.input.tsx.hbs
  polaris-migrator/templates/typescript-migration/{{kebabCase migrationName}}/tests/{{kebabCase migrationName}}.output.tsx.hbs
  polaris-migrator/templates/typescript-migration/{{kebabCase migrationName}}/tests/{{kebabCase migrationName}}.test.ts.hbs
  polaris-migrator/templates/typescript-migration/{{kebabCase migrationName}}/{{kebabCase migrationName}}.ts.hbs
  yarn.lock
Labels: 🤖Skip Changelog, #gsd:29805

#7243 Fix IndexTable rendering issue in Safari
  .changeset/gold-clouds-study.md
  polaris-react/src/components/Checkbox/Checkbox.scss
Labels: Bug

#7230 Add documentation on breakpoint token usage in media queries
  .changeset/spotty-foxes-brake.md
  polaris-tokens/src/token-groups/breakpoints.ts
  polaris.shopify.com/pages/tokens/breakpoints.tsx
Labels: #gsd:25539

#7207 [Layout] `AlphaCard` with alternate `Box` css
  .changeset/shiny-feet-bake.md
  polaris-react/src/components/AlphaCard/AlphaCard.stories.tsx
  polaris-react/src/components/AlphaCard/AlphaCard.tsx
  polaris-react/src/components/AlphaCard/index.ts
  polaris-react/src/components/AlphaCard/tests/AlphaCard.test.tsx
  polaris-react/src/components/Box/Box.scss
  polaris-react/src/components/Box/Box.tsx
  polaris-react/src/index.ts
  polaris.shopify.com/content/components/alpha-card/index.md
  polaris.shopify.com/pages/examples/alpha-card-border-radius.tsx
  polaris.shopify.com/pages/examples/alpha-card-default.tsx
  polaris.shopify.com/pages/examples/alpha-card-flat.tsx
  polaris.shopify.com/pages/examples/alpha-card-subdued.tsx
  polaris.shopify.com/public/images/components/alpha-card.png
  polaris.shopify.com/src/data/props.json
Labels: #gsd:30116, polaris.shopify.com

#7269 Update renameProps to avoid migrating nested component props
  .changeset/light-clocks-applaud.md
  polaris-migrator/src/migrations/rename-component-prop/tests/rename-component-prop.input.tsx
  polaris-migrator/src/migrations/rename-component-prop/tests/rename-component-prop.output.tsx
  polaris-migrator/src/utilities/jsx.ts
Labels: #gsd:29805

#7255 [Layout foundations] Add alpha `ContentBlock` component
  .changeset/tall-socks-cover.md
  .changeset/witty-months-compare.md
  polaris-react/src/components/ContentBlock/ContentBlock.scss
  polaris-react/src/components/ContentBlock/ContentBlock.stories.tsx
  polaris-react/src/components/ContentBlock/ContentBlock.tsx
  polaris-react/src/components/ContentBlock/index.ts
  polaris-react/src/components/ContentBlock/tests/ContentBlock.test.tsx
  polaris-react/src/index.ts
  polaris.shopify.com/content/components/content-block/index.md
  polaris.shopify.com/pages/examples/content-block-width.tsx
  polaris.shopify.com/public/images/components/content-block.png
  polaris.shopify.com/src/data/props.json
Labels: #gsd:30116

#7276 [Layout foundations] Add alpha page in style guide for `Bleed`
  polaris.shopify.com/content/components/bleed/index.md
  polaris.shopify.com/pages/examples/bleed-all-directions.tsx
  polaris.shopify.com/pages/examples/bleed-horizontal.tsx
  polaris.shopify.com/pages/examples/bleed-specific-direction.tsx
  polaris.shopify.com/pages/examples/bleed-vertical.tsx
  polaris.shopify.com/public/images/components/bleed.png
  polaris.shopify.com/src/data/props.json
Labels: #gsd:30116

#7295 💅 Format files
  polaris-icons/icons/DynamicSourceMajor.yml
  polaris-icons/icons/DynamicSourceMinor.yml
  polaris-icons/icons/InsertDynamicSourceMajor.yml
  polaris-icons/icons/InsertDynamicSourceMinor.yml
  polaris.shopify.com/content/components/app-provider/index.md
  polaris.shopify.com/content/contributing/documentation/index.md
  polaris.shopify.com/content/contributing/index.md
  polaris.shopify.com/pages/tokens/typography.tsx
  polaris.shopify.com/src/components/TokensPage/TokensPage.tsx
  polaris.shopify.com/src/data/navItems.ts
  polaris.shopify.com/src/data/props.json
Labels: 🤖Skip Changelog

#7286 [Layout foundations] Add breakpoint configuration to `Tile` component
  polaris-react/src/components/Tile/Tile.scss
  polaris-react/src/components/Tile/Tile.stories.tsx
  polaris-react/src/components/Tile/Tile.tsx
  polaris-react/src/components/Tile/tests/Tile.test.tsx
  polaris.shopify.com/pages/examples/tile-with-columns.tsx
  polaris.shopify.com/pages/examples/tile-with-spacing.tsx
  polaris.shopify.com/src/data/props.json
Labels: #gsd:30116

#7296 [Layout foundations] Refactor token types
  .changeset/three-games-cough.md
  polaris-react/src/components/AlphaCard/AlphaCard.tsx
  polaris-react/src/components/AlphaStack/AlphaStack.tsx
  polaris-react/src/components/Bleed/Bleed.tsx
  polaris-react/src/components/Box/Box.tsx
  polaris-react/src/components/Columns/Columns.tsx
  polaris-react/src/components/Inline/Inline.tsx
  polaris-tokens/src/index.ts
  polaris-tokens/src/token-groups/depth.ts
Labels: #gsd:30116

#7303 Document current migrations and tips for post-migration
  polaris-migrator/README.md
Labels: 🤖Skip Changelog

#7288 Add processed marker to the Sass migrations template
  polaris-migrator/templates/sass-migration/{{kebabCase migrationName}}/{{kebabCase migrationName}}.ts.hbs
Labels: 🤖Skip Changelog
