Repository Shopify/polaris, pull requests merged in 2022-06, with the labels that each got.

#5957 [TextField] Fixed verticalContent not supporting text selection
  .changeset/eight-pianos-try.md
  polaris-react/CHANGELOG.md
  polaris-react/src/components/Autocomplete/README.md
  polaris-react/src/components/TextField/TextField.scss
  polaris-react/src/components/TextField/TextField.tsx
  polaris-react/src/components/TextField/components/Spinner/Spinner.tsx
  polaris-react/src/components/TextField/tests/TextField.test.tsx
Labels: #gsd:23639

#6009 [Polaris website refresh] Refactor Left Nav and TOC
  .changeset/flat-monkeys-lie.md
  polaris.shopify.com/src/components/ComponentsPage/ComponentsPage.module.scss
  polaris.shopify.com/src/components/ComponentsPage/ComponentsPage.tsx
  polaris.shopify.com/src/components/LeftNavLayout/LeftNavLayout.module.scss
  polaris.shopify.com/src/components/LeftNavLayout/LeftNavLayout.tsx
  polaris.shopify.com/src/components/LeftNavLayout/index.ts
  polaris.shopify.com/src/components/LeftNavWithTOCLayout/LeftNavWithTOCLayout.module.scss
  polaris.shopify.com/src/components/LeftNavWithTOCLayout/LeftNavWithTOCLayout.tsx
  polaris.shopify.com/src/components/LeftNavWithTOCLayout/index.ts
  polaris.shopify.com/src/pages/_app.tsx
  polaris.shopify.com/src/pages/components/[category]/[component].tsx
  polaris.shopify.com/src/pages/components/index.tsx
Labels: #gsd:25820

#5840 [Badge] 🐛 makes `new` and `info` Pip colors the same as in `Badge`
  .changeset/unlucky-baboons-breathe.md
  polaris-react/src/components/Badge/components/Pip/Pip.scss
Labels: Bug

#6072 Enable /snapit on Version Packages pull requests
  .github/workflows/snapit.yml
Labels: #gsd:23655

#5812 [Listbox] Fix: preserve scroll position when lazy-loading additional items
  .changeset/curvy-rockets-provide.md
  polaris-react/src/components/Listbox/Listbox.tsx
Labels: Bug

#6086 Temp fix version packages pull requests
  polaris-react/CHANGELOG.md
  polaris-react/package.json
  polaris-tokens/CHANGELOG.md
  polaris-tokens/package.json
  polaris.shopify.com/CHANGELOG.md
  polaris.shopify.com/package.json
Labels: cla-needed

#5829 Performance Benchmarking of Stories using React Profiler
  .changeset/smooth-lemons-warn.md
  .github/workflows/ci-a11y-vrt.yml
  polaris-react/.storybook/RenderPerformanceProfiler/RenderPerformanceProfiler.tsx
  polaris-react/.storybook/RenderPerformanceProfiler/index.ts
  polaris-react/.storybook/main.js
  polaris-react/.storybook/preview.js
  polaris-react/package.json
  yarn.lock
Labels: #gsd:25464

#6045 Move size-limit to the root of Polaris
  .github/workflows/size-limit.yml
  package.json
  polaris-react/package.json
Labels: #gsd:23655, 🤖Skip Changelog

#6098 [IndexTable] Hide ScrollBar when table is not scrollable
  .changeset/great-coats-kick.md
  polaris-react/src/components/IndexTable/IndexTable.scss
  polaris-react/src/components/IndexTable/IndexTable.tsx
  polaris-react/src/components/IndexTable/tests/IndexTable.test.tsx
Labels: cla-needed

#6110 Add CSS unit utilities
  .changeset/bright-wasps-think.md
  polaris-tokens/src/utilities.ts
  polaris-tokens/tests/utilities.test.js
Labels: #gsd:25539

#6106 Update experimental breakpoints for down media conditions
  .changeset/tidy-lemons-poke.md
  polaris-react/scripts/gen-media-queries.js
Labels: #gsd:25539

#5803 feat: Improve emitted TypeScript declarations for Polaris tokens
  .changeset/neat-glasses-shave.md
  polaris-for-vscode/src/server.ts
  polaris-tokens/src/tokens.ts
  polaris-tokens/src/types.ts
  polaris-tokens/src/utilities.ts
  polaris.shopify.com/src/utils/search.ts
Labels: #gsd:23655

#6123 [polaris.shopify.com reboot] Style example section of the component pages
  polaris.shopify.com/src/components/Examples/Examples.module.scss
  polaris.shopify.com/src/components/Examples/Examples.tsx
  polaris.shopify.com/src/pages/components/[component].tsx
Labels: 🤖Skip Changelog

#6095 BREAKING CHANGE: Convert breakpoint mixins to scss variables
  .changeset/slow-timers-enjoy.md
  polaris-react/src/components/CalloutCard/CalloutCard.scss
  polaris-react/src/components/Card/Card.scss
  polaris-react/src/components/DescriptionList/DescriptionList.scss
  polaris-react/src/components/EmptyState/EmptyState.scss
  polaris-react/src/components/FooterHelp/FooterHelp.scss
  polaris-react/src/components/Frame/Frame.scss
  polaris-react/src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.scss
  polaris-react/src/components/Layout/Layout.scss
  polaris-react/src/components/MediaCard/MediaCard.scss
  polaris-react/src/components/Modal/components/Dialog/Dialog.scss
  polaris-react/src/components/Page/components/Header/Header.scss
  polaris-react/src/components/PageActions/PageActions.scss
  polaris-react/src/components/RangeSlider/components/DualThumb/DualThumb.scss
  polaris-react/src/components/RangeSlider/components/SingleThumb/SingleThumb.scss
  polaris-react/src/components/ResourceItem/ResourceItem.scss
  polaris-react/src/components/Sheet/Sheet.scss
  polaris-react/src/components/SkeletonPage/SkeletonPage.scss
  polaris-react/src/components/TopBar/components/Search/Search.scss
  polaris-react/src/styles/shared/_breakpoints.scss
  polaris-react/src/styles/shared/_page.scss
Labels: #gsd:25539

#6149 Add Playground to Storybook workflow
  .github/workflows/ci-a11y-vrt.yml
Labels: 🤖Skip Changelog, #gsd:25298

#5820 feat: Update CalloutCard to use Polaris SM media conditions
  polaris-react/src/components/CalloutCard/CalloutCard.scss
Labels: 🤖Skip Changelog, #gsd:25539

#5864 feat: Update TopBar Search to use Polaris SM media conditions
  polaris-react/src/components/TopBar/components/Search/Search.scss
Labels: 🤖Skip Changelog, #gsd:25539

#5859 feat: Update PageActions to use Polaris SM media conditions
  polaris-react/src/components/PageActions/PageActions.scss
Labels: 🤖Skip Changelog, #gsd:25539

#5849 feat: Update Card to use Polaris SM media conditions
  polaris-react/src/components/Card/Card.scss
Labels: 🤖Skip Changelog, #gsd:25539

#5858 feat: Update page mixins to use Polaris SM media conditions
  polaris-react/src/styles/shared/_page.scss
Labels: 🤖Skip Changelog, #gsd:25539

#5867 Removed unused class from Page Header component
  .changeset/poor-boats-provide.md
  polaris-react/src/components/Page/components/Header/Header.scss
  polaris-react/src/components/Page/components/Header/tests/Header.test.tsx
Labels: #gsd:25539

#6148 [Navigation] Add white background to Navigation if logo is present
  .changeset/stupid-books-unite.md
  polaris-react/src/components/Navigation/Navigation.scss
Labels: #gsd:25139

#6185 feat: Update MediaCard to use Polaris SM media conditions
  polaris-react/src/components/MediaCard/MediaCard.scss
Labels: #gsd:25539

#6186 Refactor react perf profiler for local dev, local data collection
  .changeset/healthy-maps-watch.md
  polaris-react/.storybook/RenderPerformanceProfiler/RenderPerformanceProfiler.tsx
  polaris-react/.storybook/manager.js
  polaris-react/.storybook/preview.js
Labels: #gsd:25464

#6224 [TextField] Revert #6143 and make expecting onBlur event arg optional
  .changeset/small-beds-report.md
  polaris-react/src/components/TextField/TextField.tsx
Labels: Bug

#6225 [Releasing.md] Update the instructions to include testing a snapshot prior to releasing
  documentation/Releasing.md
Labels: 🤖Skip Changelog

#6216 [Token] change shadow-popover token
  .changeset/rare-games-wave.md
  polaris-tokens/src/token-groups/depth.ts
Labels: #gsd:25772

#6183 [Documentation] add contribution guidelines to figma ui kit and icon pages
  .changeset/spotty-seas-cough.md
  polaris.shopify.com/content/contributing/figma-ui-kit.md
  polaris.shopify.com/content/contributing/icons.md
Labels: Contribution

#6221 feat: Update Dialog to use Polaris LG media conditions
  polaris-react/src/components/Modal/components/Dialog/Dialog.scss
Labels: #gsd:25539

#6222 feat: Update Header to use Polaris LG media conditions
  polaris-react/src/components/Page/components/Header/Header.scss
Labels: #gsd:25539

#6272 Fix typos
  polaris.shopify.com/src/components/ResourcesPage/ResourcesPage.tsx
Labels: 🤖Skip Changelog

#6292 Update HomePage content
  polaris.shopify.com/src/components/ResourcesPage/ResourcesPage.tsx
Labels: 🤖Skip Changelog

#6269 feat: Update Dialog to Polaris MD media conditions
  polaris-react/src/components/Modal/components/Dialog/Dialog.scss
  polaris-react/src/styles/shared/_breakpoints.scss
Labels: #gsd:25539

#6266 feat: Update Sheet to Polaris MD media conditions
  polaris-react/src/components/Sheet/Sheet.scss
  polaris-react/src/styles/shared/_breakpoints.scss
Labels: #gsd:25539

#6263 feat: Update not-partially-condensed mixins to Polaris MD media conditions
  polaris-react/src/components/EmptyState/EmptyState.scss
  polaris-react/src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.scss
  polaris-react/src/components/RangeSlider/components/DualThumb/DualThumb.scss
  polaris-react/src/components/RangeSlider/components/SingleThumb/SingleThumb.scss
  polaris-react/src/components/SkeletonPage/SkeletonPage.scss
  polaris-react/src/components/TopBar/components/Search/Search.scss
  polaris-react/src/styles/shared/_breakpoints.scss
  polaris-react/src/styles/shared/_page.scss
Labels: #gsd:25539

#6312 feat: Update Dialog to use Polaris MD media conditions
  polaris-react/src/components/Modal/components/Dialog/Dialog.scss
Labels: #gsd:25539

#6308 [polaris.shopify.com reboot] Update tokens content for accuracy, plus a small edit
  .changeset/unlucky-snails-relax.md
  polaris.shopify.com/src/components/ResourcesPage/ResourcesPage.tsx
Labels: #gsd:25820

#6314 Remove unused breakpoint variables
  polaris-react/src/styles/shared/_breakpoints.scss
Labels: #gsd:25539

#6324 Removed unused when not fully condensed variable
  polaris-react/src/styles/shared/_breakpoints.scss
  polaris-react/src/styles/shared/_page.scss
Labels: #gsd:25539

#6387 [polaris.shopify.com] Reset [preview | code] switcher when moving between components
  polaris.shopify.com/src/components/Examples/Examples.tsx
Labels: 🤖Skip Changelog

#6355 feat: Update TopBar to Polaris LG media conditions
  polaris-react/src/components/TopBar/TopBar.scss
Labels: #gsd:25539

#6325 feat: Update not-condensed-content mixins to use Polaris MD media conditions
  polaris-react/src/components/TopBar/TopBar.scss
  polaris-react/src/styles/foundation/_layout.scss
  polaris-react/src/styles/shared/_breakpoints.scss
Labels: #gsd:25539

#6327 feat: Update layout-not-stacked mixins to Polaris MD media conditions
  polaris-react/src/components/Layout/Layout.scss
  polaris-react/src/components/SkeletonPage/SkeletonPage.scss
  polaris-react/src/styles/shared/_breakpoints.scss
Labels: #gsd:25539

#6322 feat: Update partially-condensed mixins to Polaris LG media conditions
  polaris-react/src/components/ResourceItem/ResourceItem.scss
  polaris-react/src/components/SkeletonPage/SkeletonPage.scss
  polaris-react/src/styles/shared/_breakpoints.scss
Labels: #gsd:25539

#6367 feat: Update DescriptionList to Polaris SM media conditions
  polaris-react/src/components/DescriptionList/DescriptionList.scss
Labels: #gsd:25539

#6364 feat: Update all 458px breakpoints to use Polaris SM media conditions
  polaris-react/src/components/BulkActions/BulkActions.scss
  polaris-react/src/components/CheckableButton/CheckableButton.scss
  polaris-react/src/components/IndexTable/IndexTable.scss
  polaris-react/src/components/IndexTable/IndexTable.tsx
  polaris-react/src/components/ResourceItem/ResourceItem.scss
  polaris-react/src/components/ResourceList/ResourceList.scss
  polaris-react/src/components/ResourceList/ResourceList.tsx
  polaris-react/src/components/ResourceList/_variables.scss
Labels: #gsd:25539

#6352 feat: Update Header to Polaris MD media conditions
  polaris-react/src/components/Page/components/Header/Header.scss
  polaris-react/src/utilities/breakpoints.ts
Labels: #gsd:25539

#6460 Add fallbacks to stylelint-polaris/media-queries-allowed-list plugin
  polaris-for-figma/package.json
  polaris-react/package.json
  polaris-tokens/package.json
  polaris.shopify.com/package.json
  stylelint-polaris/plugins/media-queries-allowed-list/index.js
Labels: 🤖Skip Changelog
