Repository Shopify/polaris, pull requests merged in 2022-07, with the labels that each got.

#6344 Add profiler scripts
  .changeset/yellow-boxes-press.md
  polaris-react/.storybook/GridOverlay/GridOverlay.tsx
  polaris-react/.storybook/RenderPerformanceProfiler/RenderPerformanceProfiler.tsx
  polaris-react/.storybook/manager.js
  polaris-react/.storybook/preview.js
  polaris-react/package.json
  polaris-react/playground/KitchenSink.tsx
  polaris-react/scripts/profiler.js
  polaris-react/tsconfig.json
Labels: #gsd:25464

#6483 Deprecate Layout.AnnotatedSection
  .changeset/shy-needles-battle.md
  polaris-react/src/components/Layout/Layout.tsx
  polaris-react/src/components/Layout/README.md
  polaris-react/src/components/Layout/components/AnnotatedSection/AnnotatedSection.tsx
Labels: #gsd:25156

#6473 [polaris.shopify.com] Various a11y improvements
  .changeset/little-scissors-talk.md
  polaris.shopify.com/src/components/HomePage/HomePage.module.scss
  polaris.shopify.com/src/components/HomePage/HomePage.tsx
  polaris.shopify.com/src/components/HomePage/vscode.jpg
  polaris.shopify.com/src/components/IconGrid/IconGrid.module.scss
  polaris.shopify.com/src/components/IconGrid/IconGrid.tsx
  polaris.shopify.com/src/styles/globals.scss
Labels: Accessibility, polaris.shopify.com

#6521 [Typography foundations] Add Text component
  .changeset/curly-llamas-bathe.md
  polaris-react/src/components/Text/Text.scss
  polaris-react/src/components/Text/Text.tsx
  polaris-react/src/components/Text/index.ts
  polaris-react/src/index.ts
Labels: #gsd:25298

#6590 Update token tests
  polaris-tokens/tests/utilities.test.js
Labels: 🤖Skip Changelog

#6618 Remove platform frontmatter from polaris react
  .changeset/tidy-shirts-tap.md
  documentation/Component READMEs.md
  polaris-react/.storybook/polaris-readme-loader.js
  polaris-react/src/components/Avatar/README.md
  polaris-react/src/components/Badge/README.md
  polaris-react/src/components/Banner/README.md
  polaris-react/src/components/Button/README.md
  polaris-react/src/components/ButtonGroup/README.md
  polaris-react/src/components/Caption/README.md
  polaris-react/src/components/Card/README.md
  polaris-react/src/components/Checkbox/README.md
  polaris-react/src/components/ChoiceList/README.md
  polaris-react/src/components/Collapsible/README.md
  polaris-react/src/components/DatePicker/README.md
  polaris-react/src/components/DescriptionList/README.md
  polaris-react/src/components/DisplayText/README.md
  polaris-react/src/components/EmptyState/README.md
  polaris-react/src/components/FormLayout/README.md
  polaris-react/src/components/Heading/README.md
  polaris-react/src/components/InlineError/README.md
  polaris-react/src/components/List/README.md
  polaris-react/src/components/Modal/README.md
  polaris-react/src/components/Page/README.md
  polaris-react/src/components/Pagination/README.md
  polaris-react/src/components/Popover/README.md
  polaris-react/src/components/RadioButton/README.md
  polaris-react/src/components/RangeSlider/README.md
  polaris-react/src/components/Select/README.md
  polaris-react/src/components/Sheet/README.md
  polaris-react/src/components/Spinner/README.md
  polaris-react/src/components/Subheading/README.md
  polaris-react/src/components/Tabs/README.md
  polaris-react/src/components/Tag/README.md
  polaris-react/src/components/TextContainer/README.md
  polaris-react/src/components/TextField/README.md
  polaris-react/src/components/TextStyle/README.md
  polaris-react/src/components/Thumbnail/README.md
  polaris-react/src/components/Toast/README.md
Labels: #gsd:25820

#6620 Remove non existent examples frontmatter
  polaris.shopify.com/content/components/modal.md
  polaris.shopify.com/content/components/pagination.md
  polaris.shopify.com/content/components/popover.md
  polaris.shopify.com/content/components/radio-button.md
  polaris.shopify.com/content/components/text-field.md
  polaris.shopify.com/content/components/toast.md
Labels: #gsd:25820

#6616 [polaris.shopify.com] yarn tsc finds unused code, also remove any that exists
  .changeset/moody-keys-protect.md
  polaris.shopify.com/src/components/FoundationsIndexPage/FoundationsIndexPage.tsx
  polaris.shopify.com/src/components/Markdown/Markdown.tsx
  polaris.shopify.com/src/components/PropsTable/PropsTable.tsx
  polaris.shopify.com/src/components/Tabs/Tabs.tsx
  polaris.shopify.com/src/components/TokensPage/TokensPage.tsx
  polaris.shopify.com/src/components/Tooltip/Tooltip.tsx
  polaris.shopify.com/src/pages/api/v0/tokens/[tokens].tsx
  polaris.shopify.com/src/pages/api/v0/tokens/index.tsx
  polaris.shopify.com/src/pages/contributing/[doc].tsx
  polaris.shopify.com/src/utils/hooks.ts
  polaris.shopify.com/tsconfig.json
Labels: #gsd:25820

#6453 [Layout] Use `Grid` component
  documentation/guides/migrating-from-v9-to-v10.md
  polaris-react/.storybook/GridOverlay/GridOverlay.css
  polaris-react/.storybook/GridOverlay/GridOverlay.tsx
  polaris-react/playground/DetailsPage.tsx
  polaris-react/src/components/AppProvider/README.md
  polaris-react/src/components/Frame/README.md
  polaris-react/src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.scss
  polaris-react/src/components/Layout/Layout.scss
  polaris-react/src/components/Layout/Layout.tsx
  polaris-react/src/components/Layout/README.md
  polaris-react/src/components/Layout/components/AnnotatedSection/AnnotatedSection.tsx
  polaris-react/src/components/Layout/components/AnnotatedSection/index.ts
  polaris-react/src/components/Layout/components/Section/Section.tsx
  polaris-react/src/components/Layout/components/Section/tests/Section.test.tsx
  polaris-react/src/components/Layout/components/index.ts
  polaris-react/src/components/Layout/tests/Layout.test.tsx
  polaris-react/src/components/Navigation/Navigation.scss
  polaris-react/src/components/SkeletonPage/README.md
  polaris-react/src/components/TopBar/TopBar.scss
  polaris-react/src/styles/foundation/_layout.scss
  polaris-react/src/styles/shared/_page.scss
  polaris.shopify.com/content/foundations/patterns/layout.md
  polaris.shopify.com/src/data/components.json
  polaris.shopify.com/src/pages/examples/frame-in-an-application.tsx
  polaris.shopify.com/src/pages/examples/frame-with-an-offset.tsx
  polaris.shopify.com/src/pages/examples/layout-annotated-with-banner-at-the-top.tsx
  polaris.shopify.com/src/pages/examples/layout-annotated.tsx
  stylelint-polaris/configs/coverage.js
Labels: #gsd:25156

#6430 [polaris.shopify.com] Polish contribution guidance
  .changeset/late-apples-cry.md
  polaris.shopify.com/content/contributing/components.md
  polaris.shopify.com/content/contributing/documentation.md
  polaris.shopify.com/content/contributing/figma-ui-kit.md
  polaris.shopify.com/content/contributing/icons.md
  polaris.shopify.com/content/contributing/illustrations.md
  polaris.shopify.com/content/contributing/index.md
  polaris.shopify.com/content/contributing/shipping-your-contribution.md
  polaris.shopify.com/public/sitemap.xml
  polaris.shopify.com/src/components/Examples/Examples.tsx
  polaris.shopify.com/src/components/Layout/Layout.module.scss
  polaris.shopify.com/src/components/Longform/Longform.module.scss
  polaris.shopify.com/src/components/Markdown/Markdown.tsx
  polaris.shopify.com/src/components/Select/Select.module.scss
  polaris.shopify.com/src/components/Select/Select.tsx
  polaris.shopify.com/src/components/Select/index.ts
  polaris.shopify.com/src/data/navItems.ts
  polaris.shopify.com/src/pages/contributing/[doc].tsx
  polaris.shopify.com/src/styles/globals.scss
  polaris.shopify.com/src/types.ts
  polaris.shopify.com/src/utils/hooks.ts
Labels: Contribution, polaris.shopify.com

#6457 [Icon] Add StatusActiveMajor icon
  .changeset/silly-news-matter.md
  polaris-icons/icons/StatusActiveMajor.svg
  polaris-icons/icons/StatusActiveMajor.yml
Labels: Icon

#6597 Update legacy text style mixins to use tokens
  .changeset/polite-camels-walk.md
  documentation/guides/legacy-polaris-v8-public-api.scss
Labels: #gsd:25298

#6664 Call package preversion scripts before running changeset version
  .github/workflows/release.yml
  package.json
  polaris-react/package.json
  turbo.json
Labels: 🤖Skip Changelog

#6700 [Typography foundations] Update `<InlineCode>` styling for accessibility
  polaris-react/src/components/InlineCode/InlineCode.scss
Labels: #gsd:25298, typography alpha release

#6738 [polaris.shopify.com] Fix broken image
  .changeset/young-socks-yell.md
  polaris.shopify.com/content/foundations/patterns/help-content.md
  polaris.shopify.com/public/images/foundations/patterns/help-content/after.png
  polaris.shopify.com/public/images/foundations/patterns/help-content/before.png
  polaris.shopify.com/public/images/foundations/patterns/help-content/learn-more-badges-interaction.png
  polaris.shopify.com/public/images/foundations/patterns/help-content/learn-more-badges.png
Labels: #gsd:25820

#6735 [Typography foundations] Refactor `display` variants to `heading2xl-4xl`
  polaris-react/src/components/Text/Text.scss
  polaris-react/src/components/Text/Text.tsx
Labels: #gsd:25298, typography alpha release

#6758 Fix export const in readme-update-version
  polaris-react/scripts/readme-update-version.js
  polaris-react/tests/readme-update-version.test.js
Labels: 🤖Skip Changelog

#6772 Polish README.md files before migration
  polaris-react/src/components/Combobox/README.md
  polaris-react/src/components/DropZone/README.md
  polaris-react/src/components/Frame/README.md
  polaris-react/src/components/Modal/README.md
  polaris-react/src/components/Page/README.md
  polaris-react/src/components/README.md
Labels: 🤖Skip Changelog

#6791 Revert storybook version bump and clean up
  .changeset/green-trees-beam.md
  polaris-react/.storybook/main.js
  polaris-react/package.json
  yarn.lock
Labels: 🤖Skip Changelog

#6789 Edit copy for Contributing to Polaris guidelines
  .changeset/lemon-maps-camp.md
  polaris.shopify.com/content/contributing/code-of-conduct.md
  polaris.shopify.com/content/contributing/components.md
  polaris.shopify.com/content/contributing/designing-with-a-system.md
  polaris.shopify.com/content/contributing/documentation.md
  polaris.shopify.com/content/contributing/figma-ui-kit.md
  polaris.shopify.com/content/contributing/icons.md
  polaris.shopify.com/content/contributing/index.md
  polaris.shopify.com/content/contributing/shipping-your-contribution.md
  polaris.shopify.com/content/contributing/when-to-contribute-new-patterns.md
Labels: Contribution

#6797 [Typography foundations] Feat/Update Text component to support Labels
  polaris-react/src/components/Text/Text.tsx
Labels: #gsd:25298, typography beta release

#6092 Reduce breakpoints
  .changeset/slow-timers-enjoy.md
  polaris-react/.storybook/GridOverlay/GridOverlay.css
  polaris-react/.storybook/GridOverlay/GridOverlay.tsx
  polaris-react/playground/DetailsPage.scss
  polaris-react/src/components/AppProvider/AppProvider.stories.tsx
  polaris-react/src/components/BulkActions/BulkActions.scss
  polaris-react/src/components/CalloutCard/CalloutCard.scss
  polaris-react/src/components/Card/Card.scss
  polaris-react/src/components/CheckableButton/CheckableButton.scss
  polaris-react/src/components/Choice/Choice.scss
  polaris-react/src/components/ChoiceList/ChoiceList.scss
  polaris-react/src/components/DescriptionList/DescriptionList.scss
  polaris-react/src/components/EmptyState/EmptyState.scss
  polaris-react/src/components/FooterHelp/FooterHelp.scss
  polaris-react/src/components/Frame/Frame.scss
  polaris-react/src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.scss
  polaris-react/src/components/Frame/components/Toast/Toast.scss
  polaris-react/src/components/IndexTable/IndexTable.scss
  polaris-react/src/components/IndexTable/IndexTable.tsx
  polaris-react/src/components/Layout/Layout.scss
  polaris-react/src/components/MediaCard/MediaCard.scss
  polaris-react/src/components/Modal/Modal.scss
  polaris-react/src/components/Modal/components/Dialog/Dialog.scss
  polaris-react/src/components/Navigation/Navigation.scss
  polaris-react/src/components/Navigation/_variables.scss
  polaris-react/src/components/Page/components/Header/Header.scss
  polaris-react/src/components/Page/components/Header/components/Title/Title.scss
  polaris-react/src/components/PageActions/PageActions.scss
  polaris-react/src/components/RadioButton/RadioButton.scss
  polaris-react/src/components/RangeSlider/components/DualThumb/DualThumb.scss
  polaris-react/src/components/RangeSlider/components/SingleThumb/SingleThumb.scss
  polaris-react/src/components/ResourceItem/ResourceItem.scss
  polaris-react/src/components/ResourceList/ResourceList.scss
  polaris-react/src/components/ResourceList/ResourceList.tsx
  polaris-react/src/components/ResourceList/_variables.scss
  polaris-react/src/components/Sheet/Sheet.scss
  polaris-react/src/components/SkeletonDisplayText/SkeletonDisplayText.scss
  polaris-react/src/components/SkeletonPage/SkeletonPage.scss
  polaris-react/src/components/Tag/Tag.scss
  polaris-react/src/components/TextField/TextField.scss
  polaris-react/src/components/TopBar/TopBar.scss
  polaris-react/src/components/TopBar/components/Menu/Menu.scss
  polaris-react/src/components/TopBar/components/Search/Search.scss
  polaris-react/src/components/TopBar/components/UserMenu/UserMenu.scss
  polaris-react/src/styles/foundation/_layout.scss
  polaris-react/src/styles/shared/_breakpoints.scss
  polaris-react/src/styles/shared/_layout.scss
  polaris-react/src/styles/shared/_page.scss
  polaris-react/src/styles/shared/_typography.scss
  polaris-react/src/utilities/breakpoints.ts
  stylelint-polaris/configs/internal.js
  stylelint-polaris/plugins/media-queries-allowed-list/index.js
  stylelint-polaris/plugins/media-queries-allowed-list/index.test.js
Labels: #gsd:25539

#6572 [Typography foundations] Release alpha Text component
  .changeset/curly-llamas-bathe.md
  polaris-for-vscode/src/server.ts
  polaris-react/playground/DetailsPage.scss
  polaris-react/src/components/ActionList/ActionList.scss
  polaris-react/src/components/Autocomplete/components/MappedAction/MappedAction.scss
  polaris-react/src/components/Badge/Badge.scss
  polaris-react/src/components/Banner/Banner.scss
  polaris-react/src/components/Button/Button.scss
  polaris-react/src/components/CheckableButton/CheckableButton.scss
  polaris-react/src/components/DataTable/DataTable.scss
  polaris-react/src/components/DatePicker/DatePicker.scss
  polaris-react/src/components/DropZone/components/FileUpload/FileUpload.scss
  polaris-react/src/components/Filters/Filters.scss
  polaris-react/src/components/Heading/Heading.scss
  polaris-react/src/components/InlineCode/InlineCode.scss
  polaris-react/src/components/InlineCode/InlineCode.tsx
  polaris-react/src/components/InlineCode/index.ts
  polaris-react/src/components/InlineCode/tests/InlineCode.test.tsx
  polaris-react/src/components/KeyboardKey/KeyboardKey.scss
  polaris-react/src/components/Layout/Layout.scss
  polaris-react/src/components/Navigation/Navigation.scss
  polaris-react/src/components/Navigation/_variables.scss
  polaris-react/src/components/Page/Page.scss
  polaris-react/src/components/Page/components/Header/components/Title/Title.scss
  polaris-react/src/components/SkeletonDisplayText/SkeletonDisplayText.scss
  polaris-react/src/components/Subheading/Subheading.scss
  polaris-react/src/components/Tag/Tag.scss
  polaris-react/src/components/Text/README.md
  polaris-react/src/components/Text/Text.scss
  polaris-react/src/components/Text/Text.tsx
  polaris-react/src/components/Text/index.ts
  polaris-react/src/components/Text/tests/Text.test.tsx
  polaris-react/src/components/TextStyle/TextStyle.scss
  polaris-react/src/components/TopBar/components/UserMenu/UserMenu.scss
  polaris-react/src/index.ts
  polaris-react/src/styles/shared/_buttons.scss
  polaris-react/src/styles/shared/_controls.scss
  polaris-react/src/styles/shared/_typography.scss
  polaris-tokens/src/metadata.ts
  polaris-tokens/src/token-groups/font.ts
  polaris-tokens/src/types.ts
  polaris-tokens/tests/toStyleSheet.test.js
  polaris.shopify.com/content/components/text.md
  polaris.shopify.com/src/components/TokensPage/TokensPage.tsx
  polaris.shopify.com/src/data/components.json
  polaris.shopify.com/src/data/props.json
  polaris.shopify.com/src/data/tokensNav.ts
  polaris.shopify.com/src/pages/examples/text-align.tsx
  polaris.shopify.com/src/pages/examples/text-body.tsx
  polaris.shopify.com/src/pages/examples/text-color.tsx
  polaris.shopify.com/src/pages/examples/text-heading.tsx
  polaris.shopify.com/src/pages/examples/text-weight.tsx
  polaris.shopify.com/src/pages/tokens/font.tsx
  polaris.shopify.com/src/utils/search.ts
Labels: #gsd:25298, typography alpha release
