Repository Shopify/polaris, pull requests merged in 2022-08, with the labels that each got.

#6839 [polaris.shopify.com][/contributing] Update the intro of the 'Shipping your contribution' guide
  .changeset/violet-rivers-work.md
  polaris.shopify.com/content/contributing/shipping-your-contribution/index.md
Labels: Contribution, Documentation, #gsd:29814

#6841 Contribution quality principles
  .changeset/rude-gorillas-run.md
  polaris.shopify.com/content/contributing/index.md
Labels: Contribution, polaris.shopify.com, #gsd:29814

#6850 Link changeset docs in contribution instructions
  polaris.shopify.com/content/contributing/shipping-your-contribution/index.md
Labels: 🤖Skip Changelog

#6658 [polaris.shopify.com] Table style tweaks
  .changeset/hip-countries-smash.md
  polaris.shopify.com/src/components/Longform/Longform.module.scss
  polaris.shopify.com/src/styles/globals.scss
Labels: polaris.shopify.com

#6310 Update contribution guidelines with ux review feedback
  polaris.shopify.com/content/contributing/index.md
Labels: 🤖Skip Changelog, Enablement

#6946 Update tsconfig to reflect move of pages directory
  polaris.shopify.com/tsconfig.json
Labels: 🤖Skip Changelog

#6945 Update space token names design foundations
  polaris.shopify.com/content/foundations/design/space/index.md
  polaris.shopify.com/public/images/foundations/design/space/spacing-polaris-units.svg
  polaris.shopify.com/public/images/foundations/design/space/spacing-polaris-units@2x.png
Labels: Documentation

#6953 [Badge] Use real product use cases in examples
  .changeset/long-tomatoes-refuse.md
  polaris-react/src/components/Badge/Badge.stories.tsx
  polaris.shopify.com/pages/examples/badge-attention.tsx
  polaris.shopify.com/pages/examples/badge-incomplete.tsx
  polaris.shopify.com/pages/examples/badge-informational.tsx
  polaris.shopify.com/pages/examples/badge-partially-complete.tsx
  polaris.shopify.com/pages/examples/badge-success.tsx
  polaris.shopify.com/pages/examples/badge-warning.tsx
Labels: Documentation

#6951 Update intro of About Polaris page
  polaris.shopify.com/content/foundations/foundations/about-polaris/index.md
Labels: 🤖Skip Changelog, #gsd:29814, Enablement

#6954 [Combobox][Listbox.Option] Fixed click event bubbling causing Popover close
  .changeset/warm-clocks-jog.md
  polaris-react/src/components/Autocomplete/Autocomplete.stories.tsx
  polaris-react/src/components/Autocomplete/Autocomplete.tsx
  polaris-react/src/components/Combobox/Combobox.tsx
  polaris-react/src/components/Listbox/Listbox.stories.tsx
  polaris-react/src/components/Listbox/components/Option/Option.tsx
  polaris-react/src/components/Listbox/components/Option/tests/Option.test.tsx
  polaris-react/src/components/Popover/Popover.stories.tsx
  polaris-react/src/components/Sheet/Sheet.stories.tsx
  polaris.shopify.com/pages/examples/autocomplete-with-action.tsx
  polaris.shopify.com/pages/examples/autocomplete-with-destructive-action.tsx
  polaris.shopify.com/pages/examples/autocomplete-with-wrapping-action.tsx
  polaris.shopify.com/pages/examples/combobox-with-manual-selection.tsx
  polaris.shopify.com/pages/examples/listbox-with-search.tsx
  polaris.shopify.com/pages/examples/popover-with-searchable-listbox.tsx
  polaris.shopify.com/pages/examples/sheet-with-searchable-listbox.tsx
Labels: Bug

#6969 [polaris.shopify.com] Fix progress-bar example
  .changeset/strange-cheetahs-give.md
  polaris.shopify.com/pages/examples/progress-bar-colored.tsx
  polaris.shopify.com/pages/examples/progress-bar-default.tsx
  polaris.shopify.com/pages/examples/progress-bar-non-animated.tsx
  polaris.shopify.com/pages/examples/progress-bar-small.tsx
Labels: Contribution

#6981 [polaris.shopify.com] Update CustomProperties to use sentence case format
  .changeset/poor-rivers-enjoy.md
  polaris.shopify.com/content/components/custom-properties/index.md
  polaris.shopify.com/src/data/components.json
Labels: Contribution, polaris.shopify.com

#6983 [Typography foundations] Update `bodyLg` variant line height
  polaris-react/src/components/Text/Text.scss
Labels: #gsd:25298, typography alpha release

#6984 Update typography updates post
  polaris.shopify.com/content/updates/typography-updates/index.md
Labels: 🤖Skip Changelog, #gsd:25298, polaris.shopify.com, typography alpha release

#6985 [Typography foundations] Add `headingXs` variant
  polaris-react/src/components/Text/README.md
  polaris-react/src/components/Text/Text.scss
  polaris-react/src/components/Text/Text.tsx
  polaris.shopify.com/content/components/text/index.md
  polaris.shopify.com/pages/examples/text-heading.tsx
Labels: #gsd:25298, typography alpha release

#6993 Remove deprecation warning from annotated section
  .changeset/rude-donuts-return.md
  polaris-react/src/components/Layout/Layout.stories.tsx
  polaris-react/src/components/Layout/Layout.tsx
  polaris-react/src/components/Layout/components/AnnotatedSection/AnnotatedSection.tsx
Labels: #gsd:30116

#6915 [Typography foundations] Deprecate existing typography components on polaris.shopify.com
  .changeset/grumpy-donuts-agree.md
  polaris.shopify.com/content/components/caption/index.md
  polaris.shopify.com/content/components/display-text/index.md
  polaris.shopify.com/content/components/heading/index.md
  polaris.shopify.com/content/components/subheading/index.md
  polaris.shopify.com/content/components/text-style/index.md
  polaris.shopify.com/content/components/visually-hidden/index.md
  polaris.shopify.com/pages/components/[component].tsx
  polaris.shopify.com/pages/examples/caption-default.tsx
  polaris.shopify.com/pages/examples/display-text-extra-large.tsx
  polaris.shopify.com/pages/examples/display-text-large.tsx
  polaris.shopify.com/pages/examples/display-text-medium.tsx
  polaris.shopify.com/pages/examples/display-text-small.tsx
  polaris.shopify.com/pages/examples/heading-default.tsx
  polaris.shopify.com/pages/examples/subheading-default.tsx
  polaris.shopify.com/pages/examples/text-style-code.tsx
  polaris.shopify.com/pages/examples/text-style-negative.tsx
  polaris.shopify.com/pages/examples/text-style-positive.tsx
  polaris.shopify.com/pages/examples/text-style-strong.tsx
  polaris.shopify.com/pages/examples/text-style-subdued.tsx
  polaris.shopify.com/pages/examples/text-style-warning.tsx
  polaris.shopify.com/pages/examples/visually-hidden-default.tsx
  polaris.shopify.com/pages/examples/visually-hidden-table-headers.tsx
  polaris.shopify.com/src/data/components.json
Labels: #gsd:25298, typography beta release

#6766 Breakpoints migration guide
  documentation/guides/migrating-from-v9-to-v10.md
Labels: 🤖Skip Changelog, #gsd:25539

#7004 Fix storybook link for perf profiler
  polaris-react/scripts/profiler.js
Labels: 🤖Skip Changelog, #gsd:25464

#7015 Update Navigation column in breakpoints table
  .changeset/slimy-vans-doubt.md
  polaris.shopify.com/content/foundations/design/space/index.md
Labels: #gsd:25539

#7013 [Icon] Add IdentityCard Icon
  .changeset/spotty-boats-hide.md
  polaris-icons/icons/IdentityCardMajor.svg
  polaris-icons/icons/IdentityCardMajor.yml
Labels: Icon

#7039 Icons use curly quotes
  polaris-icons/icons/IdentityCardMajor.yml
  polaris-icons/icons/MarketsMajor.yml
Labels: 🤖Skip Changelog

#7027 [polaris.shopify.com] Add design guidance for typography
  .changeset/sweet-deers-sing.md
  polaris.shopify.com/content/foundations/design/typography/index.md
  polaris.shopify.com/public/images/foundations/design/typography/text-align-baseline@2x.png
  polaris.shopify.com/public/images/foundations/design/typography/text-bounding-box@2x.png
  polaris.shopify.com/public/images/foundations/design/typography/text-center-baseline@2x.png
  polaris.shopify.com/public/images/foundations/design/typography/text-color-different@2x.png
  polaris.shopify.com/public/images/foundations/design/typography/text-featured@2x.png
  polaris.shopify.com/public/images/foundations/design/typography/text-line-length@2x.png
  polaris.shopify.com/public/images/foundations/design/typography/text-principles@2x.png
  polaris.shopify.com/public/images/foundations/design/typography/text-spacing-adjustments@2x.png
  polaris.shopify.com/public/images/foundations/design/typography/text-tabular-numbers@2x.png
  polaris.shopify.com/public/images/foundations/design/typography/text-weight-different@2x.png
  polaris.shopify.com/public/images/foundations/design/typography/text-weights@2x.png
Labels: #gsd:25298, polaris.shopify.com, typography alpha release

#7062 [Layout foundations] Refactor `Box` without polymorphic dep
  polaris-react/package.json
  polaris-react/src/components/Box/Box.scss
  polaris-react/src/components/Box/Box.tsx
  yarn.lock
Labels: #gsd:30116

#6919 [Typography foundations] Add responsive styling for heading2xl-4xl variants on <Text>
  .changeset/brown-swans-punch.md
  .changeset/curly-llamas-bathe.md
  .changeset/hot-teachers-rule.md
  .changeset/plenty-drinks-watch.md
  .changeset/slow-timers-enjoy.md
  .changeset/violet-chicken-care.md
Labels: #gsd:25298, typography beta release
