Repository Shopify/polaris, pull requests merged in 2022-10, with the labels that each got.

#7325 Rename `AlphaCard` shadow prop
  .changeset/selfish-poets-lick.md
  polaris-react/src/components/AlphaCard/AlphaCard.stories.tsx
  polaris-react/src/components/AlphaCard/AlphaCard.tsx
  polaris.shopify.com/pages/examples/alpha-card-flat.tsx
Labels: #gsd:30116

#7326 Columns spacing
  .changeset/few-ghosts-carry.md
  polaris-react/src/components/Columns/Columns.scss
  polaris-react/src/components/Columns/Columns.stories.tsx
  polaris-react/src/components/Columns/Columns.tsx
  polaris-react/src/components/Columns/tests/Columns.test.tsx
  polaris.shopify.com/content/components/columns/index.md
  polaris.shopify.com/pages/examples/columns-default.tsx
  polaris.shopify.com/pages/examples/columns-with-free-and-fixed-widths.tsx
  polaris.shopify.com/pages/examples/columns-with-varying-spacing.tsx
Labels: #gsd:30116

#7327 Remove `margin` from `Box`
  polaris-react/src/components/Box/Box.scss
  polaris-react/src/components/Box/Box.tsx
  polaris-react/src/components/Box/tests/Box.test.tsx
  polaris.shopify.com/content/components/box/index.md
  polaris.shopify.com/pages/examples/box-with-margin.tsx
Labels: #gsd:30116

#7315 Remove migration for `0` and `0px` length values
  .changeset/dull-roses-deliver.md
  polaris-migrator/src/migrations/replace-sass-lengths/replace-sass-lengths.ts
  polaris-migrator/src/migrations/replace-sass-lengths/tests/replace-sass-lengths.output.scss
  polaris-migrator/src/migrations/replace-sass-lengths/tests/with-namespace.output.scss
Labels: #gsd:29805

#7328 Add namespace support to the `replace-static-breakpoint-mixins` migrations
  .changeset/sharp-phones-film.md
  polaris-migrator/README.md
  polaris-migrator/src/migrations/replace-static-breakpoint-mixins/replace-static-breakpoint-mixins.ts
  polaris-migrator/src/migrations/replace-static-breakpoint-mixins/tests/replace-static-breakpoint-mixins.test.ts
  polaris-migrator/src/migrations/replace-static-breakpoint-mixins/tests/with-namespace.input.scss
  polaris-migrator/src/migrations/replace-static-breakpoint-mixins/tests/with-namespace.output.scss
  polaris-migrator/src/utilities/sass.ts
Labels: #gsd:29805

#7349 Remove KonamiCode component
  polaris-react/src/components/KonamiCode/KonamiCode.tsx
  polaris-react/src/components/KonamiCode/index.ts
  polaris-react/src/components/KonamiCode/tests/KonamiCode.test.tsx
  polaris-react/src/index.ts
  polaris.shopify.com/src/data/props.json
Labels: 🤖Skip Changelog

#7216 Migrate static mixins
  .changeset/lovely-boats-relate.md
  polaris-migrator/README.md
  polaris-migrator/src/migrations/replace-static-mixins-with-declarations/replace-static-mixins-with-declarations.ts
  polaris-migrator/src/migrations/replace-static-mixins-with-declarations/tests/replace-static-mixins-with-declarations.input.scss
  polaris-migrator/src/migrations/replace-static-mixins-with-declarations/tests/replace-static-mixins-with-declarations.output.scss
  polaris-migrator/src/migrations/replace-static-mixins-with-declarations/tests/replace-static-mixins-with-declarations.test.ts
  polaris-migrator/src/migrations/replace-static-mixins-with-declarations/tests/with-namespace.input.scss
  polaris-migrator/src/migrations/replace-static-mixins-with-declarations/tests/with-namespace.output.scss
Labels: #gsd:29805

#7370 [polaris.shopify.com] Remove 'About Polaris' page
  .changeset/lucky-wolves-behave.md
  polaris.shopify.com/content/foundations/about-polaris/index.md
Labels: polaris.shopify.com

#7371 Make Polaris migrator comment generic
  .changeset/thick-crews-hope.md
  polaris-migrator/README.md
  polaris-migrator/src/constants.ts
  polaris-migrator/src/migrations/replace-sass-lengths/tests/replace-sass-lengths.output.scss
  polaris-migrator/src/migrations/replace-sass-lengths/tests/with-namespace.output.scss
  polaris-migrator/src/migrations/replace-sass-spacing/tests/replace-spacing.output.scss
  polaris-migrator/src/migrations/replace-sass-spacing/tests/with-namespace.output.scss
Labels: #gsd:29805

#7373 Add Polaris migrator utility to `getFunctionArgs`
  .changeset/five-eyes-kiss.md
  polaris-migrator/src/utilities/sass.ts
  polaris-migrator/src/utilities/tests/sass.test.ts
Labels: #gsd:29805

#7363 Add `id` prop to `Text` and `Box`
  .changeset/cyan-months-think.md
  polaris-react/src/components/Box/Box.tsx
  polaris-react/src/components/Text/Text.tsx
Labels: #gsd:30116

#7398 Getting Started update
  .changeset/bears-drink-oj-too.md
  polaris.shopify.com/content/getting-started/design.md
  polaris.shopify.com/content/getting-started/develop.md
  polaris.shopify.com/content/getting-started/index.md
  polaris.shopify.com/content/getting-started/patterns-components-and-tokens.md
  polaris.shopify.com/content/getting-started/polaris-101.md
  polaris.shopify.com/content/getting-started/shared-resources.md
  polaris.shopify.com/content/patterns/index.md
  polaris.shopify.com/public/images/foundations/patterns/components@2x.png
  polaris.shopify.com/public/images/foundations/patterns/patterns@2x.png
  polaris.shopify.com/public/images/foundations/patterns/tokens@2x.png
  polaris.shopify.com/public/images/getting-started/patterns-components-tokens/combined@2x.png
  polaris.shopify.com/public/images/getting-started/patterns-components-tokens/primitives@2x.png
  polaris.shopify.com/public/images/getting-started/polaris-101/mobile-web-admin@2x.png
Labels: polaris.shopify.com

#7396 [Layout foundations] Update `get-props` script and refactor types in `Box`
  .changeset/dry-moles-lay.md
  polaris-react/src/components/Box/Box.tsx
  polaris-react/src/components/Box/tests/Box.test.tsx
  polaris.shopify.com/scripts/get-props/src/get-props.ts
  polaris.shopify.com/src/data/props.json
Labels: #gsd:30116, polaris.shopify.com

#7432 [Box] Add support for `overflowX`, `overflowY`, and `width` props
  .changeset/kind-carrots-leave.md
  polaris-react/src/components/Box/Box.scss
  polaris-react/src/components/Box/Box.tsx
Labels: #gsd:30116

#7434 [Box] Fix reference to `width` custom property
  .changeset/dry-apples-listen.md
  polaris-react/src/components/Box/Box.tsx
Labels: #gsd:30116

#7438 Simplify `AlphaCard` by removing `hasBorderRadius` and `shadow` props
  .changeset/yellow-chairs-walk.md
  polaris-react/src/components/AlphaCard/AlphaCard.stories.tsx
  polaris-react/src/components/AlphaCard/AlphaCard.tsx
  polaris.shopify.com/content/components/alpha-card.md
  polaris.shopify.com/pages/examples/alpha-card-flat.tsx
  polaris.shopify.com/src/data/props.json
Labels: #gsd:30116

#7423 Update comment strategy for the `replace-typography-declarations`
  .changeset/loud-sheep-drive.md
  polaris-migrator/src/migrations/replace-typography-declarations/replace-typography-declarations.ts
  polaris-migrator/src/migrations/replace-typography-declarations/tests/replace-typography-declarations.input.scss
  polaris-migrator/src/migrations/replace-typography-declarations/tests/replace-typography-declarations.output.scss
  polaris-migrator/src/migrations/replace-typography-declarations/tests/with-namespace.input.scss
  polaris-migrator/src/migrations/replace-typography-declarations/tests/with-namespace.output.scss
Labels: #gsd:29805

#7450 [Box] Add support for `minHeight` and `minWidth`
  .changeset/funny-hairs-raise.md
  polaris-react/src/components/Box/Box.scss
  polaris-react/src/components/Box/Box.tsx
Labels: #gsd:30116

#7483 [Columns/Box] Add missing `children` prop back to prop type
  .changeset/large-peas-happen.md
  polaris-react/src/components/Columns/Columns.tsx
  polaris.shopify.com/src/data/props.json
Labels: #gsd:30116

#7375 Create Sass `color()` function migration
  .changeset/twenty-mayflies-fix.md
  polaris-migrator/README.md
  polaris-migrator/src/migrations/replace-sass-color/replace-sass-color.ts
  polaris-migrator/src/migrations/replace-sass-color/tests/replace-sass-color.input.scss
  polaris-migrator/src/migrations/replace-sass-color/tests/replace-sass-color.output.scss
  polaris-migrator/src/migrations/replace-sass-color/tests/replace-sass-color.test.ts
  polaris-migrator/src/migrations/replace-sass-color/tests/with-namespace.input.scss
  polaris-migrator/src/migrations/replace-sass-color/tests/with-namespace.output.scss
  polaris-migrator/src/utilities/sass.ts
Labels: #gsd:29805

#7491 [Box] Add support for `section` element type
  .changeset/odd-zebras-yell.md
  polaris-react/src/components/Box/Box.tsx
  polaris.shopify.com/src/data/props.json
Labels: #gsd:30116

#7429 Update `AlphaStack`
  .changeset/friendly-radios-sparkle.md
  polaris-react/src/components/AlphaStack/AlphaStack.scss
  polaris-react/src/components/AlphaStack/AlphaStack.stories.tsx
  polaris-react/src/components/AlphaStack/AlphaStack.tsx
  polaris-react/src/components/AlphaStack/tests/AlphaStack.test.tsx
  polaris-react/src/utilities/css.ts
  polaris-react/src/utilities/tests/css.test.ts
Labels: #gsd:30116

#7469 [Layout foundations] Update AlphaStack component docs and guidance
  .changeset/heavy-eagles-train.md
  polaris.shopify.com/content/components/alpha-stack.md
  polaris.shopify.com/pages/examples/alpha-stack-default.tsx
  polaris.shopify.com/pages/examples/alpha-stack-with-align.tsx
  polaris.shopify.com/pages/examples/alpha-stack-with-full-width-children.tsx
  polaris.shopify.com/pages/examples/alpha-stack-with-spacing.tsx
Labels: #gsd:30116

#7538 [Text] Add responsive styling to heading2xl-heading4xl variants
  .changeset/eighty-pumas-repair.md
  polaris-react/src/components/Text/Text.scss
Labels: #gsd:29805

#7560 Document faster operations for staging changes after running migrations.
  polaris-migrator/README.md
Labels: 🤖Skip Changelog

#7548 [Icon] Add cancel major
  .changeset/cyan-jars-punch.md
  polaris-icons/icons/CancelMajor.svg
  polaris-icons/icons/CancelMajor.yml
  polaris-icons/icons/CancelMinor.svg
  polaris-icons/icons/CancelMinor.yml
Labels: Icon

#7454 [Modal] Rebuild with layout primitives
  .changeset/hip-wombats-sin.md
  polaris-react/src/components/Modal/Modal.scss
  polaris-react/src/components/Modal/Modal.tsx
  polaris-react/src/components/Modal/components/Dialog/Dialog.tsx
  polaris-react/src/components/Modal/components/Footer/Footer.scss
  polaris-react/src/components/Modal/components/Footer/Footer.tsx
  polaris-react/src/components/Modal/components/Header/Header.scss
  polaris-react/src/components/Modal/components/Header/Header.tsx
  polaris-react/src/components/Modal/components/Section/Section.scss
  polaris-react/src/components/Modal/components/Section/Section.tsx
  polaris-react/src/components/Modal/tests/Modal.test.tsx
Labels: #gsd:30116

#7551 Add `stylelint-polaris/coverage` rule
  .changeset/weak-islands-wait.md
  stylelint-polaris/plugins/coverage/index.js
  stylelint-polaris/plugins/coverage/index.test.js
  stylelint-polaris/utils/index.js
Labels: #gsd:31276
