Repository Shopify/polaris, pull requests merged in 2022-05, with the labels that each got.

#5629 Replace `768px` breakpoint Sass variables with tokens
  polaris-react/UNRELEASED.md
  polaris-react/src/components/ActionMenu/components/SecondaryAction/SecondaryAction.scss
  polaris-react/src/components/DataTable/DataTable.scss
  polaris-react/src/components/Page/components/Header/Header.scss
  polaris-react/src/styles/_common.scss
Labels: #gsd:25156

#5694 Add Turborepo and common npm scripts
  .eslintrc
  .gitignore
  package.json
  polaris-for-vscode/.eslintignore
  polaris-for-vscode/package.json
  polaris-icons/package.json
  polaris-react/package.json
  polaris-tokens/package.json
  polaris.shopify.com/package.json
  stylelint-polaris/package.json
  stylelint-polaris/src/configs/coverage.js
  stylelint-polaris/src/configs/internal.js
  stylelint-polaris/src/configs/shared.js
  stylelint-polaris/src/index.js
  stylelint-polaris/src/plugins/custom-properties-allowed-list/README.md
  stylelint-polaris/src/plugins/custom-properties-allowed-list/index.js
  stylelint-polaris/src/plugins/global-disallowed-list/index.js
  stylelint-polaris/src/utils/index.js
  stylelint-polaris/tests/index.js
  stylelint-polaris/tsconfig.json
  turbo.json
  yarn.lock
Labels: 🤖Skip Changelog

#5675 Replace padding value with token
  polaris-react/UNRELEASED.md
  polaris-react/src/components/DropZone/components/FileUpload/FileUpload.scss
Labels: #gsd:25156

#5692 Move Babel config to root level for better monorepo support
  babel.config.js
  package.json
  polaris-icons/.babelrc
  polaris-icons/package.json
  polaris-icons/rollup.config.js
  polaris-react/.storybook/babel.config.js
  polaris-react/.storybook/main.js
  polaris-react/babel.config.js
  polaris-react/loom.config.ts
  polaris-react/package.json
  polaris-tokens/.babelrc
  polaris-tokens/jest.config.js
  polaris-tokens/package.json
  polaris-tokens/rollup.config.js
  polaris-tokens/tsconfig.json
  yarn.lock
Labels: 🤖Skip Changelog

#5698 Add single CI for build, test, and linting
  .eslintignore
  .eslintrc
  .github/workflows/ci-a11y-vrt.yml
  .github/workflows/ci-polaris-icons.yml
  .github/workflows/ci-polaris-react.yml
  .github/workflows/ci-polaris-tokens.yml
  .github/workflows/ci-stylelint-polaris.yml
  .github/workflows/ci.yml
  documentation/Nodejs support.md
  polaris-for-vscode/.eslintignore
  polaris-for-vscode/package.json
  polaris-react/package.json
  polaris-tokens/package.json
  polaris.shopify.com/package.json
  shipit.polaris-icons.yml
  shipit.polaris-react.yml
  shipit.polaris-tokens.yml
  shipit.stylelint-polaris.yml
  stylelint-polaris/package.json
  turbo.json
Labels: 🤖Skip Changelog

#5685 Added min-height to Popover.Pane
  polaris-react/UNRELEASED.md
  polaris-react/src/components/Popover/components/Pane/Pane.tsx
  polaris-react/src/components/Popover/components/Pane/tests/Pane.test.tsx
Labels: #gsd:23639

#5754 WIP steps in context learning
  polaris-for-vscode/server/src/tmp-tokens/allTokens.ts
  polaris-react/playground/Learner.scss
  polaris-react/playground/Learner.tsx
  polaris-react/playground/stories.tsx
  polaris-react/src/components/InContextLearning/InContextLearning.tsx
  polaris.shopify.com/src/data/guidelines.json
  stylelint-polaris/data/polaris-custom-property-names.js
  stylelint-polaris/tmp-tokens/polaris-custom-property-names.js
  stylelint-polaris/tmp-tokens/polaris-keyframe-names.js
Labels: cla-needed

#5668 v9.6.0
  polaris-react/CHANGELOG.md
  polaris-react/README.md
  polaris-react/package.json
  polaris-react/src/components/Autocomplete/Autocomplete.tsx
  polaris-react/src/components/Autocomplete/tests/Autocomplete.test.tsx
  polaris-react/src/components/Combobox/README.md
  polaris-react/src/components/Listbox/Listbox.tsx
  polaris-react/src/components/Listbox/tests/Listbox.test.tsx
  polaris-react/src/components/README.md
  polaris-react/src/index.ts
Labels: 🤖Skip Changelog, #gsd:23639

#5777 Example tooltips
  polaris-react/playground/Learner.tsx
  polaris-react/playground/learner-assets/5.png
  polaris-react/playground/learner-assets/Rectangle2464.png
  polaris-react/src/components/InContextLearning/InContextLearning.scss
Labels: cla-needed

#5786 Cache the Next.js site build in CI
  .github/workflows/ci.yml
Labels: 🤖Skip Changelog, Smarter monorepo tooling

#5720 Clean up tsconfigs to use shared @shopify/typescript-configs
  .github/workflows/publish-polaris-for-vscode.yml
  .vscode/launch.json
  polaris-for-vscode/client/tsconfig.json
  polaris-for-vscode/package.json
  polaris-for-vscode/server/tsconfig.json
  polaris-for-vscode/src/client.ts
  polaris-for-vscode/src/server.ts
  polaris-for-vscode/tsconfig.json
  polaris-icons/package.json
  polaris-react/tsconfig.json
  polaris-tokens/package.json
  polaris-tokens/tsconfig.json
  polaris.shopify.com/tsconfig.json
  stylelint-polaris/tsconfig.json
Labels: 🤖Skip Changelog

#5794 mv /src/ ../
  stylelint-polaris/configs/coverage.js
  stylelint-polaris/configs/internal.js
  stylelint-polaris/configs/shared.js
  stylelint-polaris/index.js
  stylelint-polaris/package.json
  stylelint-polaris/plugins/custom-properties-allowed-list/README.md
  stylelint-polaris/plugins/custom-properties-allowed-list/index.js
  stylelint-polaris/plugins/global-disallowed-list/index.js
  stylelint-polaris/utils/index.js
Labels: cla-needed

#5804 feat: Update experimental breakpoint values
  polaris-react/UNRELEASED.md
  polaris-react/src/tokens/token-groups/breakpoints.json
  polaris-tokens/src/token-groups/breakpoints.ts
Labels: #gsd:25539

#5722 feat: Port breakpoint/layout functions to SCSS variables
  polaris-react/UNRELEASED.md
  polaris-react/playground/DetailsPage.scss
  polaris-react/src/components/Filters/Filters.scss
  polaris-react/src/components/Frame/Frame.scss
  polaris-react/src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.scss
  polaris-react/src/components/Layout/Layout.scss
  polaris-react/src/components/Modal/Modal.scss
  polaris-react/src/components/Modal/components/Dialog/Dialog.scss
  polaris-react/src/components/Navigation/Navigation.scss
  polaris-react/src/components/Navigation/_variables.scss
  polaris-react/src/components/Page/Page.scss
  polaris-react/src/components/Page/components/Header/Header.scss
  polaris-react/src/components/SkeletonPage/SkeletonPage.scss
  polaris-react/src/components/TopBar/TopBar.scss
  polaris-react/src/components/TopBar/_variables.scss
  polaris-react/src/components/TopBar/components/Menu/Menu.scss
  polaris-react/src/components/TopBar/components/Search/Search.scss
  polaris-react/src/components/TopBar/components/UserMenu/UserMenu.scss
  polaris-react/src/styles/foundation/_layout.scss
  polaris-react/src/styles/shared/_breakpoints.scss
Labels: 🤖Skip Changelog, #gsd:25539

#5799 Clean `tsbuildinfo` and add common scripts to `polaris-for-figma`
  .eslintrc
  polaris-for-figma/package.json
  polaris-for-figma/src/tokens/tokenScript.js
  polaris-for-vscode/package.json
  polaris-tokens/package.json
  polaris.shopify.com/package.json
Labels: 🤖Skip Changelog, Smarter monorepo tooling

#5830 feat: Update experimental XL breakpoint value
  polaris-react/UNRELEASED.md
  polaris-react/src/tokens/token-groups/breakpoints.json
  polaris-tokens/src/token-groups/breakpoints.ts
Labels: #gsd:25539

#5798 [Badge] 🐛 matches `new` and `info` Pip colors with the ones in `Badge`
  polaris-react/UNRELEASED.md
  polaris-react/src/components/Badge/components/Pip/Pip.scss
  polaris-react/src/components/Badge/components/Pip/Pip.tsx
  polaris-react/src/components/Badge/tests/Badge.test.tsx
Labels: 🐛Bug

#5800 Add Changesets and GitHub Actions release workflow
  .changeset/README.md
  .changeset/config.json
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/changelog.yml
  .github/probots.yml
  .github/workflows/changelog.yml
  .github/workflows/release.yml
  README.md
  documentation/Deprecation guidelines.md
  documentation/Releasing.md
  documentation/Versioning and changelog.md
  package.json
  polaris-for-vscode/CHANGELOG.md
  polaris-react/CHANGELOG.md
  polaris-react/UNRELEASED.md
  yarn.lock
Labels: 🤖Skip Changelog

#5841 Replace deprecationNotice with notice
  polaris-react/UNRELEASED.md
  polaris-react/src/components/Sheet/README.md
  polaris.shopify.com/src/data/components.json
  polaris.shopify.com/src/pages-from-old-website/resources/graphql-api.md
Labels: #gsd:25156

#5844 Make Polaris for VS Code and Figma private to prevent publishing
  .github/workflows/changelog.yml
  polaris-for-figma/package.json
  polaris-for-vscode/package.json
Labels: 🤖Skip Changelog

#5652 Move grid globals to grid tab within addons
  polaris-react/.storybook/GridPanel/GridOverlay.css
  polaris-react/.storybook/GridPanel/GridOverlay.tsx
  polaris-react/.storybook/GridPanel/GridPanel.tsx
  polaris-react/.storybook/GridPanel/index.ts
  polaris-react/.storybook/configure.ts
  polaris-react/.storybook/main.js
  polaris-react/.storybook/manager.js
  polaris-react/.storybook/preview.js
  polaris-react/package.json
  yarn.lock
Labels: 🤖Skip Changelog

#5868 Fix storybook:build
  polaris-react/.storybook/GridOverlay/GridOverlay.css
  polaris-react/.storybook/GridOverlay/GridOverlay.tsx
  polaris-react/.storybook/GridOverlay/index.ts
  polaris-react/.storybook/GridPanel/GridPanel.tsx
  polaris-react/.storybook/manager.js
  polaris-react/.storybook/preview.js
Labels: 🤖Skip Changelog

#5871 Fix storybook manager
  polaris-react/.storybook/manager.js
Labels: 🤖Skip Changelog

#5920 Simplify changelog format
  polaris-for-figma/CHANGELOG.md
  polaris-for-figma/package.json
  polaris-for-vscode/CHANGELOG.md
  polaris-icons/CHANGELOG.md
  polaris-react/CHANGELOG.md
  polaris-tokens/CHANGELOG.md
  stylelint-polaris/CHANGELOG.md
Labels: 🤖Skip Changelog

#5785 [IndexTable] Updates to IndexTable from polaris-next version
  .changeset/wet-trainers-admire.md
  polaris-react/src/components/IndexTable/IndexTable.scss
  polaris-react/src/components/IndexTable/IndexTable.tsx
  polaris-react/src/components/IndexTable/README.md
  polaris-react/src/components/IndexTable/components/Cell/Cell.tsx
  polaris-react/src/components/IndexTable/components/Cell/tests/Cell.test.tsx
  polaris-react/src/components/IndexTable/components/Checkbox/Checkbox.scss
  polaris-react/src/components/IndexTable/components/Row/Row.tsx
  polaris-react/src/components/IndexTable/components/Row/tests/Row.test.tsx
  polaris-react/src/components/IndexTable/tests/IndexTable.test.tsx
  polaris-react/src/utilities/tests/use-index-resource-state.test.tsx
  polaris-react/src/utilities/use-index-resource-state.ts
Labels: #gsd:24858

#5874 [Modal] Allow close on `Backdrop` click or tap
  .changeset/lemon-singers-hug.md
  polaris-react/src/components/Modal/Modal.tsx
  polaris-react/src/components/Modal/README.md
  polaris-react/src/components/Modal/components/Dialog/Dialog.scss
  polaris-react/src/components/Modal/tests/Modal.test.tsx
Labels: Accessibility
