Repository Shopify/polaris, pull requests merged in 2022-04, with the labels that each got.

#5401 [Listbox] Update scroll into view logic
  polaris-react/UNRELEASED.md
  polaris-react/src/components/Listbox/Listbox.tsx
  polaris-react/src/components/Listbox/tests/Listbox.test.tsx
Labels: Multiselect, #gsd:23639

#5410 fix: Remove postinstall script from stylelint-polaris
  stylelint-polaris/README.md
  stylelint-polaris/package.json
Labels: 🤖Skip Changelog, Get admin on Polaris mainline

#5412 fix: Add @shopify/stylelint-plugin to Stylelint Polaris
  .github/workflows/ci.yml
  polaris-react/package.json
  stylelint-polaris/package.json
Labels: 🤖Skip Changelog, Get admin on Polaris mainline

#5422 feat: Move @shopify/stylelint-plugin out of @shopify/stylelint-polaris
  polaris-react/package.json
  stylelint-polaris/configs/shared.js
  stylelint-polaris/package.json
Labels: 🤖Skip Changelog, Get admin on Polaris mainline

#5418 Root-level linter configuration
  .eslintignore
  .eslintrc
  .github/workflows/ci.yml
  .gitignore
  .prettierignore
  .stylelintignore
  .stylelintrc.js
  package.json
  polaris-react/.eslintignore
  polaris-react/.gitignore
  polaris-react/.prettierignore
  polaris-react/.stylelintignore
  polaris-react/loom.config.ts
  polaris-react/package.json
  polaris.shopify.com/next.config.js
  yarn.lock
Labels: 🤖Skip Changelog

#5428 [Listbox] Fix disabled option styles not applying
  polaris-react/UNRELEASED.md
  polaris-react/src/components/Listbox/components/TextOption/TextOption.tsx
Labels: 🐛Bug

#5465 Consolidate keyframe tokens
  polaris-react/scripts/utilities/getCustomPropertyNames.js
  polaris-react/scripts/utilities/getKeyframeNames.js
  polaris-react/src/components/Backdrop/Backdrop.scss
  polaris-react/src/components/CustomProperties/styles.ts
  polaris-react/src/components/Indicator/Indicator.scss
  polaris-react/src/components/ProgressBar/ProgressBar.scss
  polaris-react/src/components/Spinner/Spinner.scss
  polaris-react/src/tokens/token-groups/beta-tokens.json
  polaris-react/src/tokens/token-groups/keyframes.json
  polaris-react/src/tokens/token-groups/motion.json
  polaris-react/src/tokens/tokens.ts
Labels: 🤖Skip Changelog

#5303 [TextField] Add support for inline autocompletion
  polaris-react/UNRELEASED.md
  polaris-react/playground/Playground.tsx
  polaris-react/src/components/Autocomplete/Autocomplete.tsx
  polaris-react/src/components/Combobox/Combobox.tsx
  polaris-react/src/components/Combobox/components/TextField/TextField.tsx
  polaris-react/src/components/Listbox/Listbox.tsx
  polaris-react/src/components/Listbox/components/Action/Action.tsx
  polaris-react/src/components/Listbox/components/Option/Option.tsx
  polaris-react/src/components/Listbox/components/TextOption/TextOption.scss
  polaris-react/src/components/Listbox/tests/Listbox.test.tsx
  polaris-react/src/components/TextField/README.md
  polaris-react/src/components/TextField/TextField.scss
  polaris-react/src/components/TextField/TextField.tsx
  polaris-react/src/components/TextField/tests/TextField.test.tsx
  polaris-react/src/styles/foundation/_focus-ring.scss
  polaris-react/src/utilities/combobox/context.tsx
  polaris-react/src/utilities/listbox/types.ts
Labels: #gsd:23639

#5392 [TextField] Add support for vertical content above input
  polaris-react/UNRELEASED.md
  polaris-react/playground/Playground.tsx
  polaris-react/src/components/Autocomplete/README.md
  polaris-react/src/components/Combobox/README.md
  polaris-react/src/components/DataTable/README.md
  polaris-react/src/components/TextField/README.md
  polaris-react/src/components/TextField/TextField.scss
  polaris-react/src/components/TextField/TextField.tsx
  polaris-react/src/components/TextField/tests/TextField.test.tsx
Labels: #gsd:23639

#5490 fix: Update opacity coverage rules
  polaris-react/src/components/Select/Select.scss
  stylelint-polaris/configs/coverage.js
Labels: 🤖Skip Changelog, #gsd:22300

#5524 Review and update .vscode directory content
  .vscode/extensions.json
  .vscode/settings.json
Labels: 🤖Skip Changelog

#5517 Update spacing tokens
  polaris-react/UNRELEASED-v10.md
  polaris-react/src/tokens/token-groups/spacing.json
Labels: 🤖Skip Changelog, #gsd:25156

#5567 [Tag] Fix styling for removable tag with link
  polaris-react/UNRELEASED.md
  polaris-react/src/components/Tag/README.md
  polaris-react/src/components/Tag/Tag.scss
Labels: #gsd:23639

#5571 [Combobox] Add support for maxHeight on popover
  polaris-react/UNRELEASED.md
  polaris-react/src/components/Combobox/Combobox.tsx
  polaris-react/src/components/Combobox/tests/Combobox.test.tsx
  polaris-react/src/components/Popover/components/Pane/Pane.tsx
  polaris-react/src/components/Popover/components/Pane/tests/Pane.test.tsx
  polaris-react/src/components/Scrollable/Scrollable.scss
  polaris-react/src/components/TextField/TextField.scss
Labels: #gsd:23639

#5581 Remove non-committable check
  .github/workflows/non-committable.yml
Labels: 🤖Skip Changelog

#5584 Combobox polish
  polaris-react/UNRELEASED.md
  polaris-react/src/components/Combobox/Combobox.tsx
  polaris-react/src/components/Combobox/README.md
  polaris-react/src/components/Combobox/tests/Combobox.test.tsx
  polaris-react/src/components/Popover/components/Pane/Pane.tsx
  polaris-react/src/components/Popover/components/Pane/tests/Pane.test.tsx
  polaris-react/src/components/TextField/TextField.scss
  polaris-tokens/scripts/toStyleSheet.js
Labels: #gsd:23639

#5590 add `--p-` prefix to token labels
  polaris-for-vscode/server/src/server.ts
Labels: #gsd:25000

#5528 Boost spacing coverage
  polaris-react/UNRELEASED.md
  polaris-react/playground/DetailsPage.scss
  polaris-react/src/components/ActionMenu/components/RollupActions/RollupActions.scss
  polaris-react/src/components/Autocomplete/components/MappedAction/MappedAction.scss
  polaris-react/src/components/Badge/Badge.scss
  polaris-react/src/components/Button/Button.scss
  polaris-react/src/components/ButtonGroup/ButtonGroup.scss
  polaris-react/src/components/CheckableButton/CheckableButton.scss
  polaris-react/src/components/ColorPicker/ColorPicker.scss
  polaris-react/src/components/DatePicker/DatePicker.scss
  polaris-react/src/components/DropZone/DropZone.scss
  polaris-react/src/components/IndexTable/IndexTable.scss
  polaris-react/src/components/Link/Link.scss
  polaris-react/src/components/MessageIndicator/MessageIndicator.scss
  polaris-react/src/components/Navigation/Navigation.scss
  polaris-react/src/components/Page/components/Header/Header.scss
  polaris-react/src/components/Popover/Popover.scss
  polaris-react/src/components/RadioButton/RadioButton.scss
  polaris-react/src/components/RangeSlider/components/DualThumb/DualThumb.scss
  polaris-react/src/components/ResourceItem/ResourceItem.scss
  polaris-react/src/components/Scrollable/Scrollable.scss
  polaris-react/src/components/SkeletonTabs/SkeletonTabs.scss
  polaris-react/src/components/Tabs/Tabs.scss
  polaris-react/src/components/TextField/TextField.scss
  polaris-react/src/components/TextStyle/TextStyle.scss
  polaris-react/src/components/TopBar/TopBar.scss
  polaris-react/src/styles/foundation/_focus-ring.scss
  polaris-react/src/styles/shared/_buttons.scss
  polaris-react/src/styles/shared/_controls.scss
  polaris-react/src/tokens/token-groups/shape.json
  polaris-tokens/token-groups/shape.ts
Labels: #gsd:25156

#5569 Mobile input field styles
  polaris-react/package.json
  polaris-react/playground/MobilePrototype.tsx
  polaris-react/playground/MobilePrototypeTextInput.scss
  polaris-react/playground/MobilePrototypeTextInput.tsx
  polaris-react/playground/stories.tsx
  polaris-react/src/components/Checkbox/Checkbox.tsx
  polaris-react/src/components/ChoiceList/ChoiceList.scss
  polaris-react/src/components/Connected/Connected.scss
  polaris-react/src/components/Label/Label.scss
  polaris-react/src/components/Layout/Layout.scss
  polaris-react/src/components/Select/Select.scss
  polaris-react/src/components/TextField/TextField.scss
  polaris-react/src/components/TextField/TextField.tsx
  polaris-react/src/utilities/breakpoints.ts
  yarn.lock
Labels: #gsd:25002

#5618 v9.5.2
  polaris-react/CHANGELOG.md
  polaris-react/README.md
  polaris-react/package.json
  polaris-react/src/components/Autocomplete/README.md
  polaris-react/src/components/Badge/components/Pip/Pip.scss
  polaris-react/src/components/Badge/components/Pip/Pip.tsx
  polaris-react/src/components/Combobox/README.md
  polaris-react/src/components/README.md
Labels: 🤖Skip Changelog

#5624 [Combobox] Add height to loading example
  polaris-react/UNRELEASED.md
  polaris-react/src/components/Combobox/README.md
Labels: #gsd:23639

#5641 Remove duplicated file extension in GitHub Action for `publish-polaris-for-vscode`
  .github/workflows/publish-polaris-for-vscode.yml
Labels: cla-needed

#5621 Tokens, port vscode and stylelint to polaris-tokens rc.6
  .eslintignore
  .gitignore
  .prettierignore
  .stylelintignore
  package.json
  polaris-for-vscode/package.json
  polaris-for-vscode/scripts/prepublish.js
  polaris-for-vscode/server/src/server.ts
  polaris-react/scripts/utilities/getCustomPropertyNames.js
  polaris-react/scripts/utilities/getKeyframeNames.js
  polaris.shopify.com/package.json
  stylelint-polaris/configs/internal.js
  stylelint-polaris/index.js
  stylelint-polaris/package.json
  stylelint-polaris/scripts/gen-polaris-data.js
Labels: 🤖Skip Changelog

#5667 [Listbox] Add `autoSelection` prop
  polaris-react/UNRELEASED.md
  polaris-react/src/components/Autocomplete/Autocomplete.tsx
  polaris-react/src/components/Autocomplete/tests/Autocomplete.test.tsx
  polaris-react/src/components/Combobox/README.md
  polaris-react/src/components/Listbox/Listbox.tsx
  polaris-react/src/components/Listbox/tests/Listbox.test.tsx
  polaris-react/src/index.ts
Labels: #gsd:23639

#5661 Update yarn.lock and newly caught linting, type check, a11y, and component errors
  .eslintrc
  .stylelintrc.js
  polaris-icons/package.json
  polaris-react/UNRELEASED.md
  polaris-react/package.json
  polaris-react/src/components/AppProvider/AppProvider.tsx
  polaris-react/src/components/Collapsible/Collapsible.tsx
  polaris-react/src/components/Collapsible/tests/Collapsible.test.tsx
  polaris-react/src/components/ColorPicker/ColorPicker.tsx
  polaris-react/src/components/CustomProperties/CustomProperties.tsx
  polaris-react/src/components/IndexTable/IndexTable.tsx
  polaris-react/src/utilities/debounce.ts
  polaris-react/tests/setup/matchers/index.ts
  stylelint-polaris/plugins/custom-properties-allowed-list/index.js
  stylelint-polaris/plugins/global-disallowed-list/index.js
  stylelint-polaris/tests/index.js
  yarn.lock
Labels: 🤖Skip Changelog, #gsd:25007
