Repository Shopify/polaris, pull requests merged in 2023-09, with the labels that each got.

#10284 [IndexFiltering] Set focus default to true
  .changeset/chilled-otters-sing.md
  polaris-react/src/components/IndexFilters/IndexFilters.tsx
Labels: Contribution, Component, 2023

#10355 Revert "Fix action list filtering to accept components"
  .changeset/grumpy-llamas-divide.md
  polaris-react/src/components/ActionList/ActionList.tsx
  polaris-react/src/components/ActionList/tests/text-content.test.tsx
  polaris-react/src/components/ActionList/utils/text-content.ts
Labels: 🤖Skip Changelog

#10290 Add multi-theme support to Polaris
  .changeset/cool-insects-wonder.md
  polaris-react/src/components/AppProvider/AppProvider.tsx
  polaris-react/src/index.ts
  polaris-react/src/utilities/use-theme.ts
  polaris-tokens/package.json
  polaris-tokens/scripts/index.ts
  polaris-tokens/scripts/toJSON.ts
  polaris-tokens/scripts/toMediaConditions.ts
  polaris-tokens/scripts/toStyleSheet.ts
  polaris-tokens/scripts/toTokenValues.ts
  polaris-tokens/scripts/toValues.ts
  polaris-tokens/src/index.ts
  polaris-tokens/src/metadata.ts
  polaris-tokens/src/themes/base.ts
  polaris-tokens/src/themes/constants.ts
  polaris-tokens/src/themes/index.ts
  polaris-tokens/src/themes/light-uplift.ts
  polaris-tokens/src/themes/light.ts
  polaris-tokens/src/themes/types.ts
  polaris-tokens/src/themes/utils.ts
  polaris-tokens/src/token-groups/color.ts
  polaris-tokens/src/token-groups/font.ts
  polaris-tokens/src/token-groups/motion.ts
  polaris-tokens/src/token-groups/shadow.ts
  polaris-tokens/src/types.ts
  polaris-tokens/src/utilities.ts
  polaris-tokens/tests/toStyleSheet.test.js
  yarn.lock
Labels: Tokens, #gsd:36565

#10418 Add private primitive `size` token scale
  .changeset/modern-lobsters-cheer.md
  polaris-tokens/src/size.ts
Labels: #gsd:36565

#10432 Add public primitive `border-radius` token scale
  .changeset/five-cameras-deny.md
  polaris-tokens/src/token-groups/border.ts
Labels: #gsd:36565

#10453 Add private primitive `size` tokens
  polaris-tokens/src/size.ts
Labels: 🤖Skip Changelog, #gsd:36565

#10456 Add private primitive `space` token
  polaris-tokens/src/token-groups/space.ts
Labels: 🤖Skip Changelog, #gsd:36565

#10428 [IndexFilters] Fix layout shift when going from between default and filtering modes
  .changeset/forty-dolphins-love.md
  polaris-react/src/components/Filters/components/SearchField/SearchField.scss
  polaris-react/src/components/IndexFilters/IndexFilters.scss
  polaris-react/src/components/IndexFilters/IndexFilters.tsx
Labels: Contribution, Component, 2023

#10429 [Filters] Fix vanishing applied filters bug
  .changeset/beige-jeans-scream.md
  polaris-react/src/components/Filters/Filters.tsx
  polaris-react/src/components/Filters/tests/Filters.test.tsx
Labels: Contribution, Component, 2023

#10462 Add public primitive `line-height` token scale
  .changeset/fuzzy-mails-judge.md
  polaris-tokens/src/token-groups/font.ts
Labels: #gsd:36565

#10434 Add public primitive and semantic `border-width` token scales
  .changeset/sour-turkeys-switch.md
  polaris-tokens/src/token-groups/border.ts
Labels: #gsd:36565

#10473 [TOC] Fix bug to render TOC on section content pages
  polaris.shopify.com/content/tools/polaris-for-vscode.md
  polaris.shopify.com/content/tools/polaris-migrator.md
  polaris.shopify.com/content/tools/stylelint-polaris.md
  polaris.shopify.com/pages/[...slug].tsx
Labels: #gsd:36550

#10464 Update `polaris-tokens` tests
  polaris-tokens/tests/toStyleSheet.test.js
Labels: 🤖Skip Changelog, #gsd:36565

#10460 Add public primitive `width` token scale
  .changeset/twelve-radios-stare.md
  polaris-for-vscode/src/server.ts
  polaris-tokens/src/index.ts
  polaris-tokens/src/themes/base.ts
  polaris-tokens/src/token-groups/width.ts
Labels: #gsd:36565

#10482 Move `token-groups` to `themes/base` directory
  polaris-tokens/src/index.ts
  polaris-tokens/src/themes/base.ts
  polaris-tokens/src/themes/base/border.ts
  polaris-tokens/src/themes/base/breakpoints.ts
  polaris-tokens/src/themes/base/color.ts
  polaris-tokens/src/themes/base/font.ts
  polaris-tokens/src/themes/base/height.ts
  polaris-tokens/src/themes/base/index.ts
  polaris-tokens/src/themes/base/motion.ts
  polaris-tokens/src/themes/base/shadow.ts
  polaris-tokens/src/themes/base/space.ts
  polaris-tokens/src/themes/base/width.ts
  polaris-tokens/src/themes/base/zIndex.ts
  polaris-tokens/src/utilities.ts
  polaris.shopify.com/pages/api/tokens/v0/index.tsx
Labels: 🤖Skip Changelog, #gsd:36565

#10480 [GitHub Workflows] Update next on push to main
  .github/workflows/merge-main-into-next.yml
Labels: #gsd:36579

#10485 Update public primitive `base` and `light-uplift` theme scales
  .changeset/tasty-ducks-punch.md
  polaris-tokens/src/themes/base/border.ts
  polaris-tokens/src/themes/base/font.ts
  polaris-tokens/src/themes/base/space.ts
  polaris-tokens/src/themes/light-uplift.ts
  polaris-tokens/src/utilities.ts
Labels: #gsd:36565

#10465 Update private primitive `colors`
  .changeset/chatty-dryers-sneeze.md
  polaris-tokens/src/colors-experimental.ts
  polaris-tokens/src/themes/base/color.ts
  polaris-tokens/src/themes/light-uplift.ts
Labels: #gsd:36565

#10507 [Sandbox] Mock Frame functions in the Sandbox to avoid hard failures
  polaris.shopify.com/playroom/FrameComponent.tsx
Labels: 🤖Skip Changelog

#10542 [Docs] Update Table of Contents
  polaris.shopify.com/content/design/colors.md
  polaris.shopify.com/content/design/data-visualizations.md
  polaris.shopify.com/src/components/Page/Page.module.scss
  polaris.shopify.com/src/components/TOC/TOC.module.scss
  polaris.shopify.com/src/components/TOC/TOC.tsx
Labels: #gsd:36550

#10562 [Docs] Update StatusBadge
  polaris.shopify.com/src/components/StatusBadge/StatusBadge.module.scss
  polaris.shopify.com/src/components/StatusBadge/StatusBadge.tsx
  polaris.shopify.com/src/utils/various.ts
Labels: #gsd:36550

#10477 Update semantic `color` tokens
  .changeset/hip-gorillas-sparkle.md
  polaris-tokens/src/themes/base/color.ts
  polaris-tokens/src/themes/light-uplift.ts
Labels: #gsd:36565

#10338 [Coming soon][View Transitions API] Initial prototype
  polaris.shopify.com/content/coming-soon/index.md
  polaris.shopify.com/content/coming-soon/view-transitions.md
  polaris.shopify.com/content/patterns/app-settings-layout/variants/default.md
  polaris.shopify.com/content/patterns/resource-details-layout/variants/default.md
  polaris.shopify.com/content/patterns/resource-index-layout/variants/default.md
  polaris.shopify.com/next.config.js
  polaris.shopify.com/pages/_app.tsx
  polaris.shopify.com/src/components/ComponentExamples/ComponentExamples.tsx
  polaris.shopify.com/src/components/ExampleWrapper/ExampleWrapper.module.scss
  polaris.shopify.com/src/components/ExampleWrapper/ExampleWrapper.tsx
  polaris.shopify.com/src/components/ExampleWrapper/LinkButton/LinkButton.module.scss
  polaris.shopify.com/src/components/ExampleWrapper/LinkButton/LinkButton.tsx
  polaris.shopify.com/src/components/Icon/Icon.module.scss
  polaris.shopify.com/src/components/Page/Page.module.scss
  polaris.shopify.com/src/components/PatternsExample/PatternsExample.module.scss
  polaris.shopify.com/src/components/PatternsExample/PatternsExample.tsx
  polaris.shopify.com/src/components/ViewTransition/ViewTransition.jsx
  polaris.shopify.com/src/components/ViewTransition/index.ts
  polaris.shopify.com/src/styles/globals.scss
  polaris.shopify.com/src/utils/various.ts
Labels: 🤖Skip Changelog, polaris.shopify.com, 🧪 Experiment

#10577 Sophie/merge main again
  .changeset/hip-gorillas-sparkle.md
  .changeset/three-trains-tie.md
  polaris-react/src/components/ActionList/tests/ActionList.test.tsx
  polaris-react/src/components/ButtonGroup/ButtonGroup.scss
  polaris-react/src/components/Filters/Filters.tsx
  polaris-react/src/components/Filters/tests/Filters.test.tsx
  polaris-react/src/components/IndexFilters/IndexFilters.stories.tsx
  polaris-tokens/src/themes/base/color.ts
  polaris-tokens/src/themes/light-uplift.ts
Labels: cla-needed

#10593 Remove `featured` item from `What's New`
  polaris.shopify.com/content/whats-new/uplifting-shopify-polaris.md
Labels: #gsd:36550

#10423 [next] Add multi-theme support to Polaris
  polaris-react/.storybook/preview.js
  polaris-react/src/components/AppProvider/AppProvider.scss
  polaris-react/src/components/AppProvider/AppProvider.tsx
  polaris-tokens/scripts/toStyleSheet.ts
  polaris-tokens/src/index.ts
  polaris-tokens/src/themes/base/border.ts
  polaris-tokens/src/themes/base/color.ts
  polaris-tokens/src/themes/base/font.ts
  polaris-tokens/src/themes/base/motion.ts
  polaris-tokens/src/themes/base/shadow.ts
  polaris-tokens/src/themes/base/space.ts
  polaris-tokens/src/themes/constants.ts
  polaris-tokens/src/themes/index.ts
  polaris-tokens/src/themes/light-high-contrast.ts
  polaris-tokens/src/themes/light-uplift.ts
  polaris-tokens/src/themes/utils.ts
Labels: #gsd:36565

#10079 [Docs] Clarify why Grid#areas is deprecated
  polaris-react/src/components/Grid/Grid.tsx
  polaris-react/src/components/Grid/components/Cell/Cell.tsx
  polaris.shopify.com/src/components/StatusBadge/StatusBadge.module.scss
Labels: 🤖Skip Changelog

#10605 [polaris.shopify.com] Fix preview for color tokens
  .changeset/silly-years-search.md
  polaris.shopify.com/src/components/TokenList/TokenList.tsx
Labels: Bug, polaris.shopify.com

#10570 [Docs] Refactor TOC
  polaris.shopify.com/src/components/TOC/TOC.module.scss
  polaris.shopify.com/src/components/TOC/TOC.tsx
Labels: #gsd:36550

#10600 Add public primitive and semantic `shadow` token scale
  .changeset/light-cherries-compare.md
  polaris-tokens/src/themes/base/shadow.ts
Labels: #gsd:36565

#10635 [AppProvider] Consolidate se23 logic
  .changeset/short-kids-buy.md
  polaris-react/.storybook/preview.js
  polaris-react/src/components/AppProvider/AppProvider.stories.tsx
  polaris-react/src/components/AppProvider/AppProvider.tsx
  polaris-react/src/components/Frame/Frame.stories.tsx
  polaris-react/src/components/IndexTable/IndexTable.scss
  polaris-react/src/components/Pagination/tests/Pagination.test.tsx
  polaris-react/src/components/PolarisTestProvider/PolarisTestProvider.tsx
  polaris-react/src/styles/_common.scss
  polaris-react/src/utilities/features/types.ts
  polaris-react/tests/utilities/react-testing.tsx
Labels: #gsd:36579

#10643 Add semantic `space` token scale
  .changeset/sweet-toes-divide.md
  polaris-tokens/src/themes/base/space.ts
Labels: #gsd:36565

#10647 Add composite `text` and `font-letter-spacing` tokens
  .changeset/breezy-peas-type.md
  .changeset/spotty-owls-brake.md
  polaris-for-vscode/src/server.ts
  polaris-tokens/src/themes/base/font.ts
  polaris-tokens/src/themes/base/index.ts
  polaris-tokens/src/themes/base/text.ts
Labels: #gsd:36565

#10663 [Page] Revert page action disabling when in IndexFilter's filter mode
  .changeset/kind-lemons-jump.md
  polaris-react/src/components/Page/components/Header/Header.tsx
  polaris-react/src/components/Page/components/Header/tests/Header.test.tsx
Labels: Bug, Component, P0

#10665 [Modal] Only announce toast messages if frame context exists
  .changeset/brave-ties-pay.md
  polaris-react/src/components/Modal/components/Dialog/Dialog.tsx
Labels: Bug, Component, P1

#10684 Add documentation for Frame/Toast/Modal a11y improvements
  polaris.shopify.com/content/components/feedback-indicators/toast.md
  polaris.shopify.com/content/components/overlays/modal.md
Labels: 🤖Skip Changelog

#10703 Add `resolveMetaThemeRefs` util to `metadata`
  polaris-tokens/src/metadata.ts
Labels: 🤖Skip Changelog

#10713 [ExceptionList] Manually migrate `color` custom properties for v11 to v12
  polaris-react/src/components/ExceptionList/ExceptionList.scss
Labels: #gsd:36565

#10714 [InlineError] Manually migrate `color` custom properties for v11 to v12
  polaris-react/src/components/InlineError/InlineError.scss
Labels: #gsd:36565

#10715 [TopBar] Manually migrate `color` custom properties for v11 to v12
  polaris-react/src/components/TopBar/components/SearchField/SearchField.scss
Labels: 🤖Skip Changelog, #gsd:36565

#10725 Add CODEOWNERS
  .github/CODEOWNERS
Labels: 🤖Skip Changelog

#10734 Revert "[Filters] Fix hitting max call depth when appliedFilters is undefined"
  .changeset/seven-apricots-provide.md
  polaris-react/src/components/Filters/Filters.tsx
Labels: 🤖Skip Changelog

#10673 Update `font` token values
  .changeset/twenty-bags-mate.md
  polaris-tokens/src/themes/base/font.ts
Labels: #gsd:36565

#10722 [Icon] Add support for `emphasis` and `text` tones and migrated `color` custom properties
  .changeset/five-cooks-fly.md
  polaris-react/src/components/Icon/Icon.scss
  polaris-react/src/components/Icon/Icon.stories.tsx
  polaris-react/src/components/Icon/Icon.tsx
Labels: #gsd:36565

#10712 Fix `untriaged-labeler` workflow
  .github/workflows/untriaged-labeler.yml
Labels: Bug

#10759 Revert "[IndexFilters] Add Edit Columns optional button"
  .changeset/strange-bananas-obey.md
  polaris-react/locales/cs.json
  polaris-react/locales/da.json
  polaris-react/locales/de.json
  polaris-react/locales/en.json
  polaris-react/locales/es.json
  polaris-react/locales/fi.json
  polaris-react/locales/fr.json
  polaris-react/locales/it.json
  polaris-react/locales/ja.json
  polaris-react/locales/ko.json
  polaris-react/locales/nb.json
  polaris-react/locales/nl.json
  polaris-react/locales/pl.json
  polaris-react/locales/pt-BR.json
  polaris-react/locales/pt-PT.json
  polaris-react/locales/sv.json
  polaris-react/locales/th.json
  polaris-react/locales/tr.json
  polaris-react/locales/vi.json
  polaris-react/locales/zh-CN.json
  polaris-react/locales/zh-TW.json
  polaris-react/src/components/IndexFilters/IndexFilters.stories.tsx
  polaris-react/src/components/IndexFilters/IndexFilters.tsx
  polaris-react/src/components/IndexFilters/components/EditColumnsButton/EditColumnsButton.tsx
  polaris-react/src/components/IndexFilters/components/EditColumnsButton/index.ts
  polaris-react/src/components/IndexFilters/components/index.ts
  polaris-react/src/components/IndexFilters/tests/IndexFilters.test.tsx
  polaris-react/src/components/Tabs/Tabs.stories.tsx
  polaris-react/src/components/Tabs/components/Tab/Tab.tsx
  polaris-react/src/components/Tabs/components/Tab/tests/Tab.test.tsx
  polaris-react/src/components/Tabs/types.ts
  polaris.shopify.com/content/components/tables/index-table.md
  polaris.shopify.com/pages/examples/index-filters-with-edit-colums-button.tsx
Labels: 🤖Skip Changelog

#10762 Migrate `font` custom properties from v11 to v12
  .changeset/empty-baboons-rule.md
  documentation/guides/legacy-polaris-v8-public-api.scss
  polaris-react/playground/DetailsPage.scss
  polaris-react/src/components/AppProvider/AppProvider.scss
  polaris-react/src/components/Avatar/Avatar.scss
  polaris-react/src/components/Button/Button.scss
  polaris-react/src/components/CheckableButton/CheckableButton.scss
  polaris-react/src/components/DatePicker/DatePicker.scss
  polaris-react/src/components/DropZone/components/FileUpload/FileUpload.scss
  polaris-react/src/components/Filters/Filters.scss
  polaris-react/src/components/IndexFilters/components/SortButton/components/DirectionButton/DirectionButton.scss
  polaris-react/src/components/IndexTable/IndexTable.scss
  polaris-react/src/components/KeyboardKey/KeyboardKey.scss
  polaris-react/src/components/Layout/Layout.scss
  polaris-react/src/components/LegacyCard/LegacyCard.scss
  polaris-react/src/components/MediaCard/MediaCard.scss
  polaris-react/src/components/Navigation/Navigation.scss
  polaris-react/src/components/Navigation/_variables.scss
  polaris-react/src/components/Page/components/Header/components/Title/Title.scss
  polaris-react/src/components/Popover/Popover.stories.tsx
  polaris-react/src/components/Select/Select.scss
  polaris-react/src/components/SelectAllActions/SelectAllActions.scss
  polaris-react/src/components/SkeletonPage/SkeletonPage.scss
  polaris-react/src/components/Tabs/Tabs.scss
  polaris-react/src/components/Tag/Tag.scss
  polaris-react/src/components/Text/Text.scss
  polaris-react/src/components/TextField/TextField.scss
  polaris-react/src/components/TopBar/components/UserMenu/UserMenu.scss
  polaris-react/src/styles/shared/_controls.scss
  polaris-react/src/styles/shared/_typography.scss
  polaris.shopify.com/pages/examples/popover-with-searchable-listbox.tsx
  polaris.shopify.com/src/components/TOC/TOC.module.scss
  polaris.shopify.com/src/styles/globals.scss
Labels: #gsd:36565

#10771 [Text] Remove `headingXs` and `heading4xl` and migrate usage
  polaris-react/src/components/Avatar/Avatar.stories.tsx
  polaris-react/src/components/Badge/Badge.stories.tsx
  polaris-react/src/components/Divider/Divider.stories.tsx
  polaris-react/src/components/Listbox/components/Header/Header.tsx
  polaris-react/src/components/Listbox/components/Header/tests/Header.test.tsx
  polaris-react/src/components/OptionList/OptionList.tsx
  polaris-react/src/components/RangeSlider/components/DualThumb/DualThumb.tsx
  polaris-react/src/components/RangeSlider/components/SingleThumb/SingleThumb.tsx
  polaris-react/src/components/Sheet/Sheet.stories.tsx
  polaris-react/src/components/Text/Text.scss
  polaris-react/src/components/Text/Text.stories.tsx
  polaris-react/src/components/Text/Text.tsx
  polaris-react/src/components/Text/tests/Text.test.tsx
  polaris.shopify.com/content/components/deprecated/display-text.md
  polaris.shopify.com/content/components/deprecated/subheading.md
  polaris.shopify.com/content/components/typography/text.md
  polaris.shopify.com/content/design/typography.md
  polaris.shopify.com/pages/examples/divider-with-border-color.tsx
  polaris.shopify.com/pages/examples/legacy-card-with-custom-react-node-title.tsx
  polaris.shopify.com/pages/examples/sheet-with-searchable-listbox.tsx
  polaris.shopify.com/pages/examples/text-heading.tsx
Labels: #gsd:36573, #gsd:36565

#10300 Token migration guidance
  polaris.shopify.com/content/version-guides/migrating-from-v11-to-v12.md
Labels: 🤖Skip Changelog, Tokens, #gsd:36565

#10305 Create migration for replacing v11 `space` custom properties
  .changeset/short-llamas-hope.md
  polaris-migrator/src/migrations/v12-styles-replace-custom-property-space/tests/transform.test.ts
  polaris-migrator/src/migrations/v12-styles-replace-custom-property-space/tests/v12-styles-replace-custom-property-space.input.scss
  polaris-migrator/src/migrations/v12-styles-replace-custom-property-space/tests/v12-styles-replace-custom-property-space.output.scss
  polaris-migrator/src/migrations/v12-styles-replace-custom-property-space/transform.ts
Labels: Tokens, #gsd:36565

#10304 Create migration for replacing v11 `font` custom properties
  .changeset/hungry-bikes-impress.md
  polaris-migrator/src/migrations/v12-styles-replace-custom-property-font/tests/step1.input.scss
  polaris-migrator/src/migrations/v12-styles-replace-custom-property-font/tests/step1.output.scss
  polaris-migrator/src/migrations/v12-styles-replace-custom-property-font/tests/step2.input.scss
  polaris-migrator/src/migrations/v12-styles-replace-custom-property-font/tests/step2.output.scss
  polaris-migrator/src/migrations/v12-styles-replace-custom-property-font/tests/step3.input.scss
  polaris-migrator/src/migrations/v12-styles-replace-custom-property-font/tests/step3.output.scss
  polaris-migrator/src/migrations/v12-styles-replace-custom-property-font/tests/step4.input.scss
  polaris-migrator/src/migrations/v12-styles-replace-custom-property-font/tests/step4.output.scss
  polaris-migrator/src/migrations/v12-styles-replace-custom-property-font/tests/transform.test.ts
  polaris-migrator/src/migrations/v12-styles-replace-custom-property-font/transform.ts
Labels: Tokens, #gsd:36565

#10774 `Navigation` color updates
  polaris-react/src/components/Navigation/Navigation.scss
  polaris-react/src/components/Navigation/_variables.scss
Labels: #gsd:36565

#10793 [Docs] Document `Text` heading variants removal in migration guide
  polaris.shopify.com/content/version-guides/migrating-from-v11-to-v12.md
Labels: #gsd:36550, #gsd:36573
