Repository Shopify/polaris, pull requests merged in 2023-01, with the labels that each got.

#7958 [Layout] Rebuild `OptionList` with layout primitives
  .changeset/slimy-years-tie.md
  polaris-react/src/components/OptionList/OptionList.scss
  polaris-react/src/components/OptionList/OptionList.tsx
  polaris-react/src/components/OptionList/components/Option/Option.scss
Labels: #gsd:30116

#7954 Update `stylelint-polaris` config to address out of memory issues
  .changeset/nervous-bats-switch.md
  stylelint-polaris/index.js
Labels: #gsd:31276

#7963 [Layout] `AlphaStack` update docs for `align` prop
  .changeset/loud-onions-check.md
  polaris-react/src/components/AlphaStack/AlphaStack.tsx
  polaris.shopify.com/content/components/alpha-stack.md
  polaris.shopify.com/src/data/props.json
Labels: #gsd:30116

#7988 [ChoiceList] Fix children spacing
  .changeset/afraid-zoos-build.md
  polaris-react/src/components/ChoiceList/ChoiceList.stories.tsx
  polaris-react/src/components/ChoiceList/ChoiceList.tsx
Labels: #gsd:30116

#7997 Update `styles-tokenize-font` migration to ignore `@font-face` at-rules
  .changeset/famous-years-destroy.md
  polaris-migrator/src/migrations/styles-tokenize-font/styles-tokenize-font.ts
  polaris-migrator/src/migrations/styles-tokenize-font/tests/styles-tokenize-font.input.scss
  polaris-migrator/src/migrations/styles-tokenize-font/tests/styles-tokenize-font.output.scss
Labels: #gsd:31276

#8007 Remove extraneous disable comments
  polaris-react/src/components/ActionList/ActionList.scss
  polaris-react/src/components/Autocomplete/components/MappedAction/MappedAction.scss
  polaris-react/src/components/Banner/Banner.scss
  polaris-react/src/components/CheckableButton/CheckableButton.scss
  polaris-react/src/components/DropZone/components/FileUpload/FileUpload.scss
  polaris-react/src/components/Frame/Frame.scss
  polaris-react/src/components/Link/Link.scss
  polaris-react/src/components/RangeSlider/components/DualThumb/DualThumb.scss
  polaris-react/src/components/RangeSlider/components/SingleThumb/SingleThumb.scss
  polaris-react/src/components/SkeletonBodyText/SkeletonBodyText.scss
  polaris-react/src/components/SkeletonDisplayText/SkeletonDisplayText.scss
  polaris-react/src/components/SkeletonPage/SkeletonPage.scss
  polaris-react/src/components/SkeletonThumbnail/SkeletonThumbnail.scss
  polaris-react/src/components/Tag/Tag.scss
  polaris-react/src/components/TextStyle/TextStyle.scss
  polaris-react/src/components/Tooltip/components/TooltipOverlay/TooltipOverlay.scss
  polaris-react/src/components/TopBar/TopBar.scss
  polaris-react/src/components/TopBar/components/Menu/Menu.scss
  polaris-react/src/styles/shared/_buttons.scss
Labels: 🤖Skip Changelog

#7783 Update `react-replace-text-components` migration
  .changeset/hot-bugs-tease.md
  polaris-migrator/src/migrate.ts
  polaris-migrator/src/migrations/react-replace-text-components/steps/replace-display-text.ts
  polaris-migrator/src/migrations/react-replace-text-components/steps/replace-other.ts
  polaris-migrator/src/migrations/react-replace-text-components/steps/replace-text-style.ts
  polaris-migrator/src/migrations/react-replace-text-components/tests/react-replace-text-components.input.tsx
  polaris-migrator/src/migrations/react-replace-text-components/tests/react-replace-text-components.output.tsx
  polaris-migrator/src/migrations/react-replace-text-components/tests/react-replace-text-components.test.ts
  polaris-migrator/src/migrations/react-replace-text-components/tests/remove-imports-all.input.tsx
  polaris-migrator/src/migrations/react-replace-text-components/tests/remove-imports-all.output.tsx
  polaris-migrator/src/migrations/react-replace-text-components/tests/remove-imports-partial-identifier.input.tsx
  polaris-migrator/src/migrations/react-replace-text-components/tests/remove-imports-partial-identifier.output.tsx
  polaris-migrator/src/migrations/react-replace-text-components/tests/remove-imports-partial-props-invalid.input.tsx
  polaris-migrator/src/migrations/react-replace-text-components/tests/remove-imports-partial-props-invalid.output.tsx
  polaris-migrator/src/migrations/react-replace-text-components/tests/remove-imports-partial-props-type.input.tsx
  polaris-migrator/src/migrations/react-replace-text-components/tests/remove-imports-partial-props-type.output.tsx
  polaris-migrator/src/migrations/react-replace-text-components/tests/with-identifier.input.tsx
  polaris-migrator/src/migrations/react-replace-text-components/tests/with-identifier.output.tsx
  polaris-migrator/src/migrations/react-replace-text-components/tests/with-other-component-and-other-component-props.input.tsx
  polaris-migrator/src/migrations/react-replace-text-components/tests/with-other-component-and-other-component-props.output.tsx
  polaris-migrator/src/migrations/react-replace-text-components/tests/with-relative-display-text.input.tsx
  polaris-migrator/src/migrations/react-replace-text-components/tests/with-relative-display-text.output.tsx
  polaris-migrator/src/migrations/react-replace-text-components/tests/with-relative-other-component-and-other-component-props.input.tsx
  polaris-migrator/src/migrations/react-replace-text-components/tests/with-relative-other-component-and-other-component-props.output.tsx
  polaris-migrator/src/migrations/react-replace-text-components/tests/with-relative-text-style-props.input.tsx
  polaris-migrator/src/migrations/react-replace-text-components/tests/with-relative-text-style-props.output.tsx
  polaris-migrator/src/migrations/react-replace-text-components/tests/with-relative.input.tsx
  polaris-migrator/src/migrations/react-replace-text-components/tests/with-relative.output.tsx
  polaris-migrator/src/migrations/react-replace-text-components/tests/with-text-style-props.input.tsx
  polaris-migrator/src/migrations/react-replace-text-components/tests/with-text-style-props.output.tsx
  polaris-migrator/src/utilities/imports.ts
  polaris-migrator/src/utilities/jsx.ts
  polaris-migrator/src/utilities/type-guards.ts
  polaris-migrator/tsconfig.json
Labels: #gsd:29805

#8048 Fix deprecated sheet message
  polaris-react/src/components/Sheet/Sheet.tsx
Labels: 🤖Skip Changelog

#8030 [Layout foundations] Adjust size and position of title and body in SkeletonPage to closer match Page
  .changeset/fluffy-hotels-explain.md
  polaris-react/src/components/SkeletonPage/SkeletonPage.tsx
Labels: #gsd:30116

#8074 Use next.js standalone builds
  package.json
  polaris.shopify.com/next.config.js
  polaris.shopify.com/package.json
  yarn.lock
Labels: 🤖Skip Changelog

#8054 [Focus states] Use :focus-visible over :focus for focus-ring state.
  .changeset/pink-students-compare.md
  polaris-react/src/components/ActionList/ActionList.scss
  polaris-react/src/components/Autocomplete/components/MappedAction/MappedAction.scss
  polaris-react/src/components/Banner/Banner.scss
  polaris-react/src/components/Breadcrumbs/Breadcrumbs.scss
  polaris-react/src/components/Button/Button.scss
  polaris-react/src/components/Checkbox/Checkbox.scss
  polaris-react/src/components/Checkbox/Checkbox.tsx
  polaris-react/src/components/Checkbox/tests/Checkbox.test.tsx
  polaris-react/src/components/DataTable/DataTable.scss
  polaris-react/src/components/DatePicker/DatePicker.scss
  polaris-react/src/components/Filters/Filters.scss
  polaris-react/src/components/Modal/components/CloseButton/CloseButton.scss
  polaris-react/src/components/Navigation/Navigation.scss
  polaris-react/src/components/Navigation/Navigation.stories.tsx
  polaris-react/src/components/Navigation/_variables.scss
  polaris-react/src/components/Navigation/components/Item/Item.tsx
  polaris-react/src/components/Navigation/components/Item/tests/Item.test.tsx
  polaris-react/src/components/OptionList/components/Checkbox/Checkbox.scss
  polaris-react/src/components/OptionList/components/Checkbox/Checkbox.tsx
  polaris-react/src/components/OptionList/components/Checkbox/tests/Checkbox.test.tsx
  polaris-react/src/components/OptionList/components/Option/Option.scss
  polaris-react/src/components/RadioButton/RadioButton.scss
  polaris-react/src/components/RadioButton/RadioButton.tsx
  polaris-react/src/components/RadioButton/tests/RadioButton.test.tsx
  polaris-react/src/components/RangeSlider/components/DualThumb/DualThumb.scss
  polaris-react/src/components/Select/Select.scss
  polaris-react/src/components/SelectAllActions/SelectAllActions.scss
  polaris-react/src/components/Tabs/Tabs.scss
  polaris-react/src/components/Tag/Tag.scss
  polaris-react/src/components/TextField/TextField.scss
  polaris-react/src/components/TopBar/TopBar.scss
  polaris-react/src/components/TopBar/components/Menu/Menu.scss
  polaris-react/src/components/TopBar/components/SearchField/SearchField.scss
  polaris-react/src/styles/shared/_buttons.scss
Labels: Contribution, Engineering

#8063 [Icon] New icon <diamond_alert_minor>
  .changeset/unlucky-tools-greet.md
  polaris-icons/icons/DiamondAlertMinor.svg
  polaris-icons/icons/DiamondAlertMinor.yml
Labels: Figma UI Kit

#8086 Update Stylelint rules list content
  polaris.shopify.com/content/tools/stylelint-polaris/index.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/index.md
Labels: 🤖Skip Changelog

#8087 Add Polaris migrator and sandbox to tools
  polaris-migrator/README.md
  polaris.shopify.com/content/getting-started/index.md
  polaris.shopify.com/content/tools/index.md
  polaris.shopify.com/content/tools/polaris-for-vscode.md
  polaris.shopify.com/content/tools/polaris-migrator.md
  polaris.shopify.com/content/tools/sandbox.md
  polaris.shopify.com/content/tools/stylelint-polaris/index.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/colors-at-rule-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/colors-color-named.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/colors-color-no-hex.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/colors-declaration-property-value-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/colors-function-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/colors-global-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/conventions-custom-property-allowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/depth-declaration-property-unit-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/depth-function-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/depth-global-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/depth-property-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/layout-at-rule-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/layout-declaration-property-value-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/layout-function-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/layout-global-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/layout-property-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/legacy-at-rule-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/legacy-function-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/legacy-global-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/media-queries-at-rule-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/media-queries-function-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/media-queries-media-queries-allowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/motion-at-rule-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/motion-declaration-property-unit-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/motion-function-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/motion-global-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/shape-at-rule-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/shape-declaration-property-unit-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/shape-function-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/shape-global-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/spacing-declaration-property-unit-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/spacing-function-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/spacing-global-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/typography-at-rule-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/typography-declaration-property-unit-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/typography-declaration-property-value-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/typography-function-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/typography-global-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/z-index-declaration-property-value-allowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/z-index-function-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/z-index-global-disallowed-list.md
  polaris.shopify.com/src/components/HomePage/HomePage.tsx
  polaris.shopify.com/src/utils/foundations.ts
Labels: 🤖Skip Changelog, #gsd:31276

#8118 Update best practice for nav component
  polaris.shopify.com/content/components/navigation.md
Labels: 🤖Skip Changelog, Documentation

#8119 Bump size limit
  package.json
Labels: 🤖Skip Changelog

#8111 7937/mobile fixes
  polaris.shopify.com/content/patterns/date-picking.ts
  polaris.shopify.com/package.json
  polaris.shopify.com/src/components/ExampleWrapper/ExampleWrapper.module.scss
  polaris.shopify.com/src/components/Markdown/Markdown.tsx
  polaris.shopify.com/src/components/PatternPage/Blocks.tsx
  polaris.shopify.com/src/components/PatternPage/PatternPage.module.scss
  polaris.shopify.com/src/components/PatternPage/PatternPage.tsx
  polaris.shopify.com/src/components/PatternsDatePickingPage/PatternsDatePickingPage.tsx
  polaris.shopify.com/src/components/PatternsExample/PatternsExample.module.scss
  polaris.shopify.com/src/styles/variables.scss
  yarn.lock
Labels: 🤖Skip Changelog

#8083 [ResourceList] Add headerContent prop for customizing header on ResourceList
  .changeset/great-eyes-cheer.md
  polaris-react/src/components/ResourceList/ResourceList.stories.tsx
  polaris-react/src/components/ResourceList/ResourceList.tsx
  polaris-react/src/components/ResourceList/tests/ResourceList.test.tsx
Labels: cla-needed

#8154 update related components logic in pattern page to pull from data-structure
  polaris.shopify.com/content/patterns/app-settings-layout.ts
  polaris.shopify.com/content/patterns/date-picking.ts
  polaris.shopify.com/src/components/PatternPage/PatternPage.tsx
  polaris.shopify.com/src/components/PatternsExample/PatternsExample.tsx
Labels: 🤖Skip Changelog, #gsd30559, Engineering

#8155 8061/resource index layout
  polaris.shopify.com/content/patterns/resource-index-layout.md
  polaris.shopify.com/content/patterns/resource-index-layout.ts
  polaris.shopify.com/pages/patterns/resource-index-layout.tsx
  polaris.shopify.com/public/images/patterns/resource-index-cover-image.png
  polaris.shopify.com/public/images/patterns/resource-index-pattern-usage-1.png
  polaris.shopify.com/public/images/patterns/resource-index-pattern-usage-2.png
  polaris.shopify.com/public/images/patterns/resource-index-pattern-usage-3.png
  polaris.shopify.com/src/components/ExampleWrapper/ExampleWrapper.module.scss
  polaris.shopify.com/src/components/PatternPage/PatternPage.module.scss
Labels: 🤖Skip Changelog

#8168 Ignore needless disables for the Stylelint Polaris layout category
  .changeset/tidy-laws-sit.md
  stylelint-polaris/index.js
  stylelint-polaris/plugins/coverage/index.js
  stylelint-polaris/plugins/coverage/index.test.js
Labels: #gsd:31276

#8160 Update image assets for patterns page
  polaris.shopify.com/content/patterns/app-settings-layout.ts
  polaris.shopify.com/content/patterns/resource-index-layout.ts
  polaris.shopify.com/public/images/patterns/app-settings-cover-image.png
  polaris.shopify.com/public/images/patterns/app-settings-usage-1.png
  polaris.shopify.com/public/images/patterns/app-settings-usage-2.png
  polaris.shopify.com/public/images/patterns/app-settings-usage-3.png
  polaris.shopify.com/public/images/patterns/date-list-cover-image.png
  polaris.shopify.com/public/images/patterns/date-list-usage-1.png
  polaris.shopify.com/public/images/patterns/date-list-usage-2.png
  polaris.shopify.com/public/images/patterns/date-list-usage-3.png
  polaris.shopify.com/public/images/patterns/date-range-cover-image.png
  polaris.shopify.com/public/images/patterns/date-range-usage-1.png
  polaris.shopify.com/public/images/patterns/date-range-usage-2.png
  polaris.shopify.com/public/images/patterns/date-range-usage-3.png
  polaris.shopify.com/public/images/patterns/resource-detail-cover-image.png
  polaris.shopify.com/public/images/patterns/resource-detail-usage-1.png
  polaris.shopify.com/public/images/patterns/resource-detail-usage-2.png
  polaris.shopify.com/public/images/patterns/resource-detail-usage-3.png
  polaris.shopify.com/public/images/patterns/resource-detail-usage-4.png
  polaris.shopify.com/public/images/patterns/resource-detail-usage-5.png
  polaris.shopify.com/public/images/patterns/resource-index-cover-image.png
  polaris.shopify.com/public/images/patterns/resource-index-pattern-usage-1.png
  polaris.shopify.com/public/images/patterns/resource-index-pattern-usage-2.png
  polaris.shopify.com/public/images/patterns/resource-index-pattern-usage-3.png
  polaris.shopify.com/public/images/patterns/resource-index-usage-1.png
  polaris.shopify.com/public/images/patterns/resource-index-usage-2.png
  polaris.shopify.com/public/images/patterns/resource-index-usage-3.png
  polaris.shopify.com/public/images/patterns/single-list-cover-image.png
  polaris.shopify.com/public/images/patterns/single-list-usage-1.png
  polaris.shopify.com/public/images/patterns/single-list-usage-2.png
Labels: 🤖Skip Changelog, #gsd30559, Engineering

#8156 8062/resource details layout
  polaris.shopify.com/content/patterns/resource-details-layout.md
  polaris.shopify.com/content/patterns/resource-details-layout.ts
  polaris.shopify.com/pages/patterns/[...slug].tsx
  polaris.shopify.com/pages/patterns/resource-details-layout.tsx
Labels: 🤖Skip Changelog

#8187 Remove `beta` status from `Text`
  .changeset/nasty-suns-hang.md
  polaris.shopify.com/content/components/text.md
Labels: v11.0.0

#8189 [Polaris Lighthouse] Remove legacy rules from index page
  polaris.shopify.com/pages/tools/stylelint-polaris/rules/index.tsx
Labels: #gsd:31276

#8184 Remove deprecated typography components
  .changeset/real-lemons-sniff.md
  polaris-react/src/components/Caption/Caption.scss
  polaris-react/src/components/Caption/Caption.stories.tsx
  polaris-react/src/components/Caption/Caption.tsx
  polaris-react/src/components/Caption/index.ts
  polaris-react/src/components/Caption/tests/Caption.test.tsx
  polaris-react/src/components/DisplayText/DisplayText.scss
  polaris-react/src/components/DisplayText/DisplayText.stories.tsx
  polaris-react/src/components/DisplayText/DisplayText.tsx
  polaris-react/src/components/DisplayText/index.ts
  polaris-react/src/components/DisplayText/tests/DisplayText.test.tsx
  polaris-react/src/components/Heading/Heading.scss
  polaris-react/src/components/Heading/Heading.stories.tsx
  polaris-react/src/components/Heading/Heading.tsx
  polaris-react/src/components/Heading/index.ts
  polaris-react/src/components/Heading/tests/Heading.test.tsx
  polaris-react/src/components/Subheading/Subheading.scss
  polaris-react/src/components/Subheading/Subheading.stories.tsx
  polaris-react/src/components/Subheading/Subheading.tsx
  polaris-react/src/components/Subheading/index.ts
  polaris-react/src/components/Subheading/tests/Subheading.test.tsx
  polaris-react/src/components/TextStyle/TextStyle.scss
  polaris-react/src/components/TextStyle/TextStyle.stories.tsx
  polaris-react/src/components/TextStyle/TextStyle.tsx
  polaris-react/src/components/TextStyle/index.ts
  polaris-react/src/components/TextStyle/tests/TextStyle.test.tsx
  polaris-react/src/components/VisuallyHidden/VisuallyHidden.scss
  polaris-react/src/components/VisuallyHidden/VisuallyHidden.stories.tsx
  polaris-react/src/components/VisuallyHidden/VisuallyHidden.tsx
  polaris-react/src/components/VisuallyHidden/index.ts
  polaris-react/src/index.ts
  polaris.shopify.com/content/components/caption.md
  polaris.shopify.com/content/components/display-text.md
  polaris.shopify.com/content/components/heading.md
  polaris.shopify.com/content/components/subheading.md
  polaris.shopify.com/content/components/text-style.md
  polaris.shopify.com/content/components/visually-hidden.md
  polaris.shopify.com/public/images/components/caption.png
  polaris.shopify.com/public/images/components/display-text.png
  polaris.shopify.com/public/images/components/heading.png
  polaris.shopify.com/public/images/components/subheading.png
  polaris.shopify.com/public/images/components/text-style.png
  polaris.shopify.com/public/images/components/visually-hidden.png
  polaris.shopify.com/src/data/props.json
Labels: v11.0.0

#8159 [Icons] Add Rows2Major icon
  .changeset/quick-pets-protect.md
  polaris-icons/icons/Rows2Major.svg
  polaris-icons/icons/Rows2Major.yml
Labels: Contribution, Icon

#8200 1/x Bump build dependencies
  package.json
  polaris-icons/rollup.config.mjs
  polaris-migrator/package.json
  polaris-migrator/rollup.config.mjs
  polaris-react/package.json
  polaris-react/rollup.config.mjs
  polaris-tokens/rollup.config.mjs
  yarn.lock
Labels: 🤖Skip Changelog

#7999 [Layout] Popover
  .changeset/thin-apricots-admire.md
  polaris-react/src/components/Popover/Popover.scss
  polaris-react/src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx
  polaris-react/src/components/Popover/components/Section/Section.tsx
Labels: #gsd:30116

#8224 [Checkbox] Repair broken indeterminate + disabled state
  .changeset/nine-turkeys-explode.md
  polaris-react/src/components/Checkbox/Checkbox.scss
  polaris-react/src/components/Checkbox/Checkbox.stories.tsx
Labels: Bug, cla-needed, Contribution, Engineering
