Repository Shopify/polaris, pull requests merged in 2023-03, with the labels that each got.

#8538 Remove unused devDependencies
  polaris-react/package.json
  yarn.lock
Labels: 🤖Skip Changelog

#8530 [Layout foundations] Remove alignment defaults from Inline and AlphaStack
  .changeset/fuzzy-dryers-tan.md
  polaris-react/src/components/AlphaStack/AlphaStack.stories.tsx
  polaris-react/src/components/AlphaStack/AlphaStack.tsx
  polaris-react/src/components/AlphaStack/tests/AlphaStack.test.tsx
  polaris-react/src/components/Inline/Inline.stories.tsx
  polaris-react/src/components/Inline/Inline.tsx
  polaris-react/src/components/Inline/tests/Inline.test.tsx
  polaris-react/src/components/Modal/Modal.tsx
  polaris-react/src/components/Modal/components/Header/Header.tsx
Labels: #gsd:30116

#8540 Fixes ActionList css
  .changeset/flat-masks-sniff.md
  polaris-react/src/components/ActionList/ActionList.scss
  polaris-react/src/components/ActionList/components/Item/Item.tsx
Labels: Bug, Contribution, Community

#8554 fix/erroneous deprecation
  polaris.shopify.com/content/patterns-legacy/loading.md
  polaris.shopify.com/content/patterns-legacy/new-badge.md
  polaris.shopify.com/content/patterns-legacy/pickers.md
  polaris.shopify.com/content/patterns-legacy/text-fields.md
Labels: 🤖Skip Changelog

#8556 [Layout foundations] Deprecate Stack and subcomponents
  .changeset/nice-points-confess.md
  polaris-react/src/components/Stack/Stack.tsx
  polaris-react/src/components/Stack/components/Item/Item.tsx
  polaris-react/src/components/Stack/tests/Stack.test.tsx
  polaris.shopify.com/content/components/deprecated/stack.md
  polaris.shopify.com/next.config.js
  polaris.shopify.com/public/images/components/deprecated/stack.png
Labels: #gsd:30116

#8559 Improve trustworthy experience value
  .changeset/shiny-taxis-smell.md
  polaris.shopify.com/content/foundations/experience-values.md
Labels: 2023

#8545 Rebuild DropZone so it accesses ref.current instead of querySelector
  .changeset/sharp-feet-bake.md
  polaris-react/src/components/DropZone/DropZone.tsx
  polaris-react/src/components/DropZone/utils/index.ts
Labels: v11.0.0

#8573 [polaris.shopify.com] Fix component lifecycle url in alpha banners
  .changeset/tough-mugs-greet.md
  polaris.shopify.com/content/components/deprecated/index.md
  polaris.shopify.com/content/components/layout-and-structure/alpha-card.md
  polaris.shopify.com/content/components/layout-and-structure/alpha-stack.md
  polaris.shopify.com/content/components/layout-and-structure/bleed.md
  polaris.shopify.com/content/components/layout-and-structure/box.md
  polaris.shopify.com/content/components/layout-and-structure/columns.md
  polaris.shopify.com/content/components/layout-and-structure/divider.md
  polaris.shopify.com/content/components/layout-and-structure/inline.md
  polaris.shopify.com/content/components/typography/text.md
Labels: #gsd:30116, polaris.shopify.com

#8585 [polaris.shopify.com] Fix pattern examples
  polaris.shopify.com/content/patterns/app-settings-layout/variants/default.md
  polaris.shopify.com/content/patterns/date-picking/variants/date-range.md
Labels: 🤖Skip Changelog

#8396 Replace useUniqueId with useId
  polaris-react/src/components/AppProvider/AppProvider.tsx
  polaris-react/src/components/Checkbox/Checkbox.tsx
  polaris-react/src/components/Checkbox/tests/Checkbox.test.tsx
  polaris-react/src/components/ChoiceList/ChoiceList.tsx
  polaris-react/src/components/Combobox/components/TextField/TextField.tsx
  polaris-react/src/components/DropZone/DropZone.tsx
  polaris-react/src/components/FormLayout/components/Group/Group.tsx
  polaris-react/src/components/Listbox/Listbox.tsx
  polaris-react/src/components/Listbox/components/Option/Option.tsx
  polaris-react/src/components/Listbox/components/Section/Section.tsx
  polaris-react/src/components/Modal/Modal.tsx
  polaris-react/src/components/Navigation/components/Item/Item.tsx
  polaris-react/src/components/Navigation/components/Item/components/Secondary/Secondary.tsx
  polaris-react/src/components/Navigation/components/Item/components/Secondary/tests/Secondary.test.tsx
  polaris-react/src/components/Navigation/components/Item/tests/Item.test.tsx
  polaris-react/src/components/Navigation/components/Section/Section.tsx
  polaris-react/src/components/OptionList/OptionList.tsx
  polaris-react/src/components/OptionList/components/Checkbox/Checkbox.tsx
  polaris-react/src/components/PolarisTestProvider/PolarisTestProvider.tsx
  polaris-react/src/components/Popover/Popover.tsx
  polaris-react/src/components/Popover/tests/Popover.test.tsx
  polaris-react/src/components/Portal/Portal.tsx
  polaris-react/src/components/Portal/tests/Portal.test.tsx
  polaris-react/src/components/RadioButton/RadioButton.tsx
  polaris-react/src/components/RangeSlider/RangeSlider.tsx
  polaris-react/src/components/ResourceItem/ResourceItem.tsx
  polaris-react/src/components/Scrollable/components/ScrollTo/ScrollTo.tsx
  polaris-react/src/components/Select/Select.tsx
  polaris-react/src/components/SettingToggle/SettingToggle.tsx
  polaris-react/src/components/TextField/TextField.tsx
  polaris-react/src/components/TextField/tests/TextField.test.tsx
  polaris-react/src/components/Toast/Toast.tsx
  polaris-react/src/components/Tooltip/Tooltip.tsx
  polaris-react/src/components/TopBar/components/SearchField/SearchField.tsx
  polaris-react/src/utilities/focus-manager/hooks.ts
  polaris-react/src/utilities/focus-manager/tests/hooks.test.tsx
  polaris-react/src/utilities/unique-id/context.ts
  polaris-react/src/utilities/unique-id/hooks.ts
  polaris-react/src/utilities/unique-id/index.ts
  polaris-react/src/utilities/unique-id/tests/hooks.test.tsx
  polaris-react/src/utilities/unique-id/tests/unique-id-factory.test.ts
  polaris-react/src/utilities/unique-id/unique-id-factory.ts
Labels: v11.0.0

#8625 [patterns] add dividers and tighten spacing on app-settings-layout-example
  polaris.shopify.com/content/patterns/app-settings-layout/variants/default.md
Labels: 🤖Skip Changelog

#8614 [polaris.shopify.com] Add best practices for Text, AlphaStack, and AlphaCard
  .changeset/sharp-keys-march.md
  polaris.shopify.com/content/components/layout-and-structure/alpha-card.md
  polaris.shopify.com/content/components/layout-and-structure/alpha-stack.md
  polaris.shopify.com/content/components/typography/text.md
Labels: #gsd:30116, polaris.shopify.com

#8631 [Layout foundations] Mark layout components beta
  .changeset/tender-humans-cough.md
  polaris.shopify.com/content/components/layout-and-structure/bleed.md
  polaris.shopify.com/content/components/layout-and-structure/box.md
  polaris.shopify.com/content/components/layout-and-structure/card.md
  polaris.shopify.com/content/components/layout-and-structure/columns.md
  polaris.shopify.com/content/components/layout-and-structure/divider.md
  polaris.shopify.com/content/components/layout-and-structure/inline.md
  polaris.shopify.com/content/components/layout-and-structure/stack.md
Labels: #gsd:30116, v11.0.0

#8650 [SkeletonPage] Deprecate breadcrumbs, add backAction, update layout
  .changeset/curly-parrots-sit.md
  polaris-react/src/components/SkeletonPage/SkeletonPage.stories.tsx
  polaris-react/src/components/SkeletonPage/SkeletonPage.tsx
  polaris-react/src/components/SkeletonPage/tests/SkeletonPage.test.tsx
Labels: #gsd:30116

#8666 Remove needless Stylelint disables
  polaris-react/src/components/Autocomplete/components/MappedOption/MappedOption.scss
  polaris-react/src/components/Button/Button.scss
  polaris-react/src/components/Page/components/Header/components/Title/Title.scss
  polaris-react/src/components/RangeSlider/components/SingleThumb/SingleThumb.scss
  polaris-react/src/components/TextStyle/TextStyle.scss
Labels: 🤖Skip Changelog

#8604 Add `shadow` token page to doc site
  .changeset/lucky-mugs-fold.md
  polaris.shopify.com/pages/tokens/shadow.tsx
  polaris.shopify.com/src/components/TokensPage/TokensPage.module.scss
  polaris.shopify.com/src/components/TokensPage/TokensPage.tsx
Labels: v11.0.0

#8272 Create migrations for replacing legacy v11 custom properties
  .changeset/ten-drinks-refuse.md
  polaris-migrator/src/migrations/v11-styles-replace-custom-property-border/tests/v11-styles-replace-custom-property-border.input.scss
  polaris-migrator/src/migrations/v11-styles-replace-custom-property-border/tests/v11-styles-replace-custom-property-border.output.scss
  polaris-migrator/src/migrations/v11-styles-replace-custom-property-border/tests/v11-styles-replace-custom-property-border.test.ts
  polaris-migrator/src/migrations/v11-styles-replace-custom-property-border/v11-styles-replace-custom-property-border.ts
  polaris-migrator/src/migrations/v11-styles-replace-custom-property-depth/tests/v11-styles-replace-custom-property-depth.input.scss
  polaris-migrator/src/migrations/v11-styles-replace-custom-property-depth/tests/v11-styles-replace-custom-property-depth.output.scss
  polaris-migrator/src/migrations/v11-styles-replace-custom-property-depth/tests/v11-styles-replace-custom-property-depth.test.ts
  polaris-migrator/src/migrations/v11-styles-replace-custom-property-depth/v11-styles-replace-custom-property-depth.ts
  polaris-migrator/src/migrations/v11-styles-replace-custom-property-legacy/tests/v11-styles-replace-custom-property-legacy.input.scss
  polaris-migrator/src/migrations/v11-styles-replace-custom-property-legacy/tests/v11-styles-replace-custom-property-legacy.output.scss
  polaris-migrator/src/migrations/v11-styles-replace-custom-property-legacy/tests/v11-styles-replace-custom-property-legacy.test.ts
  polaris-migrator/src/migrations/v11-styles-replace-custom-property-legacy/v11-styles-replace-custom-property-legacy.ts
  polaris-migrator/src/migrations/v11-styles-replace-custom-property-zindex/tests/v11-styles-replace-custom-property-zindex.input.scss
  polaris-migrator/src/migrations/v11-styles-replace-custom-property-zindex/tests/v11-styles-replace-custom-property-zindex.output.scss
  polaris-migrator/src/migrations/v11-styles-replace-custom-property-zindex/tests/v11-styles-replace-custom-property-zindex.test.ts
  polaris-migrator/src/migrations/v11-styles-replace-custom-property-zindex/v11-styles-replace-custom-property-zindex.ts
  polaris-migrator/src/migrations/v9-styles-replace-custom-property-border/tests/v9-styles-replace-custom-property-border.input.scss
  polaris-migrator/src/migrations/v9-styles-replace-custom-property-border/tests/v9-styles-replace-custom-property-border.output.scss
  polaris-migrator/src/migrations/v9-styles-replace-custom-property-border/tests/v9-styles-replace-custom-property-border.test.ts
  polaris-migrator/src/migrations/v9-styles-replace-custom-property-border/v9-styles-replace-custom-property-border.ts
  polaris-migrator/src/migrations/v9-styles-replace-custom-property-depth/tests/v9-styles-replace-custom-property-depth.input.scss
  polaris-migrator/src/migrations/v9-styles-replace-custom-property-depth/tests/v9-styles-replace-custom-property-depth.output.scss
  polaris-migrator/src/migrations/v9-styles-replace-custom-property-depth/tests/v9-styles-replace-custom-property-depth.test.ts
  polaris-migrator/src/migrations/v9-styles-replace-custom-property-depth/v9-styles-replace-custom-property-depth.ts
  polaris-migrator/src/migrations/v9-styles-replace-custom-property-font/tests/v9-styles-replace-custom-property-font.input.scss
  polaris-migrator/src/migrations/v9-styles-replace-custom-property-font/tests/v9-styles-replace-custom-property-font.output.scss
  polaris-migrator/src/migrations/v9-styles-replace-custom-property-font/tests/v9-styles-replace-custom-property-font.test.ts
  polaris-migrator/src/migrations/v9-styles-replace-custom-property-font/v9-styles-replace-custom-property-font.ts
  polaris-migrator/src/migrations/v9-styles-replace-custom-property-legacy/tests/v9-styles-replace-custom-property-legacy.input.scss
  polaris-migrator/src/migrations/v9-styles-replace-custom-property-legacy/tests/v9-styles-replace-custom-property-legacy.output.scss
  polaris-migrator/src/migrations/v9-styles-replace-custom-property-legacy/tests/v9-styles-replace-custom-property-legacy.test.ts
  polaris-migrator/src/migrations/v9-styles-replace-custom-property-legacy/v9-styles-replace-custom-property-legacy.ts
  polaris-migrator/src/migrations/v9-styles-replace-custom-property-motion/tests/v9-styles-replace-custom-property-motion.input.scss
  polaris-migrator/src/migrations/v9-styles-replace-custom-property-motion/tests/v9-styles-replace-custom-property-motion.output.scss
  polaris-migrator/src/migrations/v9-styles-replace-custom-property-motion/tests/v9-styles-replace-custom-property-motion.test.ts
  polaris-migrator/src/migrations/v9-styles-replace-custom-property-motion/v9-styles-replace-custom-property-motion.ts
  polaris.shopify.com/content/tools/polaris-migrator.md
Labels: v11.0.0

#8664 [Layout foundations] Fix responsive gap on AlphaStack
  .changeset/tender-sloths-shop.md
  polaris-react/src/components/AlphaStack/AlphaStack.scss
Labels: #gsd:30116

#8668 [Layout foundations] Columns use responsive-props
  polaris-react/src/components/Columns/Columns.scss
Labels: 🤖Skip Changelog

#8685 [polaris.shopify.com] Fix local GA custom events
  polaris.shopify.com/src/components/GlobalSearch/GlobalSearch.tsx
Labels: 🤖Skip Changelog

#8663 [Layout foundations] Stack fix gap
  polaris-react/src/components/Stack/Stack.scss
Labels: 🤖Skip Changelog, #gsd:30116

#8680 Make SideBySide markdown component available across docs site
  .changeset/three-owls-listen.md
  polaris.shopify.com/src/components/Markdown/Markdown.module.scss
  polaris.shopify.com/src/components/Markdown/Markdown.tsx
  polaris.shopify.com/src/components/Markdown/components/index.tsx
  polaris.shopify.com/src/components/Markdown/components/styles.module.scss
  polaris.shopify.com/src/components/PatternPage/PatternPage.module.scss
  polaris.shopify.com/src/components/PatternPage/PatternPage.tsx
Labels: polaris.shopify.com

#8682 [LegacyTabs|LegacyFilters] Add legacy versions of Tabs and Filters
  .changeset/great-frogs-fry.md
  package.json
  polaris-react/src/components/LegacyFilters/LegacyFilters.scss
  polaris-react/src/components/LegacyFilters/LegacyFilters.stories.tsx
  polaris-react/src/components/LegacyFilters/LegacyFilters.tsx
  polaris-react/src/components/LegacyFilters/components/ConnectedFilterControl/ConnectedFilterControl.scss
  polaris-react/src/components/LegacyFilters/components/ConnectedFilterControl/ConnectedFilterControl.tsx
  polaris-react/src/components/LegacyFilters/components/ConnectedFilterControl/components/Item/Item.tsx
  polaris-react/src/components/LegacyFilters/components/ConnectedFilterControl/components/Item/index.ts
  polaris-react/src/components/LegacyFilters/components/ConnectedFilterControl/components/Item/tests/Item.test.tsx
  polaris-react/src/components/LegacyFilters/components/ConnectedFilterControl/components/index.ts
  polaris-react/src/components/LegacyFilters/components/ConnectedFilterControl/index.ts
  polaris-react/src/components/LegacyFilters/components/ConnectedFilterControl/tests/ConnectedFilterControl.test.tsx
  polaris-react/src/components/LegacyFilters/components/TagsWrapper/TagsWrapper.tsx
  polaris-react/src/components/LegacyFilters/components/TagsWrapper/index.ts
  polaris-react/src/components/LegacyFilters/components/TagsWrapper/tests/TagsWrapper.test.tsx
  polaris-react/src/components/LegacyFilters/components/index.ts
  polaris-react/src/components/LegacyFilters/index.ts
  polaris-react/src/components/LegacyFilters/tests/LegacyFilters.test.tsx
  polaris-react/src/components/LegacyTabs/LegacyTabs.scss
  polaris-react/src/components/LegacyTabs/LegacyTabs.stories.tsx
  polaris-react/src/components/LegacyTabs/LegacyTabs.tsx
  polaris-react/src/components/LegacyTabs/components/Item/Item.tsx
  polaris-react/src/components/LegacyTabs/components/Item/index.ts
  polaris-react/src/components/LegacyTabs/components/Item/tests/Item.test.tsx
  polaris-react/src/components/LegacyTabs/components/List/List.tsx
  polaris-react/src/components/LegacyTabs/components/List/index.ts
  polaris-react/src/components/LegacyTabs/components/List/tests/List.test.tsx
  polaris-react/src/components/LegacyTabs/components/Panel/Panel.tsx
  polaris-react/src/components/LegacyTabs/components/Panel/index.ts
  polaris-react/src/components/LegacyTabs/components/Panel/tests/Panel.test.tsx
  polaris-react/src/components/LegacyTabs/components/Tab/Tab.tsx
  polaris-react/src/components/LegacyTabs/components/Tab/index.ts
  polaris-react/src/components/LegacyTabs/components/Tab/tests/Tab.test.tsx
  polaris-react/src/components/LegacyTabs/components/TabMeasurer/TabMeasurer.tsx
  polaris-react/src/components/LegacyTabs/components/TabMeasurer/index.ts
  polaris-react/src/components/LegacyTabs/components/TabMeasurer/tests/TabMeasurer.test.tsx
  polaris-react/src/components/LegacyTabs/components/index.ts
  polaris-react/src/components/LegacyTabs/index.ts
  polaris-react/src/components/LegacyTabs/tests/LegacyTabs.test.tsx
  polaris-react/src/components/LegacyTabs/types.ts
  polaris-react/src/components/LegacyTabs/utilities.ts
  polaris-react/src/index.ts
  polaris.shopify.com/content/components/navigation/legacy-tabs.md
  polaris.shopify.com/content/components/selection-and-input/legacy-filters.md
  polaris.shopify.com/pages/examples/legacy-filters-disabled.tsx
  polaris.shopify.com/pages/examples/legacy-filters-some-disabled.tsx
  polaris.shopify.com/pages/examples/legacy-filters-with-a-data-table.tsx
  polaris.shopify.com/pages/examples/legacy-filters-with-a-resource-list.tsx
  polaris.shopify.com/pages/examples/legacy-filters-with-children-content.tsx
  polaris.shopify.com/pages/examples/legacy-filters-with-help-text.tsx
  polaris.shopify.com/pages/examples/legacy-filters-with-query-field-disabled.tsx
  polaris.shopify.com/pages/examples/legacy-filters-with-query-field-hidden.tsx
  polaris.shopify.com/pages/examples/legacy-filters-without-clear-button.tsx
  polaris.shopify.com/pages/examples/legacy-tabs-default.tsx
  polaris.shopify.com/pages/examples/legacy-tabs-fitted.tsx
  polaris.shopify.com/pages/examples/legacy-tabs-with-badge-content.tsx
  polaris.shopify.com/pages/examples/legacy-tabs-with-custom-disclosure.tsx
  polaris.shopify.com/public/images/components/navigation/legacy-tabs.png
  polaris.shopify.com/public/images/components/selection-and-input/legacy-filters.png
Labels: v11.0.0

#8697 [polaris.shopify.com] Update Legacy guidelines in component lifecycle page
  polaris.shopify.com/content/getting-started/components-lifecycle.md
Labels: 🤖Skip Changelog, #gsd:30116

#8547 [SettingToggle] UX improvements
  .changeset/nine-ghosts-reflect.md
  polaris-react/src/components/SettingToggle/SettingToggle.stories.tsx
  polaris-react/src/components/SettingToggle/SettingToggle.tsx
  polaris-react/src/components/SettingToggle/tests/SettingToggle.test.tsx
  polaris.shopify.com/content/components/actions/account-connection.md
  polaris.shopify.com/content/components/actions/setting-toggle.md
  polaris.shopify.com/content/components/selection-and-input/checkbox.md
  polaris.shopify.com/content/components/selection-and-input/setting-toggle.md
  polaris.shopify.com/content/content/accessible-and-inclusive-language.md
  polaris.shopify.com/next.config.js
  polaris.shopify.com/pages/examples/setting-toggle-default.tsx
  polaris.shopify.com/pages/examples/setting-toggle-deprecated.tsx
  polaris.shopify.com/pages/examples/setting-toggle-with-primitive-components.tsx
  polaris.shopify.com/public/images/components/actions/setting-toggle.png
  polaris.shopify.com/public/images/components/selection-and-input/setting-toggle.png
  polaris.shopify.com/public/images/components/selection-and-input/setting-toggle/Do.png
  polaris.shopify.com/public/images/components/selection-and-input/setting-toggle/Dont.png
Labels: Contribution, Component, 2023

#8740 [Tooltip][persistOnClick] Fix conditionals
  .changeset/quick-buttons-promise.md
  polaris-react/src/components/Tooltip/Tooltip.tsx
  polaris.shopify.com/content/components/overlays/tooltip.md
  polaris.shopify.com/pages/examples/tooltip-with-persistence-on-click.tsx
Labels: Bug

#8767 [Navigation] Fix item selected border radius
  .changeset/old-dots-tan.md
  polaris-react/playground/DetailsPage.tsx
  polaris-react/src/components/Navigation/Navigation.scss
Labels: 🤖Skip Comment Check

#8718 Add new `Layout` design page
  .changeset/few-pianos-join.md
  polaris.shopify.com/content/design/layout.md
  polaris.shopify.com/public/images/foundations/design/layout/default-spacing@2x.png
  polaris.shopify.com/public/images/foundations/design/layout/example1.png
  polaris.shopify.com/public/images/foundations/design/layout/example2.png
  polaris.shopify.com/public/images/foundations/design/layout/example3.png
  polaris.shopify.com/public/images/foundations/design/layout/layout-banner.png
  polaris.shopify.com/public/images/foundations/design/layout/outside-borders@2x.png
  polaris.shopify.com/public/images/foundations/design/layout/single-purpose-composible-flexible@2x.png
  polaris.shopify.com/public/images/foundations/design/layout/tokens@2x.png
Labels: #gsd:30116

#8781 Update `Layout` page example 2 link and icon
  polaris.shopify.com/content/design/layout.md
Labels: 🤖Skip Changelog

#8818 Fix example video on layout design page
  polaris.shopify.com/content/design/layout.md
Labels: 🤖Skip Changelog

#8821 [Layout foundations] Update navigation component links
  .changeset/cool-clouds-doubt.md
  polaris.shopify.com/content/components/navigation/top-bar.md
  polaris.shopify.com/content/components/utilities/frame.md
  polaris.shopify.com/content/patterns-legacy/new-badge.md
Labels: #gsd:30116
