Repository Shopify/polaris, pull requests merged in 2023-11, with the labels that each got.

#11078 Update Icon contribution guidelines
  .changeset/strange-ducks-shake.md
  polaris.shopify.com/content/contributing/icons.md
Labels: Documentation

#11102 [Filters] Fix `onQueryClear` examples
  polaris-react/src/components/IndexFilters/IndexFilters.stories.tsx
  polaris.shopify.com/pages/examples/index-filters-default.tsx
  polaris.shopify.com/pages/examples/index-filters-disabled.tsx
  polaris.shopify.com/pages/examples/index-filters-with-edit-colums-button.tsx
  polaris.shopify.com/pages/examples/index-filters-with-filtering-mode.tsx
  polaris.shopify.com/pages/examples/index-filters-with-no-filters.tsx
  polaris.shopify.com/pages/examples/index-filters-with-no-search.tsx
  polaris.shopify.com/pages/examples/index-filters-with-pinned-filters.tsx
  polaris.shopify.com/pages/examples/index-table-condensed-with-views-search-filter-sorting.tsx
  polaris.shopify.com/pages/examples/index-table-with-filtering.tsx
  polaris.shopify.com/pages/examples/index-table-with-loading-state.tsx
  polaris.shopify.com/pages/examples/index-table-with-views-search-filter-sorting.tsx
Labels: 🤖Skip Changelog

#11106 Load Inter from Shopify CDN instead of Google
  polaris-react/.storybook/preview-head.html
  polaris-react/README.md
  polaris.shopify.com/content/version-guides/migrating-from-v11-to-v12.md
  polaris.shopify.com/pages/_document.tsx
  polaris.shopify.com/scripts/gen-og-images.mjs
Labels: 🤖Skip Changelog

#11115 Fix hover issue unselected indexTable
  .changeset/silly-lies-march.md
  polaris-react/src/components/IndexTable/IndexTable.scss
  polaris-react/src/components/IndexTable/IndexTable.stories.tsx
Labels: 🤖Skip Comment Check

#11036 Fixed issue with textarea not bubbling up to parent
  .changeset/young-yaks-type.md
  polaris-react/src/components/TextField/TextField.tsx
  polaris-react/src/components/TextField/tests/TextField.test.tsx
Labels: Bug, Contribution, Component, 2023

#11132 Update node-sass to support Node 18.0+
  polaris-react/package.json
  yarn.lock
Labels: 🤖Skip Changelog

#11188 Fix storybook breakpoints
  polaris-react/.storybook/preview.js
Labels: 🤖Skip Changelog

#11187 Update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🤖Skip Changelog

#11194 Add `layout-banner.png`
  polaris.shopify.com/public/images/design/layout/layout-banner.png
Labels: 🤖Skip Changelog

#11204 [polaris.shopify.com] Content fixes and adjustments
  polaris.shopify.com/content/design/colors/palettes-and-roles.mdx
  polaris.shopify.com/public/images/design/colors/color-palettes-roles-default-do@2x.png
  polaris.shopify.com/public/images/design/colors/color-palettes-roles-default-dont@2x.png
  polaris.shopify.com/public/images/design/colors/color-palettes-roles-inverse-dont@2x.png
  polaris.shopify.com/public/images/design/colors/color-palettes-roles-magic-dont@2x.png
  polaris.shopify.com/public/images/design/colors/color-palettes-roles-transparent-dont@2x.png
  polaris.shopify.com/public/images/design/icons/icons-overview-clear-2@2x.png
Labels: 🤖Skip Changelog, #gsd:36550

#11206 [Navigation] Fix disjointed arrow line on small screens
  .changeset/poor-gifts-wait.md
  polaris-react/src/components/Navigation/Navigation.scss
Labels: #gsd:37811

#11201 [Card] Add storybook examples for Card compositions
  .changeset/empty-squids-prove.md
  polaris-react/src/components/Card/Card.stories.tsx
  polaris.shopify.com/content/components/layout-and-structure/card.mdx
  polaris.shopify.com/pages/examples/card-default.tsx
  polaris.shopify.com/pages/examples/card-with-all-elements.tsx
  polaris.shopify.com/pages/examples/card-with-critical-footer-actions.tsx
  polaris.shopify.com/pages/examples/card-with-custom-footer-actions.tsx
  polaris.shopify.com/pages/examples/card-with-custom-react-node-title.tsx
  polaris.shopify.com/pages/examples/card-with-flushed-section.tsx
  polaris.shopify.com/pages/examples/card-with-footer-actions.tsx
  polaris.shopify.com/pages/examples/card-with-header-actions.tsx
  polaris.shopify.com/pages/examples/card-with-multiple-footer-actions.tsx
  polaris.shopify.com/pages/examples/card-with-multiple-sections.tsx
  polaris.shopify.com/pages/examples/card-with-multiple-titled-sections.tsx
  polaris.shopify.com/pages/examples/card-with-responsive-border-radius.tsx
  polaris.shopify.com/pages/examples/card-with-section.tsx
  polaris.shopify.com/pages/examples/card-with-sections-and-actions.tsx
  polaris.shopify.com/pages/examples/card-with-sections-and-critical-action.tsx
  polaris.shopify.com/pages/examples/card-with-separate-header.tsx
  polaris.shopify.com/pages/examples/card-with-subdued-background.tsx
  polaris.shopify.com/pages/examples/card-with-subdued-section.tsx
  polaris.shopify.com/pages/examples/card-with-subsection.tsx
  polaris.shopify.com/pages/examples/card-with-varying-padding.tsx
Labels: #gsd:37811
