Repository Shopify/polaris, pull requests merged in 2023-12, with the labels that each got.

#11261 [Avatar] Update colors
  .changeset/modern-plums-wonder.md
  polaris-react/src/components/Avatar/Avatar.scss
  polaris-react/src/components/Avatar/Avatar.stories.tsx
  polaris-react/src/components/Avatar/Avatar.tsx
  polaris-tokens/src/themes/base/color.ts
Labels: #gsd:37811

#11306 Fix token -> color nav selection issue
  polaris.shopify.com/content/tokens/index.mdx
  polaris.shopify.com/pages/[...slug].tsx
  polaris.shopify.com/src/components/TokensNav/TokensNav.tsx
Labels: 🤖Skip Changelog

#11273 Add `inherit` to `<Icon>` `tone` property
  .changeset/twenty-wasps-cheer.md
  polaris-react/src/components/Icon/Icon.scss
  polaris-react/src/components/Icon/Icon.stories.tsx
  polaris-react/src/components/Icon/Icon.tsx
  polaris-react/src/components/Icon/tests/Icon.test.tsx
Labels: #gsd:37811

#11302 Upgrade `turbo` to v1.11.1
  package.json
  yarn.lock
Labels: 🤖Skip Changelog

#11276 Remove Data URL and placeholder support from the `Icon` component
  .changeset/loud-carrots-sniff.md
  polaris-react/playground/DetailsPage.tsx
  polaris-react/src/components/Autocomplete/components/MappedAction/tests/MappedAction.test.tsx
  polaris-react/src/components/Autocomplete/tests/Autocomplete.test.tsx
  polaris-react/src/components/Button/Button.tsx
  polaris-react/src/components/Icon/Icon.scss
  polaris-react/src/components/Icon/Icon.stories.tsx
  polaris-react/src/components/Icon/Icon.tsx
  polaris-react/src/components/Icon/tests/Icon.test.tsx
  polaris-react/src/components/Navigation/Navigation.stories.tsx
  polaris-react/src/components/Navigation/_variables.scss
  polaris-react/src/components/Navigation/components/Section/tests/Section.test.tsx
  polaris-react/src/types.ts
  polaris.shopify.com/content/components/images-and-icons/icon.mdx
  polaris.shopify.com/pages/examples/icon-with-custom-svg.tsx
  polaris.shopify.com/pages/examples/navigation-with-various-states-and-secondary-elements.tsx
Labels: #gsd:37811

#11324 Update `Subnav` to use the new `nav` data structure
  polaris.shopify.com/src/components/Subnav/Subnav.tsx
Labels: 🤖Skip Changelog

#11311 1278/refactor gen assets processes
  polaris.shopify.com/package.json
  polaris.shopify.com/pages/_app.tsx
  polaris.shopify.com/scripts/gen-assets.mjs
  polaris.shopify.com/scripts/gen-cache-json.mjs
  polaris.shopify.com/scripts/gen-og-images.ts
  polaris.shopify.com/scripts/gen-site-map.mjs
  polaris.shopify.com/scripts/gen-site-map.ts
  yarn.lock
Labels: 🤖Skip Changelog

#11329 [topbar]: fixes the color of the hamburger icon
  .changeset/unlucky-poets-occur.md
  polaris-react/src/components/TopBar/TopBar.scss
Labels: Bug, P1

#11334 [polaris.shopify.com] Add color token docs
  .changeset/brown-foxes-call.md
  polaris.shopify.com/content/design/colors/color-tokens.mdx
  polaris.shopify.com/public/images/design/colors/color-tokens-base@2x.png
  polaris.shopify.com/public/images/design/colors/color-tokens-figma@2x.png
  polaris.shopify.com/public/images/design/colors/color-tokens-formula@2x.png
  polaris.shopify.com/public/images/design/colors/color-tokens-polaris-react@2x.png
  polaris.shopify.com/public/images/design/colors/color-tokens-specialty@2x.png
  polaris.shopify.com/public/images/design/colors/color-tokens-state-active@2x.png
  polaris.shopify.com/public/images/design/colors/color-tokens-state-disabled@2x.png
  polaris.shopify.com/public/images/design/colors/color-tokens-state-focus@2x.png
  polaris.shopify.com/public/images/design/colors/color-tokens-state-hover@2x.png
  polaris.shopify.com/public/images/design/colors/color-tokens-state-selected@2x.png
  polaris.shopify.com/public/images/design/colors/color-tokens@2x.png
  yarn.lock
Labels: #gsd:37811

#11317 [LegacyFilters] Fixed button spacing on `ConnectedFilterControl`
  .changeset/little-gorillas-deny.md
  polaris-react/src/components/LegacyFilters/components/ConnectedFilterControl/ConnectedFilterControl.scss
Labels: #gsd:37811

#9019 Upgrade to Storybook v7 with Vite
  .changeset/shiny-pans-sit.md
  polaris-react/.storybook/addons/global-controls-panel/manager.jsx
  polaris-react/.storybook/addons/global-controls-panel/preset.js
  polaris-react/.storybook/main.js
  polaris-react/.storybook/manager.js
  polaris-react/.storybook/preview.jsx
  polaris-react/config/rollup/namespaced-classname.mjs
  polaris-react/package.json
  polaris-react/playground/KitchenSink.tsx
  polaris-react/playground/stories.tsx
  polaris-react/postcss.config.mjs
  polaris-react/rollup.config.mjs
  polaris-react/src/components/AppProvider/AppProvider.stories.tsx
  polaris-react/vite.config.mjs
  yarn.lock
Labels: 🤖Skip Changelog, 🤖Skip Comment Check

#11212 Button code clean up and bevel fixes
  .changeset/tender-pugs-crash.md
  polaris-react/src/components/ActionMenu/components/SecondaryAction/SecondaryAction.module.scss
  polaris-react/src/components/Button/Button.module.scss
  polaris-react/src/components/Button/Button.tsx
  polaris-react/src/components/Button/tests/Button.test.tsx
  polaris-react/src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.module.scss
  polaris-react/src/components/Page/components/Header/Header.module.scss
Labels: #gsd:37811

#11331 `Docs` Parellelize build
  polaris.shopify.com/package.json
  yarn.lock
Labels: 🤖Skip Changelog

#11365 Tjonx/fix docs images
  polaris.shopify.com/public/images/design/colors/color-tokens-state-hover@2x.png
  polaris.shopify.com/public/images/design/colors/color-tokens@2x.png
  polaris.shopify.com/public/images/design/colors/color-using-color-text@2x.png
  polaris.shopify.com/public/images/design/layout/layout-spatial-20-breaking-alignment@2x.png
Labels: 🤖Skip Changelog
