Repository Shopify/polaris, pull requests merged in 2023-02, with the labels that each got.

#8222 date-picker pattern code-examples
  polaris.shopify.com/content/patterns/date-picking.ts
  polaris.shopify.com/playroom/FrameComponent.tsx
  polaris.shopify.com/src/components/PatternsExample/PatternsExample.tsx
Labels: 🤖Skip Changelog

#8206 Re-add deprecated typography docs
  polaris.shopify.com/content/components/caption.md
  polaris.shopify.com/content/components/display-text.md
  polaris.shopify.com/content/components/heading.md
  polaris.shopify.com/content/components/subheading.md
  polaris.shopify.com/content/components/text-style.md
  polaris.shopify.com/content/components/visually-hidden.md
  polaris.shopify.com/pages/components/[component].tsx
  polaris.shopify.com/public/images/components/caption.png
  polaris.shopify.com/public/images/components/display-text.png
  polaris.shopify.com/public/images/components/heading.png
  polaris.shopify.com/public/images/components/subheading.png
  polaris.shopify.com/public/images/components/text-style.png
  polaris.shopify.com/public/images/components/visually-hidden.png
  polaris.shopify.com/scripts/get-props/src/get-props.ts
Labels: v11.0.0

#7905 [Layout Foundations] Rebuild `DropZone` with layout primitives
  polaris-react/src/components/DropZone/DropZone.stories.tsx
  polaris-react/src/components/DropZone/DropZone.tsx
  polaris-react/src/components/DropZone/components/FileUpload/FileUpload.tsx
Labels: #gsd:30116

#7271 Upgrade TypeScript to v4.9.3
  package.json
  polaris-cli/package.json
  polaris-react/src/components/OptionList/tests/OptionList.test.tsx
  polaris-react/src/components/ResourceList/ResourceList.tsx
  polaris-react/src/utilities/merge.ts
  polaris.shopify.com/content/design/typography.md
  polaris.shopify.com/package.json
  yarn.lock
Labels: 🤖Skip Changelog

#8242 Patch playroom to resolve sandbox 431 error
  patches/playroom+0.28.0.patch
  polaris.shopify.com/playroom.config.js
Labels: 🤖Skip Changelog

#7950 [Layout foundations][Batch 3] Rebuild components with layout primitives
  .changeset/beige-falcons-guess.md
  .changeset/fresh-boats-fly.md
  .changeset/lazy-crews-sing.md
  .changeset/slimy-years-tie.md
  .changeset/thin-apricots-admire.md
  polaris-react/src/components/DropZone/DropZone.stories.tsx
  polaris-react/src/components/DropZone/DropZone.tsx
  polaris-react/src/components/DropZone/components/FileUpload/FileUpload.tsx
  polaris-react/src/components/OptionList/OptionList.scss
  polaris-react/src/components/OptionList/OptionList.tsx
  polaris-react/src/components/OptionList/components/Option/Option.scss
  polaris-react/src/components/Page/components/Header/Header.scss
  polaris-react/src/components/Page/components/Header/Header.tsx
  polaris-react/src/components/Popover/Popover.scss
  polaris-react/src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx
  polaris-react/src/components/Popover/components/Section/Section.tsx
  polaris-react/src/components/Tabs/Tabs.scss
  polaris-react/src/components/Tabs/Tabs.tsx
  polaris-react/src/components/Tabs/components/List/List.tsx
Labels: #gsd:30116

#8212 Bump minimum Node version to 16.17.0
  .github/workflows/ci.yml
  documentation/Nodejs support.md
  package.json
  polaris-cli/package.json
  polaris-for-vscode/package.json
  polaris-icons/package.json
  polaris-migrator/package.json
  polaris-migrator/rollup.config.mjs
  polaris-react/package.json
  polaris-react/rollup.config.mjs
  polaris-tokens/package.json
  polaris.shopify.com/package.json
  stylelint-polaris/package.json
  yarn.lock
Labels: v11.0.0

#8268 [Layout foundations] Add codeowners for `Card`, `Stack`, `LegacyCard`, `LegacyStack`
  .github/CODEOWNERS
Labels: 🤖Skip Changelog

#8280 [EmptyState] Remove old design language flex-direction
  .changeset/silly-swans-sparkle.md
  polaris-react/src/components/EmptyState/EmptyState.tsx
Labels: Bug

#8261 Dark-mode fixes
  polaris.shopify.com/src/components/ExampleWrapper/ExampleWrapper.module.scss
  polaris.shopify.com/src/components/InlinePill/InlinePill.module.scss
  polaris.shopify.com/src/components/PatternPage/PatternPage.module.scss
  polaris.shopify.com/src/styles/globals.scss
Labels: 🤖Skip Changelog, #gsd:26204

#8243 Resource details layout code-example
  polaris.shopify.com/content/patterns/resource-details-layout.ts
Labels: 🤖Skip Changelog

#8307 Replace border-radius large with border-radius-2
  polaris-react/src/components/Box/Box.tsx
  polaris-react/src/components/Box/tests/Box.test.tsx
  polaris-react/src/components/DropZone/DropZone.scss
  polaris-react/src/components/Modal/components/CloseButton/CloseButton.scss
Labels: v11.0.0

#8321 Improve easing token docs
  polaris-tokens/src/token-groups/motion.ts
  polaris.shopify.com/src/components/TokenList/TokenList.module.scss
  polaris.shopify.com/src/components/TokenList/TokenList.tsx
Labels: 🤖Skip Changelog, Tokens

#8306 Replace border-radius-base with border-radius-1
  .changeset/tasty-weeks-wave.md
  polaris-react/src/components/ActionList/ActionList.scss
  polaris-react/src/components/Autocomplete/components/MappedAction/MappedAction.scss
  polaris-react/src/components/Banner/Banner.scss
  polaris-react/src/components/Box/Box.tsx
  polaris-react/src/components/Box/tests/Box.test.tsx
  polaris-react/src/components/CheckableButton/CheckableButton.scss
  polaris-react/src/components/DropZone/DropZone.scss
  polaris-react/src/components/DropZone/components/FileUpload/FileUpload.scss
  polaris-react/src/components/Frame/Frame.scss
  polaris-react/src/components/Link/Link.scss
  polaris-react/src/components/Modal/components/CloseButton/CloseButton.scss
  polaris-react/src/components/RangeSlider/components/DualThumb/DualThumb.scss
  polaris-react/src/components/RangeSlider/components/SingleThumb/SingleThumb.scss
  polaris-react/src/components/SkeletonBodyText/SkeletonBodyText.scss
  polaris-react/src/components/SkeletonDisplayText/SkeletonDisplayText.scss
  polaris-react/src/components/SkeletonPage/SkeletonPage.tsx
  polaris-react/src/components/SkeletonThumbnail/SkeletonThumbnail.scss
  polaris-react/src/components/Tag/Tag.scss
  polaris-react/src/components/TextStyle/TextStyle.scss
  polaris-react/src/components/TopBar/TopBar.scss
  polaris-react/src/components/TopBar/components/Menu/Menu.scss
  polaris-react/src/styles/shared/_buttons.scss
Labels: v11.0.0

#8332 Fix linting issues
  polaris-react/src/components/AppProvider/AppProvider.scss
  polaris-react/src/components/Avatar/Avatar.scss
  polaris-react/src/components/Icon/Icon.scss
  polaris-react/src/components/Thumbnail/Thumbnail.scss
  polaris-react/src/components/TopBar/TopBar.scss
  polaris-react/src/components/VideoThumbnail/VideoThumbnail.scss
Labels: 🤖Skip Changelog

#8265 Create generic codemod to replace custom properties
  .changeset/sweet-paws-tan.md
  polaris-migrator/src/migrations/styles-replace-custom-property/styles-replace-custom-property.ts
  polaris-migrator/src/migrations/styles-replace-custom-property/tests/replacement-maps.js
  polaris-migrator/src/migrations/styles-replace-custom-property/tests/styles-replace-custom-property.test.ts
  polaris-migrator/src/migrations/styles-replace-custom-property/tests/with-from-to-flags-basic.input.scss
  polaris-migrator/src/migrations/styles-replace-custom-property/tests/with-from-to-flags-basic.output.scss
  polaris-migrator/src/migrations/styles-replace-custom-property/tests/with-from-to-flags-regexp.input.scss
  polaris-migrator/src/migrations/styles-replace-custom-property/tests/with-from-to-flags-regexp.output.scss
  polaris-migrator/src/migrations/styles-replace-custom-property/tests/with-maps-flag.input.scss
  polaris-migrator/src/migrations/styles-replace-custom-property/tests/with-maps-flag.output.scss
  polaris-migrator/src/migrations/styles-replace-custom-property/tests/with-replacementMaps-option.input.scss
  polaris-migrator/src/migrations/styles-replace-custom-property/tests/with-replacementMaps-option.output.scss
  polaris-migrator/src/utilities/matchesStringOrRegExp.ts
  polaris.shopify.com/content/tools/polaris-migrator.md
Labels: v11.0.0

#8352 Bump size limit
  package.json
Labels: 🤖Skip Changelog

#8373 [Layout foundations] Add support for LegacyCard in Card styles
  .changeset/giant-apricots-roll.md
  polaris-react/src/components/Card/Card.scss
  polaris-react/src/components/LegacyCard/LegacyCard.scss
Labels: Bug, #gsd:30116

#8221 Use browserslist, remove @shopify/browserslist-config and update caniuse db
  polaris-react/package.json
  polaris-react/rollup.config.mjs
  polaris-tokens/package.json
  yarn.lock
Labels: v11.0.0

#8401 Add redirects for moved legacy patterns
  polaris.shopify.com/next.config.js
Labels: 🤖Skip Changelog

#8398 Fix date-picking pattern examples
  polaris.shopify.com/content/patterns/date-picking.ts
Labels: 🤖Skip Changelog, #gsd:30559, Engineering

#8404 [Layout foundations] Fix broken images
  .changeset/gentle-dodos-shake.md
  polaris.shopify.com/content/components/deprecated/caption.md
  polaris.shopify.com/content/components/feedback-indicators/skeleton-display-text.md
  polaris.shopify.com/content/components/feedback-indicators/skeleton-page.md
  polaris.shopify.com/content/components/lists/resource-list.md
  polaris.shopify.com/content/components/navigation/link.md
  polaris.shopify.com/content/components/selection-and-input/combobox.md
Labels: #gsd:30116, polaris.shopify.com

#8383 [Layout foundations] Remove default spacing from AlphaStack
  .changeset/empty-dancers-think.md
  polaris-react/src/components/AlphaStack/AlphaStack.scss
  polaris-react/src/components/AlphaStack/AlphaStack.stories.tsx
  polaris-react/src/components/AlphaStack/AlphaStack.tsx
  polaris-react/src/components/AlphaStack/tests/AlphaStack.test.tsx
  polaris-react/src/components/Box/Box.stories.tsx
  polaris-react/src/components/DropZone/DropZone.stories.tsx
  polaris-react/src/components/EmptyState/EmptyState.tsx
  polaris-react/src/components/Inline/Inline.stories.tsx
  polaris-react/src/components/SkeletonPage/SkeletonPage.tsx
  polaris.shopify.com/pages/components/[group]/index.tsx
  polaris.shopify.com/pages/examples/alpha-stack-with-align.tsx
  polaris.shopify.com/pages/examples/alpha-stack-with-full-width-children.tsx
  polaris.shopify.com/pages/examples/box-with-padding.tsx
  polaris.shopify.com/src/data/props.json
Labels: #gsd:30116

#7877 [stylelint-polaris] Fix custom property allowed list plugin
  .changeset/bright-snails-clean.md
  stylelint-polaris/index.js
  stylelint-polaris/plugins/coverage/index.js
  stylelint-polaris/plugins/coverage/index.test.js
  stylelint-polaris/plugins/custom-property-allowed-list/index.js
  stylelint-polaris/plugins/custom-property-allowed-list/index.test.js
Labels: #gsd:31276, stylelint-polaris

#8423 Migrate `z-index` custom properties from `v10` to `v11`
  .changeset/itchy-turtles-thank.md
  polaris-react/src/components/Backdrop/Backdrop.scss
  polaris-react/src/components/DataTable/DataTable.scss
  polaris-react/src/components/Filters/Filters.scss
  polaris-react/src/components/Frame/Frame.scss
  polaris-react/src/components/Frame/components/ToastManager/ToastManager.scss
  polaris-react/src/components/IndexTable/IndexTable.scss
  polaris-react/src/components/MediaCard/MediaCard.scss
  polaris-react/src/components/Modal/components/Dialog/Dialog.scss
  polaris-react/src/components/PositionedOverlay/PositionedOverlay.scss
  polaris-react/src/components/Sheet/Sheet.scss
  polaris-react/src/components/TopBar/TopBar.scss
  polaris-react/src/components/TopBar/components/Search/Search.scss
  polaris-react/src/components/TopBar/components/SearchDismissOverlay/SearchDismissOverlay.scss
  polaris-react/src/components/TopBar/components/SearchField/SearchField.scss
Labels: v11.0.0

#8356 Migrate `--p-space-0` tokens in SCSS files to `0`
  .changeset/calm-vans-guess.md
  polaris-react/src/components/Card/Card.scss
  polaris-react/src/components/LegacyCard/LegacyCard.scss
  polaris-react/src/components/LegacyStack/LegacyStack.scss
  polaris-react/src/components/Stack/Stack.scss
  polaris-react/src/components/TextField/TextField.scss
Labels: v11.0.0

#8425 Manually migrate `z-index` custom properties from `v10` to `v11`
  .changeset/hungry-carpets-lay.md
  polaris-react/src/components/Sheet/Sheet.stories.tsx
  polaris.shopify.com/pages/examples/sheet-with-searchable-listbox.tsx
Labels: v11.0.0

#8435 ensure scroll on focus does not occur on selection
  polaris.shopify.com/src/components/Container/Container.module.scss
  polaris.shopify.com/src/components/PatternPage/PatternPage.tsx
Labels: 🤖Skip Changelog

#8436 Clean up markdown metadata in html elements
  polaris.shopify.com/src/components/PatternPage/Blocks.tsx
  polaris.shopify.com/src/components/PatternPage/PatternPage.tsx
Labels: 🤖Skip Changelog, #gsd:30559

#8437 support conditional example pattern rendering
  polaris.shopify.com/src/components/PatternPage/PatternPage.tsx
  polaris.shopify.com/src/types.ts
Labels: #gsd:30559

#8450 [Layout foundations] Deprecate Card and subcomponents
  .changeset/quiet-seals-flow.md
  polaris-react/src/components/Card/Card.tsx
  polaris-react/src/components/Card/components/Header/Header.tsx
  polaris-react/src/components/Card/components/Header/tests/Header.test.tsx
  polaris-react/src/components/Card/components/Section/Section.tsx
  polaris-react/src/components/Card/components/Section/tests/Section.test.tsx
  polaris-react/src/components/Card/components/Subsection/Subsection.tsx
  polaris-react/src/components/Card/components/Subsection/tests/Subsection.test.tsx
  polaris-react/src/components/Card/tests/Card.test.tsx
  polaris.shopify.com/content/components/deprecated/card.md
  polaris.shopify.com/next.config.js
  polaris.shopify.com/public/images/components/deprecated/card.png
Labels: #gsd:30116

#8464 Lift up non-unique replacement properties to the `allMap`
  polaris-migrator/src/migrations/v11-styles-replace-custom-property-color/v11-styles-replace-custom-property-color.ts
Labels: #gsd:29807, v11.0.0

#8468 [Layout foundations] Replace Card with AlphaCard
  .changeset/six-jokes-drum.md
  polaris-react/src/components/AccountConnection/AccountConnection.tsx
  polaris-react/src/components/AlphaCard/AlphaCard.stories.tsx
  polaris-react/src/components/AlphaCard/AlphaCard.tsx
  polaris-react/src/components/AlphaCard/index.ts
  polaris-react/src/components/AlphaCard/tests/AlphaCard.test.tsx
  polaris-react/src/components/Bleed/Bleed.stories.tsx
  polaris-react/src/components/Card/Card.scss
  polaris-react/src/components/Card/Card.stories.tsx
  polaris-react/src/components/Card/Card.tsx
  polaris-react/src/components/Card/components/Header/Header.tsx
  polaris-react/src/components/Card/components/Header/index.ts
  polaris-react/src/components/Card/components/Header/tests/Header.test.tsx
  polaris-react/src/components/Card/components/Section/Section.tsx
  polaris-react/src/components/Card/components/Section/index.ts
  polaris-react/src/components/Card/components/Section/tests/Section.test.tsx
  polaris-react/src/components/Card/components/Subsection/Subsection.tsx
  polaris-react/src/components/Card/components/Subsection/index.ts
  polaris-react/src/components/Card/components/Subsection/tests/Subsection.test.tsx
  polaris-react/src/components/Card/components/index.ts
  polaris-react/src/components/Card/tests/Card.test.tsx
  polaris-react/src/components/LegacyCard/LegacyCard.scss
  polaris-react/src/index.ts
  polaris.shopify.com/content/components/deprecated/card.md
  polaris.shopify.com/content/components/deprecated/heading.md
  polaris.shopify.com/content/components/feedback-indicators/banner.md
  polaris.shopify.com/content/components/feedback-indicators/skeleton-body-text.md
  polaris.shopify.com/content/components/layout-and-structure/box.md
  polaris.shopify.com/content/components/layout-and-structure/callout-card.md
  polaris.shopify.com/content/components/layout-and-structure/card.md
  polaris.shopify.com/content/components/layout-and-structure/layout.md
  polaris.shopify.com/content/components/layout-and-structure/media-card.md
  polaris.shopify.com/content/components/utilities/collapsible.md
  polaris.shopify.com/content/components/utilities/scrollable.md
  polaris.shopify.com/content/patterns/page-layouts.md
  polaris.shopify.com/next.config.js
  polaris.shopify.com/pages/examples/alpha-card-with-rounded-corners.tsx
  polaris.shopify.com/pages/examples/card-default.tsx
  polaris.shopify.com/pages/examples/card-with-a-subdued-section.tsx
  polaris.shopify.com/pages/examples/card-with-all-elements.tsx
  polaris.shopify.com/pages/examples/card-with-custom-footer-actions.tsx
  polaris.shopify.com/pages/examples/card-with-custom-react-node-title.tsx
  polaris.shopify.com/pages/examples/card-with-destructive-action.tsx
  polaris.shopify.com/pages/examples/card-with-destructive-footer-action.tsx
  polaris.shopify.com/pages/examples/card-with-flushed-sections.tsx
  polaris.shopify.com/pages/examples/card-with-footer-actions.tsx
  polaris.shopify.com/pages/examples/card-with-header-actions.tsx
  polaris.shopify.com/pages/examples/card-with-multiple-footer-actions.tsx
  polaris.shopify.com/pages/examples/card-with-multiple-sections.tsx
  polaris.shopify.com/pages/examples/card-with-multiple-titled-sections.tsx
  polaris.shopify.com/pages/examples/card-with-rounded-corners.tsx
  polaris.shopify.com/pages/examples/card-with-sections-and-actions.tsx
  polaris.shopify.com/pages/examples/card-with-separate-header.tsx
  polaris.shopify.com/pages/examples/card-with-subdued-background.tsx
  polaris.shopify.com/pages/examples/card-with-subdued-for-secondary-content.tsx
  polaris.shopify.com/pages/examples/card-with-subsection.tsx
  polaris.shopify.com/pages/examples/card-with-varying-padding.tsx
  polaris.shopify.com/public/images/components/layout-and-structure/alpha-card.png
  polaris.shopify.com/public/images/components/layout-and-structure/card.png
  polaris.shopify.com/src/data/props.json
Labels: #gsd:30116, v11.0.0

#8135 Deprecate breadcrumbs and allow singular backAction prop on Page and Breadcrumbs
  .changeset/metal-cows-poke.md
  polaris-react/src/components/Breadcrumbs/Breadcrumbs.tsx
  polaris-react/src/components/Page/Page.tsx
  polaris-react/src/components/Page/components/Header/Header.tsx
  polaris-react/src/components/Page/tests/Page.test.tsx
Labels: v11.0.0

#8467 [stylelint-polaris] Disallow component overrides using `selector-disallowed-list`
  .changeset/thin-tools-sort.md
  stylelint-polaris/index.js
Labels: #gsd:31276

#8071 Breadcrumb migrator
  .changeset/silent-elephants-compare.md
  polaris-migrator/src/migrations/v11-react-update-page-breadcrumbs/tests/v11-react-update-page-breadcrumbs.input.tsx
  polaris-migrator/src/migrations/v11-react-update-page-breadcrumbs/tests/v11-react-update-page-breadcrumbs.output.tsx
  polaris-migrator/src/migrations/v11-react-update-page-breadcrumbs/tests/v11-react-update-page-breadcrumbs.test.ts
  polaris-migrator/src/migrations/v11-react-update-page-breadcrumbs/v11-react-update-page-breadcrumbs.ts
Labels: v11.0.0

#8387 Update `Columns` to accept oneThird, oneHalf, twoThirds array options
  .changeset/clean-rivers-vanish.md
  polaris-react/src/components/Columns/Columns.scss
  polaris-react/src/components/Columns/Columns.stories.tsx
  polaris-react/src/components/Columns/Columns.tsx
  polaris-react/src/components/Columns/tests/Columns.test.tsx
  polaris-react/src/utilities/css.ts
  polaris.shopify.com/src/data/props.json
Labels: #gsd:30116, v11.0.0

#8475 Selector disallowed list doc
  .changeset/long-moons-obey.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/conventions-custom-property-allowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/conventions-selector-disallowed-list.md
Labels: #gsd:31276

#8454 [Layout foundations] Remove default spacing from `Inline`
  .changeset/eight-spies-complain.md
  polaris-react/src/components/ActionList/components/Item/Item.tsx
  polaris-react/src/components/Banner/Banner.stories.tsx
  polaris-react/src/components/DropZone/DropZone.stories.tsx
  polaris-react/src/components/Frame/components/Toast/Toast.tsx
  polaris-react/src/components/Inline/Inline.tsx
  polaris-react/src/components/Inline/tests/Inline.test.tsx
  polaris-react/src/components/Modal/Modal.tsx
  polaris-react/src/components/Modal/components/Footer/Footer.tsx
  polaris-react/src/components/Modal/components/Header/Header.tsx
  polaris-react/src/components/Page/components/Header/Header.tsx
  polaris-react/src/components/ResourceItem/ResourceItem.tsx
  polaris-react/src/components/SkeletonPage/SkeletonPage.tsx
  polaris.shopify.com/pages/examples/alpha-stack-with-align.tsx
  polaris.shopify.com/pages/examples/bleed-all-directions.tsx
  polaris.shopify.com/pages/examples/bleed-horizontal.tsx
  polaris.shopify.com/pages/examples/bleed-specific-direction.tsx
  polaris.shopify.com/pages/examples/bleed-vertical.tsx
  polaris.shopify.com/pages/examples/box-with-padding.tsx
  polaris.shopify.com/pages/examples/columns-default.tsx
  polaris.shopify.com/pages/examples/columns-with-fixed-widths.tsx
  polaris.shopify.com/pages/examples/columns-with-set-number.tsx
  polaris.shopify.com/pages/examples/columns-with-varying-gap.tsx
  polaris.shopify.com/pages/examples/inline-with-gap.tsx
  polaris.shopify.com/pages/examples/inline-with-horizontal-alignment.tsx
  polaris.shopify.com/pages/examples/inline-with-non-wrapping.tsx
  polaris.shopify.com/pages/examples/inline-with-vertical-alignment.tsx
  polaris.shopify.com/src/data/props.json
Labels: #gsd:30116

#8465 Change breadcrumb to backlink
  .changeset/afraid-scissors-work.md
  polaris-react/src/components/AppProvider/AppProvider.stories.tsx
  polaris-react/src/components/Breadcrumbs/Breadcrumbs.tsx
  polaris-react/src/components/Breadcrumbs/tests/Breadcrumbs.test.tsx
  polaris-react/src/components/DropZone/DropZone.stories.tsx
  polaris-react/src/components/Page/Page.stories.tsx
  polaris-react/src/components/Page/Page.tsx
  polaris-react/src/components/Page/components/Header/Header.tsx
  polaris-react/src/components/Page/components/Header/tests/Header.test.tsx
  polaris-react/src/components/Page/tests/Page.test.tsx
  polaris.shopify.com/content/components/layout-and-structure/page.md
Labels: v11.0.0

#8418 [Layout foundations] Deprecate grid component
  .changeset/stale-maps-ring.md
  polaris-react/src/components/Grid/Grid.tsx
  polaris-react/src/components/Grid/components/Cell/Cell.tsx
  polaris-react/src/components/Grid/components/Cell/tests/Cell.test.tsx
  polaris-react/src/components/Grid/tests/Grid.test.tsx
  polaris.shopify.com/content/components/deprecated/grid.md
  polaris.shopify.com/content/components/deprecated/index.md
  polaris.shopify.com/next.config.js
  polaris.shopify.com/pages/components/[group]/index.tsx
  polaris.shopify.com/public/images/components/deprecated/grid.png
  polaris.shopify.com/src/data/props.json
Labels: #gsd:30116

#8483 Adjust colors to meet color contrast requirements
  .changeset/young-mayflies-count.md
  polaris-tokens/src/colors.ts
  polaris-tokens/src/token-groups/color.ts
Labels: #gsd:29807, v11.0.0

#8426 Migrate `legacy` custom properties from `v10` to `v11`
  .changeset/new-baboons-fail.md
  polaris-react/src/components/Banner/Banner.scss
  polaris-react/src/components/CalloutCard/CalloutCard.scss
  polaris-react/src/components/CheckableButton/CheckableButton.scss
  polaris-react/src/components/Checkbox/Checkbox.scss
  polaris-react/src/components/Choice/Choice.scss
  polaris-react/src/components/ChoiceList/ChoiceList.scss
  polaris-react/src/components/Columns/Columns.scss
  polaris-react/src/components/Filters/components/ConnectedFilterControl/ConnectedFilterControl.scss
  polaris-react/src/components/OptionList/components/Checkbox/Checkbox.scss
  polaris-react/src/components/OptionList/components/Option/Option.scss
  polaris-react/src/components/RadioButton/RadioButton.scss
  polaris-react/src/components/RangeSlider/RangeSlider.scss
  polaris-react/src/components/RangeSlider/components/DualThumb/DualThumb.scss
  polaris-react/src/components/RangeSlider/components/SingleThumb/SingleThumb.scss
  polaris-react/src/components/TextField/TextField.scss
  polaris-react/src/styles/shared/_controls.scss
Labels: v11.0.0

#8485 Update pattern thumbnail copy
  polaris.shopify.com/content/patterns/app-settings-layout.md
  polaris.shopify.com/content/patterns/app-settings-layout.ts
  polaris.shopify.com/content/patterns/date-picking.md
  polaris.shopify.com/content/patterns/date-picking.ts
  polaris.shopify.com/content/patterns/resource-details-layout.md
  polaris.shopify.com/content/patterns/resource-details-layout.ts
  polaris.shopify.com/content/patterns/resource-index-layout.md
  polaris.shopify.com/content/patterns/resource-index-layout.ts
Labels: 🤖Skip Changelog, #gsd:30559

#8482 Update banners on patterns index and legacy-banner
  polaris.shopify.com/content/patterns-legacy/index.md
  polaris.shopify.com/src/components/PatternsPage/index.tsx
  polaris.shopify.com/src/components/StatusBanner/StatusBanner.module.scss
  polaris.shopify.com/src/types.ts
Labels: 🤖Skip Changelog, #gsd:30559

#8496 Revert "Migrate `legacy` custom properties from `v10` to `v11`"
  .changeset/new-baboons-fail.md
  polaris-react/src/components/Banner/Banner.scss
  polaris-react/src/components/CalloutCard/CalloutCard.scss
  polaris-react/src/components/CheckableButton/CheckableButton.scss
  polaris-react/src/components/Checkbox/Checkbox.scss
  polaris-react/src/components/Choice/Choice.scss
  polaris-react/src/components/ChoiceList/ChoiceList.scss
  polaris-react/src/components/Columns/Columns.scss
  polaris-react/src/components/Filters/components/ConnectedFilterControl/ConnectedFilterControl.scss
  polaris-react/src/components/OptionList/components/Checkbox/Checkbox.scss
  polaris-react/src/components/OptionList/components/Option/Option.scss
  polaris-react/src/components/RadioButton/RadioButton.scss
  polaris-react/src/components/RangeSlider/RangeSlider.scss
  polaris-react/src/components/RangeSlider/components/DualThumb/DualThumb.scss
  polaris-react/src/components/RangeSlider/components/SingleThumb/SingleThumb.scss
  polaris-react/src/components/TextField/TextField.scss
  polaris-react/src/styles/shared/_controls.scss
Labels: 🤖Skip Changelog

#8489 Update alternative-text.md
  .changeset/stupid-needles-appear.md
  polaris.shopify.com/content/content/alternative-text.md
Labels: Accessibility, Documentation

#8515 Remove dead link from content file
  polaris.shopify.com/content/content/alternative-text.md
Labels: 🤖Skip Changelog
