Repository Shopify/polaris, pull requests merged in 2023-08, with the labels that each got.

#9870 [BannerExperimental] Add gap between dismiss button and content
  polaris-react/src/components/Banner/Banner.stories.tsx
  polaris-react/src/components/Banner/components/BannerExperimental/BannerExperimental.tsx
Labels: 🤖Skip Changelog

#9906 Remove se23 styles and code from Avatar
  .changeset/tall-chicken-repeat.md
  .github/workflows/major-version-check.yml
  polaris-react/.storybook/manager.js
  polaris-react/src/components/Avatar/Avatar.scss
  polaris-react/src/components/Avatar/Avatar.tsx
Labels: v12

#9908 [AccountConnection] Remove se23 conditional logic
  .changeset/tall-chicken-repeat.md
  polaris-react/src/components/AccountConnection/AccountConnection.tsx
Labels: v12

#9911 [ActionList] Consolidate se23 logic and styles
  .changeset/tall-chicken-repeat.md
  polaris-react/src/components/ActionList/ActionList.scss
  polaris-react/src/components/ActionList/components/Item/Item.tsx
  polaris-react/src/components/ActionList/components/Section/Section.tsx
Labels: v12

#9893 [IndexTable] Update hover styles for status and subdued rows
  polaris-react/src/components/IndexTable/IndexTable.scss
  polaris-react/src/components/IndexTable/IndexTable.stories.tsx
Labels: 🤖Skip Changelog, #gsd:32218

#9999 [ActionMenu] Consolidate se23 logic and styles
  .changeset/tall-chicken-repeat.md
  polaris-react/src/components/ActionMenu/components/Actions/Actions.tsx
  polaris-react/src/components/ActionMenu/components/RollupActions/RollupActions.scss
  polaris-react/src/components/ActionMenu/components/SecondaryAction/SecondaryAction.scss
Labels: v12

#10030 [Breadcrumbs] Consolidate se23 logic and styles
  .changeset/tall-chicken-repeat.md
  polaris-react/src/components/Breadcrumbs/Breadcrumbs.scss
  polaris-react/src/components/Breadcrumbs/Breadcrumbs.tsx
Labels: v12

#10004 [Badge] Consolidate se23 logic and styles
  polaris-react/src/components/Badge/Badge.scss
  polaris-react/src/components/Badge/Badge.stories.tsx
  polaris-react/src/components/Badge/Badge.tsx
  polaris-react/src/components/Badge/components/Pip/Pip.scss
  polaris-react/src/components/Badge/tests/Badge.test.tsx
Labels: 🤖Skip Changelog

#9819 Bulk actions style updates
  polaris-react/src/components/BulkActions/BulkActions.scss
Labels: 🤖Skip Changelog

#10048 Preload inter on Storybook
  .github/workflows/ci-a11y-vrt-experimental.yml
  polaris-react/.storybook/preview-head.html
Labels: 🤖Skip Changelog

#10087 Fix icon optimize config
  polaris-icons/svgo.config.js
Labels: 🤖Skip Changelog

#10015 [Checkbox] consolidates se23 styles and logic
  polaris-react/src/components/Checkbox/Checkbox.scss
  polaris-react/src/components/Checkbox/Checkbox.tsx
  polaris-react/src/styles/shared/_controls.scss
Labels: 🤖Skip Changelog, 🤖Skip Comment Check

#10117 [Listbox] Consolidate se23 styles and logic
  polaris-react/src/components/Listbox/Listbox.stories.tsx
  polaris-react/src/components/Listbox/components/TextOption/TextOption.scss
  polaris-react/src/components/Listbox/components/TextOption/TextOption.tsx
Labels: #gsd:36579

#10141 [Tag] Consolidate se23 styles
  polaris-react/src/components/Tag/Tag.scss
Labels: #gsd:36579

#10171 [Thumbnail] Consolidate conditional logic
  polaris-react/src/components/Thumbnail/Thumbnail.scss
Labels: 🤖Skip Comment Check

#10187 [Page] Consolidate se23 styles and logic
  polaris-react/src/components/Page/Page.scss
  polaris-react/src/components/Page/Page.stories.tsx
  polaris-react/src/components/Page/Page.tsx
  polaris-react/src/components/Page/components/Header/Header.scss
  polaris-react/src/components/Page/components/Header/Header.tsx
  polaris-react/src/components/Page/components/Header/components/Title/Title.scss
  polaris-react/src/components/Page/components/Header/components/Title/Title.tsx
  polaris-react/src/components/Page/tests/Page.test.tsx
  polaris.shopify.com/content/components/layout-and-structure/page.md
  polaris.shopify.com/pages/examples/page-with-divider.tsx
Labels: #gsd:36579

#10213 [Navigation] Consolidate se23 logic and styles
  polaris-react/src/components/Navigation/Navigation.scss
  polaris-react/src/components/Navigation/_variables.scss
  polaris-react/src/components/Navigation/components/Item/Item.tsx
  polaris-react/src/components/Navigation/components/Item/components/SecondaryNavigation/SecondaryNavigation.tsx
Labels: #gsd:36579

#10221 [TopBar] Consolidate se23 styles and logic
  polaris-react/src/components/TopBar/TopBar.scss
  polaris-react/src/components/TopBar/TopBar.stories.tsx
  polaris-react/src/components/TopBar/components/Menu/Menu.scss
  polaris-react/src/components/TopBar/components/Menu/Menu.tsx
  polaris-react/src/components/TopBar/components/SearchField/SearchField.scss
  polaris-react/src/components/TopBar/components/UserMenu/UserMenu.scss
  polaris-react/src/components/TopBar/components/UserMenu/UserMenu.tsx
Labels: #gsd:36579

#10232 [v12] Update changesets
  .changeset/kind-phones-yell.md
  .changeset/tall-chicken-repeat.md
  .changeset/wise-pianos-unite.md
Labels: #gsd:36579

#10234 Remove shadow-bevel opt out logic
  polaris-react/src/components/AppProvider/AppProvider.scss
  polaris-react/src/components/AppProvider/AppProvider.tsx
  polaris-react/src/components/Banner/Banner.scss
  polaris-react/src/styles/_common.scss
  polaris-react/src/styles/foundation/_shadow-bevel.scss
  polaris-react/src/utilities/features/context.ts
  polaris-react/src/utilities/features/types.ts
Labels: #gsd:36579

#10241 Consolidate se23 in the rest of stories
  polaris-react/src/components/AccountConnection/AccountConnection.stories.tsx
  polaris-react/src/components/AppProvider/AppProvider.stories.tsx
  polaris-react/src/components/Card/Card.stories.tsx
  polaris-react/src/components/Frame/Frame.stories.tsx
  polaris-react/src/components/FullscreenBar/FullscreenBar.stories.tsx
  polaris-react/src/components/LegacyFilters/LegacyFilters.stories.tsx
  polaris-react/src/components/Popover/Popover.stories.tsx
Labels: #gsd:36579

#10239 Consolidate the rest of se23 scss styles
  polaris-react/src/components/ActionList/ActionList.scss
  polaris-react/src/components/Avatar/Avatar.scss
  polaris-react/src/components/CheckableButton/CheckableButton.scss
  polaris-react/src/components/Checkbox/Checkbox.scss
  polaris-react/src/components/OptionList/components/Option/Option.scss
  polaris-react/src/components/Select/Select.scss
Labels: 🤖Skip Changelog, #gsd:36579

#10228 `Filters` remove unused disabled states and styles from FilterPill
  .changeset/dull-pans-give.md
  polaris-react/src/components/Filters/components/FilterPill/FilterPill.scss
  polaris-react/src/components/Filters/components/FilterPill/FilterPill.tsx
Labels: 🤖Skip Changelog

#10268 [ResourceItem] Fix broken focus ring styles
  .changeset/light-seahorses-sit.md
  polaris-react/src/components/ResourceItem/ResourceItem.scss
  polaris-react/src/components/ResourceItem/ResourceItem.stories.tsx
  polaris-react/src/components/ResourceItem/ResourceItem.tsx
  polaris-react/src/components/ResourceList/ResourceList.stories.tsx
Labels: #gsd:36579

#10287 [ActionList.SearchField] Fix text and focus styles
  .changeset/tough-frogs-speak.md
  polaris-react/src/components/ActionList/components/SearchField/SearchField.scss
Labels: Bug, Uplift polish

#10103 Add multi-theme support to Polaris tokens
  .changeset/cyan-clouds-reply.md
  polaris-tokens/package.json
  polaris-tokens/scripts/index.ts
  polaris-tokens/scripts/toStyleSheet.ts
  polaris-tokens/src/themes/base.ts
  polaris-tokens/src/themes/constants.ts
  polaris-tokens/src/themes/index.ts
  polaris-tokens/src/themes/light-uplift.ts
  polaris-tokens/src/themes/light.ts
  polaris-tokens/src/themes/types.ts
  polaris-tokens/src/themes/utils.ts
  polaris-tokens/src/utilities.ts
  polaris-tokens/tests/toStyleSheet.test.js
  yarn.lock
Labels: Tokens, #gsd:36565

#10250 Add multi-theme build artifacts to Polaris tokens 2
  .changeset/cool-insects-wonder.md
  polaris-tokens/package.json
  polaris-tokens/scripts/index.ts
  polaris-tokens/scripts/toJSON.ts
  polaris-tokens/scripts/toMediaConditions.ts
  polaris-tokens/scripts/toStyleSheet.ts
  polaris-tokens/scripts/toTokenValues.ts
  polaris-tokens/scripts/toValues.ts
  polaris-tokens/scripts/utils.ts
  polaris-tokens/src/metadata.ts
  polaris-tokens/src/themes/constants.ts
  polaris-tokens/src/themes/index.ts
  polaris-tokens/src/themes/light-uplift.ts
  polaris-tokens/src/themes/light.ts
  polaris-tokens/src/themes/types.ts
  polaris-tokens/src/token-groups/color.ts
  polaris-tokens/src/token-groups/font.ts
  polaris-tokens/src/token-groups/motion.ts
  polaris-tokens/src/token-groups/shadow.ts
  polaris-tokens/src/types.ts
Labels: #gsd:36565

#10252 Add `useTheme` hook for runtime Polaris tokens access
  polaris-react/src/components/AppProvider/AppProvider.tsx
  polaris-react/src/index.ts
  polaris-react/src/utilities/use-theme.ts
  polaris-tokens/scripts/toJSON.ts
  polaris-tokens/scripts/toMediaConditions.ts
  polaris-tokens/scripts/toStyleSheet.ts
  polaris-tokens/scripts/toValues.ts
  polaris-tokens/src/index.ts
  polaris-tokens/src/metadata.ts
  polaris-tokens/src/themes/base.ts
  polaris-tokens/src/themes/index.ts
  polaris-tokens/src/themes/light-uplift.ts
  polaris-tokens/src/themes/light.ts
  polaris-tokens/src/themes/types.ts
  polaris-tokens/src/themes/utils.ts
  polaris-tokens/tests/toStyleSheet.test.js
Labels: Tokens, #gsd:36565
