Repository Shopify/polaris, pull requests merged in 2023-07, with the labels that each got.

#9575 Link to GitHub from within Storybooks built on CI
  .github/workflows/ci-a11y-vrt.yml
  polaris-react/.storybook/manager.js
Labels: 🤖Skip Changelog

#9566 Fix `primary` `plain` `destructive` hover & active states
  polaris-react/src/components/Button/Button.scss
Labels: 🤖Skip Changelog

#9583 Fixed primary button styling in all states
  polaris-react/src/components/Button/Button.scss
  polaris-tokens/src/token-groups/shadow.ts
Labels: 🤖Skip Changelog

#9586 [Inputs] Update border widths
  polaris-react/src/components/Checkbox/Checkbox.scss
  polaris-react/src/components/DropZone/DropZone.scss
  polaris-react/src/components/RadioButton/RadioButton.scss
  polaris-react/src/components/Select/Select.scss
  polaris-react/src/components/TextField/TextField.scss
  polaris-tokens/src/token-groups/color.ts
Labels: 🤖Skip Changelog

#9603 Adjust spacing on `Page` breadcrumbs
  polaris-react/src/components/Page/components/Header/Header.tsx
Labels: 🤖Skip Changelog

#9571 Update `ActionList` item suffix position
  polaris-react/src/components/ActionList/components/Item/Item.tsx
Labels: 🤖Skip Changelog

#9558 [LegacyCard] Experimental updates
  polaris-react/src/components/LegacyCard/LegacyCard.scss
  polaris-react/src/components/LegacyCard/LegacyCard.stories.tsx
  polaris-react/src/components/LegacyCard/LegacyCard.tsx
  polaris-react/src/components/LegacyCard/components/Header/Header.tsx
  polaris-react/src/components/LegacyCard/components/Section/Section.tsx
  polaris-react/src/components/LegacyCard/tests/LegacyCard.test.tsx
Labels: 🤖Skip Changelog

#9567 Avatar update
  polaris-react/src/components/Avatar/Avatar.scss
  polaris-react/src/components/Avatar/Avatar.tsx
Labels: 🤖Skip Changelog

#9599 Added inset shadows to `SecondaryActions` and `Pagination`
  polaris-react/src/components/ActionMenu/components/RollupActions/RollupActions.scss
  polaris-react/src/components/ActionMenu/components/SecondaryAction/SecondaryAction.scss
  polaris-react/src/components/Button/Button.scss
  polaris-react/src/components/Pagination/Pagination.scss
Labels: 🤖Skip Changelog

#9610 [Tag] Remove inline padding for Tag with link
  polaris-react/src/components/Tag/Tag.scss
Labels: 🤖Skip Changelog

#9594 Update `EmptyState` `Text` variant and spacing
  polaris-react/src/components/EmptyState/EmptyState.tsx
Labels: 🤖Skip Changelog

#9605 [Checkbox] Fix disabled unchecked background-color
  polaris-react/src/components/Checkbox/Checkbox.scss
  polaris-react/src/components/Checkbox/Checkbox.stories.tsx
Labels: 🤖Skip Changelog

#9612 [Choice][Checkbox][RadioButton] Use CSS-native :hover styling
  .changeset/famous-hats-heal.md
  polaris-react/src/components/Checkbox/Checkbox.scss
  polaris-react/src/components/Checkbox/Checkbox.tsx
  polaris-react/src/components/Checkbox/tests/Checkbox.test.tsx
  polaris-react/src/components/Choice/Choice.tsx
  polaris-react/src/components/Choice/tests/Choice.test.tsx
  polaris-react/src/components/RadioButton/RadioButton.scss
  polaris-react/src/components/RadioButton/RadioButton.tsx
  polaris-react/src/components/RadioButton/tests/RadioButton.test.tsx
Labels: 🤖Skip Comment Check

#9616 Index table sticky header fixes
  polaris-react/src/components/IndexTable/IndexTable.scss
Labels: 🤖Skip Changelog

#9619 [Tabs][Uplift]: Match hover and active colour
  polaris-react/src/components/Tabs/Tabs.scss
Labels: 🤖Skip Changelog

#9604 [IndexTable, Tabs, LegacyCard] update tokens
  polaris-react/src/components/IndexTable/IndexTable.scss
  polaris-react/src/components/LegacyCard/LegacyCard.scss
Labels: 🤖Skip Changelog

#9644 [Nav] Fix item image filter color
  polaris-react/src/components/Navigation/_variables.scss
Labels: 🤖Skip Changelog

#9638 Add `ShadowBevel` component and mixin
  polaris-react/src/components/ShadowBevel/ShadowBevel.scss
  polaris-react/src/components/ShadowBevel/ShadowBevel.stories.tsx
  polaris-react/src/components/ShadowBevel/ShadowBevel.tsx
  polaris-react/src/components/ShadowBevel/index.ts
  polaris-react/src/components/ShadowBevel/tests/ShadowBevel.test.tsx
  polaris-react/src/styles/_common.scss
  polaris-react/src/styles/foundation/_shadow-bevel.scss
  polaris-tokens/src/token-groups/shadow.ts
Labels: 🤖Skip Changelog

#9650 Apply shadow-bevel to Card
  polaris-react/src/components/Card/Card.tsx
Labels: 🤖Skip Changelog

#9659 [Banner Experimental] Bump dismiss button icon override specificity
  polaris-react/src/components/Banner/components/BannerExperimental/BannerExperimental.scss
Labels: 🤖Skip Changelog

#9655 [Tabs] Update hover and active experimental colors
  polaris-react/src/components/Tabs/Tabs.scss
  polaris-react/src/components/Tabs/Tabs.tsx
Labels: 🤖Skip Changelog

#9656 [ActionList] Bump gap between prefix + content + suffix from 2 to 3
  polaris-react/src/components/ActionList/components/Item/Item.tsx
Labels: 🤖Skip Changelog

#9643 Update `Button` `pressed` hover and active states
  polaris-react/src/components/ButtonGroup/ButtonGroup.scss
  polaris-react/src/components/ButtonGroup/ButtonGroup.stories.tsx
  polaris-react/src/styles/shared/_buttons.scss
Labels: 🤖Skip Changelog

#9666 [Button] Update iconOnly plain to subdued icon
  .changeset/swift-onions-study.md
  polaris-react/src/components/Button/Button.scss
Labels: 🤖Skip Changelog

#9667 Remove experimental changeset
  .changeset/swift-onions-study.md
Labels: 🤖Skip Changelog

#9649 [IndexTable] Select all overlay height adjustment
  polaris-react/src/components/IndexTable/IndexTable.scss
Labels: 🤖Skip Changelog

#9657 Update LegacyFilters
  polaris-react/src/components/LegacyFilters/LegacyFilters.stories.tsx
  polaris-react/src/components/LegacyFilters/LegacyFilters.tsx
  polaris-react/src/components/LegacyFilters/components/ConnectedFilterControl/ConnectedFilterControl.scss
Labels: 🤖Skip Changelog, #gsd:32218

#9652 Apply shadow-bevel to Toast component
  polaris-react/src/components/Frame/components/Toast/Toast.scss
Labels: 🤖Skip Changelog

#9672 [Navigation] Fix navigation on hover actions
  polaris-react/src/components/Navigation/Navigation.scss
Labels: 🤖Skip Changelog

#9680 [LegacyTabs] Fix markup of Tab content for LegacyTabs using URL prop
  polaris-react/src/components/LegacyTabs/LegacyTabs.stories.tsx
  polaris-react/src/components/LegacyTabs/components/Tab/Tab.tsx
Labels: 🤖Skip Changelog

#9681 Hide Button text when loading for all style variants
  polaris-react/src/components/Button/Button.scss
  polaris-react/src/components/Button/Button.stories.tsx
Labels: 🤖Skip Changelog

#9663 Adjust link and plain button focus ring
  polaris-react/src/components/Button/Button.scss
  polaris-react/src/components/Link/Link.scss
Labels: 🤖Skip Changelog

#9696 [IndexTable] Fix select mode jank
  polaris-react/src/components/CheckableButton/CheckableButton.scss
Labels: 🤖Skip Changelog

#9700 [LegacyCard] Center LegacyCard.Heading content
  polaris-react/src/components/LegacyCard/LegacyCard.scss
  polaris-react/src/components/LegacyCard/LegacyCard.stories.tsx
  polaris-react/src/components/LegacyCard/components/Header/Header.tsx
Labels: 🤖Skip Changelog

#9702 [RadioButton, Checkbox] Fix styling and transitions
  polaris-react/src/components/Checkbox/Checkbox.scss
  polaris-react/src/components/RadioButton/RadioButton.scss
  polaris-react/src/styles/shared/_controls.scss
Labels: 🤖Skip Changelog

#9711 [Navigation] Fix background colour for items without url
  polaris-react/src/components/Navigation/Navigation.stories.tsx
  polaris-react/src/components/Navigation/components/Item/Item.tsx
Labels: 🤖Skip Changelog

#9714 Apply `shadow-bevel` to `Tooltip`
  polaris-react/src/components/Tooltip/Tooltip.tsx
  polaris-react/src/components/Tooltip/components/TooltipOverlay/TooltipOverlay.scss
  polaris-react/src/components/Tooltip/components/TooltipOverlay/TooltipOverlay.tsx
Labels: 🤖Skip Changelog

#9713 Add `shadow-bevel` opt out flag
  polaris-react/.storybook/manager.js
  polaris-react/.storybook/preview.js
  polaris-react/src/components/AppProvider/AppProvider.scss
  polaris-react/src/components/AppProvider/AppProvider.tsx
  polaris-react/src/components/Banner/Banner.scss
  polaris-react/src/components/LegacyCard/LegacyCard.scss
  polaris-react/src/components/ShadowBevel/ShadowBevel.tsx
  polaris-react/src/components/Tooltip/components/TooltipOverlay/TooltipOverlay.scss
  polaris-react/src/styles/_common.scss
  polaris-react/src/styles/foundation/_shadow-bevel.scss
  polaris-react/src/utilities/features/context.ts
  polaris-react/src/utilities/features/types.ts
Labels: 🤖Skip Changelog

#9722 Update `IndexFilters` `DirectionButton` styles
  polaris-react/src/components/IndexFilters/components/SortButton/components/DirectionButton/DirectionButton.scss
  polaris-react/src/components/IndexFilters/components/SortButton/components/DirectionButton/DirectionButton.tsx
Labels: 🤖Skip Changelog

#9724 [Index Filters] Fix search jumpiness
  polaris-react/src/components/Filters/Filters.tsx
Labels: 🤖Skip Changelog

#9737 Update `default` and `primary` button disabled styles
  polaris-react/src/components/Button/Button.scss
Labels: 🤖Skip Changelog

#9738 [PageActions]Remove border top
  polaris-react/src/components/PageActions/PageActions.scss
Labels: 🤖Skip Changelog

#9755 [ActionList] Fix focus ring border radius
  polaris-react/src/components/ActionList/ActionList.scss
Labels: 🤖Skip Changelog, #gsd:32218

#9767 Rename `shadow-bevel` opt out class name
  polaris-react/src/styles/_common.scss
  polaris-react/src/utilities/features/context.ts
Labels: 🤖Skip Changelog

#9743 [Button] Add vertical align middle to plain buttons
  polaris-react/src/components/Button/Button.scss
Labels: 🤖Skip Changelog

#9763 Update `Select` disabled state styles
  polaris-react/src/components/Select/Select.scss
Labels: 🤖Skip Changelog

#9768 Update `RadioButton` disabled styles
  polaris-react/src/components/RadioButton/RadioButton.scss
Labels: 🤖Skip Changelog

#9785 Icon button plain destructive `active` and `hover` styles
  polaris-react/src/components/Button/Button.scss
  polaris-tokens/src/token-groups/color.ts
Labels: 🤖Skip Changelog

#9784 Updated bg-transparent-subdued value
  polaris-tokens/src/token-groups/color.ts
Labels: 🤖Skip Changelog

#9795 Fix missing Inter font on existing `font-family-sans` usages
  polaris-react/src/components/AppProvider/AppProvider.scss
  polaris-tokens/src/token-groups/font.ts
Labels: 🤖Skip Changelog

#9793 Remove unused experimental tokens and clean up experimental token usage
  polaris-react/src/components/Button/Button.scss
  polaris-tokens/src/token-groups/color.ts
  polaris-tokens/src/token-groups/shadow.ts
Labels: 🤖Skip Changelog

#9808 [Breadcrumb] add `backAction.onAction` to button click
  polaris-react/src/components/Breadcrumbs/Breadcrumbs.tsx
  polaris-react/src/components/Page/Page.stories.tsx
Labels: 🤖Skip Changelog

#9781 Update disabled `Checkbox` styles
  polaris-react/src/components/Checkbox/Checkbox.scss
Labels: 🤖Skip Changelog

#9813 [EmptyState] Update EmptyState Text size and color for children and footer
  polaris-react/src/components/EmptyState/EmptyState.tsx
Labels: 🤖Skip Changelog

#9766 [Navigation] Fixed visual regressions
  polaris-react/src/components/Navigation/Navigation.scss
Labels: 🤖Skip Changelog

#9719 [Checkbox] Restyled Checkbox with box-shadow to fit gen3 and fix display issues
  polaris-react/src/components/Checkbox/Checkbox.scss
  polaris-react/src/styles/shared/_controls.scss
Labels: 🤖Skip Changelog

#9815 [OptionList] Remove section dividers
  polaris-react/src/components/OptionList/OptionList.tsx
Labels: 🤖Skip Changelog

#9816 [IndexFilters] Update cancel/save button spacing
  polaris-react/src/components/Filters/Filters.scss
  polaris-react/src/components/Filters/Filters.tsx
  polaris-react/src/components/IndexFilters/IndexFilters.tsx
  polaris-react/src/components/IndexFilters/components/UpdateButtons/UpdateButtons.tsx
Labels: 🤖Skip Changelog

#9806 [Page] Fix additionalMeta alignment with no BackAction
  polaris-react/src/components/Page/Page.stories.tsx
  polaris-react/src/components/Page/components/Header/Header.scss
Labels: 🤖Skip Changelog

#9805 [Tabs] fix hover bg color
  polaris-react/src/components/Tabs/Tabs.scss
Labels: 🤖Skip Changelog

#9825 tweaks to content
  .github/workflows/ci.yml
  polaris.shopify.com/content/new-design-language/index.md
  polaris.shopify.com/pages/new-design-language/index.tsx
  polaris.shopify.com/tsconfig.json
Labels: 🤖Skip Changelog

#9833 Update version format in the New Design Language page
  polaris.shopify.com/content/new-design-language/index.md
Labels: 🤖Skip Changelog

#9837 fixed install instructions
  polaris.shopify.com/content/new-design-language/index.md
Labels: 🤖Skip Changelog

#9842 added whats new section for uplift
  polaris.shopify.com/pages/whats-new.tsx
  polaris.shopify.com/public/images/updates/uplift-beta@2x.png
  polaris.shopify.com/public/images/updates/uplift-blogpost@2x.png
Labels: 🤖Skip Changelog

#9854 [Icons] Cancel Icons updates
  .changeset/olive-turkeys-bathe.md
  polaris-icons/icons/CancelMajor.svg
  polaris-icons/icons/CancelMajor.yml
  polaris-icons/icons/CancelMinor.svg
  polaris-icons/icons/CancelMinor.yml
Labels: Icon
