Repository Shopify/polaris, pull requests merged in 2023-10, with the labels that each got.

#10809 [Docs] Add in `color` replacement maps in v12 migration guide
  polaris.shopify.com/content/version-guides/migrating-from-v11-to-v12.md
Labels: #gsd:36565

#10674 Remove deprecated v11 custom properties
  polaris-react/src/components/Banner/Banner.tsx
  polaris-react/src/components/Icon/Icon.stories.tsx
  polaris-react/src/utilities/sticky-manager/sticky-manager.ts
  polaris-tokens/src/themes/base/border.ts
  polaris-tokens/src/themes/base/font.ts
  polaris-tokens/src/themes/base/shadow.ts
  polaris-tokens/src/themes/base/space.ts
  polaris-tokens/src/themes/light-high-contrast.ts
  polaris-tokens/src/themes/light-uplift.ts
Labels: #gsd:36565

#10812 Fix Patterns page TOC
  polaris.shopify.com/src/components/PatternPage/PatternPage.tsx
Labels: 🤖Skip Changelog

#10705 [IndexTable.Row] Fix `tone` interaction states; remove `subdued` and `status`
  .changeset/dirty-pugs-retire.md
  polaris-react/src/components/IndexTable/IndexTable.scss
  polaris-react/src/components/IndexTable/IndexTable.stories.tsx
  polaris-react/src/components/IndexTable/components/Row/Row.tsx
  polaris-react/src/components/IndexTable/components/Row/tests/Row.test.tsx
  polaris.shopify.com/content/components/tables/index-table.md
  polaris.shopify.com/content/version-guides/migrating-from-v11-to-v12.md
  polaris.shopify.com/content/whats-new/version-12.md
Labels: 🤖Skip Comment Check, 🤖Skip Major Check, #gsd:36579, next

#10815 Update stepped migration documentation
  polaris.shopify.com/content/version-guides/migrating-from-v11-to-v12.md
Labels: #gsd:36565

#10816 [Docs] Update new design language page for `v12.0.0-beta.2` release guidance
  polaris.shopify.com/content/new-design-language/index.md
  polaris.shopify.com/pages/whats-new.tsx
Labels: 🤖Skip Changelog, #gsd:36579

#10706 [polaris.shopify.com] Add `Docs` depth pages
  polaris.shopify.com/content/design/depth/creating-depth.md
  polaris.shopify.com/content/design/depth/index.md
  polaris.shopify.com/public/images/design/depth/creating/depth-creating-10@2x.png
  polaris.shopify.com/public/images/design/depth/creating/depth-creating-11@2x.png
  polaris.shopify.com/public/images/design/depth/creating/depth-creating-12@2x.png
  polaris.shopify.com/public/images/design/depth/creating/depth-creating-13@2x.png
  polaris.shopify.com/public/images/design/depth/creating/depth-creating-14@2x.png
  polaris.shopify.com/public/images/design/depth/creating/depth-creating-15@2x.png
  polaris.shopify.com/public/images/design/depth/creating/depth-creating-16@2x.png
  polaris.shopify.com/public/images/design/depth/creating/depth-creating-17@2x.png
  polaris.shopify.com/public/images/design/depth/creating/depth-creating-1@2x.png
  polaris.shopify.com/public/images/design/depth/creating/depth-creating-2@2x.png
  polaris.shopify.com/public/images/design/depth/creating/depth-creating-3@2x.png
  polaris.shopify.com/public/images/design/depth/creating/depth-creating-4@2x.png
  polaris.shopify.com/public/images/design/depth/creating/depth-creating-5@2x.png
  polaris.shopify.com/public/images/design/depth/creating/depth-creating-6@2x.png
  polaris.shopify.com/public/images/design/depth/creating/depth-creating-7@2x.png
  polaris.shopify.com/public/images/design/depth/creating/depth-creating-8@2x.png
  polaris.shopify.com/public/images/design/depth/creating/depth-creating-9@2x.png
  polaris.shopify.com/public/images/design/depth/overview/depth-overview-10@2x.png
  polaris.shopify.com/public/images/design/depth/overview/depth-overview-1@2x.png
  polaris.shopify.com/public/images/design/depth/overview/depth-overview-2@2x.png
  polaris.shopify.com/public/images/design/depth/overview/depth-overview-3@2x.png
  polaris.shopify.com/public/images/design/depth/overview/depth-overview-4@2x.png
  polaris.shopify.com/public/images/design/depth/overview/depth-overview-5@2x.png
  polaris.shopify.com/public/images/design/depth/overview/depth-overview-6@2x.png
  polaris.shopify.com/public/images/design/depth/overview/depth-overview-7@2x.png
  polaris.shopify.com/public/images/design/depth/overview/depth-overview-8@2x.png
  polaris.shopify.com/public/images/design/depth/overview/depth-overview-9@2x.png
  polaris.shopify.com/src/components/Markdown/components/DoDont/index.tsx
  polaris.shopify.com/src/components/Markdown/components/DoDont/styles.module.scss
Labels: 🤖Skip Changelog, #gsd:36550

#10873 [InlineGrid] Fix typo in typedoc @example for `columns` prop
  polaris-react/src/components/InlineGrid/InlineGrid.tsx
Labels: 🤖Skip Changelog, 🤖Skip Major Check, #gsd:36579

#10874 Add `v12-react-avatar-component` migration
  .changeset/spotty-garlics-kick.md
  polaris-migrator/src/migrations/v12-react-avatar-component/tests/transform.test.ts
  polaris-migrator/src/migrations/v12-react-avatar-component/tests/v12-react-avatar-component.input.tsx
  polaris-migrator/src/migrations/v12-react-avatar-component/tests/v12-react-avatar-component.output.tsx
  polaris-migrator/src/migrations/v12-react-avatar-component/transform.ts
Labels: #gsd:36579, #gsd:36565

#10877 Fix column layout conflict with DoDont component
  polaris.shopify.com/content/design/colors/index.md
  polaris.shopify.com/content/design/icons/creating-icons.md
  polaris.shopify.com/content/design/icons/index.md
  polaris.shopify.com/content/design/icons/using-icons.md
  polaris.shopify.com/content/design/typography/font-and-typescale.md
  polaris.shopify.com/content/design/typography/index.md
  polaris.shopify.com/content/design/typography/using-type.md
  polaris.shopify.com/src/components/Markdown/components/DoDont/styles.module.scss
Labels: 🤖Skip Changelog

#10881 Update description for `Spacial organization` page
  polaris.shopify.com/content/design/layout/spacial-organization.md
Labels: 🤖Skip Changelog

#10899 Update `snapit` workflow to use the GitHub CLI
  .github/workflows/snapit.yml
Labels: 🤖Skip Changelog

#10930 fixed dark mode menu button on Safari
  polaris.shopify.com/src/components/Frame/Frame.module.scss
Labels: 🤖Skip Changelog

#10932 Change comment in SettingToggle so it does not fail build-validate script
  polaris-react/src/components/SettingToggle/SettingToggle.tsx
Labels: 🤖Skip Changelog

#10940 [polaris.shopify.com] Fix thumbnail images in safari
  polaris.shopify.com/src/components/ThumbnailPreview/index.tsx
Labels: 🤖Skip Changelog

#10943 [v12 Migration guide] Update component migration commands
  polaris.shopify.com/content/version-guides/migrating-from-v11-to-v12.md
  polaris.shopify.com/src/styles/globals.scss
Labels: 🤖Skip Changelog

#10947 Add `new` label to /design
  polaris.shopify.com/content/design/index.md
Labels: 🤖Skip Changelog

#10951 [polaris.shopify.com] Fix layout-tokens do usages
  polaris.shopify.com/content/design/layout/layout-tokens.md
Labels: 🤖Skip Changelog

#10910 Fix segmented `ButtonGroup` spacing
  .changeset/proud-cougars-turn.md
  polaris-react/src/components/Button/Button.stories.tsx
  polaris-react/src/components/ButtonGroup/ButtonGroup.scss
Labels: #gsd:36579

#10969 Fix modal migration title in guide
  polaris.shopify.com/content/version-guides/migrating-from-v11-to-v12.md
Labels: 🤖Skip Changelog

#10970 [polaris.shopify.com] Wrap `Avatar` migration docs in CollapsibleDetails
  polaris.shopify.com/content/version-guides/migrating-from-v11-to-v12.md
Labels: 🤖Skip Changelog, #gsd:36579

#10964 [polaris.shopify.com] Fix do / don't layouts in Safari
  polaris.shopify.com/src/components/Markdown/components/DoDont/index.tsx
  polaris.shopify.com/src/components/Markdown/components/DoDont/styles.module.scss
Labels: 🤖Skip Changelog

#10973 Add layout components for improving MDX
  polaris.shopify.com/content/design/colors/index.md
  polaris.shopify.com/src/components/Markdown/Markdown.tsx
  polaris.shopify.com/src/components/Markdown/components/Mdx/Mdx.module.css
  polaris.shopify.com/src/components/Markdown/components/Mdx/index.tsx
Labels: 🤖Skip Changelog

#10986 [polaris.shopify.com] Set up deep linking to component examples
  polaris.shopify.com/pages/components/[group]/[component]/index.tsx
  polaris.shopify.com/src/components/ComponentExamples/ComponentExamples.module.scss
  polaris.shopify.com/src/components/ComponentExamples/ComponentExamples.tsx
  polaris.shopify.com/src/styles/globals.scss
Labels: 🤖Skip Changelog

#11033 Add Section, Row, Column components for MDX
  polaris.shopify.com/content/design/motion/index.md
  polaris.shopify.com/src/components/Markdown/Markdown.tsx
  polaris.shopify.com/src/components/Markdown/components/Mdx/index.tsx
Labels: 🤖Skip Changelog

#11032 [Sandbox] Enforce null origin for sandbox preview iframes
  patches/playroom+0.28.0.patch
  polaris.shopify.com/pages/sandbox/index.tsx
  polaris.shopify.com/pages/sandbox/preview.tsx
  polaris.shopify.com/playroom.config.js
  polaris.shopify.com/playroom/FrameComponent.tsx
  polaris.shopify.com/src/components/PatternsExample/PatternsExample.tsx
  polaris.shopify.com/src/components/PlayroomLink/PlayroomLink.tsx
  polaris.shopify.com/src/components/SandboxHeader/SandboxHeader.module.scss
  polaris.shopify.com/src/components/SandboxHeader/SandboxHeader.tsx
Labels: 🤖Skip Changelog

#11030 Update `stylelint-polaris` version matchups chart
  .changeset/silver-baboons-laugh.md
  polaris.shopify.com/content/tools/stylelint-polaris.md
Labels: #gsd:36579, #gsd:36565

#11028 Migration guide patch
  .changeset/silly-ducks-sit.md
  polaris-react/src/components/Button/utils.tsx
  polaris-react/src/components/Checkbox/Checkbox.scss
  polaris-react/src/components/Modal/Modal.stories.tsx
  polaris.shopify.com/content/components/overlays/modal.md
  polaris.shopify.com/content/whats-new/version-11-tokens.md
  polaris.shopify.com/pages/examples/modal-with-destructive-primary-action.tsx
Labels: Bug, P1

#10949 Add `/design` middleware to get all card grid posts
  polaris.shopify.com/pages/[...slug].tsx
Labels: 🤖Skip Changelog

#10795 fix(docs): text variant tokens
  .changeset/angry-months-agree.md
  polaris.shopify.com/content/components/typography/text.md
Labels: 🤖Skip Changelog, Contribution, 🤖Skip Comment Check, 🤖Skip Major Check

#11051 Alphabetize component list in v11 to v12 migration guide
  .changeset/honest-zoos-act.md
  polaris.shopify.com/content/version-guides/migrating-from-v11-to-v12.md
Labels: #gsd:36579

#11062 [ContextualSaveBar] Update icon from CircleAlertMajor to RiskMajor
  .changeset/hip-houses-accept.md
  polaris-react/src/components/ContextualSaveBar/ContextualSaveBar.stories.tsx
  polaris-react/src/components/Frame/Frame.stories.tsx
  polaris-react/src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.tsx
  polaris-react/src/components/TopBar/TopBar.stories.tsx
  polaris.shopify.com/pages/examples/contextual-save-bar-default.tsx
  polaris.shopify.com/pages/examples/contextual-save-bar-with-flush-contents.tsx
  polaris.shopify.com/pages/examples/contextual-save-bar-with-full-width.tsx
  polaris.shopify.com/pages/examples/frame-in-an-application.tsx
  polaris.shopify.com/pages/examples/frame-with-an-offset.tsx
  polaris.shopify.com/pages/examples/top-bar-default.tsx
Labels: #gsd:36579

#11061 [TextField] Fix Spinner border radius
  .changeset/famous-peas-shave.md
  polaris-react/src/components/TextField/TextField.scss
Labels: Bug

#11066 [IndexTable] Fix header tooltip styling
  .changeset/weak-roses-doubt.md
  polaris-react/src/components/IndexTable/IndexTable.tsx
Labels: Bug
