Repository Shopify/polaris, pull requests merged in 2023-05, with the labels that each got.

#9109 Update MarketingMajor
  .changeset/lucky-plums-shop.md
  polaris-icons/icons/MarketingMajor.svg
Labels: Icon

#9172 Enhance and simplify contribution documentation
  .changeset/lovely-monkeys-drum.md
  polaris.shopify.com/content/contributing/code-of-conduct.md
  polaris.shopify.com/content/contributing/components.md
  polaris.shopify.com/content/contributing/documentation.md
  polaris.shopify.com/content/contributing/figma-ui-kit.md
  polaris.shopify.com/content/contributing/icons.md
  polaris.shopify.com/content/contributing/illustrations.md
  polaris.shopify.com/content/contributing/index.md
  polaris.shopify.com/content/contributing/shipping-your-contribution.md
  polaris.shopify.com/content/contributing/when-to-contribute-new-patterns.md
  polaris.shopify.com/content/contributing/working-with-the-polaris-team.md
  polaris.shopify.com/content/getting-started/designing-with-a-system.md
  polaris.shopify.com/content/tools/polaris-cli.md
  polaris.shopify.com/content/tools/polaris-for-vscode.md
  polaris.shopify.com/content/tools/polaris-migrator.md
  polaris.shopify.com/content/tools/sandbox.md
  polaris.shopify.com/content/tools/stylelint-polaris/index.md
Labels: cla-needed, polaris.shopify.com

#9178 Remove links to the /contribution/shipping-your-contribution page
  polaris.shopify.com/content/contributing/components.md
  polaris.shopify.com/content/contributing/documentation.md
  polaris.shopify.com/content/contributing/icons.md
Labels: 🤖Skip Changelog

#8774 Create version-11-color.md
  .changeset/rude-teachers-doubt.md
  polaris.shopify.com/content/whats-new/version-11-color.md
  polaris.shopify.com/public/images/updates/alias-tokens.png
  polaris.shopify.com/public/images/updates/new-colors-cover.png
  polaris.shopify.com/public/images/updates/new-palette.png
  polaris.shopify.com/public/images/updates/old-palette.png
  polaris.shopify.com/src/components/WhatsNewListing/WhatsNewListing.module.scss
Labels: v11.0.0

#9233 [v11.x.x] Fix Storybook AppProviderDecorator
  polaris-react/.storybook/preview.js
  polaris-react/src/components/AppProvider/AppProvider.stories.tsx
  polaris-react/src/components/Frame/Frame.stories.tsx
  polaris-react/src/utilities/features/context.ts
  polaris-react/src/utilities/features/tests/hooks.test.tsx
Labels: #gsd:32218

#9303 Use minor release for sub v1 packages
  .changeset/cool-starfishes-cry.md
  .changeset/quiet-toes-play.md
Labels: 🤖Skip Major Check

#8840 Update design/color page
  .changeset/chilly-news-tan.md
  polaris.shopify.com/content/design/colors.md
  polaris.shopify.com/public/images/design/colors/color-intro@2x.png
  polaris.shopify.com/public/images/design/colors/color-role-critical@2x.png
  polaris.shopify.com/public/images/design/colors/color-role-decorative@2x.png
  polaris.shopify.com/public/images/design/colors/color-role-highlight@2x.png
  polaris.shopify.com/public/images/design/colors/color-role-interactive@2x.png
  polaris.shopify.com/public/images/design/colors/color-role-onsurface@2x.png
  polaris.shopify.com/public/images/design/colors/color-role-primary@2x.png
  polaris.shopify.com/public/images/design/colors/color-role-secondary@2x.png
  polaris.shopify.com/public/images/design/colors/color-role-success@2x.png
  polaris.shopify.com/public/images/design/colors/color-role-surface@2x.png
  polaris.shopify.com/public/images/design/colors/color-role-warning@2x.png
  polaris.shopify.com/public/images/design/colors/color-roles@2x.png
  polaris.shopify.com/public/images/design/colors/color-token-naming-example@2x.png
  polaris.shopify.com/public/images/design/colors/color-tokens@2x.png
  polaris.shopify.com/public/images/design/colors/color-usage-123@2x.png
  polaris.shopify.com/public/images/design/colors/color-variant-naming@2x.png
  polaris.shopify.com/public/images/design/colors/color-variants@2x.png
  polaris.shopify.com/public/images/design/colors/interaction-states@2x.png
  polaris.shopify.com/src/styles/globals.scss
  polaris.shopify.com/src/utils/markdown.mjs
  polaris.shopify.com/tsconfig.json
Labels: v11.0.0

#9295 [Avatar] Fix initials overflowing when round
  .changeset/eight-windows-glow.md
  polaris-react/src/components/Avatar/Avatar.scss
  polaris-react/src/components/Avatar/Avatar.stories.tsx
  polaris.shopify.com/content/components/images-and-icons/avatar.md
  polaris.shopify.com/pages/examples/avatar-initials.tsx
Labels: Bug
