Repository Shopify/polaris, pull requests merged in 2023-04, with the labels that each got.

#8831 fix stylelint needless disable failure
  polaris-react/src/components/Tooltip/components/TooltipOverlay/TooltipOverlay.scss
Labels: 🤖Skip Changelog

#8866 Fix changeset for added prop
  .changeset/odd-mayflies-sip.md
Labels: 🤖Skip Changelog, 🤖Skip Comment Check

#8863 [Toast][InlineError]Update icon for critical state
  .changeset/unlucky-fireants-kiss.md
  polaris-react/src/components/Frame/components/Toast/Toast.tsx
  polaris-react/src/components/InlineError/InlineError.tsx
Labels: Component

#8584 Add workflow for encouraging issue activity and auto closing issues
  .github/workflows/stale.yml
Labels: 🤖Skip Changelog

#8884 AppProvider patterns
  polaris-patterns/.storybook/preview.js
  polaris-patterns/config/rollup/namespaced-classname.js
  polaris-patterns/src/components/AppProvider/AppProvider.tsx
  polaris-patterns/src/components/AppProvider/index.ts
  polaris-patterns/src/configure.ts
  polaris-patterns/src/index.ts
Labels: #gsd:33833

#8874 [SettingToggle] Update do/dont images with typo fix
  polaris.shopify.com/public/images/components/deprecated/setting-toggle/Do.png
  polaris.shopify.com/public/images/components/deprecated/setting-toggle/Dont.png
Labels: Bug, 🤖Skip Changelog

#8887 Bump size limit
  package.json
Labels: 🤖Skip Changelog

#8889 Update `ContextualSaveBar` overrides
  .changeset/empty-numbers-tickle.md
  polaris-react/src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.scss
Labels: v11.0.0

#8936 Rename Inline to HorizontalStack
  .changeset/afraid-lizards-know.md
  polaris-react/src/components/AccountConnection/AccountConnection.tsx
  polaris-react/src/components/ActionList/components/Item/Item.tsx
  polaris-react/src/components/AlphaFilters/AlphaFilters.tsx
  polaris-react/src/components/AlphaFilters/components/FilterPill/FilterPill.tsx
  polaris-react/src/components/AlphaTabs/components/Tab/Tab.tsx
  polaris-react/src/components/Banner/Banner.stories.tsx
  polaris-react/src/components/BulkActions/BulkActions.tsx
  polaris-react/src/components/DropZone/DropZone.stories.tsx
  polaris-react/src/components/EmptyState/EmptyState.tsx
  polaris-react/src/components/EmptyState/tests/EmptyState.test.tsx
  polaris-react/src/components/Frame/components/Toast/Toast.tsx
  polaris-react/src/components/HorizontalStack/HorizontalStack.scss
  polaris-react/src/components/HorizontalStack/HorizontalStack.stories.tsx
  polaris-react/src/components/HorizontalStack/HorizontalStack.tsx
  polaris-react/src/components/HorizontalStack/index.ts
  polaris-react/src/components/HorizontalStack/tests/HorizontalStack.test.tsx
  polaris-react/src/components/IndexFilters/IndexFilters.tsx
  polaris-react/src/components/IndexFilters/components/SearchFilterButton/SearchFilterButton.tsx
  polaris-react/src/components/IndexFilters/components/UpdateButtons/UpdateButtons.tsx
  polaris-react/src/components/Inline/index.ts
  polaris-react/src/components/MediaCard/MediaCard.tsx
  polaris-react/src/components/Modal/Modal.tsx
  polaris-react/src/components/Modal/components/Footer/Footer.tsx
  polaris-react/src/components/Modal/components/Header/Header.tsx
  polaris-react/src/components/Page/components/Header/Header.tsx
  polaris-react/src/components/ResourceItem/ResourceItem.tsx
  polaris-react/src/components/ResourceItem/tests/ResourceItem.test.tsx
  polaris-react/src/components/SettingToggle/SettingToggle.stories.tsx
  polaris-react/src/components/SkeletonPage/SkeletonPage.tsx
  polaris-react/src/index.ts
  polaris.shopify.com/content/components/layout-and-structure/columns.md
  polaris.shopify.com/content/components/layout-and-structure/horizontal-stack.md
  polaris.shopify.com/content/components/layout-and-structure/vertical-stack.md
  polaris.shopify.com/content/design/layout.md
  polaris.shopify.com/content/patterns/date-picking/variants/date-range.md
  polaris.shopify.com/next.config.js
  polaris.shopify.com/pages/examples/bleed-horizontal.tsx
  polaris.shopify.com/pages/examples/bleed-specific-direction.tsx
  polaris.shopify.com/pages/examples/bleed-vertical.tsx
  polaris.shopify.com/pages/examples/box-with-padding.tsx
  polaris.shopify.com/pages/examples/columns-with-fixed-widths.tsx
  polaris.shopify.com/pages/examples/horizontal-stack-with-align.tsx
  polaris.shopify.com/pages/examples/horizontal-stack-with-block-align.tsx
  polaris.shopify.com/pages/examples/horizontal-stack-with-gap.tsx
  polaris.shopify.com/pages/examples/horizontal-stack-with-non-wrapping.tsx
  polaris.shopify.com/pages/examples/index-table-condensed-with-views-search-filter-sorting.tsx
  polaris.shopify.com/pages/examples/index-table-small-screen.tsx
  polaris.shopify.com/pages/examples/setting-toggle-with-primitive-components.tsx
  polaris.shopify.com/pages/examples/tooltip-with-suffix.tsx
  polaris.shopify.com/pages/examples/vertical-stack-with-align.tsx
  polaris.shopify.com/pages/examples/vertical-stack-with-inline-align.tsx
  polaris.shopify.com/public/images/components/layout-and-structure/horizontal-stack.png
  polaris.shopify.com/src/components/TipBanner/TipBanner.tsx
Labels: 🤖Skip Comment Check

#8937 Rename Columns to HorizontalGrid
  .changeset/loud-clouds-kiss.md
  polaris-react/src/components/Columns/index.ts
  polaris-react/src/components/HorizontalGrid/HorizontalGrid.scss
  polaris-react/src/components/HorizontalGrid/HorizontalGrid.stories.tsx
  polaris-react/src/components/HorizontalGrid/HorizontalGrid.tsx
  polaris-react/src/components/HorizontalGrid/index.ts
  polaris-react/src/components/HorizontalGrid/tests/HorizontalGrid.test.tsx
  polaris-react/src/components/Modal/components/Header/Header.tsx
  polaris-react/src/components/ResourceItem/ResourceItem.tsx
  polaris-react/src/index.ts
  polaris.shopify.com/content/components/layout-and-structure/horizontal-grid.md
  polaris.shopify.com/content/components/layout-and-structure/horizontal-stack.md
  polaris.shopify.com/content/components/layout-and-structure/index.md
  polaris.shopify.com/content/design/layout.md
  polaris.shopify.com/content/patterns/app-settings-layout/variants/default.md
  polaris.shopify.com/content/patterns/date-picking/variants/date-range.md
  polaris.shopify.com/content/patterns/resource-details-layout/variants/default.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/layout-property-disallowed-list.md
  polaris.shopify.com/next.config.js
  polaris.shopify.com/pages/examples/horizontal-grid-with-fixed-widths.tsx
  polaris.shopify.com/pages/examples/horizontal-grid-with-set-number.tsx
  polaris.shopify.com/pages/examples/horizontal-grid-with-varying-gap.tsx
  polaris.shopify.com/public/images/components/layout-and-structure/horizontal-grid.png
Labels: 🤖Skip Comment Check

#8948 [Layout foundations] Update redirects for renamed layout components
  polaris.shopify.com/next.config.js
  polaris.shopify.com/public/images/components/layout-and-structure/alpha-stack.png
Labels: 🤖Skip Changelog, #gsd:30116

#8954 [Layout foundations] Update layout component custom properties
  .changeset/rotten-coats-drive.md
  polaris-react/src/components/HorizontalGrid/HorizontalGrid.scss
  polaris-react/src/components/HorizontalGrid/HorizontalGrid.tsx
  polaris-react/src/components/HorizontalGrid/tests/HorizontalGrid.test.tsx
  polaris-react/src/components/HorizontalStack/HorizontalStack.scss
  polaris-react/src/components/HorizontalStack/HorizontalStack.tsx
  polaris-react/src/components/HorizontalStack/tests/HorizontalStack.test.tsx
  polaris-react/src/components/VerticalStack/VerticalStack.scss
  polaris-react/src/components/VerticalStack/VerticalStack.tsx
  polaris-react/src/components/VerticalStack/tests/VerticalStack.test.tsx
Labels: #gsd:30116

#8934 [Prototype] Add DateList to polaris-patterns
  polaris-patterns/.storybook/main.js
  polaris-patterns/package.json
  polaris-patterns/src/components/DateList/DateList.stories.tsx
  polaris-patterns/src/components/DateList/DateList.tsx
  polaris-patterns/src/components/DateList/index.ts
  polaris-patterns/src/components/DateList/tests/DateList.test.tsx
  polaris-patterns/src/index.ts
Labels: 🤖Skip Changelog

#8962 [Layout foundations] Mark components with API changes as alpha
  polaris.shopify.com/content/components/layout-and-structure/box.md
  polaris.shopify.com/content/components/layout-and-structure/card.md
  polaris.shopify.com/content/components/layout-and-structure/horizontal-grid.md
  polaris.shopify.com/content/components/layout-and-structure/horizontal-stack.md
  polaris.shopify.com/content/components/layout-and-structure/vertical-stack.md
Labels: #gsd:30116, v11.0.0

#8967 Add `stylelint-polaris` version matchup docs
  .changeset/old-suns-burn.md
  polaris.shopify.com/content/tools/stylelint-polaris/index.md
Labels: v11.0.0

#8953 [UserMenu] Allow activator content to be passed in Top bar menu
  .changeset/wicked-knives-begin.md
  polaris-react/src/components/ActionList/ActionList.tsx
  polaris-react/src/components/ActionList/components/Section/Section.tsx
  polaris-react/src/components/TopBar/TopBar.stories.tsx
  polaris-react/src/components/TopBar/components/Menu/Menu.tsx
  polaris-react/src/components/TopBar/components/UserMenu/UserMenu.scss
  polaris-react/src/components/TopBar/components/UserMenu/UserMenu.tsx
  polaris-react/src/types.ts
Labels: #gsd:32744

#8973 Enable `custom-property-disallowed-list` in `stylelint-polaris`
  .changeset/khaki-walls-wash.md
  polaris-react/src/components/AlphaFilters/AlphaFilters.scss
  polaris-react/src/components/AlphaTabs/AlphaTabs.scss
  polaris-react/src/components/IndexFilters/IndexFilters.scss
  polaris-react/src/components/TopBar/components/Menu/tests/Menu.test.tsx
  polaris.shopify.com/content/tools/stylelint-polaris/rules/colors-custom-property-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/colors-global-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/depth-custom-property-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/depth-global-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/layout-custom-property-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/layout-global-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/motion-global-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/shape-custom-property-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/shape-global-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/spacing-custom-property-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/spacing-global-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/typography-global-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/z-index-custom-property-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/z-index-global-disallowed-list.md
  stylelint-polaris/index.js
  stylelint-polaris/plugins/global-disallowed-list/index.test.js
Labels: v11.0.0

#8986 [Layout foundations] Add documentation for react-rename-component codemod
  .changeset/popular-papayas-breathe.md
  polaris.shopify.com/content/tools/polaris-migrator.md
Labels: #gsd:30116

#8910 <Box> Replace border shorthand with individual values for color, width and style
  .changeset/stale-tigers-serve.md
  polaris-react/src/components/ActionList/components/Section/Section.tsx
  polaris-react/src/components/AlphaTabs/AlphaTabs.tsx
  polaris-react/src/components/Bleed/Bleed.stories.tsx
  polaris-react/src/components/Box/Box.scss
  polaris-react/src/components/Box/Box.stories.tsx
  polaris-react/src/components/Box/Box.tsx
  polaris-react/src/components/Box/tests/Box.test.tsx
  polaris-react/src/components/IndexFilters/components/SortButton/SortButton.tsx
  polaris-react/src/components/LegacyTabs/LegacyTabs.tsx
  polaris-react/src/components/Modal/components/Footer/Footer.tsx
  polaris-react/src/components/Modal/components/Header/Header.tsx
  polaris-react/src/components/OptionList/OptionList.tsx
  polaris-react/src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx
  polaris-react/src/components/Tabs/Tabs.tsx
  polaris.shopify.com/pages/examples/bleed-horizontal.tsx
  polaris.shopify.com/pages/examples/bleed-specific-direction.tsx
  polaris.shopify.com/pages/examples/bleed-vertical.tsx
  polaris.shopify.com/pages/examples/box-with-border.tsx
Labels: v11.0.0

#8965 [Polaris Patterns] Add i18n translations to package
  babel.config.js
  polaris-patterns/.storybook/main.js
  polaris-patterns/.storybook/preview.js
  polaris-patterns/babel.config.js
  polaris-patterns/package.json
  polaris-patterns/src/components/AccountConnection/AccountConnection.stories.tsx
  polaris-patterns/src/components/DatePickerTextField/DatePickerTextField.stories.tsx
  polaris-patterns/src/components/DatePickerTextField/DatePickerTextField.tsx
  polaris-patterns/src/components/DatePickerTextField/tests/DatePickerTextField.test.tsx
  polaris-patterns/src/components/DatePickerTextField/translations/cs.json
  polaris-patterns/src/components/DatePickerTextField/translations/da.json
  polaris-patterns/src/components/DatePickerTextField/translations/de.json
  polaris-patterns/src/components/DatePickerTextField/translations/en.json
  polaris-patterns/src/components/DatePickerTextField/translations/es.json
  polaris-patterns/src/components/DatePickerTextField/translations/fi.json
  polaris-patterns/src/components/DatePickerTextField/translations/fr.json
  polaris-patterns/src/components/DatePickerTextField/translations/it.json
  polaris-patterns/src/components/DatePickerTextField/translations/ja.json
  polaris-patterns/src/components/DatePickerTextField/translations/ko.json
  polaris-patterns/src/components/DatePickerTextField/translations/nb.json
  polaris-patterns/src/components/DatePickerTextField/translations/nl.json
  polaris-patterns/src/components/DatePickerTextField/translations/pl.json
  polaris-patterns/src/components/DatePickerTextField/translations/pt-BR.json
  polaris-patterns/src/components/DatePickerTextField/translations/pt-PT.json
  polaris-patterns/src/components/DatePickerTextField/translations/sv.json
  polaris-patterns/src/components/DatePickerTextField/translations/th.json
  polaris-patterns/src/components/DatePickerTextField/translations/tr.json
  polaris-patterns/src/components/DatePickerTextField/translations/vi.json
  polaris-patterns/src/components/DatePickerTextField/translations/zh-CN.json
  polaris-patterns/src/components/DatePickerTextField/translations/zh-TW.json
  translation.yml
  yarn.lock
Labels: #gsd:33833

#9006 Update `polaris.shopify.com` and `stylelint-polaris` config categories for new token groups
  .changeset/khaki-penguins-obey.md
  polaris.shopify.com/content/components/layout-and-structure/alpha-card.md
  polaris.shopify.com/content/components/layout-and-structure/box.md
  polaris.shopify.com/content/components/layout-and-structure/divider.md
  polaris.shopify.com/content/contributing/index.md
  polaris.shopify.com/content/contributing/working-with-the-polaris-team.md
  polaris.shopify.com/content/design/layout.md
  polaris.shopify.com/content/design/typography.md
  polaris.shopify.com/content/patterns/date-picking/variants/date-range.md
  polaris.shopify.com/content/tokens.md
  polaris.shopify.com/content/tools/polaris-for-vscode.md
  polaris.shopify.com/content/tools/polaris-migrator.md
  polaris.shopify.com/content/tools/stylelint-polaris/index.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/border-at-rule-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/border-custom-property-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/border-declaration-property-unit-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/border-function-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/color-at-rule-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/color-color-named.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/color-color-no-hex.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/color-custom-property-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/color-function-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/color-global-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/colors-declaration-property-value-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/conventions-custom-property-allowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/depth-declaration-property-unit-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/depth-global-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/legacy-at-rule-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/shadow-custom-property-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/shadow-declaration-property-unit-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/shadow-function-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/shadow-global-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/shadow-property-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/z-index-declaration-property-value-allowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/z-index-function-disallowed-list.md
  polaris.shopify.com/next.config.js
  polaris.shopify.com/pages/api/search/v0/index.tsx
  polaris.shopify.com/pages/tokens/border.tsx
  polaris.shopify.com/pages/tokens/color.tsx
  polaris.shopify.com/pages/tokens/colors.tsx
  polaris.shopify.com/pages/tools/stylelint-polaris/rules/[rule].tsx
  polaris.shopify.com/src/components/HomePage/HomePage.tsx
  polaris.shopify.com/src/components/TokensPage/TokensPage.module.scss
  polaris.shopify.com/src/components/TokensPage/TokensPage.tsx
  stylelint-polaris/index.js
  stylelint-polaris/plugins/custom-property-allowed-list/index.test.js
Labels: v11.0.0

#9045 fix: Refactor `Box` border width properties
  .changeset/fifty-trees-shake.md
  polaris-react/src/components/Box/Box.scss
  polaris-react/src/components/Box/Box.stories.tsx
Labels: Bug

#9055 Update `z-index` token page visuals with new tokens
  .changeset/eleven-apes-unite.md
  polaris.shopify.com/src/components/TokenList/TokenList.tsx
Labels: v11.0.0

#9068 Add migration/codemod to replace motion custom properties
  .changeset/stupid-meals-hear.md
  polaris-codemods/src/codemods/11.0.0/transform.ts
  polaris-codemods/src/codemods/v11-styles-replace-custom-property-color/tests/transform.test.ts
  polaris-codemods/src/codemods/v11-styles-replace-custom-property-color/tests/v11-styles-replace-custom-property-color.input.scss
  polaris-codemods/src/codemods/v11-styles-replace-custom-property-color/tests/v11-styles-replace-custom-property-color.output.scss
  polaris-codemods/src/codemods/v11-styles-replace-custom-property-color/transform.ts
  polaris-codemods/src/codemods/v11-styles-replace-custom-property-motion/tests/transform.test.ts
  polaris-codemods/src/codemods/v11-styles-replace-custom-property-motion/tests/v11-styles-replace-custom-property-motion.input.scss
  polaris-codemods/src/codemods/v11-styles-replace-custom-property-motion/tests/v11-styles-replace-custom-property-motion.output.scss
  polaris-codemods/src/codemods/v11-styles-replace-custom-property-motion/transform.ts
  polaris-migrator/src/migrations/v11-styles-replace-custom-property-motion/tests/v11-styles-replace-custom-property-motion.input.scss
  polaris-migrator/src/migrations/v11-styles-replace-custom-property-motion/tests/v11-styles-replace-custom-property-motion.output.scss
  polaris-migrator/src/migrations/v11-styles-replace-custom-property-motion/tests/v11-styles-replace-custom-property-motion.test.ts
  polaris-migrator/src/migrations/v11-styles-replace-custom-property-motion/v11-styles-replace-custom-property-motion.ts
Labels: v11.0.0

#8374 Remove `v10` legacy custom properties
  documentation/guides/migrating-from-v10-to-v11.md
  polaris-codemods/src/codemods/v9-scss-replace-color/transform.ts
  polaris-codemods/src/codemods/v9-scss-replace-color/v10-legacy-colors.ts
  polaris-for-vscode/src/server.ts
  polaris-migrator/src/migrations/v9-scss-replace-color/v10-legacy-colors.ts
  polaris-migrator/src/migrations/v9-scss-replace-color/v9-scss-replace-color.ts
  polaris-react/scripts/build-validate.js
  polaris-react/src/components/Filters/Filters.scss
  polaris-react/src/components/Filters/Filters.tsx
  polaris-react/src/components/Frame/Frame.tsx
  polaris-react/src/components/IndexFilters/IndexFilters.tsx
  polaris-react/src/components/IndexTable/IndexTable.tsx
  polaris-react/src/components/Modal/components/Dialog/Dialog.tsx
  polaris-react/src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx
  polaris-react/src/components/ProgressBar/ProgressBar.tsx
  polaris-react/src/components/Sheet/Sheet.tsx
  polaris-tokens/README.md
  polaris-tokens/src/index.ts
  polaris-tokens/src/metadata.ts
  polaris-tokens/src/token-groups/depth.ts
  polaris-tokens/src/token-groups/motion.ts
  polaris-tokens/src/token-groups/shape.ts
  polaris-tokens/src/token-groups/spacing.ts
  polaris-tokens/src/token-groups/zIndex.ts
  polaris-tokens/src/utilities.ts
  polaris-tokens/tests/toStyleSheet.test.js
  polaris-tokens/tests/utilities.test.js
  polaris.shopify.com/content/tools/stylelint-polaris/rules/motion-at-rule-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/motion-declaration-property-unit-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/motion-function-disallowed-list.md
  polaris.shopify.com/content/tools/stylelint-polaris/rules/motion-global-disallowed-list.md
  polaris.shopify.com/pages/api/search/v0/index.tsx
Labels: v11.0.0

#9091 Remove `Polaris.VERSION` from the global window object
  .changeset/light-steaks-promise.md
  polaris-react/package.json
  polaris-react/scripts/build-validate.js
  polaris-react/src/configure.ts
Labels: 🤖Skip Major Check

#9102 Set addition of layout rules for stylelint-polaris to major
  .changeset/stale-tools-allow.md
Labels: 🤖Skip Major Check

#9112 [Polaris.shopify.com] Update legacy pattern copy
  polaris.shopify.com/src/components/PatternsPage/index.tsx
Labels: 🤖Skip Changelog

#9118 Revert "[Banner] Change banner focus ring from box shadow to outline"
  .changeset/clean-gifts-destroy.md
  polaris-react/src/components/Banner/Banner.scss
Labels: 🤖Skip Changelog, 🤖Skip Comment Check

#9116 [AlphaFilters] Refactor additionalFilters and include rest of filter object
  .changeset/khaki-snakes-pretend.md
  polaris-react/src/components/AlphaFilters/AlphaFilters.tsx
  polaris-react/src/components/AlphaFilters/tests/AlphaFilters.test.tsx
Labels: Bug
