Repository Shopify/polaris, pull requests merged in 2023-06, with the labels that each got.

#9341 Fix typo from strech to stretch
  polaris-react/src/components/HorizontalStack/HorizontalStack.stories.tsx
  polaris.shopify.com/pages/examples/horizontal-stack-with-block-align.tsx
Labels: 🤖Skip Changelog

#9350 Update Tooltip
  polaris-react/src/components/Tooltip/Tooltip.stories.tsx
  polaris-react/src/components/Tooltip/components/TooltipOverlay/TooltipOverlay.scss
  polaris-tokens/src/token-groups/shadow.ts
Labels: #gsd:32218

#9223 Deprecate `external` prop in `Link` component
  .changeset/nine-cycles-invent.md
  polaris-react/src/components/Link/Link.tsx
Labels: #gsd:32613

#9339 V11.x.x modal
  polaris-react/src/components/Modal/Modal.stories.tsx
  polaris-react/src/components/Modal/components/CloseButton/CloseButton.scss
  polaris-react/src/components/Modal/components/Dialog/Dialog.scss
  polaris-react/src/components/Modal/components/Footer/Footer.tsx
  polaris-react/src/components/Modal/components/Header/Header.tsx
  polaris-react/src/components/Modal/components/Section/Section.scss
Labels: 🤖Skip Changelog, #gsd:32218

#9364 `ButtonGroup` and `pressed` Button styles
  polaris-react/src/components/Button/Button.scss
  polaris-react/src/styles/shared/_buttons.scss
Labels: 🤖Skip Changelog

#9373 [polaris.shopify.com] Filter out experimental tokens
  polaris.shopify.com/src/components/TokensPage/TokensPage.tsx
Labels: 🤖Skip Changelog

#9369 [Select] updates
  polaris-react/src/components/Select/Select.scss
  polaris-react/src/components/Select/Select.stories.tsx
  polaris-react/src/components/Select/Select.tsx
Labels: 🤖Skip Changelog

#9354 Update `ActionList` component styles
  polaris-react/src/components/ActionList/ActionList.scss
  polaris-react/src/components/ActionList/ActionList.stories.tsx
  polaris-react/src/components/ActionList/components/Item/Item.tsx
  polaris-react/src/components/ActionList/components/Section/Section.tsx
  polaris-react/src/components/Popover/Popover.scss
  polaris-react/src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx
Labels: 🤖Skip Changelog

#9356 [TopBar] Update styles for v11
  polaris-react/src/components/TopBar/TopBar.scss
  polaris-react/src/components/TopBar/TopBar.stories.tsx
  polaris-react/src/components/TopBar/components/Menu/Menu.scss
  polaris-react/src/components/TopBar/components/Menu/Menu.tsx
  polaris-react/src/components/TopBar/components/SearchField/SearchField.scss
  polaris-react/src/components/TopBar/components/UserMenu/UserMenu.scss
  polaris-react/src/components/TopBar/components/UserMenu/UserMenu.tsx
Labels: 🤖Skip Changelog

#9380 Update `Avatar`
  polaris-react/src/components/Avatar/Avatar.scss
  polaris-react/src/components/Avatar/Avatar.stories.tsx
  polaris-tokens/src/token-groups/color.ts
Labels: 🤖Skip Changelog, #gsd:32218

#9381 [AppProvider] Default props for features
  polaris-react/src/components/AppProvider/AppProvider.tsx
  polaris.shopify.com/src/components/PolarisExampleWrapper/PolarisExampleWrapper.tsx
Labels: 🤖Skip Changelog

#9386 Update Polaris Help Documentation guidance to prepare for internal use
  polaris.shopify.com/content/content/help-documentation.md
Labels: 🤖Skip Changelog

#9402 Update card shadow sm
  polaris-react/src/components/Card/Card.tsx
  polaris-tokens/src/token-groups/shadow.ts
Labels: 🤖Skip Changelog

#9410 v11.x.x ChoiceList updates
  polaris-react/src/components/Checkbox/Checkbox.scss
  polaris-react/src/components/RadioButton/RadioButton.scss
Labels: 🤖Skip Changelog

#9400 Update AccountConnection
  polaris-react/src/components/AccountConnection/AccountConnection.stories.tsx
  polaris-react/src/components/AccountConnection/AccountConnection.tsx
  polaris-react/src/components/SettingAction/SettingAction.scss
Labels: 🤖Skip Changelog, #gsd:32218

#9406 [Key dependencies] Bump @types/react
  .changeset/tall-donuts-notice.md
  polaris-react/package.json
  polaris.shopify.com/package.json
  yarn.lock
Labels: dependencies

#9388 Button large size styles
  polaris-react/src/components/Button/Button.scss
  polaris-react/src/components/Button/Button.stories.tsx
Labels: 🤖Skip Changelog

#9415 Update `ProgressBar`
  polaris-react/src/components/ProgressBar/ProgressBar.scss
Labels: 🤖Skip Changelog, #gsd:32218

#9418 Update `List`
  polaris-react/src/components/List/List.scss
Labels: 🤖Skip Changelog, #gsd:32218

#9399 [OptionList] updates
  polaris-react/src/components/OptionList/OptionList.stories.tsx
  polaris-react/src/components/OptionList/OptionList.tsx
  polaris-react/src/components/OptionList/components/Option/Option.scss
  polaris-react/src/components/OptionList/components/Option/Option.tsx
Labels: 🤖Skip Changelog

#9419 Fix details page branding
  polaris-react/playground/DetailsPage.scss
Labels: 🤖Skip Changelog

#9420 Update FullscreenBar
  polaris-react/src/components/FullscreenBar/FullscreenBar.scss
  polaris-react/src/components/FullscreenBar/FullscreenBar.stories.tsx
  polaris-react/src/components/FullscreenBar/FullscreenBar.tsx
Labels: 🤖Skip Changelog, #gsd:32218

#9422 Add responsive `Text` styles
  polaris-react/src/components/Text/Text.scss
Labels: 🤖Skip Changelog

#9414 Update `Divider`
  polaris-react/src/components/Divider/Divider.tsx
Labels: 🤖Skip Changelog, #gsd:32218

#9424 fix outline offset being too small, and border-width on checked
  polaris-react/src/components/Checkbox/Checkbox.scss
Labels: 🤖Skip Changelog

#9411 v11.x.x CalloutCard updates
  polaris-react/src/components/CalloutCard/CalloutCard.scss
Labels: 🤖Skip Changelog

#9428 Update Layout
  polaris-react/src/components/Layout/Layout.scss
  polaris-react/src/components/Layout/Layout.stories.tsx
  polaris-react/src/components/Layout/components/AnnotatedSection/AnnotatedSection.tsx
Labels: 🤖Skip Changelog, #gsd:32218

#9435 [Vertical Stack] Fix broken link to horizontal stack
  polaris.shopify.com/content/components/layout-and-structure/vertical-stack.md
Labels: 🤖Skip Changelog

#9434 Refactor pagination
  polaris-react/src/components/Page/components/Header/Header.scss
  polaris-react/src/components/Pagination/Pagination.scss
  polaris-react/src/components/Pagination/Pagination.tsx
Labels: 🤖Skip Changelog

#9376 [ResourceItem | ResourceList | LegacyFilters] Design updates
  polaris-react/src/components/CheckableButton/CheckableButton.scss
  polaris-react/src/components/Checkbox/Checkbox.scss
  polaris-react/src/components/LegacyFilters/LegacyFilters.stories.tsx
  polaris-react/src/components/LegacyFilters/LegacyFilters.tsx
  polaris-react/src/components/LegacyFilters/components/ConnectedFilterControl/ConnectedFilterControl.scss
  polaris-react/src/components/LegacyFilters/components/ConnectedFilterControl/ConnectedFilterControl.tsx
  polaris-react/src/components/ResourceItem/ResourceItem.scss
  polaris-react/src/components/ResourceItem/ResourceItem.stories.tsx
  polaris-react/src/components/ResourceItem/ResourceItem.tsx
  polaris-react/src/components/ResourceList/ResourceList.scss
  polaris-react/src/components/ResourceList/ResourceList.stories.tsx
  polaris-react/src/components/ResourceList/_variables.scss
  polaris-react/src/components/Tag/Tag.scss
Labels: 🤖Skip Changelog, #gsd:32218

#9431 Update `Thumbnail`
  polaris-react/src/components/Avatar/Avatar.stories.tsx
  polaris-react/src/components/Thumbnail/Thumbnail.scss
  polaris-react/src/components/Thumbnail/Thumbnail.stories.tsx
Labels: 🤖Skip Changelog, #gsd:32218

#9432 [FormLayout] updates
  polaris-react/src/components/FormLayout/FormLayout.scss
  polaris-react/src/components/FormLayout/FormLayout.stories.tsx
  polaris-react/src/components/FormLayout/components/Group/Group.tsx
Labels: 🤖Skip Changelog

#9372 [Tabs][Filters][IndexFilters] Experimental
  polaris-react/src/components/Filters/Filters.scss
  polaris-react/src/components/Filters/Filters.stories.tsx
  polaris-react/src/components/Filters/Filters.tsx
  polaris-react/src/components/Filters/components/FilterPill/FilterPill.scss
  polaris-react/src/components/Filters/components/FilterPill/FilterPill.tsx
  polaris-react/src/components/IndexFilters/IndexFilters.scss
  polaris-react/src/components/IndexFilters/IndexFilters.stories.tsx
  polaris-react/src/components/IndexFilters/IndexFilters.tsx
  polaris-react/src/components/IndexFilters/components/FilterButton/FilterButton.tsx
  polaris-react/src/components/IndexFilters/components/SearchFilterButton/SearchFilterButton.tsx
  polaris-react/src/components/IndexFilters/components/SortButton/SortButton.tsx
  polaris-react/src/components/IndexFilters/components/UpdateButtons/UpdateButtons.tsx
  polaris-react/src/components/LegacyTabs/LegacyTabs.stories.tsx
  polaris-react/src/components/Tabs/Tabs.scss
  polaris-react/src/components/Tabs/Tabs.stories.tsx
  polaris-react/src/components/Tabs/Tabs.tsx
  polaris-react/src/components/Tabs/components/Tab/Tab.tsx
  polaris-react/src/components/Tabs/types.ts
  polaris.shopify.com/content/patterns-legacy/new-badge.md
Labels: 🤖Skip Changelog

#9436 [Checkbox][Select][TextField] error border updates
  polaris-react/src/components/Checkbox/Checkbox.scss
  polaris-react/src/components/RadioButton/RadioButton.scss
  polaris-react/src/components/Select/Select.scss
  polaris-react/src/components/TextField/TextField.scss
Labels: 🤖Skip Changelog

#9438 Update `DatePicker`
  polaris-react/src/components/DatePicker/DatePicker.scss
  polaris-react/src/components/DatePicker/DatePicker.stories.tsx
  polaris-react/src/components/DatePicker/DatePicker.tsx
Labels: 🤖Skip Changelog, #gsd:32218

#9443 Update `Toast`
  polaris-react/src/components/Frame/components/Toast/Toast.scss
  polaris-react/src/components/Frame/components/Toast/Toast.tsx
  polaris-react/src/components/Toast/Toast.stories.tsx
Labels: 🤖Skip Changelog, #gsd:32218

#9430 Update Popover
  polaris-react/src/components/Listbox/Listbox.stories.tsx
  polaris-react/src/components/Listbox/components/TextOption/TextOption.scss
  polaris-react/src/components/Popover/Popover.scss
  polaris-react/src/components/Popover/Popover.stories.tsx
  polaris-react/src/components/Popover/components/Section/Section.tsx
Labels: 🤖Skip Changelog, #gsd:32218

#9447 [KeyboardKey] Add back large variant
  polaris-react/src/components/KeyboardKey/KeyboardKey.scss
  polaris-react/src/components/KeyboardKey/KeyboardKey.tsx
Labels: 🤖Skip Changelog

#9444 Update LegacyTabs
  polaris-react/src/components/LegacyTabs/LegacyTabs.scss
  polaris-react/src/components/LegacyTabs/LegacyTabs.stories.tsx
  polaris-react/src/components/LegacyTabs/LegacyTabs.tsx
  polaris-react/src/components/LegacyTabs/components/Tab/Tab.tsx
Labels: 🤖Skip Changelog, #gsd:32218

#9442 Fix `IndexTable` hover and selected states
  polaris-react/src/components/IndexTable/IndexTable.scss
Labels: 🤖Skip Changelog

#9433 Update `Link` focus styles
  polaris-react/src/components/Button/Button.scss
  polaris-react/src/components/Link/Link.scss
Labels: 🤖Skip Changelog

#9437 Update `Button` font size for small screens
  polaris-react/src/components/Button/Button.scss
  polaris-react/src/styles/shared/_buttons.scss
Labels: 🤖Skip Changelog

#9440 [Banner] styling updates
  polaris-react/src/components/Banner/Banner.scss
  polaris-react/src/components/Banner/components/BannerExperimental/BannerExperimental.scss
  polaris-react/src/components/Banner/components/BannerExperimental/BannerExperimental.tsx
  polaris-react/src/components/Banner/components/BannerExperimental/utilities.ts
Labels: 🤖Skip Changelog

#9449 [ActionList] Fix alignment bug
  polaris-react/src/components/ActionList/ActionList.scss
Labels: 🤖Skip Changelog

#9455 chore: bump polaris-tokens to 7.2.0
  .changeset/friendly-nails-repeat.md
Labels: #gsd:32218

#9460 [Navigation] Fix image icons
  polaris-react/playground/DetailsPage.tsx
  polaris-react/src/components/Navigation/Navigation.scss
  polaris-react/src/components/Navigation/_variables.scss
Labels: 🤖Skip Changelog

#9457 [Banner] small refactor
  polaris-react/src/components/Banner/components/BannerExperimental/BannerExperimental.tsx
  polaris-react/src/components/Banner/components/BannerExperimental/utilities.ts
Labels: 🤖Skip Changelog

#9470 Add pointer events none to banner
  polaris-react/src/components/Banner/Banner.scss
Labels: 🤖Skip Changelog

#9488 Remove outline on `primary plain` `disabled` button
  polaris-react/src/components/Button/Button.scss
Labels: 🤖Skip Changelog

#9490 Update Modal
  .changeset/modern-tomatoes-draw.md
  polaris-react/src/components/Modal/components/CloseButton/CloseButton.scss
  polaris-react/src/components/Modal/components/Header/Header.tsx
  polaris-tokens/src/token-groups/color.ts
Labels: 🤖Skip Comment Check, #gsd:32218

#9462 Update `DataTable` component styles
  polaris-react/src/components/DataTable/DataTable.scss
  polaris-react/src/components/DataTable/components/Navigation/Navigation.tsx
Labels: 🤖Skip Changelog

#9461 Icon `primary` and `plain` button updates
  polaris-react/src/components/Button/Button.scss
  polaris-react/src/components/Button/Button.stories.tsx
  polaris-react/src/components/DatePicker/DatePicker.scss
  polaris-react/src/components/MediaCard/MediaCard.tsx
Labels: 🤖Skip Changelog

#9492 Fix `plain` button focus styles
  polaris-react/src/components/Button/Button.scss
Labels: 🤖Skip Changelog

#9496 Fix stylelint failure
  polaris-react/src/components/DataTable/DataTable.scss
Labels: 🤖Skip Changelog

#9495 Update `bg-subdued` value and add `bg-secondary-disabled` token
  polaris-tokens/src/token-groups/color.ts
Labels: 🤖Skip Changelog

#9505 Update `Tabs` font-weight to medium
  polaris-react/src/components/Tabs/components/Tab/Tab.tsx
Labels: 🤖Skip Changelog

#9487 [CheckableButton] Be less opinionated about height so callsites can adjust dynamically
  polaris-react/src/components/CheckableButton/CheckableButton.scss
  polaris-react/src/components/ResourceList/ResourceList.scss
Labels: 🤖Skip Changelog, #gsd:32218

#9506 Fix margins on plain icon only buttons
  polaris-react/src/components/Banner/components/BannerExperimental/BannerExperimental.tsx
  polaris-react/src/components/Button/Button.scss
Labels: 🤖Skip Changelog

#9475 Update `Badge` component
  .changeset/large-teachers-push.md
  polaris-react/locales/en.json
  polaris-react/src/components/Badge/Badge.scss
  polaris-react/src/components/Badge/Badge.stories.tsx
  polaris-react/src/components/Badge/Badge.tsx
  polaris-react/src/components/Badge/types.ts
  polaris-react/src/components/Badge/utils.ts
Labels: 🤖Skip Changelog

#9498 Swap `bg-subdued` and `bg-secondary` tokens
  polaris-react/src/components/Card/Card.stories.tsx
  polaris-react/src/components/DataTable/DataTable.scss
  polaris-react/src/components/Filters/Filters.scss
  polaris-react/src/components/Filters/components/FilterPill/FilterPill.scss
  polaris-react/src/components/IndexTable/IndexTable.scss
  polaris-react/src/components/KeyboardKey/KeyboardKey.scss
  polaris-react/src/components/LegacyCard/LegacyCard.scss
  polaris-react/src/components/LegacyFilters/LegacyFilters.scss
  polaris-react/src/components/Modal/components/Section/Section.tsx
  polaris-react/src/components/Tabs/Tabs.scss
Labels: 🤖Skip Changelog

#9517 Fix duplicate selector in LegacyCard
  polaris-react/src/components/LegacyCard/LegacyCard.scss
Labels: 🤖Skip Changelog

#9515 Update IndexTable bullk actions shadow
  polaris-react/src/components/BulkActions/BulkActions.scss
Labels: 🤖Skip Changelog

#9512 Convolute `destructive` and `outline` Button styles
  polaris-react/src/components/Button/Button.stories.tsx
  polaris-react/src/components/Button/Button.tsx
Labels: 🤖Skip Changelog

#9493 [Listbox] Added gap between selected icon and child contents
  polaris-react/src/components/Listbox/Listbox.stories.tsx
  polaris-react/src/components/Listbox/components/TextOption/TextOption.tsx
Labels: 🤖Skip Changelog

#9537 [Page] Remove divider and divider spacing from page
  polaris-react/src/components/Page/Page.scss
Labels: 🤖Skip Changelog

#9533 [Modal] Design update updates
  polaris-react/src/components/Modal/components/CloseButton/CloseButton.scss
  polaris-react/src/components/Modal/components/CloseButton/CloseButton.tsx
  polaris-react/src/components/Modal/components/Dialog/Dialog.scss
  polaris-react/src/components/Modal/components/Footer/Footer.tsx
  polaris-react/src/components/Modal/components/Header/Header.tsx
  polaris-react/src/components/Modal/components/Section/Section.tsx
Labels: 🤖Skip Changelog, #gsd:32218

#9542 [LegacyCard] Fix flush sections
  polaris-react/src/components/LegacyCard/LegacyCard.scss
Labels: 🤖Skip Changelog

#9450 Primary button update
  polaris-react/src/components/Button/Button.scss
  polaris-react/src/components/Button/Button.stories.tsx
  polaris-tokens/src/token-groups/color.ts
  polaris-tokens/src/token-groups/shadow.ts
Labels: 🤖Skip Changelog

#9550 [IndexTable][Cell] Fix experimental flush cell styles overriding chil…
  polaris-react/src/components/IndexTable/IndexTable.scss
Labels: 🤖Skip Changelog

#9532 [ResourceItem] Update hover style
  polaris-react/src/components/ResourceItem/ResourceItem.scss
Labels: 🤖Skip Changelog

#9555 Fix `primary` `plain` hover and active text styles
  polaris-react/src/components/Button/Button.scss
Labels: 🤖Skip Changelog

#9554 Update Polaris changelog
  polaris-react/CHANGELOG.md
Labels: 🤖Skip Changelog

#9553 [Nav item] App icon with rounded corners
  polaris-react/src/components/Navigation/Navigation.stories.tsx
  polaris-react/src/components/Navigation/_variables.scss
Labels: 🤖Skip Changelog

#9574 [Navigation] Fixes for the heading and actions
  polaris-react/src/components/Navigation/Navigation.scss
  polaris-react/src/components/Navigation/components/Item/components/SecondaryNavigation/SecondaryNavigation.tsx
Labels: 🤖Skip Changelog

#9569 Add experimental snappy curve to ease-out
  polaris-tokens/src/token-groups/motion.ts
Labels: 🤖Skip Changelog

#9573 Update `AccountConnection` `Avatar` to be top aligned
  polaris-react/src/components/AccountConnection/AccountConnection.tsx
Labels: 🤖Skip Changelog

#9570 Update `CalloutCard` `secondaryAction` button to plain primary
  polaris-react/src/components/AccountConnection/AccountConnection.tsx
  polaris-react/src/components/CalloutCard/CalloutCard.tsx
Labels: 🤖Skip Changelog
