Repository Shopify/polaris, pull requests merged in 2024-01, with the labels that each got.

#11380 Remove readme-update-version and related scripts
  polaris-react/README.md
  polaris-react/package.json
  polaris-react/scripts/readme-update-version.js
  polaris-react/scripts/utilities/index.js
  polaris-react/scripts/utilities/semver-reg-exp.js
  polaris-react/tests/readme-update-version.test.js
Labels: 🤖Skip Changelog

#11381 Remove scripts/profiler.js
  polaris-react/package.json
  polaris-react/scripts/profiler.js
  yarn.lock
Labels: 🤖Skip Changelog

#11304 [Tooltip] Added `min-width` to `TooltipOverlay`
  .changeset/cuddly-gorillas-vanish.md
  polaris-react/src/components/Tooltip/Tooltip.stories.tsx
  polaris-react/src/components/Tooltip/components/TooltipOverlay/TooltipOverlay.module.scss
Labels: #gsd:37811

#11400 Modal: remove sizeSmall max-width
  .changeset/sixty-plums-worry.md
  polaris-react/src/components/Modal/components/Dialog/Dialog.module.scss
Labels: #gsd:37811

#11403 [Navigation] Change `padding-top` to `space-100` for small viewports
  .changeset/hip-oranges-joke.md
  polaris-react/src/components/Navigation/Navigation.module.scss
Labels: #gsd:37811

#11414 Init v13 migration guide with Inter v4 updates
  polaris.shopify.com/content/version-guides/migrating-from-v11-to-v13.mdx
Labels: 🤖Skip Changelog

#11401 Changed the icon color for the Magic tone of the Badge component.
  .changeset/tasty-doors-arrive.md
  polaris-react/src/components/Badge/Badge.module.scss
Labels: Component, Contribution, 2024

#11410 Update `SkeletonTabs` to reflect `Tabs`
  .changeset/smooth-lemons-appear.md
  polaris-react/src/components/SkeletonTabs/SkeletonTabs.module.scss
  polaris-react/src/components/SkeletonTabs/SkeletonTabs.stories.tsx
  polaris-react/src/components/SkeletonTabs/SkeletonTabs.tsx
  polaris.shopify.com/content/components/feedback-indicators/skeleton-tabs.mdx
  polaris.shopify.com/pages/examples/skeleton-tabs-fitted.tsx
Labels: #gsd:37811

#11394 Add Inter v4
  polaris-react/.storybook/preview-head.html
  polaris-react/README.md
  polaris.shopify.com/content/version-guides/migrating-from-v11-to-v12.mdx
  polaris.shopify.com/pages/_document.tsx
Labels: 🤖Skip Changelog, #gsd:37811

#10981 [Bulk Actions] Update Bulk Actions UI
  .changeset/gentle-snakes-relax.md
  polaris-react/src/components/Box/Box.tsx
  polaris-react/src/components/BulkActions/BulkActions.module.scss
  polaris-react/src/components/BulkActions/BulkActions.tsx
  polaris-react/src/components/BulkActions/components/BulkActionButton/BulkActionButton.tsx
  polaris-react/src/components/BulkActions/components/BulkActionMenu/BulkActionMenu.tsx
  polaris-react/src/components/BulkActions/hooks/index.ts
  polaris-react/src/components/BulkActions/hooks/use-is-bulk-actions-sticky.ts
  polaris-react/src/components/BulkActions/index.ts
  polaris-react/src/components/BulkActions/tests/BulkActions.test.tsx
  polaris-react/src/components/Card/Card.tsx
  polaris-react/src/components/CheckableButton/CheckableButton.tsx
  polaris-react/src/components/IndexTable/IndexTable.module.scss
  polaris-react/src/components/IndexTable/IndexTable.stories.tsx
  polaris-react/src/components/IndexTable/IndexTable.tsx
  polaris-react/src/components/IndexTable/tests/IndexTable.test.tsx
  polaris-react/src/components/ResourceList/ResourceList.module.scss
  polaris-react/src/components/ResourceList/ResourceList.stories.tsx
  polaris-react/src/components/ResourceList/ResourceList.tsx
  polaris-react/src/components/ResourceList/_variables.scss
  polaris-react/src/components/ResourceList/tests/ResourceList.test.tsx
  polaris-react/src/components/SelectAllActions/SelectAllActions.module.scss
  polaris-react/src/components/SelectAllActions/SelectAllActions.tsx
  polaris-react/src/components/SelectAllActions/hooks/index.ts
  polaris-react/src/components/SelectAllActions/hooks/tests/use-is-select-all-actions-sticky.test.tsx
  polaris-react/src/components/SelectAllActions/hooks/use-is-select-all-actions-sticky.ts
  polaris-react/src/components/SelectAllActions/index.ts
  polaris-react/src/components/SelectAllActions/tests/SelectAllActions.test.tsx
  polaris-react/src/components/ShadowBevel/ShadowBevel.module.scss
  polaris.shopify.com/content/components/lists/resource-list.mdx
  polaris.shopify.com/content/components/tables/index-table.mdx
  polaris.shopify.com/pages/examples/index-table-with-pagination-and-bulk-actions.tsx
  polaris.shopify.com/pages/examples/index-table-with-selection-and-no-bulk-actions.tsx
  polaris.shopify.com/pages/examples/index-table-with-sticky-scroll-bar.tsx
  polaris.shopify.com/pages/examples/resource-list-with-bulk-actions-and-many-items.tsx
  polaris.shopify.com/pages/examples/resource-list-with-bulk-actions-and-pagination.tsx
Labels: Component, 2023, Contribution

#11493 Add documentation back for deprecated components
  polaris.shopify.com/content/components/deprecated/contextual-save-bar.mdx
  polaris.shopify.com/content/components/deprecated/frame.mdx
  polaris.shopify.com/content/components/deprecated/loading.mdx
  polaris.shopify.com/content/components/deprecated/modal.mdx
  polaris.shopify.com/content/components/deprecated/navigation.mdx
  polaris.shopify.com/content/components/deprecated/toast.mdx
  polaris.shopify.com/content/components/deprecated/top-bar.mdx
Labels: 🤖Skip Changelog

#11499 [Button] Fix styling for `fullWidth` buttons in `ButtonGroup`
  .changeset/dry-chicken-roll.md
  polaris-react/src/components/Button/Button.module.scss
  polaris-react/src/components/ButtonGroup/ButtonGroup.module.scss
  polaris-react/src/components/ButtonGroup/ButtonGroup.stories.tsx
  polaris-react/src/components/Tooltip/Tooltip.stories.tsx
Labels: #gsd:38846

#11503 Add workaround for `font-optical-sizing` issue in Safari 16
  .changeset/few-colts-attend.md
  polaris-react/src/components/AppProvider/AppProvider.scss
  polaris-react/src/components/AppProvider/AppProvider.tsx
Labels: #gsd:38846

#11476 Update icon guidelines
  polaris-icons/CONTRIBUTING.md
  polaris-icons/icons/DatabaseConnectIcon.yml
Labels: 🤖Skip Changelog

#11505 [polaris.shopify.com] Adds icon and icon-only examples to `Button` docs
  polaris.shopify.com/content/components/actions/button.mdx
  polaris.shopify.com/pages/examples/button-icon-only.tsx
  polaris.shopify.com/pages/examples/button-with-icon.tsx
Labels: 🤖Skip Changelog, #gsd:38846

#11501 Added icons package to eslint-ts config and fixed some eslint errors
  .eslintrc.js
  polaris-icons/package.json
  polaris-icons/tests/validate-svg-content.test.js
  tsconfig.eslint.json
Labels: 🤖Skip Changelog

#11420 adds IncentivesIcon
  .changeset/poor-crabs-think.md
  polaris-icons/icons/IncentiveIcon.svg
  polaris-icons/icons/IncentiveIcon.yml
Labels: Icon, #gsd:37720

#11523 [Polaris][IndexTable] fix z-index for nested rows
  .changeset/five-geckos-end.md
  polaris-react/src/components/IndexTable/IndexTable.module.scss
Labels: Bug, Priority: Urgent

#11525 [Button] Fix border radius for connectedTop buttons in ButtonGroup
  .changeset/old-phones-watch.md
  polaris-react/src/components/Button/Button.module.scss
  polaris-react/src/components/ButtonGroup/ButtonGroup.module.scss
Labels: #gsd:38846
