Repository Shopify/polaris, pull requests merged in 2024-04, with the labels that each got.

#11804 [EmptyState] Fix layout shift when image is loading with skeleton image
  .changeset/tidy-dryers-stare.md
  polaris-react/src/components/EmptyState/EmptyState.module.css
  polaris-react/src/components/EmptyState/EmptyState.tsx
  polaris-react/src/components/EmptyState/tests/EmptyState.test.tsx
Labels: Bug

#11801 Add dark experimental tokens for `TopBar`
  .changeset/tasty-clocks-help.md
  polaris-react/src/components/Tooltip/components/TooltipOverlay/TooltipOverlay.tsx
  polaris-tokens/src/colors.ts
  polaris-tokens/src/themes/base/color.ts
  polaris-tokens/src/themes/dark.ts
Labels: #gsd:38420

#11813 Remove `Text` `heading2xl` and associated tokens from v14 font migration
  .changeset/twenty-chefs-float.md
  polaris-migrator/src/migrations/v14-styles-replace-custom-property-font/tests/v14-styles-replace-custom-property-font.input.scss
  polaris-migrator/src/migrations/v14-styles-replace-custom-property-font/tests/v14-styles-replace-custom-property-font.output.scss
  polaris-migrator/src/migrations/v14-styles-replace-custom-property-font/transform.ts
Labels: #gsd:40131

#11828 Remove semantic text tokens
  .changeset/afraid-pears-crash.md
  .changeset/sixty-bananas-cover.md
  .changeset/tall-plums-joke.md
  polaris-for-vscode/src/server.ts
  polaris-tokens/src/themes/base/index.ts
  polaris-tokens/src/themes/base/text.ts
  polaris-tokens/src/themes/constants.ts
  polaris-tokens/src/themes/index.ts
  polaris-tokens/src/themes/light-mobile.ts
  polaris.shopify.com/content/tokens/text.mdx
  polaris.shopify.com/content/version-guides/migrating-from-v13-to-v14.mdx
  polaris.shopify.com/src/components/TokensNav/TokensNav.module.scss
  polaris.shopify.com/src/components/TokensNav/TokensNav.tsx
Labels: #gsd:40131

#11827 Remove `light-mobile` theme
  polaris.shopify.com/content/version-guides/migrating-from-v13-to-v14.mdx
Labels: #gsd:40131

#11783 [Filters] Add support for indicating an applied filter has unsaved changes
  .changeset/cold-windows-occur.md
  polaris-react/locales/cs.json
  polaris-react/locales/de.json
  polaris-react/locales/en.json
  polaris-react/locales/fi.json
  polaris-react/locales/fr.json
  polaris-react/locales/it.json
  polaris-react/locales/ja.json
  polaris-react/locales/ko.json
  polaris-react/locales/pl.json
  polaris-react/locales/pt-PT.json
  polaris-react/locales/sv.json
  polaris-react/locales/th.json
  polaris-react/locales/tr.json
  polaris-react/locales/vi.json
  polaris-react/locales/zh-CN.json
  polaris-react/locales/zh-TW.json
  polaris-react/src/components/Filters/Filters.stories.tsx
  polaris-react/src/components/Filters/components/FilterPill/FilterPill.module.css
  polaris-react/src/components/Filters/components/FilterPill/FilterPill.tsx
  polaris-react/src/components/Filters/components/FilterPill/tests/FilterPill.test.tsx
  polaris-react/src/components/Filters/components/FiltersBar/FiltersBar.tsx
  polaris-react/src/components/Filters/components/FiltersBar/tests/FiltersBar.test.tsx
  polaris-react/src/components/Filters/components/SearchField/SearchField.tsx
  polaris-react/src/components/IndexFilters/IndexFilters.tsx
  polaris-react/src/types.ts
  polaris.shopify.com/content/components/selection-and-input/filters.mdx
  polaris.shopify.com/pages/examples/filters-with-children-content-and-unsaved-changes.tsx
Labels: #gsd:38846

#11844 [v13] Miniumum required node version updated to v20.10.0
  .changeset/cyan-houses-cross.md
  .github/CONTRIBUTING.md
  .github/workflows/ci-test.yml
  documentation/Nodejs support.md
  package.json
  polaris-for-vscode/package.json
  polaris-icons/package.json
  polaris-migrator/package.json
  polaris-react/config/rollup/plugin-styles.js
  polaris-react/package.json
  polaris-react/rollup.config.mjs
  polaris-tokens/package.json
  polaris.shopify.com/package.json
  stylelint-polaris/package.json
  yarn.lock
Labels: 🤖Skip Major Check, v13.0.0

#11799 [v13] Use pnpm for package management
  .changeset/README.md
  .changeset/flat-cougars-look.md
  .changeset/wise-vans-notice.md
  .eslintrc.js
  .github/CONTRIBUTING.md
  .github/workflows/changelog.yml
  .github/workflows/ci-a11y-vrt.yml
  .github/workflows/ci-lint.yml
  .github/workflows/ci-test.yml
  .github/workflows/publish-polaris-for-vscode.yml
  .github/workflows/release.yml
  .github/workflows/snapit.yml
  README.md
  dev.yml
  documentation/Component READMEs.md
  documentation/Releasing.md
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  polaris-for-vscode/CONTRIBUTING.md
  polaris-for-vscode/src/server.ts
  polaris-icons/CONTRIBUTING.md
  polaris-icons/package.json
  polaris-migrator/src/utilities/imports.ts
  polaris-migrator/src/utilities/sass.ts
  polaris-react/config/postcss-plugins.js
  polaris-react/package.json
  polaris-react/src/components/AppProvider/global.css
  polaris-react/src/components/Avatar/Avatar.stories.tsx
  polaris-react/src/components/ThemeProvider/ThemeProvider.tsx
  polaris-react/src/utilities/tests/use-index-resource-state.test.tsx
  polaris-tokens/src/themes/base/breakpoints.ts
  polaris-tokens/src/themes/types.ts
  polaris.shopify.com/README.md
  polaris.shopify.com/content/contributing/icons.mdx
  polaris.shopify.com/content/tools/polaris-migrator.mdx
  polaris.shopify.com/content/tools/stylelint-polaris.mdx
  polaris.shopify.com/jest.config.js
  polaris.shopify.com/package.json
  polaris.shopify.com/patches/playroom+0.28.0.patch
  polaris.shopify.com/scripts/get-props/package.json
  polaris.shopify.com/scripts/get-props/src/get-props.ts
  polaris.shopify.com/scripts/get-props/yarn.lock
  polaris.shopify.com/scripts/util.mjs
  stylelint-polaris/plugins/at-rule-disallowed-list/README.md
  stylelint-polaris/plugins/custom-property-allowed-list/README.md
  stylelint-polaris/plugins/media-query-allowed-list/README.md
  yarn.lock
Labels: 🤖Skip Major Check, v13.0.0

#11875 [Picker] Fix activator type
  polaris-react/src/components/Picker/components/Activator/Activator.tsx
Labels: 🤖Skip Changelog, #gsd:38419

#11846 Create rounded corner frame content
  .changeset/clean-turtles-grab.md
  polaris-react/src/components/AppProvider/AppProvider.tsx
  polaris-react/src/components/Frame/Frame.module.css
  polaris-react/src/components/Frame/Frame.tsx
  polaris-react/src/components/Navigation/Navigation.module.css
  polaris-react/src/components/Navigation/Navigation.tsx
  polaris-react/src/components/PolarisTestProvider/PolarisTestProvider.tsx
Labels: #gsd:38420

#11884 [Image] Add optional `ref` prop type
  polaris-react/src/components/Image/Image.tsx
Labels: 🤖Skip Changelog

#11889 [TextField][Select][PickerSearchField] Fix mobile zoom due to font-size
  .changeset/olive-frogs-draw.md
  polaris-react/src/components/Picker/components/SearchField/SearchField.module.css
  polaris-react/src/components/Select/Select.module.css
  polaris-react/src/components/TextField/TextField.module.css
Labels: Bug, Component

#11891 [Frame] Add scrollbar width buffer onto Content
  .changeset/unlucky-coats-add.md
  polaris-react/src/components/Frame/Frame.module.css
  polaris-react/src/components/Frame/Frame.tsx
Labels: #gsd:38420

#11909 Fixed missing image for card layout patterns
  .changeset/soft-cups-think.md
  polaris.shopify.com/content/patterns/card-layout/index.mdx
  polaris.shopify.com/public/images/patterns/card-layout/structure/card-layout-structure-header-actions-table-actions@2x.png
Labels: Bug

#11911 Remove @shopify/cli
  package.json
  pnpm-lock.yaml
Labels: 🤖Skip Changelog

#11734 Upgrade from Storybook v7 -> Storybook v8
  .changeset/neat-pandas-explode.md
  .github/workflows/ci-a11y-vrt.yml
  pnpm-lock.yaml
  polaris-react/.storybook/addons/global-controls-panel/manager.jsx
  polaris-react/.storybook/main.js
  polaris-react/.storybook/test-runner.ts
  polaris-react/package.json
  polaris-react/playground/DetailsPage.tsx
  polaris-react/playground/KitchenSink.tsx
  polaris-react/playground/Playground.tsx
  polaris-react/scripts/accessibility-check.js
  polaris-react/src/components/Banner/Banner.stories.tsx
  polaris-react/src/components/Checkbox/Checkbox.stories.tsx
  polaris-react/src/components/ContextualSaveBar/ContextualSaveBar.stories.tsx
  polaris-react/src/components/DataTable/DataTable.stories.tsx
  polaris-react/src/components/Frame/Frame.stories.tsx
  polaris-react/src/components/Icon/Icon.stories.tsx
  polaris-react/src/components/IndexTable/IndexTable.stories.tsx
  polaris-react/src/components/Listbox/Listbox.stories.tsx
  polaris-react/src/components/Modal/Modal.stories.tsx
  polaris-react/src/components/ResourceList/ResourceList.stories.tsx
  polaris-react/src/components/Tabs/Tabs.stories.tsx
  polaris-react/src/components/Toast/Toast.stories.tsx
  polaris-react/test-runner-jest.config.js
Labels: Tech Debt, Key dependency, Engineering, Priority: Low
