Repository Shopify/polaris, pull requests merged in 2024-02, with the labels that each got.

#11556 Fix bugs on polaris website
  polaris.shopify.com/content/components/deprecated/legacy-filters.mdx
  polaris.shopify.com/content/design/colors/palettes-and-roles.mdx
  polaris.shopify.com/content/design/layout/spacial-organization.mdx
  polaris.shopify.com/content/design/typography/font-and-typescale.mdx
  polaris.shopify.com/content/design/typography/using-type.mdx
  polaris.shopify.com/pages/api/search/v0/index.tsx
Labels: 🤖Skip Changelog

#11570 [IndexTable][ResourceList] Set SelectAllActions sticky bottom offset based on closest scrollable ancestor
  .changeset/smart-badgers-yawn.md
  polaris-react/src/components/IndexTable/IndexTable.stories.tsx
  polaris-react/src/components/IndexTable/IndexTable.tsx
  polaris-react/src/components/IndexTable/tests/IndexTable.test.tsx
  polaris-react/src/components/ResourceList/ResourceList.stories.tsx
  polaris-react/src/components/ResourceList/ResourceList.tsx
  polaris-react/src/components/ResourceList/tests/ResourceList.test.tsx
  polaris-react/src/components/SelectAllActions/hooks/tests/use-is-select-all-actions-sticky.test.tsx
  polaris-react/src/components/SelectAllActions/hooks/use-is-select-all-actions-sticky.ts
Labels: #gsd:38846

#11585 [ResourceItem] Add `disabled` prop
  .changeset/proud-items-do.md
  polaris-react/src/components/ResourceItem/ResourceItem.module.scss
  polaris-react/src/components/ResourceItem/ResourceItem.stories.tsx
  polaris-react/src/components/ResourceItem/ResourceItem.tsx
  polaris-react/src/components/ResourceItem/tests/ResourceItem.test.tsx
Labels: Component, Contribution, 2024

#11596 Migrations for `Text` `heading3xl` and `heading2xl` removal
  .changeset/spicy-dryers-nail.md
  polaris-migrator/src/migrations/v13-styles-replace-custom-property-font/tests/transform.test.ts
  polaris-migrator/src/migrations/v13-styles-replace-custom-property-font/tests/v13-styles-replace-custom-property-font.input.scss
  polaris-migrator/src/migrations/v13-styles-replace-custom-property-font/tests/v13-styles-replace-custom-property-font.output.scss
  polaris-migrator/src/migrations/v13-styles-replace-custom-property-font/transform.ts
  polaris.shopify.com/content/tools/polaris-migrator.mdx
Labels: #gsd:38846

#11609 Updated icon set with consistency improvements
  .changeset/ninety-baboons-help.md
  polaris-icons/icons/ChartStackedIcon.svg
  polaris-icons/icons/ChartStackedIcon.yml
  polaris-icons/icons/CollectionFeaturedIcon.svg
  polaris-icons/icons/CollectionFeaturedIcon.yml
  polaris-icons/icons/CollectionFilledIcon.svg
  polaris-icons/icons/CollectionFilledIcon.yml
  polaris-icons/icons/CollectionIcon.svg
  polaris-icons/icons/CollectionIcon.yml
  polaris-icons/icons/CollectionReferenceIcon.svg
  polaris-icons/icons/CollectionReferenceIcon.yml
  polaris-icons/icons/DiscountCodeIcon.svg
  polaris-icons/icons/DiscountCodeIcon.yml
  polaris-icons/icons/DuplicateIcon.svg
  polaris-icons/icons/DuplicateIcon.yml
  polaris-icons/icons/EnterIcon.svg
  polaris-icons/icons/EnterIcon.yml
  polaris-icons/icons/ExitIcon.svg
  polaris-icons/icons/ExitIcon.yml
  polaris-icons/icons/EyeDropperIcon.svg
  polaris-icons/icons/EyeDropperIcon.yml
  polaris-icons/icons/GiftCardFilledIcon.svg
  polaris-icons/icons/GiftCardFilledIcon.yml
  polaris-icons/icons/GiftCardIcon.svg
  polaris-icons/icons/GiftCardIcon.yml
  polaris-icons/icons/ImagesIcon.svg
  polaris-icons/icons/ImagesIcon.yml
  polaris-icons/icons/LayoutBuyButtonHorizontalIcon.svg
  polaris-icons/icons/LayoutBuyButtonHorizontalIcon.yml
  polaris-icons/icons/LayoutBuyButtonIcon.svg
  polaris-icons/icons/LayoutBuyButtonIcon.yml
  polaris-icons/icons/LayoutBuyButtonVerticalIcon.svg
  polaris-icons/icons/LayoutBuyButtonVerticalIcon.yml
  polaris-icons/icons/LayoutColumn1Icon.svg
  polaris-icons/icons/LayoutColumn1Icon.yml
  polaris-icons/icons/LayoutColumns2Icon.svg
  polaris-icons/icons/LayoutColumns2Icon.yml
  polaris-icons/icons/LayoutColumns3Icon.svg
  polaris-icons/icons/LayoutColumns3Icon.yml
  polaris-icons/icons/LayoutPopupIcon.svg
  polaris-icons/icons/LayoutPopupIcon.yml
  polaris-icons/icons/LayoutSectionIcon.svg
  polaris-icons/icons/LayoutSectionIcon.yml
  polaris-icons/icons/MeasurementSizeIcon.svg
  polaris-icons/icons/MeasurementSizeIcon.yml
  polaris-icons/icons/MoneyFilledIcon.svg
  polaris-icons/icons/MoneyFilledIcon.yml
  polaris-icons/icons/MoneyIcon.svg
  polaris-icons/icons/MoneyIcon.yml
  polaris-icons/icons/MoneyNoneIcon.svg
  polaris-icons/icons/MoneyNoneIcon.yml
  polaris-icons/icons/VariantIcon.svg
  polaris-icons/icons/VariantIcon.yml
  polaris-icons/icons/WandIcon.svg
  polaris-icons/icons/WandIcon.yml
  polaris-icons/icons/WifiIcon.svg
  polaris-icons/icons/WifiIcon.yml
  polaris-icons/tests/validate-svg-content.test.js
Labels: #gsd:38846

#11633 [Icon] Update 'Mobile' icon
  .changeset/rare-cobras-destroy.md
  polaris-icons/icons/MobileIcon.svg
  polaris-icons/icons/MobileIcon.yml
Labels: Icon

#11613 [Text] Deprecate `heading2xl` and `heading3xl` variants
  .changeset/slimy-tips-smash.md
  documentation/Deprecation guidelines.md
  polaris-react/src/components/Text/Text.tsx
Labels: #gsd:38846

#11399 [PositionedOverlay] Add scroll support for all scroll containers
  .changeset/olive-forks-call.md
  polaris-react/src/components/Popover/Popover.stories.tsx
  polaris-react/src/components/PositionedOverlay/PositionedOverlay.tsx
  polaris-react/src/components/PositionedOverlay/utilities/math.ts
Labels: #gsd:38846

#11642 [Icon] Add sun icon
  .changeset/cyan-lemons-crash.md
  polaris-icons/icons/SunIcon.svg
  polaris-icons/icons/SunIcon.yml
Labels: Icon

#11409 [InlineError] Updated right margin from 200 to 100
  .changeset/lanky-flamingos-kick.md
  polaris-react/src/components/InlineError/InlineError.module.scss
Labels: #gsd:38846
