Repository Shopify/polaris, pull requests merged in 2024-03, with the labels that each got.

#11687 [Icons] Plus and minus icon design fix
  .changeset/two-ducks-sing.md
  polaris-icons/icons/MinusIcon.svg
  polaris-icons/icons/PlusIcon.svg
Labels: Icon

#11704 Update font-and-typescale.mdx
  polaris.shopify.com/content/design/typography/font-and-typescale.mdx
Labels: 🤖Skip Changelog

#11721 [Popover] Remove transition for cover position
  polaris-react/src/components/Popover/Popover.module.css
  polaris-react/src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx
Labels: 🤖Skip Changelog, #gsd38419

#11745 fix: bug in math.ts for popovers with position cover
  .changeset/tall-buttons-search.md
  polaris-react/src/components/PositionedOverlay/utilities/math.ts
Labels: #gsd38419

#11736 [OptionList] Fix layout shift within popovers
  .changeset/chatty-timers-marry.md
  polaris-react/src/components/OptionList/components/Option/Option.tsx
Labels: 🤖Skip Changelog, #gsd38419

#11751 Revert "Add controlled prop to open the Tooltip"
  .changeset/three-plants-smile.md
  polaris-react/src/components/Tooltip/Tooltip.stories.tsx
  polaris-react/src/components/Tooltip/Tooltip.tsx
  polaris-react/src/components/Tooltip/tests/Tooltip.test.tsx
  polaris.shopify.com/pages/examples/tooltip-default.tsx
  polaris.shopify.com/pages/examples/tooltip-with-persistence-on-click.tsx
  polaris.shopify.com/pages/examples/tooltip-with-underline.tsx
Labels: 🤖Skip Changelog

#11763 [IndexTable] Allow row click when onClick is passed in on non-selectable tables
  .changeset/odd-swans-teach.md
  polaris-react/src/components/IndexTable/components/Row/Row.tsx
  polaris-react/src/components/IndexTable/components/Row/tests/Row.test.tsx
Labels: Component, Contribution, 2024

#11771 Add popover cover position story to prevent regressions
  .changeset/fluffy-meals-repair.md
  polaris-react/src/components/Popover/Popover.stories.tsx
Labels: #gsd38419

#11776 Update common actions focus ring example
  .changeset/swift-ants-eat.md
  polaris.shopify.com/public/images/patterns/common-actions/common-actions-interactivity-focus-with-cursor.mp4
Labels: #gsd:38421

#11691 Add component level theming
  .changeset/mighty-hounds-boil.md
  polaris-react/src/components/AppProvider/AppProvider.tsx
  polaris-react/src/components/PolarisTestProvider/PolarisTestProvider.tsx
  polaris-react/src/components/Portal/Portal.tsx
  polaris-react/src/components/ThemeProvider/ThemeProvider.module.css
  polaris-react/src/components/ThemeProvider/ThemeProvider.stories.tsx
  polaris-react/src/components/ThemeProvider/ThemeProvider.tsx
  polaris-react/src/components/ThemeProvider/index.ts
  polaris-react/src/components/ThemeProvider/tests/ThemeProvider.test.tsx
  polaris-react/src/index.ts
  polaris-react/src/utilities/use-theme.ts
  polaris-tokens/scripts/toStyleSheet.ts
  polaris-tokens/src/themes/base/color.ts
  polaris-tokens/src/themes/constants.ts
  polaris-tokens/src/themes/dark.ts
  polaris-tokens/src/themes/index.ts
  polaris-tokens/src/themes/utils.ts
  polaris-tokens/tests/toStyleSheet.test.js
Labels: #gsd:38420

#11728 Add AlphaPicker
  .changeset/few-wolves-fail.md
  polaris-react/playground/DetailsPage.tsx
  polaris-react/src/components/Combobox/Combobox.tsx
  polaris-react/src/components/Listbox/components/index.ts
  polaris-react/src/components/Listbox/index.ts
  polaris-react/src/components/Picker/Picker.tsx
  polaris-react/src/components/Picker/components/Activator/Activator.module.css
  polaris-react/src/components/Picker/components/Activator/Activator.tsx
  polaris-react/src/components/Picker/components/Activator/index.ts
  polaris-react/src/components/Picker/components/Activator/tests/Activator.test.tsx
  polaris-react/src/components/Picker/components/SearchField/SearchField.module.css
  polaris-react/src/components/Picker/components/SearchField/SearchField.tsx
  polaris-react/src/components/Picker/components/SearchField/index.ts
  polaris-react/src/components/Picker/components/SearchField/tests/SearchField.test.tsx
  polaris-react/src/components/Picker/components/index.ts
  polaris-react/src/components/Picker/index.ts
  polaris-react/src/components/Picker/tests/Picker.test.tsx
  polaris-react/src/components/Popover/Popover.module.css
  polaris-react/src/components/Popover/components/Pane/Pane.tsx
  polaris-react/src/index.ts
Labels: #gsd38419

#11645 [Common actions] Add Copy To Clipboard recipe
  .changeset/flat-eagles-press.md
  polaris-react/src/components/Button/Button.stories.tsx
  polaris-react/src/components/Tooltip/Tooltip.tsx
  polaris-react/src/components/Tooltip/tests/Tooltip.test.tsx
  polaris-react/src/index.ts
  polaris-react/src/utilities/use-copy-to-clipboard.ts
Labels: #gsd:38421

#11795 [Common actions] Update Button storybook examples to use `PlusCircleIcon`
  polaris-react/src/components/Button/Button.stories.tsx
Labels: 🤖Skip Changelog, #gsd:38421

#11800 Revert Tooltip updates to close on child enter/space key interactions
  .changeset/flat-eagles-press.md
  polaris-react/src/components/Button/Button.stories.tsx
  polaris-react/src/components/Tooltip/Tooltip.tsx
  polaris-react/src/components/Tooltip/tests/Tooltip.test.tsx
Labels: 🤖Skip Changelog
